export function stationerySticker(ctx,t,glow=1){ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.rotation);ctx.scale(t.scale,t.scale);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=4;ctx.strokeStyle='#b68b92';ctx.fillStyle='#efd1d6';
const stroke=(p)=>{ctx.beginPath();p.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();};
if(t.kind==='sparkle'){const star=(x,y,r)=>{ctx.save();ctx.translate(x,y);ctx.shadowColor='#edc875';ctx.shadowBlur=9*glow;ctx.fillStyle='#d6b26b';ctx.beginPath();ctx.moveTo(0,-r);ctx.quadraticCurveTo(r*.14,-r*.14,r*.58,0);ctx.quadraticCurveTo(r*.14,r*.14,0,r);ctx.quadraticCurveTo(-r*.14,r*.14,-r*.58,0);ctx.quadraticCurveTo(-r*.14,-r*.14,0,-r);ctx.fill();ctx.restore();};star(-15,8,50);star(38,-34,23);star(46,38,15);ctx.fillStyle='#d6b26b';for(const [x,y]of[[-48,-32],[16,62]]){ctx.beginPath();ctx.arc(x,y,3,0,7);ctx.fill();}}
else if(t.kind==='heart'){for(const [x,y,k] of [[-17,8,1],[40,-25,.43]]){ctx.save();ctx.translate(x,y);ctx.scale(k,k);ctx.beginPath();ctx.moveTo(0,36);ctx.bezierCurveTo(-81,-8,-34,-63,0,-25);ctx.bezierCurveTo(34,-63,81,-8,0,36);ctx.fill();ctx.stroke();ctx.restore();}}
else if(t.kind==='crown'){ctx.strokeStyle='#c5a064';ctx.fillStyle='#f3e5bd';ctx.beginPath();ctx.moveTo(-48,27);ctx.lineTo(-58,-24);ctx.lineTo(-22,-4);ctx.lineTo(0,-43);ctx.lineTo(22,-4);ctx.lineTo(58,-24);ctx.lineTo(48,27);ctx.closePath();ctx.fill();ctx.stroke();for(const [x,y]of[[-58,-24],[0,-43],[58,-24]]){ctx.beginPath();ctx.arc(x,y,4,0,7);ctx.fill();ctx.stroke();}stroke([[-39,38],[39,38]]);}
else if(t.kind==='sideGrin'){ctx.strokeStyle='#997b80';ctx.lineWidth=4.5;for(const x of[-33,33]){ctx.fillStyle='#fffaf4';ctx.beginPath();ctx.moveTo(x-25,-29);ctx.lineTo(x+24,-31);ctx.quadraticCurveTo(x+29,-8,x+3,-4);ctx.quadraticCurveTo(x-23,0,x-25,-29);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#997b80';ctx.beginPath();ctx.ellipse(x+13,-20,4.8,6.5,.22,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#fffaf4';ctx.beginPath();ctx.moveTo(-38,19);ctx.quadraticCurveTo(1,22,41,13);ctx.bezierCurveTo(32,53,-44,66,-38,19);ctx.closePath();ctx.fill();ctx.stroke();ctx.lineWidth=3.5;for(const p of [[-26,21,-23,44],[-9,22,-6,48],[9,20,14,44],[27,17,31,32]]){ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.quadraticCurveTo(p[0]+3,(p[1]+p[3])/2,p[2],p[3]);ctx.stroke();}}
else if(t.kind==='squeeze'){ctx.strokeStyle='#997b80';stroke([[-43,-25],[-24,-12],[-43,0]]);stroke([[43,-25],[24,-12],[43,0]]);ctx.beginPath();ctx.moveTo(-21,17);ctx.quadraticCurveTo(0,34,23,16);ctx.stroke();ctx.fillStyle='#e4a6b4';ctx.beginPath();ctx.moveTo(3,27);ctx.lineTo(21,23);ctx.lineTo(20,37);ctx.quadraticCurveTo(10,51,3,37);ctx.closePath();ctx.fill();ctx.strokeStyle='#c58c9b';ctx.lineWidth=2.5;ctx.stroke();stroke([[12,29],[12,37]]);}
else{ctx.strokeStyle='#997b80';for(const x of[-30,30]){ctx.beginPath();if(t.kind==='wink'&&x===30)ctx.moveTo(x-8,-8),ctx.lineTo(x+8,-15);else ctx.arc(x,-8,9,Math.PI,2*Math.PI);ctx.stroke();}ctx.beginPath();ctx.arc(0,8,17,0,Math.PI);ctx.stroke();if(t.kind==='shy'){ctx.fillStyle='#eac1c780';for(const x of[-48,48]){ctx.beginPath();ctx.ellipse(x,9,12,6,0,0,7);ctx.fill();}}}ctx.restore();}
export function attachCardDecor({content,controls,image,button,paint,backgroundColor, setBackground}){
const c=content.cardDecor,items=[];let selected=-1,drag=null,alive=true,photo=null,ticket=0,scale=1,px=0,py=0,opacity=1;
const panel=document.createElement('details');panel.className='card-decor-panel';const summary=document.createElement('summary');summary.textContent=c.add;const library=document.createElement('div');library.className='sticker-library';const tools=document.createElement('div');tools.className='card-decor-tools';const note=document.createElement('p');note.textContent=c.hint;panel.append(summary,note,library,tools);controls.prepend(panel);
function edit(){tools.replaceChildren();const t=items[selected];if(!t)return;tools.append(button(c.remove,()=>{items.splice(selected,1);selected=-1;edit();paint();}),button(c.done,()=>{selected=-1;edit();paint();}));}
for(const item of c.stickers){const b=button(item.name,()=>{if(items.length>=24)return;items.push({kind:item.id,x:805,y:390,scale:1,rotation:0});selected=items.length-1;edit();paint();});const icon=document.createElement('canvas');icon.width=160;icon.height=140;stationerySticker(icon.getContext('2d'),{kind:item.id,x:80,y:70,scale:1,rotation:0});b.prepend(icon);library.append(b);}
const point=e=>{const r=image.getBoundingClientRect();return{x:(e.clientX-r.left)*1080/r.width,y:(e.clientY-r.top)*1440/r.height};};
const unit=()=>1080/image.getBoundingClientRect().width;
const handles=t=>{const r=Math.max(80*t.scale,22*unit()),h=28*unit();return {r,h};};
const local=(p,t)=>{const dx=p.x-t.x,dy=p.y-t.y;return{x:dx*Math.cos(t.rotation)+dy*Math.sin(t.rotation),y:-dx*Math.sin(t.rotation)+dy*Math.cos(t.rotation)};};
image.onpointerdown=e=>{if(e.button!==0||drag)return;const p=point(e),t=items[selected];let action='move';if(t){const q=local(p,t),{r,h}=handles(t),hit=18*unit();if(Math.hypot(q.x-r,q.y-r)<hit)action='scale';else if(Math.hypot(q.x,q.y+r+h)<hit)action='rotate';}if(action==='move'){selected=-1;for(let i=items.length-1;i>=0;i--){const q=local(p,items[i]),{r}=handles(items[i]);if(Math.abs(q.x)<r&&Math.abs(q.y)<r){selected=i;break;}}}if(selected>=0){const t=items[selected];drag={id:e.pointerId,action,...p,scale:t.scale,distance:Math.max(1,Math.hypot(p.x-t.x,p.y-t.y)),angle:Math.atan2(p.y-t.y,p.x-t.x),rotation:t.rotation};image.setPointerCapture(e.pointerId);e.preventDefault();}edit();paint();};
image.onpointermove=e=>{if(!drag||drag.id!==e.pointerId||!items[selected])return;const p=point(e),t=items[selected];if(drag.action==='scale')t.scale=Math.max(.4,Math.min(2.5,drag.scale*Math.hypot(p.x-t.x,p.y-t.y)/drag.distance));else if(drag.action==='rotate')t.rotation=drag.rotation+Math.atan2(p.y-t.y,p.x-t.x)-drag.angle;else{t.x=Math.max(0,Math.min(1080,t.x+p.x-drag.x));t.y=Math.max(0,Math.min(1440,t.y+p.y-drag.y));drag.x=p.x;drag.y=p.y;}paint();};image.onpointerup=image.onpointercancel=image.onlostpointercapture=e=>{if(drag?.id===e.pointerId)drag=null;};
const background=document.createElement('details');background.className='card-decor-panel';const bs=document.createElement('summary');bs.textContent=c.background;const f=document.createElement('input');f.type='file';f.accept='image/*';f.hidden=true;const help=document.createElement('p');help.textContent=c.backgroundHint;const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=950;const ctx=canvas.getContext('2d');const update=()=>{if(!photo||opacity===0){setBackground(null);return;}ctx.globalAlpha=1;ctx.fillStyle=backgroundColor||'#f5eee6';ctx.fillRect(0,0,1000,950);const k=Math.max(1000/photo.width,950/photo.height)*scale;ctx.globalAlpha=opacity;ctx.drawImage(photo,500-photo.width*k/2+px,475-photo.height*k/2+py,photo.width*k,photo.height*k);setBackground(canvas);};
f.onchange=()=>{const file=f.files[0];if(!file)return;const id=++ticket,url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);if(!alive||id!==ticket)return;photo=img;scale=1;px=py=0;opacity=1;for(const input of background.querySelectorAll('input[type=range]'))input.value=input.dataset.initial;update();};img.onerror=()=>{URL.revokeObjectURL(url);if(alive)help.textContent=c.error;};img.src=url;};background.append(bs,help,button(c.choose,()=>f.click()),f,button(c.reset,()=>{ticket++;photo=null;update();}));for(const [label,min,max,initial,fn]of[[c.opacity,0,100,0,v=>opacity=1-v/100],[c.size,1,3,1,v=>scale=v],[c.horizontal,-500,500,0,v=>px=v],[c.vertical,-475,475,0,v=>py=v]]){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.step=.01;input.value=initial;input.dataset.initial=initial;input.oninput=()=>{fn(Number(input.value));update();};l.append(input);background.append(l);}controls.prepend(background);
return {shimmer(ctx,time){ctx.save();ctx.globalAlpha=.16+.12*Math.sin(time/650);for(const t of items)if(t.kind==='sparkle')stationerySticker(ctx,t,1.5);ctx.restore();},draw(ctx){for(const t of items)stationerySticker(ctx,t);},outline(ctx){const t=items[selected];if(!t)return;const {r,h}=handles(t),u=unit();ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.rotation);ctx.strokeStyle='#a36b83';ctx.lineWidth=1.2*u;ctx.setLineDash([4*u,3*u]);ctx.strokeRect(-r,-r,2*r,2*r);ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(0,-r);ctx.lineTo(0,-r-h);ctx.stroke();for(const [x,y,kind]of[[r,r,'scale'],[0,-r-h,'rotate']]){ctx.fillStyle='#fffaf3';ctx.beginPath();ctx.arc(x,y,12*u,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.save();ctx.translate(x,y);ctx.beginPath();if(kind==='rotate'){ctx.arc(0,0,5*u,.5,5.5);ctx.moveTo(4*u,-4*u);ctx.lineTo(5*u,0);ctx.lineTo(1*u,-u);}else{ctx.moveTo(-4*u,4*u);ctx.lineTo(4*u,-4*u);ctx.moveTo(0,-4*u);ctx.lineTo(4*u,-4*u);ctx.lineTo(4*u,0);}ctx.stroke();ctx.restore();}ctx.restore();},dispose(){alive=false;ticket++;photo=null;canvas.width=canvas.height=0;}};
}
