import {pickSticker} from './collage-layout.js';
import {createAtelier} from './scene.js';
import {saveCardToAlbum} from './album.js';
export function drawSticker(ctx,t){
 ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.rotation||0);ctx.scale(t.scale||1,t.scale||1);ctx.lineWidth=9;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#65404b';ctx.fillStyle='#ef91ad';
 const line=points=>{ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();};
 if(t.kind==='heart'){ctx.beginPath();ctx.moveTo(0,48);ctx.bezierCurveTo(-115,-17,-45,-94,0,-39);ctx.bezierCurveTo(45,-94,115,-17,0,48);ctx.fill();ctx.stroke();}
 else if(t.kind==='crown'){ctx.fillStyle='#f0c75d';ctx.beginPath();[[-66,34],[-80,-41],[-34,-10],[0,-62],[34,-10],[80,-41],[66,34]].forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();ctx.stroke();line([[-56,51],[56,51]]);}
 else if(t.kind==='star'){ctx.fillStyle='#f0c75d';ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5-Math.PI/2,r=i%2?31:65;i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fill();ctx.stroke();}
 else{for(const x of [-38,38]){if(t.kind==='sleep')line([[x-13,-17],[x+13,-17]]);else if(t.kind==='smile'||t.kind==='shy'||(t.kind==='wink'&&x>0)){ctx.beginPath();ctx.arc(x,-9,13,Math.PI,2*Math.PI);ctx.stroke();}else{ctx.beginPath();ctx.ellipse(x,-20,5,10,0,0,Math.PI*2);ctx.fillStyle='#65404b';ctx.fill();}}
 ctx.beginPath();if(t.kind==='surprise')ctx.ellipse(0,22,12,17,0,0,Math.PI*2);else if(t.kind==='sleep')ctx.moveTo(-9,22),ctx.lineTo(9,22);else ctx.arc(0,9,23,0,Math.PI);ctx.stroke();if(t.kind==='shy'){ctx.strokeStyle='#e890a4';for(const x of [-60,52]){line([[x,7],[x-5,21]]);line([[x+13,7],[x+8,21]]);}}}
 ctx.restore();
}
export function openCollage(content,recipe,name,initialView,initialMessage){
 const c=content.collage,s=content.share,dialog=document.createElement('dialog');dialog.className='share-dialog collage-dialog';
 const title=document.createElement('h2');title.textContent=c.title;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1440;canvas.className='collage-preview';canvas.setAttribute('aria-label',c.title);const ctx=canvas.getContext('2d');
 const host=document.createElement('div');host.className='share-render-host collage-render-host';document.body.append(host);
 const background=document.createElement('canvas');background.width=1080;background.height=1440;const bg=background.getContext('2d');
 const tabs=document.createElement('div');tabs.className='card-style-choices';const controls=document.createElement('div');controls.className='share-controls';const hint=document.createElement('p'),status=document.createElement('p');status.setAttribute('role','status');
 let studio=null,alive=true,tab=0,selected=-1,photo=null,photoScale=1,photoX=0,photoY=0,stickers=[],preview=false,drag=null,raf=0,frame=null,busy=false,uploadTicket=0;
 const view=initialView?JSON.parse(JSON.stringify(initialView)):{rotation:[0,0,0,1],pan:[0,0,0],zoom:1};let yaw=0,pitch=0,words=initialMessage||s.phrases[Math.floor(Math.random()*s.phrases.length)];
 const button=(text,fn)=>{const b=document.createElement('button');b.type='button';b.className='soft-button';b.textContent=text;b.onclick=fn;return b;};
 function range(label,min,max,value,fn){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.step='.01';input.value=value;input.oninput=()=>fn(Number(input.value));l.append(input);controls.append(l);}
 function compose(out,selection=false){out.clearRect(0,0,1080,1440);if(frame)out.drawImage(frame,0,0,1080,1440);for(const t of stickers.filter(t=>!t.back))drawSticker(out,t);if(name||words){out.save();out.fillStyle='#fff9eef0';out.fillRect(70,1250,940,144);out.fillStyle='#754b59';out.textAlign='center';out.font='34px serif';out.fillText(name||content.ui.brand||'',540,1302,870);out.font='29px serif';out.fillText(words,540,1361,870);out.restore();}if(selection&&tab===1&&stickers[selected]){const t=stickers[selected];out.save();out.translate(t.x,t.y);out.rotate(t.rotation);out.strokeStyle='#a95876';out.lineWidth=3;out.setLineDash([10,8]);out.strokeRect(-95*t.scale,-85*t.scale,190*t.scale,170*t.scale);out.restore();}}
 function refresh(){if(!alive||raf)return;raf=requestAnimationFrame(()=>{raf=0;if(!studio)return;bg.fillStyle='#f6ebdd';bg.fillRect(0,0,1080,1440);if(photo){const k=Math.max(1080/photo.width,1440/photo.height)*photoScale,w=photo.width*k,h=photo.height*k;bg.drawImage(photo,540-w/2+photoX,720-h/2+photoY,w,h);}for(const t of stickers.filter(t=>t.back))drawSticker(bg,t);studio.setCardBackground(background);studio.setView(view);requestAnimationFrame(()=>{if(!alive)return;try{frame=studio.snapshot();compose(ctx,!preview);}catch{status.textContent=s.renderError;}});});}
 function renderControls(){tabs.replaceChildren();controls.replaceChildren();hint.textContent=c.hint[tab];tabs.hidden=controls.hidden=hint.hidden=preview;c.tabs.forEach((label,i)=>{const b=button(label,()=>{tab=i;renderControls();refresh();});b.setAttribute('aria-pressed',String(tab===i));tabs.append(b);});
 if(tab===0){const file=document.createElement('input');file.type='file';file.accept='image/*';file.hidden=true;file.onchange=()=>{const f=file.files[0];if(!f)return;if(!/^image\//.test(f.type)){status.textContent=c.error;return;}const ticket=++uploadTicket,reader=new FileReader();reader.onerror=()=>{if(alive)status.textContent=c.error;};reader.onload=()=>{const img=new Image();img.onerror=()=>{if(alive&&ticket===uploadTicket)status.textContent=c.error;};img.onload=()=>{if(!alive||ticket!==uploadTicket)return;const reduced=document.createElement('canvas'),k=Math.min(1,2048/Math.max(img.width,img.height));reduced.width=Math.max(1,Math.round(img.width*k));reduced.height=Math.max(1,Math.round(img.height*k));reduced.getContext('2d').drawImage(img,0,0,reduced.width,reduced.height);photo=reduced;photoScale=1;photoX=photoY=0;status.textContent=c.privacy;renderControls();refresh();};img.src=reader.result;};reader.readAsDataURL(f);};controls.append(button(c.upload,()=>file.click()),file,button(c.clear,()=>{uploadTicket++;photo=null;photoScale=1;photoX=photoY=0;renderControls();refresh();}));range(c.size,1,3,photoScale,v=>{photoScale=v;refresh();});}
 if(tab===1){const library=document.createElement('div');library.className='sticker-library';for(const item of c.stickers){const b=button(item.name,()=>{if(stickers.length>=24){status.textContent=c.limit;return;}stickers.push({kind:item.id,x:540,y:470,scale:1,rotation:0,back:false});selected=stickers.length-1;renderControls();refresh();});const icon=document.createElement('canvas');icon.width=200;icon.height=160;drawSticker(icon.getContext('2d'),{kind:item.id,x:100,y:85,scale:.8});b.prepend(icon);library.append(b);}controls.append(library);const placed=document.createElement('div');placed.className='collage-placed';stickers.forEach((item,i)=>{const b=button(c.stickers.find(x=>x.id===item.kind).name+' · '+(i+1),()=>{selected=i;renderControls();refresh();});b.setAttribute('aria-pressed',String(selected===i));placed.append(b);});controls.append(placed);const t=stickers[selected];if(t){range(c.size,.35,3,t.scale,v=>{t.scale=v;refresh();});range(c.rotate,-Math.PI,Math.PI,t.rotation,v=>{t.rotation=v;refresh();});const layer=button(t.back?c.front:c.back,()=>{t.back=!t.back;renderControls();refresh();});controls.append(layer,button(c.remove,()=>{stickers.splice(selected,1);selected=-1;renderControls();refresh();}));}else{const p=document.createElement('p');p.textContent=c.empty;controls.append(p);}}
 if(tab===2){const label=document.createElement('label');label.textContent=s.message;const input=document.createElement('input');input.value=words;input.maxLength=48;input.oninput=()=>{words=input.value;refresh();};label.append(input);controls.append(label,button(s.shuffle,()=>{words=s.phrases[Math.floor(Math.random()*s.phrases.length)];input.value=words;refresh();}));range(c.size,.45,1.8,2.25-view.zoom,v=>{view.zoom=2.25-v;refresh();});const rotate=()=>{const sy=Math.sin(yaw/2),cy=Math.cos(yaw/2),sx=Math.sin(pitch/2),cx=Math.cos(pitch/2);view.rotation=[sx*cy,cx*sy,-sx*sy,cx*cy];refresh();};range(c.angle,-Math.PI,Math.PI,yaw,v=>{yaw=v;rotate();});range(c.tilt,-1.08,.25,pitch,v=>{pitch=v;rotate();});}}
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1080/r.width,y:(e.clientY-r.top)*1440/r.height};};canvas.onpointerdown=e=>{if(preview||e.button!==0)return;const p=point(e);if(tab===1){selected=pickSticker(stickers,p);renderControls();}drag={id:e.pointerId,...p};canvas.setPointerCapture(e.pointerId);refresh();};canvas.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const p=point(e),dx=p.x-drag.x,dy=p.y-drag.y;if(tab===0){photoX+=dx;photoY+=dy;}if(tab===1&&stickers[selected]){stickers[selected].x=Math.max(0,Math.min(1080,stickers[selected].x+dx));stickers[selected].y=Math.max(0,Math.min(1440,stickers[selected].y+dy));}if(tab===2){view.pan[0]-=dx/200;view.pan[1]+=dy/200;}drag={id:e.pointerId,...p};refresh();};canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=()=>{drag=null;};
 const actions=document.createElement('div');actions.className='share-actions';const peek=button(c.preview,()=>{preview=!preview;peek.textContent=preview?c.edit:c.preview;renderControls();refresh();});const save=button(s.save,async()=>{if(busy||!frame)return;const bridge=window.xhs?.miniTool;if(!bridge?.saveImageToPhotosAlbum){status.textContent=s.fallback;return;}busy=true;save.disabled=true;await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);if(!alive)return;frame=studio.snapshot();const output=document.createElement('canvas');output.width=1080;output.height=1440;compose(output.getContext('2d'));try{await saveCardToAlbum(bridge,output.toDataURL('image/png'));if(alive)status.textContent=s.success;}catch{if(alive)status.textContent=s.error;}finally{busy=false;save.disabled=false;output.width=output.height=0;}});save.className='primary';actions.append(peek,save,button(s.close,()=>dialog.close()));dialog.append(title,canvas,hint,tabs,controls,status,actions);document.body.append(dialog);dialog.onclose=()=>{alive=false;uploadTicket++;cancelAnimationFrame(raf);studio?.dispose();photo=null;frame=null;host.remove();canvas.width=canvas.height=background.width=background.height=0;dialog.remove();};dialog.showModal();renderControls();try{studio=createAtelier(host,content,{preview:true,showcase:true,capture:true});studio.setRecipe(structuredClone(recipe),'ready',1);refresh();}catch{status.textContent=s.renderError;}
}
