import {jellyImpact,liquidStream} from './sound-texture.js';
export function createSound(settings){
 let context=null,enabled=false,output=null,pour=null,streamBuffer=null,serial=17;const voices=new Set();
 function ready(){if(!enabled)return null;if(!context){context=new AudioContext();output=context.createDynamicsCompressor();output.threshold.value=-14;output.knee.value=20;output.ratio.value=3;output.attack.value=.025;output.release.value=.22;output.connect(context.destination);}if(context.state==='suspended')void context.resume().catch(()=>{});return context;}
 function buffer(ctx,samples){const b=ctx.createBuffer(1,samples.length,ctx.sampleRate);b.getChannelData(0).set(samples);return b;}
 function impact(kind='poke'){const ctx=ready();if(!ctx)return;while(voices.size>=settings.maxVoices)voices.values().next().value.stop();const source=ctx.createBufferSource(),gain=ctx.createGain(),land=kind==='land';source.buffer=buffer(ctx,jellyImpact(ctx.sampleRate,{land,seed:serial++}));gain.gain.value=settings.volume*(land?1.1:1);source.connect(gain);gain.connect(output);let stopping=false;const voice={stop(){if(stopping)return;stopping=true;gain.gain.setTargetAtTime(0,ctx.currentTime,.015);source.stop(ctx.currentTime+.08);voices.delete(voice)}};source.onended=()=>{voices.delete(voice);source.disconnect();gain.disconnect()};voices.add(voice);source.start();source.stop(ctx.currentTime+source.buffer.duration+.02);}
 function stopPour(){if(!pour)return;const current=pour;pour=null;clearTimeout(current.endTimer);const now=context.currentTime;current.gain.gain.cancelScheduledValues(now);current.gain.gain.setTargetAtTime(0,now,.035);current.source.stop(now+.18);}
 function startPour(duration=null){const ctx=ready();if(!ctx||pour)return;if(!streamBuffer)streamBuffer=buffer(ctx,liquidStream(ctx.sampleRate));const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=streamBuffer;source.loop=true;gain.gain.setValueAtTime(0,ctx.currentTime);gain.gain.linearRampToValueAtTime(settings.pourVolume*1.8,ctx.currentTime+.14);source.connect(gain);gain.connect(output);const current={source,gain,endTimer:null};pour=current;source.onended=()=>{source.disconnect();gain.disconnect()};source.start();if(duration)current.endTimer=setTimeout(()=>{if(pour===current)stopPour()},duration*1000);}
 return {impact,startPour,stopPour,setEnabled(value){enabled=value;if(!value){stopPour();for(const voice of [...voices])voice.stop();}},suspend(){stopPour();for(const voice of [...voices])voice.stop();if(context?.state==='running')void context.suspend();}};
}
