import {decorationFits} from './decorations.js';
import {isCandle} from './decoration-models.js';
export function createStudio(api){
  const {content:c}=api,s=c.studio,root=document.createElement('section');root.className='studio-tools';document.querySelector('.control-deck').append(root);const selectionPanel=document.createElement('section');selectionPanel.className='selected-editor';selectionPanel.hidden=true;document.querySelector('.control-deck').prepend(selectionPanel);
  const dock=document.createElement('section');dock.className='placement-dock';document.body.append(dock);const finish=document.createElement('button');finish.className='primary decorate-finish';finish.type='button';finish.onclick=()=>document.querySelector('#primary')?.click();
  let mode='poke',selected=-1,category='fruit',color=s.colors[0],digits='18',lastStage='',invalidMove=false,candidates=[],listOpen=false;
  const btn=(text,action,active=false)=>{const b=document.createElement('button');b.type='button';b.className='soft-button';b.textContent=text;b.setAttribute('aria-pressed',String(active));b.onclick=action;return b;};
  const update=()=>{api.sync();api.refresh();};
  function change(patch){const r=api.recipe(),t=r.toppings[selected];if(!t)return;const next={...t,...patch};if(!decorationFits(r,next,c)){api.notify(s.invalid);return;}r.toppings[selected]=next;update();}
  function renderDock(){const active=api.stage()==='decorate';dock.hidden=finish.hidden=!active;document.body.classList.toggle('has-placement-dock',active);dock.replaceChildren();if(!active)return;const kind=api.selectedTopping(),item=c.toppings.find(t=>t.id===kind),name=kind==='number'?s.numberPlacement.replace('{digit}',digits):item.name;const caption=document.createElement('p');caption.textContent=s.placementSelected.replace('{name}',name);const actions=document.createElement('div');actions.className='placement-actions';const undo=btn(c.workshop.undo,()=>document.querySelector('#undo')?.click());undo.disabled=!api.recipe().toppings.length;const place=btn(s.placementAction.replace('{name}',name),()=>document.querySelector('#auto-place')?.click());place.className='soft-button auto-place-button';place.setAttribute('aria-label',s.autoPlaceLabel.replace('{name}',name));const plus=document.createElement('span');plus.className='place-plus';plus.setAttribute('aria-hidden','true');const label=document.createElement('span');label.className='place-label';label.textContent=place.textContent;place.replaceChildren(plus,label);place.disabled=api.recipe().toppings.length>=c.craft.maxToppings||(kind==='number'&&!/^\d{1,3}$/.test(digits));if(api.recipe().toppings.length>=c.craft.maxToppings){place.textContent=s.placementFull;place.setAttribute('aria-label',s.placementFull);}const count=document.createElement('span');count.className='placement-count';count.textContent=api.recipe().toppings.length+' / '+c.craft.maxToppings;caption.append(count);actions.append(undo,place,finish);dock.append(caption,actions);finish.textContent=api.isEditing()?s.finishEditing:s.unmoldAction;}
  const floating=document.createElement('section');floating.className='preview-tools';document.querySelector('.stage').append(floating);let toolsOpen=true,lightsOff=false;
  for(const type of ['pointerdown','pointermove','pointerup','pointercancel','wheel'])floating.addEventListener(type,event=>event.stopPropagation());
  function renderFloating(stage){const hasCandle=api.recipe().toppings.some(t=>isCandle(t.kind));if(!hasCandle)lightsOff=false;api.scene()?.setLightsOff(lightsOff);floating.replaceChildren();floating.hidden=!['mold','decorate','ready'].includes(stage);if(floating.hidden)return;
    const toggle=btn(toolsOpen?s.hideTools:s.showTools,()=>{toolsOpen=!toolsOpen;renderFloating(api.stage())});toggle.className='soft-button preview-toggle';toggle.setAttribute('aria-expanded',String(toolsOpen));floating.append(toggle);if(!toolsOpen)return;
    if(stage!=='mold'){const modes=document.createElement('div');modes.className='preview-modes';modes.setAttribute('role','group');modes.setAttribute('aria-label',s.modeLabel);modes.append(btn(stage==='decorate'?s.edit:s.poke,()=>{mode=stage==='decorate'?'edit':'poke';render()},mode!=='inspect'),btn(s.inspect,()=>{mode='inspect';candidates=[];render()},mode==='inspect'));floating.append(modes);}
    const views=document.createElement('div');views.className='preview-view-buttons';for(const [key,label] of [['front',s.front],['top',s.top],['side',s.side]])views.append(btn(label,()=>api.scene()?.viewPreset(key)));views.append(btn(s.zoomIn,()=>api.scene()?.zoom(.85)),btn(s.zoomOut,()=>api.scene()?.zoom(1.18)));views.append(btn(s.frameUp,()=>api.scene()?.shiftFraming(1)),btn(s.frameDown,()=>api.scene()?.shiftFraming(-1)));if(hasCandle){const light=btn(lightsOff?s.roomLightsOn:s.roomLightsOff,()=>{lightsOff=!lightsOff;renderFloating(api.stage());},lightsOff);views.append(light);}floating.append(views);
  }
  function itemName(index){const items=api.recipe().toppings,t=items[index];if(!t)return '';const n=items.slice(0,index+1).filter(x=>x.kind===t.kind).length;return c.toppings.find(x=>x.id===t.kind).name+(t.kind==='number'?' '+t.digits:'')+' · '+n;}
  function choose(index){selected=index;candidates=[];mode='edit';const t=api.recipe().toppings[index];if(t?.kind==='number'){digits=t.digits||'0';category='candle';}render();document.querySelector('.control-deck').scrollTop=0;}
  function render(){document.querySelector('.placed-list')?.remove();document.querySelector('.overlap-choices')?.remove();selectionPanel.replaceChildren();selectionPanel.hidden=true;renderDock();
    const stage=api.stage();root.replaceChildren();root.hidden=!['mold','decorate','ready'].includes(stage);if(root.hidden){renderFloating(stage);if(lastStage!==stage){api.scene()?.setToolMode('inspect');lastStage=stage;}return;}
    if(stage==='mold'){mode='inspect';lastStage=stage;api.scene()?.setToolMode('inspect');renderFloating(stage);return;}
    if(lastStage!==stage){mode=stage==='decorate'?'edit':'poke';selected=-1;lastStage=stage;if(stage==='decorate')api.scene()?.viewPreset('decorate');}
    api.scene()?.setToolMode(mode);api.scene()?.selectTopping(selected);document.querySelector('#hint').textContent=mode==='inspect'?s.viewHint:stage==='ready'?c.ui.instructions:s.placeHint;document.querySelector('#step-description').textContent=mode==='inspect'?s.viewHint:stage==='ready'?c.workshop.readyHint:s.placeHint;
    renderFloating(stage);
    if(stage==='ready'){const row=document.createElement('div');row.className='studio-row ready-secondary';row.append(btn(s.editAgain,()=>{selected=-1;api.edit()}),btn(c.ui.shake,api.shake),btn(c.ui.replay,api.replay));root.append(row);}
    if(stage==='decorate'){
      const list=document.createElement('details');list.className='placed-list';list.open=listOpen;list.ontoggle=()=>{listOpen=list.open};const summary=document.createElement('summary');summary.textContent=s.placedList.replace('{count}',api.recipe().toppings.length);list.append(summary);api.recipe().toppings.forEach((t,i)=>list.append(btn(itemName(i),()=>choose(i),selected===i)));if(!api.recipe().toppings.length){const empty=document.createElement('p');empty.textContent=s.emptyPlaced;list.append(empty);}selectionPanel.after(list);
      if(mode==='edit'&&candidates.length){const choices=document.createElement('section');choices.className='overlap-choices';const label=document.createElement('p');label.textContent=s.overlapTitle;choices.append(label);candidates.filter(i=>api.recipe().toppings[i]).forEach(i=>choices.append(btn(itemName(i),()=>choose(i))));document.querySelector('.control-deck').prepend(choices);document.querySelector('.control-deck').scrollTop=0;}
      const categories=document.createElement('div');categories.className='studio-row categories';for(const [key,label] of s.categories)categories.append(btn(label,()=>{category=key;selected=-1;api.setTopping(c.toppings.find(t=>t.category===key).id)},category===key));
      const choices=document.querySelector('#choices');choices.querySelector('.categories')?.remove();choices.prepend(categories);choices.querySelectorAll('[data-choice]').forEach(b=>{b.hidden=c.toppings.find(t=>t.id===b.dataset.choice)?.category!==category;});
      const palette=document.createElement('div');palette.className='studio-row';
      choices.querySelector('.number-editor')?.remove();choices.querySelector('.candle-palette')?.remove();
      if(category==='candle'){if((mode==='edit'&&selected>=0?api.recipe().toppings[selected]?.kind:api.selectedTopping())==='number'){const numberEditor=document.createElement('div');numberEditor.className='number-editor';const label=document.createElement('label');label.textContent=s.digits;const input=document.createElement('input');input.value=digits;input.maxLength=3;input.inputMode='numeric';input.setAttribute('aria-label',s.digits);input.placeholder=s.digitPlaceholder;const help=document.createElement('p');help.textContent=s.digitHint;help.setAttribute('role','status');input.oninput=()=>{digits=input.value;renderDock();const valid=/^\d{1,3}$/.test(digits);input.setAttribute('aria-invalid',String(!valid));help.textContent=valid?s.digitHint:s.digitError;const r=api.recipe(),t=r.toppings[selected];if(valid&&mode==='edit'&&t?.kind==='number'){const next={...t,digits};if(decorationFits(r,next,c)){r.toppings[selected]=next;api.sync();help.textContent=s.digitUpdated;}else help.textContent=s.invalid;}};label.append(input);const quickTitle=document.createElement('p');quickTitle.textContent=s.digitQuickTitle;const quick=document.createElement('div');quick.className='digit-choices';for(const digit of s.digitChoices){const choice=btn(digit,()=>{digits=digit;selected=-1;api.setTopping('number');api.notify(s.digitChosen.replace('{digit}',digit));},digits===digit);choice.setAttribute('aria-label',s.digitChoiceLabel.replace('{digit}',digit));quick.append(choice);}numberEditor.append(quickTitle,quick,label,help);choices.append(numberEditor);}const current=api.recipe().toppings[selected],editing=mode==='edit'&&isCandle(current?.kind),chosen=editing?(current.color||s.colors[0]):color;const section=document.createElement('section');section.className='candle-palette';const title=document.createElement('p');title.className='candle-palette-title';title.textContent=editing?s.candleColorSelected:s.candleColorNext;const help=document.createElement('p');help.className='studio-hint';help.textContent=editing?s.candleColorSelectedHint:s.candleColorNextHint;palette.classList.add('candle-swatches');s.colors.forEach((value,i)=>{const b=btn(s.colorNames[i],()=>{color=value;if(editing)change({color});else render()},chosen===value);const swatch=document.createElement('span');swatch.className='wax-swatch';swatch.style.backgroundColor=value;swatch.setAttribute('aria-hidden','true');b.prepend(swatch);palette.append(b);});section.append(title,palette,help);choices.append(section);}
      const t=api.recipe().toppings[selected];if(mode==='edit'&&t){
        const title=document.createElement('p');title.textContent=s.selected+' · '+itemName(selected);selectionPanel.hidden=false;selectionPanel.append(title,btn(s.deselect,()=>{selected=-1;candidates=[];render();}));
        const tools=document.createElement('div');tools.className='studio-row';tools.append(btn(s.rotate,()=>change({rotation:((t.rotation||0)+Math.PI/6)%(Math.PI*2)})));
        for(const [size,label] of [[.7,s.small],[1,s.medium],[1.35,s.large]])tools.append(btn(label,()=>change({scale:size}),Math.abs((t.scale||1)-size)<.01));
        tools.append(btn(s.copy,()=>{const r=api.recipe();if(r.toppings.length>=c.craft.maxToppings){api.notify(c.workshop.toppingLimit);return;}let next=null;for(let i=0;i<24;i++){const a=i*2.4,p={...t,x:t.x+Math.cos(a)*(.1+i*.018),z:t.z+Math.sin(a)*(.1+i*.018),seed:Date.now()%2147483647};if(decorationFits(r,p,c)){next=p;break;}}if(!next){api.notify(s.invalid);return;}r.toppings.push(next);selected=r.toppings.length-1;update();api.notify(s.copied);}),btn(s.remove,()=>{api.recipe().toppings.splice(selected,1);selected=-1;update();}));
        const arrows=[['←',-.04,0],['→',.04,0],['↑',0,-.04],['↓',0,.04]];for(const [label,x,z] of arrows)tools.append(btn(label,()=>change({x:t.x+x,z:t.z+z})));

        if(t.kind==='number'){
          if((t.digits||'0').length>1)tools.append(btn(s.split,()=>{const r=api.recipe(),parts=[...(t.digits||'0')].map((digit,i)=>{const d=(i-((t.digits||'0').length-1)/2)*.25*(t.scale||1);return {...t,digits:digit,x:t.x+Math.cos(t.rotation||0)*d,z:t.z-Math.sin(t.rotation||0)*d};});if(r.toppings.length+parts.length-1>c.craft.maxToppings){api.notify(c.workshop.toppingLimit);return;}if(!parts.every(p=>decorationFits(r,p,c))){api.notify(s.invalid);return;}r.toppings.splice(selected,1,...parts);update();}));
        }
        selectionPanel.append(tools);
      }
      if(api.isEditing())root.append(btn(s.discard,api.cancelEdit));
    }

  }
  return {render,candidates(indices){candidates=indices;render();},select(index){candidates=[];selected=index;if(index>=0&&api.stage()==='decorate')mode='edit';const item=api.recipe().toppings[index];if(item?.kind==='number'){digits=item.digits||'0';category='candle';}render();document.querySelector('.control-deck').scrollTop=0;},clearSelection(){selected=-1;candidates=[];},draft(kind){if(kind==='number'&&!/^\d{1,3}$/.test(digits)){api.notify(s.digitError);return null;}return {seed:Math.floor(Math.random()*2147483647),scale:1,rotation:api.scene()?.facingAngle()||0,...(isCandle(kind)?{color,lit:true,...(kind==='number'?{digits}:{})}:{})};},move(index,point){const r=api.recipe(),t=r.toppings[index];if(!t)return;const next={...t,x:point.x,z:point.z};if(point.top===false||!decorationFits(r,next,c)){invalidMove=true;return;}r.toppings[index]=next;invalidMove=false;api.sync();},moveEnd(){if(invalidMove)api.notify(s.invalid);invalidMove=false;render();},reset(){lastStage='';selected=-1;mode='poke';lightsOff=false;}};
}
