import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),c=JSON.parse(readFileSync(new URL('../src/content/content.json',import.meta.url),'utf8')),e=require('../src/engine.js')(c),T=1800000000000;
function rich(){const s=e.fresh(T);s.coins=1e9;s.xp=5000;s.expansion=7;s.maps=[0,1,2];return s;}
function buy(s,item,area=0,rotated=false){const p=e.suggest(s,item,area,rotated);assert.ok(p,item+' has landing');assert.equal(e.act(s,Object.assign({type:'buy',item,rotated},p),T).ok,true);return s.objects[s.objects.length-1];}
test('continuous placement accepts decimals and prevents overlapping bases',()=>{const s=rich();const p=e.suggest(s,'orchid',0,false);p.x+=.1;assert.equal(e.act(s,Object.assign({type:'buy',item:'orchid'},p),T).ok,true);assert.equal(e.canLand(s,'lantern',0,p.x,p.y,false),false);assert.equal(e.restore(JSON.stringify(s),T).error,undefined);});
test('estate exterior rejects invalid points while internal seams and all courts are open',()=>{const s=e.fresh(T);for(const p of [[0,50],[-1,50],[101,70],[NaN,70]])assert.equal(e.canLand(s,'orchid',0,p[0],p[1],false),false);assert.equal(e.canLand(s,'orchid',1,22,48,false),true);});
test('every scenery fits each empty courtyard with own geometry',()=>{for(let a=0;a<4;a++)for(const i of c.items){const s=rich();s.ground=[];for(let y=25;y<=90;y+=5){const points=[];for(let x=5;x<=95;x+=5)points.push([x,y]);s.ground.push({kind:'water',points});}buy(s,i.id,a);assert.equal(e.restore(JSON.stringify(s),T).error,undefined,i.id+' area '+a);}});
test('capacity budget works independently of point positions',()=>{const s=e.fresh(T);s.coins=1e9;s.xp=5000;for(let k=0;k<9;k++)buy(s,'pond');assert.equal(e.usedCapacity(s,0),18);assert.equal(e.capacity(s,0),18);assert.equal(e.suggest(s,'orchid',0,false),null);});
test('recommendation can form first combination without grid',()=>{const s=e.fresh(T);buy(s,'orchid');buy(s,'lantern');assert.ok(s.combos.includes('first'));assert.equal(e.rate(s),11);});
test('free move remains free, excludes itself, preserves level, checkpoint income',()=>{const s=rich(),o=buy(s,'pond');o.level=4;const coins=s.coins;assert.equal(e.act(s,{type:'move',uid:o.uid,area:0,x:o.x,y:o.y,rotated:o.rotated},T+60000).ok,true);assert.equal(o.level,4);assert.equal(s.coins,coins);assert.equal(s.bank,105);});
test('v1 migration preserves money, objects, levels, collection and settles old income',()=>{const s=rich();for(const [item,pos] of [['orchid',0],['lantern',1],['pavilion',3]])assert.equal(e.act(s,{type:'buy',item,pos},T).ok,true);s.version=1;delete s.stories;const coins=s.coins,ids=s.objects.map(x=>x.uid),income=e.rate(s);const r=e.restore(JSON.stringify(s),T+60000);assert.equal(r.migrated,true);assert.equal(r.state.coins,coins);assert.equal(r.state.bank,income);assert.deepEqual(r.state.objects.map(x=>x.uid),ids);assert.deepEqual(r.state.collection,s.collection);assert.equal(r.state.version,2);assert.equal(e.restore(JSON.stringify(r.state),T+60000).error,undefined);});
test('invalid coordinate and duplicate continuous positions are rejected',()=>{const s=rich();buy(s,'orchid');buy(s,'lantern');for(const mutation of [x=>x.objects[0].x=null,x=>x.objects[0].y=200,x=>{x.objects[1].x=x.objects[0].x;x.objects[1].y=x.objects[0].y;}]){const a=JSON.parse(JSON.stringify(s));mutation(a);assert.equal(e.restore(JSON.stringify(a),T).error,true);}});
test('stories do not bypass requirements and cannot skip stages',()=>{const s=e.fresh(T);assert.equal(e.act(s,{type:'story',id:'orchid',stage:0,choice:'wait'},T).error,'storyLocked');buy(s,'orchid');assert.equal(e.act(s,{type:'story',id:'orchid',stage:2,choice:'quiet'},T).error,'storyDuplicate');assert.equal(e.act(s,{type:'story',id:'orchid',stage:0,choice:'wait'},T).ok,true);assert.equal(e.storyReady(s,c.stories[0]),false);});
test('all 32 complete story paths have valid echoes and one-time keepsakes, equal economics',()=>{for(const story of c.stories)for(let mask=0;mask<8;mask++){const s=rich();s.collection=c.items.map(i=>i.id);s.objects=[{uid:1,item:'orchid',level:2,pos:-1,rotated:false}];s.nextId=2;const money=s.coins;for(let stage=0;stage<3;stage++){const ep=story.episodes[stage];if(ep.echo){const prev=e.storyState(s,story.id)[stage-1];assert.ok(ep.echo[prev.choice]);}const choice=ep.choices[(mask>>stage)&1];assert.equal(e.act(s,{type:'story',id:story.id,stage,choice:choice.id},T).ok,true);assert.equal(e.act(s,{type:'story',id:story.id,stage,choice:choice.id},T).error,'storyDuplicate');}assert.equal(s.coins,money);assert.equal(e.storyState(s,story.id).length,3);assert.equal(e.storyReady(s,story),false);assert.equal(e.restore(JSON.stringify(s),T).error,undefined);}});
test('malformed story saves reject invalid choice, timestamps and excess stages',()=>{const s=rich();for(const records of [[{choice:'hack',at:T}],[{choice:'wait',at:-1}],Array(4).fill({choice:'wait',at:T})]){s.stories={orchid:records};assert.equal(e.restore(JSON.stringify(s),T).error,true);}});

test('expanded districts allow formerly blocked upper ground and middle paths',()=>{const s=rich();for(let area=0;area<4;area++){assert.equal(e.canLand(s,'orchid',area,60,20,false),true);assert.equal(e.canLand(s,'orchid',area,50,60,false),true);}});
