import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';
const c=JSON.parse(readFileSync(new URL('../src/content/content.json',import.meta.url))),e=createRequire(import.meta.url)('../src/engine.js')(c),T=1800000000000;
function lake(){return Object.assign(e.fresh(T),{coins:5000,xp:5000,expansion:7,maps:[0,1],map:1,lakeEdition:7});}
test('new lake unlock opts into shoreline while existing layouts remain unchanged',()=>{const s=lake();delete s.lakeEdition;const before=JSON.stringify(s);assert.deepEqual(e.restore(before,T).state,s);assert.equal(e.lakeNew(s),false);assert.ok(e.act(s,{type:'lakeEdition',edition:7},T).ok);assert.ok(e.lakeNew(s));assert.ok(e.act(s,{type:'lakeEdition',edition:6},T).ok);});
test('fixed water blocks land scenery, permits water assets and preserves coins on failed purchase',()=>{const s=lake(),money=s.coins;assert.equal(e.landReason(s,'bamboo',1,65,90,false),'lakeWater');assert.equal(e.act(s,{type:'buy',item:'bamboo',area:1,x:65,y:90},T).ok,false);assert.equal(s.coins,money);assert.ok(e.act(s,{type:'buy',item:'lotus',area:1,x:65,y:90},T).ok);assert.equal(e.act(s,{type:'ground',kind:'path',points:[[40,40],[85,40]]},T).error,'lakeGround');});
test('legacy conflict prevents adoption without moving assets, reversible switch after storage',()=>{const s=lake();s.lakeEdition=6;assert.ok(e.act(s,{type:'buy',item:'bamboo',area:1,x:65,y:90},T).ok);const before=JSON.stringify(s.objects);assert.equal(e.lakeConflicts(s).objects.length,1);assert.equal(e.act(s,{type:'lakeEdition',edition:7},T).ok,false);assert.equal(JSON.stringify(s.objects),before);assert.equal(s.lakeEdition,6);e.act(s,{type:'store',uid:1},T);assert.ok(e.act(s,{type:'lakeEdition',edition:7},T).ok);assert.equal(s.objects.length,1);});
test('paid repair charges disclosed cost once and each reward is receipted',()=>{const s=lake(),money=s.coins;assert.ok(e.act(s,{type:'harborPay'},T).ok);assert.equal(s.coins,money-c.harbor.cost+c.harbor.bonus);assert.equal(e.act(s,{type:'harborPay'},T).ok,false);assert.ok(e.act(s,{type:'harborGift'},T).ok);assert.equal(s.objects[0].gift,'harbor');assert.equal(e.act(s,{type:'harborGift'},T).ok,false);assert.deepEqual(e.restore(JSON.stringify(s),T).state,s);});
test('manual repair requires rope, persists partial progress and mistakes defer only recoverable bonus',()=>{const s=lake();assert.equal(e.act(s,{type:'harborStep',step:0,answer:1},T).error,'harborRope');e.act(s,{type:'find',id:'rope'},T);const money=s.coins;assert.ok(e.act(s,{type:'harborStep',step:0,answer:0},T).miss);assert.equal(s.coins,money);assert.equal(s.harbor.step,0);for(let k=0;k<c.harbor.steps.length;k++){assert.ok(e.act(s,{type:'harborStep',step:k,answer:c.harbor.steps[k].answer},T).ok);assert.deepEqual(e.restore(JSON.stringify(s),T).state,s);}assert.equal(s.coins,money);assert.equal(s.harbor.bonus,false);assert.ok(e.act(s,{type:'harborBonus'},T).ok);assert.equal(s.coins,money+c.harbor.bonus);assert.equal(e.act(s,{type:'harborBonus'},T-1000).ok,false);});
test('correct manual route grants same collectible without construction fee',()=>{const s=lake();s.found=['rope'];const money=s.coins;for(let k=0;k<c.harbor.steps.length;k++)e.act(s,{type:'harborStep',step:k,answer:c.harbor.steps[k].answer},T);assert.equal(s.coins,money+c.harbor.bonus);assert.equal(s.harbor.route,'manual');assert.ok(e.act(s,{type:'harborGift'},T).ok);});
test('guest branches have different economic consequences; unavailable money cannot mutate choice',()=>{for(const choice of ['shelter','ferry']){const s=lake();assert.equal(e.act(s,{type:'harborGuest',choice,answer:0},T).ok,false);e.act(s,{type:'harborPay'},T);s.coins=0;if(choice==='shelter'){assert.equal(e.act(s,{type:'harborGuest',choice},T).error,'noMoney');assert.equal(s.harbor.guest,'');s.coins=200;}const before=s.coins;assert.ok(e.act(s,{type:'harborGuest',choice,answer:0},T).ok);assert.equal(s.coins,before+(choice==='ferry'?c.harbor.guestReward:-c.harbor.guestCost));assert.equal(e.act(s,{type:'harborGuest',choice,answer:0},T).ok,false);assert.deepEqual(e.restore(JSON.stringify(s),T).state,s);}});
test('offline and map switching cause no penalty and cannot replay rewards',()=>{const s=lake();e.act(s,{type:'harborPay'},T);const money=s.coins;e.act(s,{type:'visitMap',id:0},T);assert.equal(e.act(s,{type:'harborGift'},T).ok,false);e.advance(s,T+86400000);assert.equal(s.coins,money);e.act(s,{type:'visitMap',id:1},T+86400000);e.act(s,{type:'harborGift'},T+86400000);assert.equal(e.act(s,{type:'harborGift'},T).ok,false);});
test('malformed harbor receipts and duplicate cosmetic gifts cannot restore',()=>{const s=lake();e.act(s,{type:'harborPay'},T);e.act(s,{type:'harborGift'},T);s.harbor.step=0;assert.equal(e.restore(JSON.stringify(s),T).error,true);s.harbor.step=3;s.objects.push({...s.objects[0],uid:s.nextId++});assert.equal(e.restore(JSON.stringify(s),T).error,true);});
