import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),c=JSON.parse(readFileSync(new URL('../src/content/content.json',import.meta.url),'utf8')),e=require('../src/engine.js')(c),T=1800000000000;
function rich(){const s=e.fresh(T);s.coins=1e9;s.xp=5000;s.expansion=7;return s;}
test('every scenery has independent proportions, role and composition guidance',()=>{for(const i of c.items){assert.ok(i.visual.width>0&&i.visual.height>0&&i.visual.anchor>0&&i.visual.anchor<=100);assert.ok(i.visual.guide.length>10);assert.ok(i.visual.role);}assert.ok(e.items.bamboo.visual.height>e.items.orchid.visual.height*2.5);assert.ok(e.items.library.visual.width>e.items.lantern.visual.width*3);assert.equal(c.items.filter(i=>i.variants).reduce((n,i)=>n+i.variants.length,0),18);});
test('all plant styles and sizes fit, persist and retain equal base income',()=>{for(const i of c.items.filter(i=>i.variants))for(let variant=0;variant<3;variant++)for(let size=0;size<3;size++){const s=rich(),look={variant,size},p=e.suggest(s,i.id,0,false,undefined,0,look);assert.ok(p);assert.equal(e.act(s,Object.assign({type:'buy',item:i.id},look,p),T).ok,true);assert.equal(e.rate(s),c.tiers[i.tier-1].income);assert.deepEqual(e.restore(JSON.stringify(s),T).state,s);}});
test('style changes are free and stored scenery keeps chosen appearance',()=>{const s=rich();e.act(s,{type:'buy',item:'bamboo',area:0,x:45,y:65},T);const o=s.objects[0],money=s.coins;assert.equal(e.act(s,{type:'move',uid:o.uid,area:0,x:45,y:65,variant:2,size:2},T).ok,true);assert.equal(s.coins,money);assert.equal(e.rate(s),5);e.act(s,{type:'store',uid:o.uid},T);assert.equal(o.variant,2);assert.equal(o.size,2);const p=e.suggest(s,'bamboo',2,false,o.uid,0,o);assert.equal(e.act(s,Object.assign({type:'move',uid:o.uid},p),T).ok,true);assert.equal(o.variant,2);assert.equal(o.size,2);});
test('larger silhouettes have larger ground footprints and cannot overwrite neighbours',()=>{const s=rich();e.act(s,{type:'buy',item:'bamboo',area:0,x:35,y:65},T);e.act(s,{type:'buy',item:'lantern',area:0,x:42,y:65},T);assert.equal(s.objects.length,2);const before=JSON.stringify(s.objects);assert.equal(e.act(s,{type:'move',uid:1,area:0,x:35,y:65,variant:2,size:2},T).ok,false);assert.equal(JSON.stringify(s.objects),before);});
test('invalid appearance fails actions and save validation',()=>{for(const look of [{variant:8},{variant:-1},{variant:1.5},{size:3},{size:null},{size:-1}]){const s=rich();assert.equal(e.act(s,Object.assign({type:'buy',item:'bamboo',area:0,x:45,y:65},look),T).error,'badAppearance');assert.equal(s.objects.length,0);e.act(s,{type:'buy',item:'bamboo',area:0,x:45,y:65},T);Object.assign(s.objects[0],look);assert.equal(e.restore(JSON.stringify(s),T).error,true);}});
test('expanded capacity starts at eighteen and grows to one hundred forty four',()=>{const s=e.fresh(T);assert.equal(e.capacity(s,0),18);assert.equal(e.capacity(s,1),0);s.expansion=7;assert.equal([0,1,2,3].reduce((n,a)=>n+e.capacity(s,a),0),144);});
test('old coordinate saves without appearance fields keep all assets and coins',()=>{const s=rich();for(const [item,x,y] of [['bamboo',20,50],['orchid',40,60],['library',65,70]])e.act(s,{type:'buy',item,area:0,x,y},T);const r=e.restore(JSON.stringify(s),T);assert.equal(r.error,undefined);assert.deepEqual(r.state,s);});
