import {pathToFileURL} from 'node:url';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
await mkdir('test-results',{recursive:true});const report={layouts:[],errors:[],requests:[],game:{}};
const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1});
await context.addInitScript(()=>{const Original=window.AudioContext;window.__qaAudio=[];window.AudioContext=class extends Original{constructor(...a){super(...a);window.__qaCtx=this;}createBufferSource(){const source=super.createBufferSource();const start=source.start.bind(source);source.start=(...args)=>{window.__qaAudio.push({when:args[0],offset:args[1]||0});return start(...args);};return source;}};});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4313')&&!r.url().startsWith('data:'))report.requests.push(r.url());});
for(const width of [375,390,430]){await page.setViewportSize({width,height:844});await page.goto('http://127.0.0.1:4313');await page.waitForSelector('#start');await page.evaluate(()=>document.documentElement.style.setProperty('--safe-area-inset-top','32px'));await page.screenshot({path:`test-results/home-${width}.png`,fullPage:true});const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,headerTop:document.querySelector('.brand').getBoundingClientRect().top}));assert.ok(layout.scroll<=width);assert.ok(layout.headerTop>=32);report.layouts.push(layout);await page.click('#settings');await page.locator('#offset').fill('50');await page.locator('#offset').dispatchEvent('input');await page.click('[data-close]');await page.reload();await page.click('#settings');assert.equal(await page.locator('#offset').inputValue(),'50');await page.click('#reset');await page.click('[data-close]');}
await page.setViewportSize({width:390,height:844});await page.click('#practice');await page.waitForSelector('#notes');await page.waitForFunction(()=>document.querySelector('#countdown').hidden,{timeout:15000});await page.evaluate(()=>document.documentElement.style.setProperty('--safe-area-inset-top','32px'));const gameLayout=await page.evaluate(()=>({height:innerHeight,scroll:document.documentElement.scrollHeight,pauseTop:document.querySelector('#pause').getBoundingClientRect().top,keys:[...document.querySelectorAll('[data-lane]')].map(e=>({width:e.getBoundingClientRect().width,bottom:e.getBoundingClientRect().bottom}))}));assert.ok(gameLayout.pauseTop>=32);assert.ok(gameLayout.keys.every(k=>k.width>=44&&k.bottom<=gameLayout.height));report.game.layout=gameLayout;
// Real Chromium touch events exercise independent pointer capture and release.
const cdp=await context.newCDPSession(page);const points=await page.locator('[data-lane]').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};}));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...points[1],id:1},{...points[2],id:2}]});assert.equal(await page.locator('.lane-key.pressed').count(),2);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...points[2],id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.locator('.lane-key.pressed').count(),0);
await page.click('#pause');const paused=await page.locator('#elapsed').textContent();await page.waitForTimeout(500);assert.equal(await page.locator('#elapsed').textContent(),paused);await page.click('#resume');await page.waitForFunction(()=>document.querySelector('#countdown').hidden,{timeout:10000});await page.keyboard.press('Space');assert.equal(await page.locator('#pause-panel').isVisible(),true);await page.click('#home');
// Full uncut song via actual Web Audio clock and real app keyboard handlers.
await page.click('#start');await page.waitForSelector('#notes');await page.evaluate(async()=>{const c=await fetch('src/content/content.json').then(r=>r.json());let index=0;const releases=[];const keys=c.lanes.map(l=>'Key'+l.key);window.__qaRun={fired:0,expected:c.notes.length,screens:[],done:false};function bot(){if(!document.querySelector('#notes')){window.__qaRun.done=true;return;}const s=window.__qaAudio.at(-1),t=window.__qaCtx.currentTime-s.when+s.offset;if(document.querySelector('#countdown').hidden){while(index<c.notes.length&&c.notes[index].time<=t){const n=c.notes[index++];document.dispatchEvent(new KeyboardEvent('keydown',{code:keys[n.lane],bubbles:true}));releases.push({at:n.time+(n.duration||.06)+.025,lane:n.lane});window.__qaRun.fired++;}for(let i=releases.length-1;i>=0;i--){if(t>=releases[i].at){document.dispatchEvent(new KeyboardEvent('keyup',{code:keys[releases[i].lane],bubbles:true}));releases.splice(i,1);}}}requestAnimationFrame(bot);}requestAnimationFrame(bot);});
await page.waitForFunction(()=>window.__qaCtx.currentTime-window.__qaAudio.at(-1).when>19,{timeout:30000});await page.screenshot({path:'test-results/game-hold-390.png'});console.log('Responsive, persistence, touch, pause passed; full song running.');
await page.waitForSelector('.result',{timeout:100000});report.game.result=await page.locator('.result-content').innerText();report.game.bot=await page.evaluate(()=>window.__qaRun);await page.screenshot({path:'test-results/result-390.png',fullPage:true});assert.ok(report.game.result.includes('100.0')||report.game.result.includes('99.')||report.game.result.includes('98.'),'full-play accuracy unexpectedly low');assert.equal(report.game.bot.fired,report.game.bot.expected);assert.deepEqual(report.errors,[]);assert.deepEqual(report.requests,[]);await writeFile('test-results/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
