import {pathToFileURL} from 'node:url';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});await mkdir('test-results',{recursive:true});const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1});const errors=[],badResponses=[];
await context.addInitScript(()=>{const AC=window.AudioContext;window.AudioContext=class extends AC{constructor(...a){super(...a);window.qaCtx=this;}createBufferSource(){const s=super.createBufferSource(),start=s.start.bind(s);s.start=(...a)=>{window.qaStart={when:a[0],offset:a[1]||0};return start(...a);};return s;}};});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)badResponses.push(r.url());});
await page.goto((process.env.QA_BASE_URL||'http://127.0.0.1:4313'));await page.waitForSelector('#start');await page.evaluate(async()=>{const c=await fetch('src/content/content.json').then(r=>r.json());await Promise.all(c.cast.map(p=>new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=reject;im.src=p.art;})));});
for(const width of [375,390,430]){await page.setViewportSize({width,height:844});await page.evaluate(()=>document.documentElement.style.setProperty('--safe-area-inset-top','32px'));await page.screenshot({path:`test-results/final-home-${width}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);}
await page.setViewportSize({width:390,height:844});await page.click('#start');await page.waitForSelector('#notes');await page.evaluate(async()=>{const c=await fetch('src/content/content.json').then(r=>r.json());let idx=0;const ups=[];function bot(){if(!document.querySelector('#notes'))return;const t=window.qaCtx.currentTime-window.qaStart.when+window.qaStart.offset;if(document.querySelector('#countdown').hidden&&!document.querySelector('#pause-panel').hidden)return;if(document.querySelector('#countdown').hidden){while(idx<c.notes.length&&c.notes[idx].time<=t){const n=c.notes[idx++];document.dispatchEvent(new KeyboardEvent('keydown',{code:'Key'+c.lanes[n.lane].key}));ups.push({time:n.time+(n.duration||.07)+.02,lane:n.lane});}for(let i=ups.length-1;i>=0;i--)if(ups[i].time<=t){document.dispatchEvent(new KeyboardEvent('keyup',{code:'Key'+c.lanes[ups[i].lane].key}));ups.splice(i,1);}}requestAnimationFrame(bot);}requestAnimationFrame(bot);});
await page.waitForFunction(()=>window.qaCtx.currentTime-window.qaStart.when>26.3,null,{timeout:40000});const expectedFrozen=await page.evaluate(async()=>{const c=await fetch('src/content/content.json').then(r=>r.json());return c.phrases.filter(p=>p.end<=26).length;});assert.equal(Number(await page.locator('#frozen-count').textContent()),expectedFrozen);await page.screenshot({path:'test-results/final-double-hold-390.png'});await page.click('#pause');const layouts=[];for(const width of [375,390,430]){await page.setViewportSize({width,height:844});const m=await page.evaluate(()=>({width:innerWidth,scrollW:document.documentElement.scrollWidth,scrollH:document.documentElement.scrollHeight,pauseTop:document.querySelector('#pause').getBoundingClientRect().top,keys:[...document.querySelectorAll('[data-lane]')].map(e=>{const r=e.getBoundingClientRect();return {width:r.width,bottom:r.bottom};})}));assert.equal(m.scrollW,width);assert.ok(m.scrollH<=844);assert.ok(m.pauseTop>=32);assert.ok(m.keys.every(k=>k.width>=44&&k.bottom<=844));layouts.push(m);await page.screenshot({path:`test-results/final-pause-${width}.png`});}
await page.setViewportSize({width:375,height:667});assert.ok(await page.evaluate(()=>document.querySelector('.lane-key').getBoundingClientRect().bottom<=innerHeight));await page.click('#home');
// Audio failure path and denied storage remain usable.
const failed=await browser.newContext();await failed.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Denied','SecurityError');}});});const p=await failed.newPage();await p.route('**/*.m4a',route=>route.fulfill({status:404,body:''}));await p.goto((process.env.QA_BASE_URL||'http://127.0.0.1:4313'));await p.click('#start');await p.waitForSelector('dialog');assert.ok((await p.locator('dialog').innerText()).includes('加载失败'));await p.click('[data-close]');assert.equal(await p.locator('#start').isEnabled(),true);await failed.close();
assert.deepEqual(errors,[]);assert.deepEqual(badResponses,[]);const report={layouts,errors,badResponses,shortViewport:true,audioFailure:true,storageDenied:true};await writeFile('test-results/final-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
