import {pathToFileURL} from 'node:url';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});
await context.addInitScript(()=>{const AC=window.AudioContext;window.__audioStarts=[];window.AudioContext=class extends AC{constructor(...a){super(...a);window.__audio=this;}getOutputTimestamp(){return {contextTime:Math.max(0,this.currentTime-.12),performanceTime:performance.now()};}createBufferSource(){const s=super.createBufferSource(),start=s.start.bind(s);s.start=(when,offset=0,...rest)=>{window.__audioStarts.push({when,offset});return start(when,offset,...rest);};return s;}};localStorage.setItem('tongfu-rhythm-v1',JSON.stringify({syncVersion:3,settings:{volume:0,sfx:false,guide:false,offset:0,visualOffset:0,speed:1}}));});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('test-results',{recursive:true});await page.goto((process.env.QA_BASE_URL||'http://127.0.0.1:4313'));
await page.click('#rap-practice');await page.waitForSelector('#notes');assert.equal(await page.evaluate(()=>window.__audioStarts.at(-1).offset),32.7);await page.click('#pause');await page.click('#restart');await page.waitForSelector('#notes');assert.equal(await page.evaluate(()=>window.__audioStarts.at(-1).offset),32.7);await page.evaluate(async()=>{const c=await fetch('src/content/content.json').then(r=>r.json());c.notes=c.notes.filter(n=>n.time>=c.rapPracticeRange.start&&n.time+n.duration<c.rapPracticeRange.end);let index=0;const ups=[];window.__run={fired:0,expected:c.notes.length,maxClockLead:0};function bot(){if(!document.querySelector('#notes'))return;const s=window.__audioStarts.at(-1),t=window.__audio.getOutputTimestamp().contextTime-s.when+s.offset;if(document.querySelector('#countdown').hidden&&document.querySelector('#pause-panel').hidden){while(index<c.notes.length&&c.notes[index].time<=t){const n=c.notes[index++];document.dispatchEvent(new KeyboardEvent('keydown',{code:'Key'+c.lanes[n.lane].key,bubbles:true}));ups.push({at:n.time+(n.duration||.03)+.015,lane:n.lane});window.__run.fired++;}for(let i=ups.length-1;i>=0;i--)if(t>=ups[i].at){document.dispatchEvent(new KeyboardEvent('keyup',{code:'Key'+c.lanes[ups[i].lane].key,bubbles:true}));ups.splice(i,1);}}requestAnimationFrame(bot);}requestAnimationFrame(bot);});
await page.waitForFunction(()=>window.__run.fired>30,null,{timeout:50000});await page.screenshot({path:'test-results/rap-game-390.png'});console.log('Rap practice passed first half; continuing.');await page.waitForSelector('.result',{timeout:100000});
const result=await page.locator('.result-content').innerText(),run=await page.evaluate(()=>window.__run);assert.equal(run.fired,run.expected);assert.ok(result.includes('100.0%'),result);assert.deepEqual(errors,[]);await page.screenshot({path:'test-results/rap-result-390.png',fullPage:true});await writeFile('test-results/rap-play-report.json',JSON.stringify({simulatedQueueMs:120,result,run,errors},null,2));console.log(JSON.stringify({result,run,errors}));await browser.close();
