/* Development-only input replay. This file is never included in dist or the release ZIP. */
const fixtureControls=document.createElement('div');fixtureControls.id='qa-controls';fixtureControls.style.cssText='position:fixed;z-index:100;bottom:0;left:0;right:0;display:flex;background:#192d24;font:10px sans-serif;';document.body.appendChild(fixtureControls);
function fixtureButton(label,action){const b=document.createElement('button');b.textContent=label;b.style.cssText='font-size:10px;padding:4px 7px;min-height:32px;flex:1';b.onclick=action;fixtureControls.appendChild(b);}
fixtureButton('QA 清空测试局',()=>{localStorage.setItem('qa-next','empty');location.reload();});
fixtureButton('QA 洗净样本',()=>{localStorage.setItem('qa-next','ready');location.reload();});
fixtureButton('QA 安全区',()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');for(const side of ['left','right']){const host=document.createElement('div');host.className='qa-host';host.textContent='宿主按钮占位';host.style.cssText='position:fixed;z-index:80;top:44px;width:94px;height:48px;background:#ce384977;color:white;font:11px sans-serif;text-align:center;'+side+':0';document.body.appendChild(host);}});
fixtureButton('QA 手势回放',async()=>{if(document.getElementById('app').dataset.stage!=='shore')return;fixtureControls.style.pointerEvents='none';const note=document.createElement('output');note.style.cssText='position:fixed;z-index:101;bottom:34px;left:5px;color:#fff;background:#21392c;font:11px sans-serif';document.body.appendChild(note);const app=document.getElementById('app'),w=innerWidth,h=innerHeight,p={x:w*.5,y:h>w?h*.54:h*.55,r:Math.min(w*.43,h*.33),sy:.77},sleep=ms=>new Promise(r=>setTimeout(r,ms));let id=601;const event=(type,x,y)=>app.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,pointerType:'touch',isPrimary:true,button:0,buttons:type==='pointerup'?0:1,clientX:x,clientY:y}));
 try{note.textContent='输入回放：取半铲';event('pointerdown',p.x-40,p.y);for(let i=1;i<=30;i++){event('pointermove',p.x-40+i*4,p.y);await sleep(20);}event('pointerup',p.x+80,p.y);for(let i=0;i<200&&app.dataset.stage==='loading';i++)await sleep(100);note.textContent='输入回放：浸水';id++;event('pointerdown',p.x,p.y);event('pointermove',p.x,p.y+w*.23);for(let i=0;i<120&&!document.getElementById('status').textContent.includes('水已浸满');i++)await sleep(100);event('pointerup',p.x,p.y+w*.23);await sleep(80);
 for(let cycle=0;cycle<9&&app.dataset.stage==='wash';cycle++){note.textContent='输入回放：分层 / 倾洗 '+(cycle+1);if(cycle>0){id++;event('pointerdown',p.x,p.y);event('pointermove',p.x,p.y+w*.23);await sleep(3000);event('pointerup',p.x,p.y+w*.23);await sleep(500);}id++;const radius=p.r*.55;event('pointerdown',p.x+radius,p.y);for(let i=1;i<=400&&app.dataset.stage==='wash';i++){const a=i*.048;event('pointermove',p.x+Math.cos(a)*radius,p.y+Math.sin(a)*radius*p.sy);await sleep(20);}event('pointerup',p.x+radius,p.y);id++;const y=p.y+p.r*p.sy*.75;event('pointerdown',p.x,y);event('pointermove',p.x,y+8+p.r*.58);for(let i=0;i<300&&app.dataset.stage==='wash';i++)await sleep(20);event('pointerup',p.x,y+8+p.r*.58);await sleep(80);}
 note.textContent='输入回放结果：'+app.dataset.stage;
 }finally{fixtureControls.style.pointerEvents='auto';}
});
fixtureButton('QA 音频字节',async()=>{const result=document.createElement('output');result.style.cssText='position:fixed;z-index:102;bottom:40px;left:0;background:#15382a;color:white;font:12px sans-serif';document.body.appendChild(result);const A=window.AudioContext||window.webkitAudioContext;if(!A){result.textContent='音频能力不可用';return;}const ctx=new A();try{await ctx.resume();let count=0,duration=0;for(const [id,encoded] of Object.entries(window.CREEK_AUDIO||{})){const raw=atob(encoded),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const buffer=await new Promise((yes,no)=>ctx.decodeAudioData(bytes.buffer,yes,no));count++;duration+=buffer.duration;if(id==='water-0'){const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;gain.gain.value=.06;source.connect(gain);gain.connect(ctx.destination);source.onended=()=>{source.disconnect();gain.disconnect();};source.start();}}result.textContent='真实音频解码 '+count+'/9 · '+duration.toFixed(2)+' 秒 · 已播放水声';}catch{result.textContent='真实音频解码失败';}finally{setTimeout(()=>ctx.close(),1500);}});
fixtureButton('QA Canvas',()=>{localStorage.setItem('qa-render','canvas');location.reload();});
fixtureButton('QA 水流帧差',async()=>{const canvas=document.getElementById('scene'),ctx=canvas.getContext('2d'),x=Math.round(canvas.width*.35),y=Math.round(canvas.height*.34),w=Math.round(canvas.width*.3),h=Math.round(canvas.height*.04),a=ctx.getImageData(x,y,w,h).data;await new Promise(r=>setTimeout(r,900));const b=ctx.getImageData(x,y,w,h).data;let changed=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>8)changed++;const o=document.createElement('output');o.style.cssText='position:fixed;bottom:70px;left:0;background:#15382a;color:white;z-index:105';o.textContent='水流区域帧差 '+Math.round(changed/(w*h)*100)+'%';document.body.appendChild(o);});
fixtureButton('QA 初露晶体',()=>{localStorage.setItem('qa-next','exposed');location.reload();});
