import {escapeHtml as e,elapsedLabel,makeStudio,normalizeStudio,personUsed,randomReactionIds,recordCall,suggestNickname,suggestAvatar,switchChatMode,monthDays} from './model.mjs';
import embeddedAudio from 'embedded-audio';
import {createAudioBank} from './audio-bank.mjs';
import content from './content/content.json';
import {captureSurface,albumBridge} from './export-image.mjs';
import {createCallPlayer} from './call-player.mjs';
const app=document.querySelector('#app');
const data=content;
if(!data){app.innerHTML='<main class="page"><h1>页面暂时打不开</h1><p>请刷新重试。</p></main>';throw Error('Content unavailable');}
const STORAGE='call-stories:studio-v2';
let studio;try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'null');studio=normalizeStudio(raw,data);}catch{studio=makeStudio(data);}
const state={tab:'story',screen:'home',editPerson:null,picker:null,seconds:0,segment:0,phase:'speaking',muted:false,toast:'',countdown:0,momentMenu:false,commenting:false,commentPerson:null,commentDraft:'',commentPeople:false};
const photos=new Map();let momentImages=[],coverPhoto=null;let clock=null,arrival=null,toastTimer=null;
const audioBank=createAudioBank(embeddedAudio);
const player=createCallPlayer({audioFactory:audioBank.create});
const ring=audioBank.create(data.ringtone.file);ring.loop=true;let ringSession=0;
function stopRing(){ringSession++;ring.pause();ring.currentTime=0;}
function startRing(){if(!studio.call.ringtone)return;const session=++ringSession;ring.volume=studio.call.delay?0:1;ring.play().catch(()=>{if(session===ringSession&&['incoming','countdown'].includes(state.screen))toast(data.ringtone.blocked);});}

const person=id=>studio.people.find(p=>p.id===id)||studio.people[0];
const script=()=>data.callScripts.find(s=>s.id===studio.call.scriptId)||data.callScripts[0];
const personOptions=id=>studio.people.filter(p=>studio.chat.members.includes(p.id)).map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${e(p.name)}</option>`).join('');
function icon(name){const paths={mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0ZM5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8',hangup:'M3 15v-4c5-5 13-5 18 0v4h-4v-4a17 17 0 0 0-10 0v4Z',phone:'M6.6 3.7c.5-.5 1.2-.6 1.8-.2l2.1 1.5c.6.4.8 1.2.4 1.8L9.7 8.8a14 14 0 0 0 5.5 5.5l1.9-1.2c.6-.4 1.4-.2 1.8.4l1.5 2.1c.4.6.3 1.3-.2 1.8l-1.5 1.5c-.8.8-2 1.1-3.1.7A19.5 19.5 0 0 1 4.4 8.4c-.4-1.1-.1-2.3.7-3.1z',back:'m14 5-7 7 7 7',plus:'M12 5v14M5 12h14',chat:'M21 11a8 8 0 0 1-8 8H5l-3 3v-9a9 9 0 1 1 19-2Z',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 4a4 4 0 0 1 0 8m1 3a4 4 0 0 1 4 4v2',home:'m3 10 9-7 9 7v11h-6v-7H9v7H3Z',circle:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 3v9l6 6M3 12h9',camera:'M3 6h4l2-3h6l2 3h4v14H3ZM16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',smile:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M8 14c2 3 6 3 8 0M8 9h.01M16 9h.01',sound:'m11 4-6 4H2v8h3l6 4ZM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',mute:'m11 4-6 4H2v8h3l6 4ZM16 9l6 6m0-6-6 6',voice:'M8 8a6 6 0 0 1 0 8M12 5a10 10 0 0 1 0 14M16 2a14 14 0 0 1 0 20',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',dots:'M5 12h.01M12 12h.01M19 12h.01',check:'m5 12 4 4L19 6',edit:'m15 3 6 6-12 12H3v-6ZM12 6l6 6',close:'m6 6 12 12M18 6 6 18'};return `<svg viewBox="0 0 24 24" fill="${name==='phone'?'currentColor':'none'}" stroke="currentColor" stroke-width="${name==='dots'?3:1.65}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.circle}"/></svg>`;}
function avatar(id,size='normal'){const p=person(id),a=data.avatars.find(x=>x.id===p.avatar)||data.avatars[0];return `<span class="avatar ${size}"><img src="${photos.get(id)||a.path||`./assets/avatars/${a.id}.svg`}" alt=""></span>`;}
function save(){studio=normalizeStudio(studio,data);try{localStorage.setItem(STORAGE,JSON.stringify(studio));}catch{toast('文字草稿未能保存，请检查浏览器存储。');}}
function toast(text){state.toast=text;clearTimeout(toastTimer);render();toastTimer=setTimeout(()=>{state.toast='';render();},2600);}
function header(kicker,title,sub=''){return `<header class="page-head"><p class="eyebrow">${e(kicker)}</p><h1>${e(title)}</h1>${sub?`<p class="head-sub">${e(sub)}</p>`:''}</header>`;}
function nav(){return `<nav class="bottom-nav" aria-label="主要页面">${['story','chat','moment','person'].map((tab,i)=>`<button data-tab="${tab}" class="${state.tab===tab?'active':''}" aria-current="${state.tab===tab?'page':'false'}">${icon(['home','chat','circle','people'][i])}${e(data.ui.tabs[i])}</button>`).join('')}</nav>`;}
function pickRow(label,id,target){return `<button class="person-pick" data-pick="${target}">${avatar(id,'small')}<span><small>${label}</small><strong>${e(person(id).name)}</strong></span><em>选择 ${icon('back')}</em></button>`;}
function home(){return `<img class="brand-logo" src="./assets/logo.svg" alt="">${header('FOUND PHONE STORIES',data.product.name,data.product.tagline)}<section class="studio-hero"><div class="hero-caption">${icon('phone')}<span>${e(data.ui.currentCall)}</span></div><div class="hero-bubbles">${data.product.heroLines.map(line=>`<span>${e(line)}</span>`).join('')}</div><div class="hero-call">${avatar(studio.call.personId,'small')}<div><strong>${e(person(studio.call.personId).name)}</strong><small>${e(script().title)}</small></div><button data-action="start">${e(data.ui.startCall)} ${icon('phone')}</button></div></section><div class="section-title"><h2>从一个画面开始</h2><span>四个创作入口</span></div><div class="studio-formats"><button data-action="edit-call">${icon('phone')}<strong>来电与通话</strong><small>选好人物，接起这通电话</small><em>01</em></button><button data-tab="chat">${icon('chat')}<strong>聊天记录</strong><small>每句对白，都由你来安排</small><em>02</em></button><button data-tab="moment">${icon('circle')}<strong>朋友圈</strong><small>动态、照片、点赞和评论</small><em>03</em></button><button data-tab="person">${icon('people')}<strong>人物库</strong><small>${studio.people.length} 位人物，随时加入故事</small><em>04</em></button></div>`;}
function callEditor(){const s=script(),ready=s.segments.filter(x=>(data.audioFiles||[]).includes(x.file)).length;return `${header('VOICE CALL','设定一通来电','选择录好的台词，让对方自然地说下去。')}<div class="editor-card">${pickRow('来电人',studio.call.personId,'call')}</div><div class="editor-card form-card"><label>配音场景<select data-call="scriptId">${data.callScripts.map(x=>`<option value="${x.id}" ${x.id===s.id?'selected':''}>${e(x.optionLabel)}</option>`).join('')}</select></label><div class="audio-readiness">${ready===s.segments.length?'配音已就绪':`配音待放入 · ${ready}/${s.segments.length} 段`}<small>${ready===s.segments.length?'接听后自动播放录音':'当前可体验界面和停顿节奏'}</small></div><details class="script-details"><summary>查看通话台词</summary><div class="script-lines">${s.segments.map((x,i)=>`<p><span>${String(i+1).padStart(2,'0')}</span>${e(x.text)}<small>${i===s.segments.length-1?(s.autoEnd?'说完后自动结束':'说完后保持通话'):`随后停顿 ${x.pause} 秒`}</small></p>`).join('')}</div></details><details class="optional-settings"><summary>更多设置</summary><label>播放方式<select data-call="mode"><option value="full" ${studio.call.mode==='full'?'selected':''}>完整通话</option><option value="intro" ${studio.call.mode==='intro'?'selected':''}>只说开场白，然后保持通话</option></select></label><div class="form-pair"><label>句间停顿<select data-call="pause">${[0,3,5,8,10,15].map(n=>`<option value="${n}" ${studio.call.pause===n?'selected':''}>${n?`${n} 秒`:'跟随脚本'}</option>`).join('')}</select></label><label>多久后来电<select data-call="delay">${[0,3,5,10,30].map(n=>`<option value="${n}" ${studio.call.delay===n?'selected':''}>${n?`${n} 秒后`:'立即'}</option>`).join('')}</select></label></div><label class="call-toggle"><input type="checkbox" data-call="ringtone" ${studio.call.ringtone?'checked':''}>${e(data.ringtone.label)}</label><label class="call-toggle"><input type="checkbox" data-call="subtitles" ${studio.call.subtitles?'checked':''}>通话时显示台词</label><p class="field-note">配音按固定台词播放。你可以自然接话；页面不会录音。</p></details></div><button class="primary preview-button" data-action="start">${icon('phone')} 开始模拟来电</button>`;}
function backdrop(){const p=person(studio.call.personId),a=data.avatars.find(x=>x.id===p.avatar)||data.avatars[0];return `<div class="call-backdrop" style="background-image:url('${photos.get(p.id)||a.path||`./assets/avatars/${a.id}.svg`}')"></div>`;}
function callScreen(){const incoming=state.screen==='incoming',p=person(studio.call.personId);return `<div class="call-screen polished-call ${incoming?'incoming':'connected'}" data-phase="${state.phase}">${backdrop()}<div class="call-top"></div><div class="caller">${avatar(p.id,'large')}<h1>${e(p.name)}</h1><p>${incoming?'邀请你语音通话':`<span id="call-clock">${elapsedLabel(state.seconds)}</span>`}</p></div>${!incoming&&studio.call.subtitles?`<div class="call-subtitle" aria-live="polite">${state.phase==='speaking'?e(script().segments[state.segment].text):'…'}</div>`:''}<div class="call-bottom">${incoming?`<div class="call-actions"><button class="call-round decline" data-action="decline"><span>${icon('hangup')}</span><small>拒绝</small></button><button class="call-round accept" data-action="accept"><span>${icon('phone')}</span><small>接听</small></button></div>`:`<div class="connected-actions"><button class="sound-control ${state.muted?'muted':''}" data-action="sound" aria-pressed="${state.muted}">${icon(state.muted?'mute':'sound')}<span>${state.muted?'声音已关闭':'声音开启'}</span></button><button class="call-round decline" data-action="hangup"><span>${icon('hangup')}</span><small>挂断</small></button></div>`}</div></div>`;}
function chatEditor(){const ch=studio.chat,group=ch.mode==='group';return `${header('CHAT STUDIO','编排一段聊天','从人物库选好角色，再写下他们的对白。')}<div class="chat-modes"><button data-chat-mode="private" class="${!group?'selected':''}">${e(data.ui.privateChat)}</button><button data-chat-mode="group" class="${group?'selected':''}">${e(data.ui.groupChat)}</button></div><div class="editor-card">${group?'':pickRow('聊天对象',ch.personId,'chat')}${pickRow('右侧的我',ch.selfId,'self')}${group?`<details class="group-members"><summary>${e(data.ui.groupMembers)} · ${ch.members.length} 人</summary><div>${studio.people.map(p=>`<label><input type="checkbox" data-group-member="${p.id}" ${ch.members.includes(p.id)?'checked':''} ${[ch.selfId,ch.personId].includes(p.id)?'disabled':''}>${avatar(p.id,'tiny')}<span>${e(p.name)}</span></label>`).join('')}</div></details>`:''}</div><div class="editor-card form-card"><div class="form-pair chat-settings"><label>${group?'群聊名称':'聊天标题'}<input data-chat="${group?'groupTitle':'title'}" maxlength="32" placeholder="${e(person(ch.personId).name)}" value="${e(group?ch.groupTitle:ch.title)}"></label>${timePicker(ch)}</div></div><div class="editor-card"><div class="card-heading"><span>消息 · ${ch.messages.length}</span><small>${group?'从群成员中选择发言人':'我和对方轮流发言'}</small></div>${ch.messages.map((m,i)=>`<div class="studio-message ${m.personId===ch.selfId?'own-message':''}"><div class="message-person">${avatar(m.personId,'small')}<select data-message-person="${i}" aria-label="第 ${i+1} 条消息的人物">${personOptions(m.personId)}</select><button data-message-up="${i}" ${i===0?'disabled':''} aria-label="上移第 ${i+1} 条消息">↑</button><button data-message-down="${i}" ${i===ch.messages.length-1?'disabled':''} aria-label="下移第 ${i+1} 条消息">↓</button><button data-message-delete="${i}" aria-label="删除第 ${i+1} 条消息">${icon('close')}</button></div><textarea data-message-text="${i}" maxlength="500" aria-label="第 ${i+1} 条消息内容">${e(m.text)}</textarea></div>`).join('')}<div class="add-message-buttons"><button data-action="add-their" ${ch.messages.length>=60?'disabled':''}>＋ 对方说</button><button data-action="add-my" ${ch.messages.length>=60?'disabled':''}>＋ 我来说</button></div></div><button class="primary preview-button" data-action="preview-chat">查看聊天效果 ${icon('chat')}</button>`;}
function surfaceHeader(title,action,right='dots'){return `<header class="social-head"><button data-action="${action}" aria-label="返回编辑">${icon('back')}</button><b>${e(title)}</b><span>${icon(right)}</span></header>`;}
function chatPreview(){const ch=studio.chat,group=ch.mode==='group';return `<div class="social-screen chat-preview ${group?'group-chat':'private-chat'} ${state.screen==='call-chat'?'call-return-chat':''}">${surfaceHeader(group?ch.groupTitle+'（'+ch.members.length+'）':ch.title||person(ch.personId).name,'edit-chat')}<div class="chat-body"><div class="chat-date">${e(ch.time)}</div>${ch.messages.length?ch.messages.map(m=>{const mine=m.personId===ch.selfId;return `<div class="bubble-row ${mine?'me':'them'}">${mine?'':avatar(m.personId,'small')}<div class="message-stack">${group&&!mine?`<small class="bubble-name">${e(person(m.personId).name)}</small>`:''}<p class="bubble ${m.kind==='call'?'call-record':''}">${m.kind==='call'?icon('phone'):''}${e(m.text)}</p></div>${mine?avatar(m.personId,'small'):''}</div>`;}).join(''):'<p class="empty">暂无消息</p>'}</div><div class="chat-fake-input" aria-hidden="true"><span class="voice-circle">${icon('voice')}</span><span class="fake-compose">${icon('mic')}</span>${icon('smile')}<span class="plus-circle">${icon('plus')}</span></div><div class="home-indicator"></div></div>`;}
function momentEditor(){const m=studio.moment;return `${header('MOMENTS STUDIO','安排一条朋友圈','谁发动态、谁点赞、谁评论，都由你选择。')}<div class="editor-card">${pickRow('发布者',m.authorId,'author')}</div><div class="editor-card form-card"><label>动态正文<textarea data-moment="text" maxlength="1000">${e(m.text)}</textarea></label>${momentTimePicker()}<div class="media-picker"><label class="upload-label">${icon('camera')} 添加动态照片<input type="file" data-upload="moment" accept="image/*" multiple></label><label class="upload-label">更换封面<input type="file" data-upload="cover" accept="image/*"></label></div>${momentImages.length?`<div class="edit-photos">${momentImages.map((url,i)=>`<span><img src="${url}" alt="动态照片 ${i+1}"><button data-remove-photo="${i}" aria-label="移除照片 ${i+1}">×</button></span>`).join('')}</div>`:''}${coverPhoto?'<button class="small-link" data-action="remove-cover">恢复默认封面</button>':''}<p class="field-note">照片仅在本次预览使用，刷新后需重新选择。</p></div><div class="editor-card"><div class="card-heading"><span>点赞 · ${m.likes.length}</span><button class="small-link" data-action="random-likes">随机一组</button></div><div class="like-chips">${m.likes.map(id=>`<button data-remove-like="${id}">${avatar(id,'tiny')} ${e(person(id).name)} <span>×</span></button>`).join('')}</div><button class="add-button" data-pick="likes">从人物库选择点赞人</button></div><div class="editor-card"><div class="card-heading"><span>评论 · ${m.comments.length}</span><button class="small-link" data-action="random-comments">随机一组</button></div>${m.comments.map((c,i)=>`<div class="studio-comment"><div class="comment-editor-head">${pickRow('评论人',c.personId,`comment:${i}`)}<button class="comment-delete" data-delete-comment="${i}" aria-label="删除第 ${i+1} 条评论">${icon('close')}</button></div><textarea data-comment-text="${i}" maxlength="300" aria-label="评论 ${i+1}">${e(c.text)}</textarea></div>`).join('')}<button class="add-button" data-pick="new-comment" ${m.comments.length>=60?'disabled':''}>＋ 从人物库添加评论</button></div><button class="primary preview-button" data-action="preview-moment">查看朋友圈效果 ${icon('circle')}</button>`;}
function momentPreview(){const m=studio.moment,p=person(m.authorId);return `<div class="social-screen moment-preview">${surfaceHeader('朋友圈','edit-moment','camera')}<div class="moment-cover ${coverPhoto?'has-photo':''}" ${coverPhoto?`style="background-image:url('${coverPhoto}')"`:''}><div class="cover-person"><strong>${e(p.name)}</strong>${avatar(p.id)}</div></div><article class="post">${avatar(p.id)}<div class="post-main"><h2>${e(p.name)}</h2><p>${e(m.text)}</p>${momentImages.length?`<div class="moment-photo-grid ${momentImages.length===1?'single':''}">${momentImages.map((url,i)=>`<img src="${url}" alt="动态照片 ${i+1}">`).join('')}</div>`:''}<div class="post-meta"><span>${e(m.time)}</span><div class="moment-actions"><button class="moment-more" data-action="moment-menu" aria-label="${e(data.ui.momentActions)}" aria-expanded="${state.momentMenu}"><span><svg viewBox="0 0 24 16" fill="currentColor" aria-hidden="true"><circle cx="8" cy="8" r="2"/><circle cx="16" cy="8" r="2"/></svg></span></button>${state.momentMenu?`<div class="moment-action-menu"><button data-action="moment-like">${icon('heart')}${e(m.likes.includes(studio.chat.selfId)?data.ui.unlike:data.ui.like)}</button><button data-action="moment-comment" ${m.comments.length>=60?'disabled':''}>${icon('chat')}${e(data.ui.comment)}</button></div>`:''}</div></div>${m.likes.length||m.comments.length?`<div class="reaction-box ${m.comments.length?'has-comments':''}">${m.likes.length?`<div class="likes">${icon('heart')} ${e(m.likes.map(id=>person(id).name).join('，'))}</div>`:''}${m.comments.map(c=>`<p class="reaction-comment"><b>${e(person(c.personId).name)}：</b>${e(c.text)}</p>`).join('')}</div>`:''}${state.commenting?momentComposer():''}</div></article></div>`;}
function momentComposer(){const id=state.commentPerson||studio.chat.selfId;return `<div class="moment-composer"><button class="comment-role" data-action="comment-people" aria-expanded="${state.commentPeople}" aria-label="${e(data.ui.commentPerson)}">${avatar(id,'small')}<span><small>${e(data.ui.commentPerson)}</small><strong>${e(person(id).name)}</strong></span><em>${icon('back')}</em></button>${state.commentPeople?`<div class="comment-people" aria-label="${e(data.ui.commentPerson)}">${studio.people.map(p=>`<button data-comment-person="${p.id}" aria-pressed="${p.id===id}">${avatar(p.id,'small')}<span>${e(p.name)}</span>${p.id===id?icon('check'):''}</button>`).join('')}</div>`:''}<textarea data-preview-comment maxlength="300" aria-label="${e(data.ui.comment)}" placeholder="${e(data.ui.commentPlaceholder)}">${e(state.commentDraft)}</textarea><div class="comment-footer"><button data-action="cancel-comment">${e(data.ui.cancel)}</button><button data-action="send-comment" ${state.commentDraft.trim()?'':'disabled'}>${e(data.ui.send)}</button></div></div>`;}
function momentTimePicker(){const t=studio.moment.timeParts;const select=(key,label,count,start=0)=>`<label>${label}<select data-moment-time="${key}">${Array.from({length:count},(_,i)=>`<option value="${i+start}" ${t[key]===i+start?'selected':''}>${key==='weekday'?e(data.timePicker.weekdays[i]):['hour','minute'].includes(key)?String(i+start).padStart(2,'0'):i+start}</option>`).join('')}</select></label>`;return `<div class="moment-time-picker"><label>发布时间<select data-moment-time="format">${data.momentTimePicker.formats.map(f=>`<option value="${f.value}" ${t.format===f.value?'selected':''}>${e(f.label)}</option>`).join('')}</select></label><div class="moment-time-fields">${['minutes','hours','days'].includes(t.format)?select('amount',data.momentTimePicker.formats.find(f=>f.value===t.format).label,t.format==='hours'?23:t.format==='days'?30:59,1):t.format==='now'?'':(t.format==='date'?select('month','月',12,1)+select('day','日',monthDays(t.month),1):t.format==='weekday'?select('weekday','周几',7,1):'')+select('hour','小时',24)+select('minute','分钟',60)}</div><p class="time-example">${e(studio.moment.time)}</p></div>`;}
function peoplePage(){return `${header('CHARACTER LIBRARY','故事里的人','同一位人物，可以出现在来电、聊天、点赞与评论里。')}<div class="library-toolbar"><input type="search" id="person-search" placeholder="搜索名字或人物关系" aria-label="搜索人物"><button class="primary" data-action="add-person">${icon('plus')} 新建</button></div><div class="people-count">${studio.people.length} 位人物 · 名字和头像可修改</div><div class="people-list character-grid">${studio.people.map(p=>`<button class="library-person" data-edit-person="${p.id}" data-search="${e(p.name+' '+p.relation)}">${avatar(p.id)}<span><strong>${e(p.name)}</strong><small>${e(p.relation||'未填写关系')}</small></span>${icon('edit')}</button>`).join('')}</div><p class="search-empty" hidden>没有找到匹配的人物</p>`;}
function personEditor(){const p=person(state.editPerson);return `${header('EDIT CHARACTER','编辑人物','修改会同步到引用这个人物的画面。')}<button class="small-link back-link" data-action="back-people">${icon('back')} 返回人物库</button><div class="person-card">${avatar(p.id,'large')}<div><h2>${e(p.name)}</h2><p>${e(p.relation)}</p></div></div><div class="editor-card form-card"><div class="name-label"><span>显示名字</span><button class="small-link" data-action="suggest-name">换个昵称</button></div><label class="sr-label">显示名字<input data-person="name" maxlength="24" value="${e(p.name)}"></label><label>人物关系<input data-person="relation" maxlength="40" value="${e(p.relation)}"></label><p class="field-title">内置头像 <small>手绘人物 · 24 款</small></p><div class="avatar-grid">${data.avatars.map(a=>`<button data-avatar="${a.id}" class="${a.id===p.avatar?'chosen':''}" aria-label="选择${e(a.label)}头像"><span class="avatar small"><img src="${a.path||`./assets/avatars/${a.id}.svg`}" alt=""></span><span>${e(a.label)}</span></button>`).join('')}</div><label class="upload-label">使用本地头像<input type="file" data-upload="person" accept="image/*"></label><p class="field-note">本地头像按人物分别使用，不会存入浏览器；刷新后恢复内置头像。</p></div><button class="secondary preview-button" data-action="back-people">完成，返回人物库</button><button class="text-button danger-link" data-action="delete-person">删除这位人物</button>`;}
function picker(){const multiple=state.picker.target==='likes';return `${header('CHOOSE CHARACTER',multiple?'选择点赞的人':'从人物库选择',multiple?'可以选择多位人物。':'名字和头像会一起带入。')}<button class="small-link back-link" data-action="close-picker">${icon('back')} 返回编辑</button><div class="people-list">${studio.people.map(p=>{const selected=multiple&&studio.moment.likes.includes(p.id);return `<button class="library-person ${selected?'picked':''}" data-select-person="${p.id}" aria-pressed="${selected}">${avatar(p.id)}<span><strong>${e(p.name)}</strong><small>${e(p.relation)}</small></span>${icon(selected?'check':'plus')}</button>`;}).join('')}</div>${multiple?`<button class="primary picker-done" data-action="close-picker">选好了 · ${studio.moment.likes.length} 人</button>`:''}`;}
function render(){let body;const screen=state.screen;if(screen==='incoming'||screen==='connected')body=callScreen();else if(screen==='call-chat')body=chatPreview();else if(screen==='chat-preview')body=chatPreview()+exportActions();else if(screen==='moment-preview')body=momentPreview()+exportActions();else if(screen==='countdown')body=`<main class="page countdown">${header('INCOMING CALL','来电已安排',`${person(studio.call.personId).name} 即将打来电话`)}<strong id="arrival-clock">${state.countdown}</strong><button class="secondary" data-action="edit-call">取消，返回设置</button></main>`;else{const content=screen==='picker'?picker():screen==='person-edit'?personEditor():screen==='call-edit'?callEditor():state.tab==='chat'?chatEditor():state.tab==='moment'?momentEditor():state.tab==='person'?peoplePage():home();body=`<main class="page">${content}</main>${screen==='picker'?'':nav()}`;}app.innerHTML=`<div class="app-shell">${body}${state.toast?`<div class="toast" role="status">${e(state.toast)}</div>`:''}</div>`;applyLayoutFallback();}
function stop(){stopRing();player.stop();audioBank.clear();clearInterval(clock);clearInterval(arrival);clock=null;arrival=null;}
function go(tab){stop();state.momentMenu=false;state.commenting=false;state.tab=tab;state.screen='home';state.picker=null;render();window.scrollTo(0,0);}
function editCall(){stop();state.tab='story';state.screen='call-edit';render();window.scrollTo(0,0);}
function finish(){if(!['incoming','connected'].includes(state.screen))return;const declined=state.screen==='incoming';stop();recordCall(studio,declined,state.seconds,data);save();state.tab='chat';state.screen='call-chat';render();window.scrollTo(0,0);const messages=document.querySelector('.chat-body');messages.scrollTop=messages.scrollHeight;}
function start(){stop();state.seconds=0;state.muted=false;player.setMuted(false);state.screen=studio.call.delay?'countdown':'incoming';state.countdown=studio.call.delay;startRing();render();window.scrollTo(0,0);if(studio.call.delay)arrival=setInterval(()=>{state.countdown--;if(state.countdown<=0){clearInterval(arrival);state.screen='incoming';ring.volume=1;render();}else{const n=document.querySelector('#arrival-clock');if(n)n.textContent=state.countdown;}},1000);}
function accept(){if(state.screen!=='incoming')return;let audioErrorShown=false;audioBank.unlock().catch(()=>{});stopRing();state.screen='connected';state.phase='speaking';state.seconds=0;const started=performance.now();clock=setInterval(()=>{state.seconds=Math.floor((performance.now()-started)/1000);const n=document.querySelector('#call-clock');if(n)n.textContent=elapsedLabel(state.seconds);},250);render();player.start({script:script(),mode:studio.call.mode,pause:studio.call.pause,available:data.audioFiles||[],onSegment(index){state.segment=index;state.phase='speaking';render();},onWaiting(){state.phase='waiting';render();},onEnd(){finish();},onError(){if(!audioErrorShown){audioErrorShown=true;toast(data.ui.voiceUnavailable);}}});}
function openPicker(target){state.picker={target,screen:state.screen,tab:state.tab};state.screen='picker';render();window.scrollTo(0,0);}
function closePicker(){const p=state.picker;state.screen=p?.screen||'home';state.tab=p?.tab||state.tab;state.picker=null;render();window.scrollTo(0,0);}
function selectPerson(id){const target=state.picker.target;if((target==='chat'&&id===studio.chat.selfId)||(target==='self'&&id===studio.chat.personId)){toast('请选择与另一侧不同的人物');return;}if(target==='likes'){const likes=studio.moment.likes;studio.moment.likes=likes.includes(id)?likes.filter(x=>x!==id):[...likes,id];save();render();return;}if(target==='call')studio.call.personId=id;if(target==='chat'){const old=studio.chat.personId;studio.chat.personId=id;for(const m of studio.chat.messages)if(m.personId===old&&old!==studio.chat.selfId)m.personId=id;}if(target==='self'){const old=studio.chat.selfId;studio.chat.selfId=id;for(const m of studio.chat.messages)if(m.personId===old&&old!==studio.chat.personId)m.personId=id;}if(target==='author')studio.moment.authorId=id;if(target==='new-comment')studio.moment.comments.push({personId:id,text:data.defaults.newComment});if(target.startsWith('comment:'))studio.moment.comments[Number(target.split(':')[1])].personId=id;save();closePicker();}
app.addEventListener('click',event=>{if(state.momentMenu&&!event.target.closest('.moment-actions')){state.momentMenu=false;app.querySelector('.moment-action-menu')?.remove();app.querySelector('.moment-more')?.setAttribute('aria-expanded','false');}const b=event.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
  if(d.commentPerson){state.commentPerson=d.commentPerson;state.commentPeople=false;render();return;}if(d.chatMode){switchChatMode(studio,d.chatMode,data);save();render();return;}if(d.tab){go(d.tab);return;}if(d.pick){openPicker(d.pick);return;}if(d.selectPerson){selectPerson(d.selectPerson);return;}if(d.editPerson){state.editPerson=d.editPerson;state.screen='person-edit';render();window.scrollTo(0,0);return;}
  if(d.avatar){person(state.editPerson).avatar=d.avatar;if(photos.has(state.editPerson)){URL.revokeObjectURL(photos.get(state.editPerson));photos.delete(state.editPerson);}save();render();return;}
  if(d.messageDelete!==undefined){studio.chat.messages.splice(Number(d.messageDelete),1);save();render();return;}if(d.messageUp!==undefined||d.messageDown!==undefined){const up=d.messageUp!==undefined,i=Number(up?d.messageUp:d.messageDown),j=i+(up?-1:1),m=studio.chat.messages;if(j>=0&&j<m.length)[m[i],m[j]]=[m[j],m[i]];save();render();return;}
  if(d.removeLike){studio.moment.likes=studio.moment.likes.filter(x=>x!==d.removeLike);save();render();return;}if(d.deleteComment!==undefined){studio.moment.comments.splice(Number(d.deleteComment),1);save();render();return;}if(d.removePhoto!==undefined){const [url]=momentImages.splice(Number(d.removePhoto),1);URL.revokeObjectURL(url);render();return;}
  const a=d.action;
if(a==='moment-menu'){state.momentMenu=!state.momentMenu;state.commenting=false;render();return;}
if(a==='moment-like'){const id=studio.chat.selfId;studio.moment.likes=studio.moment.likes.includes(id)?studio.moment.likes.filter(x=>x!==id):[...studio.moment.likes,id];state.momentMenu=false;save();render();return;}
if(a==='comment-people'){state.commentPeople=!state.commentPeople;render();return;}
if(a==='moment-comment'){state.momentMenu=false;state.commenting=true;state.commentPeople=false;state.commentDraft='';state.commentPerson=studio.chat.selfId;render();app.querySelector('.moment-composer').scrollIntoView({block:'center'});app.querySelector('[data-preview-comment]').focus();return;}
if(a==='cancel-comment'){state.commenting=false;render();app.querySelector('.moment-more').focus();return;}
if(a==='send-comment'){const text=app.querySelector('[data-preview-comment]').value.trim();if(!text||studio.moment.comments.length>=60)return;studio.moment.comments.push({personId:state.commentPerson||studio.chat.selfId,text});state.commenting=false;save();render();app.querySelector('.reaction-comment:last-child')?.scrollIntoView({block:'nearest'});return;}
if(a==='save-image'){saveImage();return;}if(a==='edit-call')editCall();else if(a==='start')start();else if(a==='accept')accept();else if(a==='decline')finish();else if(a==='hangup')finish();else if(a==='sound'){state.muted=!state.muted;player.setMuted(state.muted);render();}
  else if(a==='preview-chat'||a==='preview-moment'){state.screen=a==='preview-chat'?'chat-preview':'moment-preview';render();window.scrollTo(0,0);}else if(a==='edit-chat')go('chat');else if(a==='edit-moment')go('moment');else if(a==='close-picker')closePicker();else if(a==='back-people')go('person');
  else if(a==='add-their'||a==='add-my'){if(studio.chat.messages.length>=60)return;studio.chat.messages.push({personId:a==='add-my'?studio.chat.selfId:studio.chat.personId,text:data.defaults.newMessage});save();render();}
  else if(a==='add-person'){if(studio.people.length>=60){toast('最多创建 60 位人物');return;}const id=`person-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;studio.people.push({id,name:suggestNickname(studio.people,data.nicknames),relation:'',avatar:suggestAvatar(studio.people,data.avatars)});state.editPerson=id;state.screen='person-edit';save();render();window.scrollTo(0,0);}
  else if(a==='suggest-name'){const p=person(state.editPerson);p.name=suggestNickname(studio.people,data.nicknames,p.name);save();render();}
  else if(a==='delete-person'){if(personUsed(studio,state.editPerson)){toast('这位人物正在使用，请先在对应画面更换人物。');return;}studio.people=studio.people.filter(p=>p.id!==state.editPerson);if(photos.has(state.editPerson)){URL.revokeObjectURL(photos.get(state.editPerson));photos.delete(state.editPerson);}save();go('person');}
  else if(a==='random-likes'){studio.moment.likes=randomReactionIds(studio.people,studio.moment.authorId,3+Math.floor(Math.random()*4));save();render();}
  else if(a==='random-comments'){const texts=data.comments;studio.moment.comments=randomReactionIds(studio.people,studio.moment.authorId,3).map((id,i)=>({personId:id,text:texts[(i+Math.floor(Math.random()*texts.length))%texts.length]}));save();render();}
  else if(a==='remove-cover'){if(coverPhoto)URL.revokeObjectURL(coverPhoto);coverPhoto=null;render();}
});
app.addEventListener('change',event=>{const t=event.target,d=t.dataset;if(d.upload){const files=[...(t.files||[])].filter(f=>f.type.startsWith('image/'));if(!files.length)return;if(d.upload==='person'){if(photos.has(state.editPerson))URL.revokeObjectURL(photos.get(state.editPerson));photos.set(state.editPerson,URL.createObjectURL(files[0]));}else if(d.upload==='cover'){if(coverPhoto)URL.revokeObjectURL(coverPhoto);coverPhoto=URL.createObjectURL(files[0]);}else{momentImages.push(...files.slice(0,9-momentImages.length).map(f=>URL.createObjectURL(f)));}render();return;}
  if(d.momentTime){studio.moment.timeParts[d.momentTime]=d.momentTime==='format'?t.value:Number(t.value);}else if(d.timePart){studio.chat.timeParts[d.timePart]=d.timePart==='format'?t.value:Number(t.value);}else if(d.groupMember){const ch=studio.chat,id=d.groupMember;if(!t.checked&&ch.messages.some(m=>m.personId===id)){toast(data.ui.memberInUse);return;}ch.members=t.checked?[...ch.members,id]:ch.members.filter(x=>x!==id);}else if(d.person)person(state.editPerson)[d.person]=t.value;else if(d.call)studio.call[d.call]=t.type==='checkbox'?t.checked:['pause','delay'].includes(d.call)?Number(t.value):t.value;else if(d.chat)studio.chat[d.chat]=t.value;else if(d.messagePerson!==undefined)studio.chat.messages[Number(d.messagePerson)].personId=t.value;else if(d.messageText!==undefined)studio.chat.messages[Number(d.messageText)].text=t.value;else if(d.moment)studio.moment[d.moment]=t.value;else if(d.commentText!==undefined)studio.moment.comments[Number(d.commentText)].text=t.value;else return;save();render();
});
app.addEventListener('input',event=>{if(event.target.matches('[data-preview-comment]')){state.commentDraft=event.target.value;app.querySelector('[data-action=send-comment]').disabled=!event.target.value.trim();return;}if(event.target.id!=='person-search')return;const query=event.target.value.trim().toLowerCase();let visible=0;for(const row of app.querySelectorAll('[data-search]')){row.hidden=!row.dataset.search.toLowerCase().includes(query);if(!row.hidden)visible++;}app.querySelector('.search-empty').hidden=visible>0;});
app.addEventListener('keydown',event=>{if(event.key==='Escape'&&(state.momentMenu||state.commenting)){state.momentMenu=false;state.commenting=false;render();app.querySelector('.moment-more')?.focus();}});
window.addEventListener('pagehide',()=>stop());
window.addEventListener('pageshow',event=>{if(event.persisted){if(state.screen==='countdown')editCall();else finish();}});
render();

let exporting=false;
function exportActions(){return '<div class="export-actions"><button class="primary" data-action="save-image">'+e(data.ui.saveImage)+'</button></div>';}
async function saveImage(){
  if(exporting)return;exporting=true;const button=document.querySelector('[data-action="save-image"]');button.disabled=true;button.textContent=data.ui.generating;
  const bridge=albumBridge();let dialog=null,saved=0;
  try{await captureSurface(document.querySelector('.social-screen'),async (uri,page,total)=>{
    if(bridge){await bridge.saveImageToPhotosAlbum({filePath:uri});saved++;}
    else{if(!dialog){dialog=document.createElement('div');dialog.className='image-result';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label',data.ui.imagePreview);const top=document.createElement('div');top.className='image-result-head';const label=document.createElement('p');label.textContent=data.ui.browserSave;const close=document.createElement('button');close.className='secondary';close.textContent=data.ui.closePreview;close.addEventListener('click',()=>{dialog.remove();button.focus();});top.append(label,close);dialog.append(top);document.body.append(dialog);close.focus();}const image=new Image();image.src=uri;image.alt=data.ui.imagePreview+' '+page+'/'+total;dialog.append(image);}
  });if(bridge)toast(data.ui.saved.replace('{count}',String(saved)));}
  catch(error){toast(saved?data.ui.partialSave.replace('{count}',String(saved)):data.ui.saveFailed);}
  finally{exporting=false;if(document.body.contains(button)){button.disabled=false;button.textContent=data.ui.saveImage;}}
}

function applyLayoutFallback(){
  if(window.CSS&&CSS.supports('aspect-ratio','1'))document.documentElement.classList.add('supports-aspect');
  if(window.flexGapSupported===undefined){const box=document.createElement('div');box.style.cssText='display:flex;flex-direction:column;row-gap:1px;position:absolute;visibility:hidden';box.append(document.createElement('div'),document.createElement('div'));document.body.append(box);window.flexGapSupported=box.scrollHeight===1;box.remove();}
  if(!window.flexGapSupported)Array.from(app.querySelectorAll('*')).forEach(el=>{const style=getComputedStyle(el);if(style.display!=='flex'&&style.display!=='inline-flex')return;const gap=parseFloat(style.getPropertyValue('--layout-gap'));if(!gap)return;Array.from(el.children).forEach((child,i)=>{if(i)child.style[style.flexDirection==='column'?'marginTop':'marginLeft']=gap+'px';});});
}
function updateViewport(){document.documentElement.style.setProperty('--app-height',(window.visualViewport?window.visualViewport.height:window.innerHeight)+'px');}
window.addEventListener('resize',updateViewport);if(window.visualViewport)window.visualViewport.addEventListener('resize',updateViewport);updateViewport();

function timePicker(ch){const t=ch.timeParts;const options=(count,start,value,suffix,pad=false)=>Array.from({length:count},(_,i)=>{const n=i+start;return '<option value="'+n+'" '+(n===value?'selected':'')+'>'+(pad?String(n).padStart(2,'0'):n)+suffix+'</option>';}).join('');return '<div class="time-picker"><label>时间格式<select data-time-part="format">'+data.timePicker.formats.map(f=>'<option value="'+f.value+'" '+(f.value===t.format?'selected':'')+'>'+e(f.label)+'</option>').join('')+'</select></label><div class="time-fields '+(t.format==='weekday'?'weekday-fields':'date-fields')+'">'+(t.format==='weekday'?'<label>周几<select data-time-part="weekday">'+data.timePicker.weekdays.map((w,i)=>'<option value="'+(i+1)+'" '+(i+1===t.weekday?'selected':'')+'>'+e(w)+'</option>').join('')+'</select></label>':'<label>月份<select data-time-part="month">'+options(12,1,t.month,'月')+'</select></label><label>日期<select data-time-part="day">'+options(monthDays(t.month),1,t.day,'日')+'</select></label>')+'<label>小时<select data-time-part="hour">'+options(24,0,t.hour,'',true)+'</select></label><label>分钟<select data-time-part="minute">'+options(60,0,t.minute,'',true)+'</select></label></div><p class="time-example">'+e(ch.time)+'</p></div>';}
