import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createRun,newSave,cast,step,strike,net,commit,readSave,surge,challengeMet,daySeed,localDay} from '../.cache/model.mjs';
const C=JSON.parse(readFileSync('src/content/content.json','utf8'));
function hook(r){const target=C.spots[r.spot].target,power=r.mode==='challenge'&&C.challenges[r.challenge].rule==='far'?.8:(.73-target[1])/.38;assert(cast(r,target[0],.5,power));for(let i=0;i<2000&&r.phase!=='bite';i++)step(r,1/60);assert.equal(r.phase,'bite');assert(strike(r));}
function land(r){hook(r);for(let i=0;i<12000&&r.phase==='fight';i++)step(r,1/60,!surge(r),Math.sin(i/120)*.8);assert.equal(r.phase,'net',JSON.stringify(r));for(let i=0;i<20;i++)net(r,r.x,r.y,1/60);assert.equal(r.phase,'caught');}
test('seed determines fish and plan before any casting success',()=>{assert.deepEqual(createRun(45,2,1),createRun(45,2,1));const a=createRun(45);const kind=a.kind;cast(a,.8,.6,.9);assert.equal(a.kind,kind);assert(!cast(a,.5,.5,.8));});
test('cancelled or too-short cast does not start a plan',()=>{const r=createRun(7);assert(!cast(r,.5,.5,.01));assert(!cast(r,NaN,.5,.8));assert.equal(r.phase,'ready');});
test('early and late strikes have distinct visible causes',()=>{const early=createRun(1);cast(early,.5,.5,.7);for(let i=0;i<70;i++)step(early,1/60);assert(!strike(early));assert.equal(early.reason,'early');const late=createRun(2);cast(late,.5,.5,.7);for(let i=0;i<2500;i++)step(late,1/60);assert.equal(late.reason,'late');});
test('continued hard reeling breaks only after the strain warning',()=>{const r=createRun(432);hook(r);let warning=false;for(let i=0;i<5000&&r.phase==='fight';i++){step(r,1/60,true);if(r.strain>0&&r.strain<.7)warning=true;}assert(warning);assert.equal(r.reason,'break');});
test('six families can be landed using visible surge and rest signals',()=>{const seen=new Set();for(let seed=1;seed<100;seed++){const r=createRun(seed,seed%6);const family=C.fish[r.kind].family;if(seen.has(family))continue;land(r);seen.add(family);}assert.equal(seen.size,6);});
test('net requires continuous accurate placement and commits once',()=>{const s=newSave(7);land(s.run);assert(commit(s));assert(!commit(s));assert.equal(s.records[0].count,1);const r=createRun(5);r.phase='net';for(let i=0;i<50;i++)net(r,0,0,1/60);assert.equal(r.phase,'net');});
test('practice and duplicate daily plans never add a second fish',()=>{const s=newSave(91);s.run.mode='daily';land(s.run);assert(commit(s));const original=s.records[0].count;s.run=createRun(91,0,0,'daily');land(s.run);assert(!commit(s));s.run=createRun(91,0,0,'practice');land(s.run);assert(!commit(s));assert.equal(s.records[0].count,original);});
test('all eighteen fish are reachable from all configured habitats together',()=>{const found=new Set();for(let i=1;i<300;i++)for(let spot=0;spot<6;spot++)found.add(createRun(i,spot).kind);assert.equal(found.size,18);});
for(let i=0;i<24;i++)test('challenge '+i+' has an actually landable plan and a failing case',()=>{const r=createRun(C.challenges[i].seed,Math.floor(i/4),0,'challenge',i);assert(!challengeMet(r,i));land(r);assert(challengeMet(r,i));const bad={...r};switch(C.challenges[i].rule){case 'landing':bad.accuracy=.2;break;case 'timing':bad.strikeLag=1;break;case 'steady':bad.peakTension=1;break;case 'net':bad.netMisses=1;break;case 'far':bad.castPower=.2;break;case 'safe':bad.safe=0;break;case 'steered':bad.surges=0;break;case 'efficient':bad.elapsed=121;break;}assert(!challengeMet(bad,i));r.phase='miss';assert(!challengeMet(r,i));});
test('local calendar seed and validated bounded save survive reload',()=>{assert.equal(localDay(new Date(2026,8,19,23,59)),'2026-09-19');assert.equal(daySeed('2026-09-19'),daySeed('2026-09-19'));assert.notEqual(daySeed('2026-09-19'),daySeed('2026-09-20'));const s=newSave(5);land(s.run);commit(s);assert.deepEqual(readSave(JSON.stringify(s)),s);s.run.kind=99;assert.equal(readSave(JSON.stringify(s)),null);assert.equal(readSave('{'),null);s.version=99;assert.equal(readSave(JSON.stringify(s)),null);});

test('landing position changes waiting and bite tolerance without rerolling the planned fish',()=>{const a=createRun(7),b=createRun(7);cast(a,.32,.5,(.73-.49)/.38);cast(b,.82,.5,1);assert.equal(a.kind,b.kind);assert(a.wait<b.wait);assert(a.bite>b.bite);});
import {castFlight,castLanding} from '../.cache/model.mjs';
test('cast animation starts at the rod and lands exactly at the predicted position',()=>{const from={x:250,y:840},to={x:190,y:410};assert.deepEqual(castFlight(0,from,to,150),from);const end=castFlight(1,from,to,150);assert(Math.abs(end.x-to.x)<1e-8&&Math.abs(end.y-to.y)<1e-8);assert(castFlight(.5,from,to,150).y<625);const r=createRun(22),y=.5,power=.65,expected=castLanding(y,power);cast(r,.5,y,power);assert.equal(r.targetY,expected);});
test('steering and fish positions respond continuously instead of jumping on reversal',()=>{const r=createRun(23);hook(r);for(let i=0;i<90;i++)step(r,1/60,true,1);const before={x:r.x,steer:r.steer};step(r,1/60,false,-1);assert(Math.abs(r.x-before.x)<.025);assert(r.steer>-1&&r.steer<before.steer);assert(r.tension>=0&&Number.isFinite(r.tension));});
