import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {makePlan,inventory,validatePlan,clone,History,validRoom,overlap,placement,itemFrom,walls,wallOpenings,validOpening,csvCell,canWalk} from '../src/core.js';
const catalog=JSON.parse((await readFile(new URL('../src/content/content.json',import.meta.url),'utf8')).replace(/^\uFEFF/,''));
test('all six furnished templates have valid geometry and persistable data',()=>{
  assert.equal(catalog.templates.length,6);assert.ok(catalog.furniture.length>=24);
  for(const template of catalog.templates){const p=makePlan(template,catalog);assert.ok(p.items.length>0);assert.deepEqual(validatePlan(p,catalog),p);for(const item of p.items)assert.ok(placement(p,item,catalog),`${template.id}: ${item.catalogId}`);}
});
test('unmeasured rooms never produce fabricated floor quantities',()=>{const p=makePlan(catalog.templates[0],catalog);let inv=inventory(p,catalog);assert.equal(inv.area,0);assert.equal(inv.measured,0);assert.ok(inv.materials.every(m=>m.unknown));p.rooms[0].measured=true;inv=inventory(p,catalog);assert.equal(inv.area,20.16);assert.equal(inv.measured,1);});
test('shared walls are generated once, openings deducted on both room faces',()=>{const p=makePlan({name:'test',rooms:[['A',0,0,3,3,'empty'],['B',3,0,3,3,'empty']]},catalog);p.rooms.forEach(r=>r.measured=true);p.wallHeightMeasured=true;const shared=walls(p).filter(w=>w.rooms.length===2);assert.equal(shared.length,1);assert.equal(shared[0].length,3);const doors=wallOpenings(p,shared[0]);assert.equal(doors.length,1);const inv=inventory(p,catalog);let expected=24*p.wallHeight;for(const w of walls(p))for(const o of wallOpenings(p,w))expected-=o.w*o.h*w.rooms.length;assert.equal(inv.materials.find(m=>m.surface==='wall').quantity,Math.round(expected*100)/100);});
test('room resize blocks overlap, numeric corruption and impossible openings',()=>{const p=makePlan(catalog.templates[0],catalog);assert.equal(validRoom(p,{...p.rooms[0],w:9}),false);assert.equal(validRoom(p,{...p.rooms[0],w:NaN}),false);assert.equal(validOpening(p,{...p.openings[0],w:90}),false);});
test('rotated furniture uses oriented footprint, rugs may underlay furniture',()=>{assert.equal(overlap({x:0,z:0,w:2,d:1,angle:45},{x:0,z:0,w:1,d:1,angle:0}),true);assert.equal(overlap({x:0,z:0,w:2,d:1,angle:45},{x:6,z:6,w:1,d:1,angle:0}),false);const p=makePlan({name:'test',rooms:[['A',0,0,5,5,'empty']]},catalog),r=p.rooms[0];p.items.push(itemFrom(catalog.furniture.find(f=>f.id==='rug'),r,2.5,2.5));assert.ok(placement(p,itemFrom(catalog.furniture.find(f=>f.id==='coffee'),r,2.5,2.5),catalog));});
test('history snapshots are independent and redo branch clears after new edit',()=>{const h=new History(),p=makePlan(catalog.templates[0],catalog);h.record(p);p.items[0].color='#123456';const restored=h.undo(p);assert.notEqual(restored.items[0].color,p.items[0].color);assert.equal(h.redo(restored).items[0].color,'#123456');h.record(p);assert.equal(h.future.length,0);});
test('inventory groups identical furniture by specification and colour',()=>{const p=makePlan(catalog.templates[0],catalog),item=p.items[0];p.items.push({...clone(item),id:'copy'});assert.equal(inventory(p,catalog).furniture.find(r=>r.name===catalog.furniture.find(f=>f.id===item.catalogId).name).quantity,2);p.items.at(-1).color='#000000';assert.equal(inventory(p,catalog).furniture.filter(r=>r.name===catalog.furniture.find(f=>f.id===item.catalogId).name).length,2);});
test('untrusted imports reject unknown catalogue ids, duplicate ids and nonfinite dimensions',()=>{const p=makePlan(catalog.templates[0],catalog);for(const mutate of [x=>x.items[0].catalogId='unknown',x=>x.rooms[0].w=1000,x=>x.items[0].id=x.rooms[0].id,x=>x.prices={bad:-1},x=>x.schemaVersion=99]){const bad=clone(p);mutate(bad);assert.throws(()=>validatePlan(bad,catalog));}});
test('walking cannot cross a solid wall but can cross an open doorway',()=>{const p=makePlan({name:'test',rooms:[['A',0,0,3,3,'empty'],['B',3,0,3,3,'empty']]},catalog);assert.equal(canWalk(p,{x:2,z:1.5},{x:4,z:1.5},catalog),true);p.openings=[];assert.equal(canWalk(p,{x:2,z:1.5},{x:4,z:1.5},catalog),false);});
test('CSV escapes quote delimiters and neutralizes spreadsheet formulas',()=>{assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('a,"b"'),'"a,""b"""');});
test('imports discard media and unknown fields before local persistence',()=>{const p=makePlan(catalog.templates[0],catalog);p.image='data:image/png;base64,abc';p.rooms[0].photo='media';const clean=validatePlan(p,catalog);assert.equal(clean.image,undefined);assert.equal(clean.rooms[0].photo,undefined);});
test('wall quantities remain unknown until wall height is explicitly confirmed',()=>{const p=makePlan(catalog.templates[0],catalog);p.rooms.forEach(r=>r.measured=true);assert.ok(inventory(p,catalog).materials.filter(m=>m.surface==='wall').every(m=>m.unknown));p.wallHeightMeasured=true;assert.ok(inventory(p,catalog).materials.filter(m=>m.surface==='wall').every(m=>!m.unknown&&m.quantity>0));});
