import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {makePlan,itemFrom} from '../../src/core.js';
import {doorApproaches} from '../../src/circulation.js';
const {chromium}=createRequire(import.meta.url)('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),root=resolve('dist'),out=resolve('artifacts/mobile-acceptance'),results=[];
const server=createServer(async(req,res)=>{try{const p=resolve(root,'.'+(req.url==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));assert.ok(p.startsWith(root));let data=await readFile(p);if(p===resolve(root,'src/app.js'))data=Buffer.concat([data,Buffer.from('\nwindow.__acceptance={get scene(){return scene},get plan(){return plan}};')]);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'})[extname(p)]||'application/octet-stream'});res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({channel:'chrome',headless:true});
try{
 for(const width of [375,390,430]){
  const context=await browser.newContext({viewport:{width,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const click=async selector=>{await page.locator(selector+':visible').first().tap({timeout:5000});await page.waitForTimeout(180)};const pass=name=>{checks.push(name);console.log(JSON.stringify({width,pass:name}))};
  try{
   await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__acceptance?.scene?.plan);await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','28px');document.documentElement.style.setProperty('--safe-area-inset-bottom','16px')});await page.waitForTimeout(200);assert.equal(await page.locator('#door-warning').count(),1);assert.equal(await page.locator('#door-warning').isVisible(),false);pass('single doorway notice, template has no blocked doorway');
   await click('.orientation-toggle');assert.equal(await page.locator('#mobile-dock').isVisible(),false);assert.ok(await page.locator('#floating-tools [data-action="open-studio"]').isVisible());const height=await page.locator('#viewport').evaluate(e=>e.clientHeight);assert.ok(height>=width-60,`canvas height ${height}`);pass('landscape removes permanent bottom bar and restores canvas height');
   await click('#floating-tools [data-action="open-studio"]');assert.ok(await page.locator('#library').isVisible());const separated=await page.evaluate(()=>document.querySelector('#library').getBoundingClientRect().top>=document.querySelector('#viewport').getBoundingClientRect().bottom-1);assert.ok(separated);await click('#tabs [data-action="tab-layouts"]');await click('[data-action="template"][data-id="family"]');assert.equal(await page.locator('#library').isVisible(),false);pass('floating workbench opens right drawer; selecting template closes it');
   await page.screenshot({path:out+`/floating-studio-${width}.png`});const before=await page.evaluate(()=>{const s=window.__acceptance.scene;return{camera:s.camera.position.toArray(),target:s.controls.target.toArray()}});
   await click('.mobile-view-access [data-action="toggle-views"]');await click('[data-action="inside"]');assert.ok(await page.locator('#walk-controls').isVisible());assert.equal(await page.locator('#floating-tools [data-action="open-studio"]').count(),0);assert.equal(await page.evaluate(()=>window.__acceptance.scene.selected),null);pass('walkthrough hides editing controls and shows two navigation actions');
   const destination=await page.evaluate(async()=>{const T=await import('./src/vendor/package/build/three.module.js'),{walkingPath}=await import('./src/circulation.js'),{viewportRect}=await import('./src/orientation.js'),catalog=await fetch('./src/content/content.json').then(r=>r.json()),s=window.__acceptance.scene,plan=window.__acceptance.plan,candidates=[];for(const r of plan.rooms)for(let x=r.x+.4;x<r.x+r.w-.3;x+=.35)for(let z=r.z+.4;z<r.z+r.d-.3;z+=.35){const distance=Math.hypot(x-s.camera.position.x,z-s.camera.position.z);if(distance<1.2||distance>3.4)continue;const projected=new T.Vector3(x,0,z).project(s.camera);if(projected.z>=1||projected.z<=-1||Math.abs(projected.x)>.8||Math.abs(projected.y)>.85)continue;candidates.push({x,z,distance,projected});}candidates.sort((a,b)=>a.distance-b.distance);for(const candidate of candidates){const route=walkingPath(plan,s.camera.position,candidate,catalog);if(!route||route.reduce((sum,p,i)=>sum+Math.hypot(p.x-(i?route[i-1].x:s.camera.position.x),p.z-(i?route[i-1].z:s.camera.position.z)),0)>5)continue;const rect=viewportRect(s.renderer.domElement),lx=rect.left+(candidate.projected.x+1)*rect.width/2,ly=rect.top+(1-candidate.projected.y)*rect.height/2,root=document.querySelector('#app').getBoundingClientRect();return{x:candidate.x,z:candidate.z,screenX:root.right-ly,screenY:root.top+lx,start:{x:s.camera.position.x,z:s.camera.position.z}};}return null;});
   assert.ok(destination,'visible walkable destination');await page.touchscreen.tap(destination.screenX,destination.screenY);await page.waitForTimeout(180);const middle=await page.evaluate(()=>({x:window.__acceptance.scene.camera.position.x,z:window.__acceptance.scene.camera.position.z}));assert.ok(Math.hypot(middle.x-destination.start.x,middle.z-destination.start.z)>.02,'movement starts');assert.ok(Math.hypot(middle.x-destination.x,middle.z-destination.z)>.2,'does not teleport');await page.waitForFunction(()=>!window.__acceptance.scene.walkRoute,{},{timeout:10000});const end=await page.evaluate(()=>({x:window.__acceptance.scene.camera.position.x,z:window.__acceptance.scene.camera.position.z}));assert.ok(Math.hypot(end.x-destination.x,end.z-destination.z)<.04);pass('touch floor initiates smooth movement and reaches intended destination');
   await click('[data-action="walk-rooms"]');assert.equal(await page.locator('[data-action="walk-to-room"]').count(),7);const roomId=await page.locator('[data-action="walk-to-room"]').last().getAttribute('data-id');await page.locator('[data-action="walk-to-room"]').last().tap();await page.waitForTimeout(180);const landed=await page.evaluate(async roomId=>{const {roomAt,walkable}=await import('./src/core.js'),catalog=await fetch('./src/content/content.json').then(r=>r.json()),s=window.__acceptance.scene,p=window.__acceptance.plan;return roomAt(p,s.camera.position.x,s.camera.position.z)?.id===roomId&&walkable(p,s.camera.position.x,s.camera.position.z,catalog)},roomId);assert.ok(landed);pass('room picker lands inside chosen room on unobstructed floor');await page.screenshot({path:out+`/walkthrough-${width}.png`});
   await click('[data-action="exit-walk"]');const after=await page.evaluate(()=>{const s=window.__acceptance.scene;return{camera:s.camera.position.toArray(),target:s.controls.target.toArray()}});for(const key of ['camera','target'])for(let i=0;i<3;i++)assert.ok(Math.abs(before[key][i]-after[key][i])<.02);pass('leaving walkthrough restores the original editing camera');assert.equal(await page.locator('#door-warning').count(),1);assert.deepEqual(errors,[]);results.push({width,passed:true,checks,errors});
  }catch(e){await page.screenshot({path:out+`/experience-failed-${width}.png`}).catch(()=>{});results.push({width,passed:false,error:e.message,checks,errors});console.log(JSON.stringify(results.at(-1)))}finally{await context.close()}
 }
 const catalog=JSON.parse(await readFile('src/content/content.json','utf8')),plan=makePlan(catalog.templates[0],catalog),zone=doorApproaches(plan)[0],room=plan.rooms.find(r=>r.id===zone.roomId),furniture=itemFrom(catalog.furniture.find(f=>f.id==='pouf'),room,zone.x,zone.z);plan.items.push(furniture);const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await context.addInitScript(p=>localStorage.setItem('roomish-project-15-v1',JSON.stringify({active:p.id,plans:[p],baselines:{[p.id]:p}})),plan);const page=await context.newPage();try{await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__acceptance?.scene?.plan);assert.ok(await page.locator('#door-warning').isVisible());assert.equal(await page.locator('#door-warning').count(),1);await page.locator('[data-action="locate-door-blocker"]').tap();assert.equal(await page.evaluate(()=>window.__acceptance.scene.selected.id),furniture.id);const saved=await page.evaluate(()=>window.__acceptance.plan.items);assert.deepEqual(saved,plan.items);results.push({fixture:'existing user plan',passed:true,checks:['blocked-door notice','locate obstructing furniture','saved furniture untouched']});console.log(JSON.stringify(results.at(-1)))}catch(e){results.push({fixture:'existing user plan',passed:false,error:e.message});console.log(JSON.stringify(results.at(-1)))}finally{await context.close()}
 if(results.some(r=>!r.passed))process.exitCode=1;
}finally{await browser.close();await new Promise(r=>server.close(r));await writeFile(out+'/experience-report.json',JSON.stringify({results,limits:['Desktop Chrome touch emulation','Not native Xiaohongshu WebView']},null,2));}
