import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=resolve('dist'),out=resolve('artifacts/mobile-acceptance'),results=[];
const server=createServer(async(req,res)=>{try{const p=resolve(root,'.'+(req.url==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!p.startsWith(root))throw Error();let bytes=await readFile(p);if(p===resolve(root,'src/app.js'))bytes=Buffer.concat([bytes,Buffer.from('\nwindow.__acceptance={get scene(){return scene},get plan(){return plan}};')]);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png'})[extname(p)]||'application/octet-stream'});res.end(bytes);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
for(const width of [375,390,430]){
 const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
 await context.addInitScript(()=>{window.__albumCalls=[];window.xhs={miniTool:{writeTempFile:async args=>{window.__albumCalls.push({method:'writeTempFile',prefix:args.data.slice(0,23),length:args.data.length});return {filePath:'/mock/roomish.jpg'}},saveImageToPhotosAlbum:async args=>{window.__albumCalls.push({method:'saveImageToPhotosAlbum',...args});return{}}}};});
 const page=await context.newPage(),cdp=await context.newCDPSession(page),errors=[],external=[];let stage='boot';const checks=[],findings=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))external.push(r.url())});page.on('dialog',d=>d.accept());
 const click=async s=>{await page.locator(s+':visible').first().tap({timeout:5000});await page.waitForTimeout(120);};
 const state=()=>page.evaluate(()=>JSON.parse(JSON.stringify(window.__acceptance.plan)));
 const check=(name,details={})=>{checks.push({name,...details});console.log(JSON.stringify({width,pass:name,...details}));};
 const point=async(x,z,y=0)=>page.evaluate(async({x,z,y})=>{const T=await import('./src/vendor/package/build/three.module.js'),{viewportRect}=await import('./src/orientation.js'),s=window.__acceptance.scene,r=viewportRect(s.renderer.domElement),p=new T.Vector3(x,y,z).project(s.camera);const lx=r.left+(p.x+1)*r.width/2,ly=r.top+(1-p.y)*r.height/2;if(document.body.classList.contains('forced-landscape')){const root=document.querySelector('#app').getBoundingClientRect();return{x:root.right-ly,y:root.top+lx}}return{x:lx,y:ly};},{x,z,y});
 const drag=async(a,b)=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:a.x,y:a.y}]});for(let i=1;i<=12;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:a.x+(b.x-a.x)*i/12,y:a.y+(b.y-a.y)*i/12}]});}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(300);};
 try{
  await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__acceptance?.scene?.plan);await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','28px');document.documentElement.style.setProperty('--safe-area-inset-bottom','16px')});await page.waitForTimeout(200);
  const geometry=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,brandTop:document.querySelector('.brand').getBoundingClientRect().top,canvasHeight:document.querySelector('#viewport').getBoundingClientRect().height}));assert.equal(geometry.scroll,width);assert.ok(geometry.brandTop>=28);check('initial safe area and no horizontal overflow',geometry);
  stage='custom floorplan';await click('#mobile-launch [data-action="tab-layouts"]');await click('[data-action="blank"]');let p=await state(),item;assert.equal(p.rooms.length,1);assert.equal(p.items.length,0);check('create blank floorplan');
  await click('#mobile-context [data-action="room-properties"]');await page.locator('#room-form [name="name"]').fill('我的客厅');await page.locator('#room-form [name="w"]').fill('5.4');await page.locator('#room-form [name="d"]').fill('4.4');await click('#mobile-context [data-action="room-properties"]');p=await state();assert.equal(p.rooms[0].w,5.4);assert.equal(p.rooms[0].d,4.4);assert.equal(p.rooms[0].name,'我的客厅');check('room draft saved when panel closes');
  stage='room edge touch drag';let r=p.rooms[0];await drag(await point(r.x+r.w,r.z+r.d/2,.09),await point(r.x+r.w+.6,r.z+r.d/2,.09));p=await state();if(p.rooms[0].w<=5.6){findings.push({stage,error:'Touching the east resize control rotated the camera instead of resizing',width:p.rooms[0].w});await page.screenshot({path:out+`/resize-failure-${width}.png`});await click('.mobile-view-access [data-action="toggle-views"]');await click('[data-action="top"]');}else check('touch drag east wall to resize',{width:p.rooms[0].w});
  stage='add and move door';await click('#mobile-context [data-action="add-door"]');r=(await state()).rooms[0];let pt=await point(r.x+r.w,r.z+1.3,.04);await page.touchscreen.tap(pt.x,pt.y);await page.waitForTimeout(180);p=await state();assert.equal(p.openings.length,1);let door=p.openings[0];assert.equal(door.side,'east');await drag(await point(r.x+r.w,r.z+door.offset,.025),await point(r.x+r.w,r.z+door.offset+.55,.025));p=await state();assert.ok(Math.abs(p.openings[0].offset-door.offset)>.25);check('add and directly touch-drag door',{before:door.offset,after:p.openings[0].offset});await click('#mobile-context [data-action="cancel-door"]');
  stage='adjacent room and shared door';await click('#mobile-context [data-action="add-room-shortcut"]');await click('[data-action="add-room-side"][data-id="east"]');p=await state();assert.equal(p.rooms.length,2);const shared=await page.evaluate(async()=>{const c=await import('./src/core.js'),p=window.__acceptance.plan;return c.walls(p).filter(w=>w.rooms.length===2).map(w=>({rooms:w.rooms,doors:c.wallOpenings(p,w).length}))});assert.ok(shared.some(w=>w.doors===1));check('adjacent room shares single door opening');
  stage='delete room preserves shared door';{const room=p.rooms[0],spot=await point(room.x+room.w/2,room.z+room.d/2);await page.touchscreen.tap(spot.x,spot.y);await page.waitForTimeout(150);}await click('#mobile-context [data-action="room-properties"]');if(await page.locator('[data-action="delete-room"]:visible').count()){await click('[data-action="delete-room"]');p=await state();assert.equal(p.rooms.length,1);assert.equal(p.openings.length,1);assert.equal(p.openings[0].roomId,p.rooms[0].id);await click('[data-action="undo"]');check('delete room retains shared door and undo restores room');p=await state();const restored=p.rooms[0],target=await point(restored.x+restored.w/2,restored.z+restored.d/2);await page.touchscreen.tap(target.x,target.y);await page.waitForTimeout(150);await click('#mobile-context [data-action="room-properties"]');}else{findings.push({stage,error:'Delete room control is hidden in the mobile property panel'});await page.screenshot({path:out+`/delete-hidden-${width}.png`});}await click('#mobile-context [data-action="room-properties"]');
  stage='furniture placement and touch drag';try{await click('#mobile-context [data-action="finish-layout"]');await click('#mobile-launch [data-action="tab-furniture"]');await page.locator('#search').fill('坐墩');await click('.furniture-card');r=(await state()).rooms[0];pt=await point(r.x+2,r.z+2);await page.touchscreen.tap(pt.x,pt.y);await page.waitForTimeout(150);p=await state();assert.equal(p.items.length,1);item=p.items[0];await drag(await point(item.x,item.z,.4),await point(item.x+.6,item.z+.3,.4));p=await state();assert.ok(Math.hypot(p.items[0].x-item.x,p.items[0].z-item.z)>.2);check('furniture placement and touch drag');await click('#mobile-context [data-action="rotate"]');assert.equal((await state()).items[0].angle,90);check('furniture rotation');
   }catch(e){findings.push({stage,error:e.message});console.log(JSON.stringify({width,failed:stage,error:e.message}));await page.screenshot({path:out+'/stage-'+0+'-'+width+'.png'}).catch(()=>{});if(await page.locator('#modal[open]').count())await click('[data-action="close-modal"]');}
 stage='landscape touch drag';try{await click('.orientation-toggle');await page.waitForTimeout(300);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('forced-landscape')),true);item=(await state()).items[0];await drag(await point(item.x,item.z,.4),await point(item.x+.5,item.z+.4,.4));p=await state();assert.ok(Math.hypot(p.items[0].x-item.x,p.items[0].z-item.z)>.2);check('forced landscape preserves touch coordinates');await page.screenshot({path:out+`/landscape-${width}.png`});await click('.orientation-toggle');
   }catch(e){findings.push({stage,error:e.message});console.log(JSON.stringify({width,failed:stage,error:e.message}));await page.screenshot({path:out+'/stage-'+1+'-'+width+'.png'}).catch(()=>{});if(await page.locator('#modal[open]').count())await click('[data-action="close-modal"]');}
 stage='materials';try{if(await page.locator('body').evaluate(e=>e.classList.contains('forced-landscape')))await click('.orientation-toggle');await click('#mobile-launch [data-action="tab-materials"]');await click('[data-action="material"][data-id="walnut"]');assert.equal((await state()).rooms[0].floor,'walnut');await click('#mobile-context [data-action="close-panel"]');check('change floor material');
   }catch(e){findings.push({stage,error:e.message});console.log(JSON.stringify({width,failed:stage,error:e.message}));await page.screenshot({path:out+'/stage-'+2+'-'+width+'.png'}).catch(()=>{});if(await page.locator('#modal[open]').count())await click('[data-action="close-modal"]');}
 stage='walkthrough';try{await click('.mobile-view-access [data-action="toggle-views"]');await click('[data-action="inside"]');assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('walking')),true);await click('[data-action="exit-walk"]');check('enter and exit walkthrough');
   }catch(e){findings.push({stage,error:e.message});console.log(JSON.stringify({width,failed:stage,error:e.message}));await page.screenshot({path:out+'/stage-'+3+'-'+width+'.png'}).catch(()=>{});if(await page.locator('#modal[open]').count())await click('[data-action="close-modal"]');}
 stage='finish inventory and export';try{await click('[data-action="finish"]');await click('#finish-card [data-action="inventory"]');assert.ok(await page.locator('.table-scroll tbody tr').count()>0);await click('[data-action="close-modal"]');await click('#finish-card [data-action="capture"]');await page.waitForSelector('.export-preview');await click('[data-action="save-album"]');const album=await page.evaluate(()=>window.__albumCalls);assert.equal(album.length,2);assert.equal(album[0].method,'writeTempFile');assert.equal(album[0].prefix,'data:image/jpeg;base64,');assert.ok(album[0].length<=1398100);assert.equal(album[1].filePath,'/mock/roomish.jpg');check('inventory and temporary-file album contract', {album});await page.screenshot({path:out+`/export-${width}.png`});await click('[data-action="close-modal"]');
   }catch(e){findings.push({stage,error:e.message});console.log(JSON.stringify({width,failed:stage,error:e.message}));await page.screenshot({path:out+'/stage-'+4+'-'+width+'.png'}).catch(()=>{});if(await page.locator('#modal[open]').count())await click('[data-action="close-modal"]');}
 stage='reload recovery';try{const before=await state();await page.waitForTimeout(350);await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__acceptance?.scene?.plan);const after=await state();assert.deepEqual(after.rooms,before.rooms);assert.deepEqual(after.items,before.items);assert.deepEqual(after.openings,before.openings);check('reload retains room furniture and door changes');
   }catch(e){findings.push({stage,error:e.message});console.log(JSON.stringify({width,failed:stage,error:e.message}));await page.screenshot({path:out+'/stage-'+5+'-'+width+'.png'}).catch(()=>{});if(await page.locator('#modal[open]').count())await click('[data-action="close-modal"]');}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);results.push({width,passed:!findings.length,checks,findings,errors,external});
 }catch(e){const detail=await page.evaluate(()=>({body:document.body.className,text:document.body.innerText.slice(-2200),buttons:[...document.querySelectorAll('button')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>({text:e.innerText,action:e.dataset.action}))})).catch(()=>null);await page.screenshot({path:out+`/failed-${width}.png`}).catch(()=>{});results.push({width,passed:false,stage,error:e.message,checks,findings,detail,errors,external});console.log(JSON.stringify({width,failed:stage,error:e.message,detail}));}
 await context.close();
}
if(results.some(r=>!r.passed))process.exitCode=1;
}finally{await browser.close();await new Promise(r=>server.close(r));await writeFile(out+'/report.json',JSON.stringify({date:new Date().toISOString(),results,limits:['Browser emulation, not native Xiaohongshu','Album API mocked','No physical-device FPS measurement']},null,2));}
