import test from 'node:test';import assert from 'node:assert/strict';import {generate,dig,reveal,catchItem,release,readSave,tick} from '../.cache/model.mjs';
test('fixed discoveries, local digging reveals only after burial depth',()=>{const b=generate(72);assert.deepEqual(b,generate(72));const p=b.zones[1][0];for(let i=1;i<p.item.depth;i++){dig(p);assert.equal(p.item.state,'hidden');}dig(p);assert.equal(p.item.state,'visible');assert.equal(b.zones[1][1].dig,0);});
test('rock exposure and release cannot duplicate collection',()=>{const s={beach:generate(1),zone:0,bucket:[],album:[]},p=s.beach.zones[0][0];assert.equal(catchItem(s,p.item),false);p.open=true;reveal(p,0);assert.equal(catchItem(s,p.item),true);release(s);assert.equal(catchItem(s,p.item),false);assert.equal(s.album.length,1);assert.deepEqual(readSave(JSON.stringify(s)),s);});
test('crab movement stays within visible home range',()=>{const b=generate(1),p=b.zones[0][0];p.open=true;reveal(p,0);for(let i=0;i<3600;i++)tick(b.zones[0],1/60);assert.ok(Math.abs(p.item.x-p.x)<=.075);assert.equal(readSave('{'),null);});
import {normalize,digAt,exposure,checkChallenges,challengeProgress,daySeed} from '../.cache/model.mjs';
import {readFileSync} from 'node:fs';const C=JSON.parse(readFileSync('src/content/content.json','utf8'));
test('local digging changes only nearby cells and never a neighbouring point',()=>{const b=generate(67),p=b.zones[1][0],neighbor=JSON.stringify(b.zones[1][1]);digAt(p,p.x-p.r*.8,p.y);assert(p.cells.some(n=>n===0));assert(p.cells.some(n=>n>0));assert.equal(JSON.stringify(b.zones[1][1]),neighbor);assert(exposure(p)<.55);assert.equal(p.item.state,'hidden');for(let i=0;i<6;i++)digAt(p,p.x,p.y);assert(exposure(p)>=.55);assert.equal(p.item.state,'visible');});
test('all twenty-four appearances exist across the six habitat pools',()=>{const kinds=new Set();for(let seed=1;seed<80;seed++)for(const z of generate(seed).zones)for(const p of z)if(p.item)kinds.add(p.item.kind);assert.equal(kinds.size,24);});
test('living releases preserve static shells and collection records',()=>{const s=normalize({beach:generate(37),zone:4,bucket:[],album:[]});const p=s.beach.zones[4].find(p=>p.item);for(let i=0;i<6;i++)dig(p);assert(catchItem(s,p.item));release(s);assert.equal(p.item.state,'caught');assert.equal(s.records[0].count,1);assert(!catchItem(s,p.item));});
function explore(s,z){s.zone=z;for(const p of s.beach.zones[z]){p.explored=true;p.open=true;for(let i=0;i<6;i++)dig(p);reveal(p,0);if(p.item)catchItem(s,p.item);}release(s);checkChallenges(s);}
for(let index=0;index<24;index++)test('exploration objective '+index+' succeeds from actual reveal and pickup events and fails untouched',()=>{const s=normalize({beach:generate(C.challenges[index].seed),zone:0,bucket:[],album:[]});const target=C.challenges[index].target;assert(challengeProgress(s,index)<target);explore(s,Math.floor(index/4));assert(challengeProgress(s,index)>=target);assert(s.completed.includes(index));checkChallenges(s);assert.equal(s.completed.filter(i=>i===index).length,1);});
test('fifty beaches keep entity displays and history bounded',()=>{const s=normalize({beach:generate(12),zone:0,bucket:[],album:[]});for(let i=0;i<50;i++){s.beach=generate(i);for(let z=0;z<6;z++)explore(s,z);}assert(s.bucket.length<=96);assert(s.records.length<=24);assert(JSON.stringify(s).length<200*1024);assert.equal(readSave(JSON.stringify(s)).records.length,24);});
test('malformed depth fields and future saves are rejected',()=>{const s=normalize({beach:generate(1),zone:0,bucket:[],album:[]});s.beach.zones[1][0].cells[0]=null;assert.equal(readSave(JSON.stringify(s)),null);s.version=999;assert.equal(readSave(JSON.stringify(s)),null);assert.notEqual(daySeed(new Date(2026,8,19)),daySeed(new Date(2026,8,20)));});
import {surface,rockProgress,rockCenter,covered} from '../.cache/model.mjs';
test('unopened terrain appearance does not reveal whether or what is underneath',()=>{const p=generate(92).zones[0][0],look=surface(p);assert.deepEqual(surface({...p,item:null}),look);assert.deepEqual(surface({...p,item:{...p.item,kind:22}}),look);});
test('sand clues include empty clues and unmarked buried discoveries',()=>{let emptyClue=0,hiddenUnmarked=0;for(let seed=0;seed<30;seed++)for(const p of generate(seed).zones[1]){if(!p.item&&surface(p).clue)emptyClue++;if(p.item&&!surface(p).clue)hiddenUnmarked++;}assert(emptyClue>30);assert(hiddenUnmarked>50);});
test('rock resistance scales with size and returns to the original state when cancelled',()=>{const p=generate(18).zones[0][0],raw=JSON.stringify(p);assert.equal(rockProgress(p,.003),0);assert(rockProgress(p,p.r*2)>.9);assert(rockProgress({...p,r:p.r*2},p.r)<rockProgress(p,p.r));assert.equal(JSON.stringify(p),raw);});
test('a replaced stone blocks its hidden catch and both flip directions preserve position',()=>{const p=generate(3).zones[0][0];p.item.state='visible';assert(covered(p,p.item));p.open=true;assert(!covered(p,p.item));p.shift=-1;assert(rockCenter(p).x<p.x);p.shift=1;assert(rockCenter(p).x>p.x);assert.equal(rockCenter(p,0).x,p.x);});
test('terrain refresh preserves existing finds, digging and collection ownership',()=>{const s=normalize({beach:generate(24),zone:0,bucket:[],album:[]}),p=s.beach.zones[0][0];p.open=true;reveal(p,0);catchItem(s,p.item);const id=p.item.id,kind=p.item.kind;delete s.beach.layout;p.x=.2;p.y=.2;const revised=normalize(s);assert.equal(revised.beach.layout,2);assert.equal(revised.beach.zones[0][0].item.id,id);assert.equal(revised.beach.zones[0][0].item.kind,kind);assert.equal(revised.beach.zones[0][0].item.state,'caught');assert.equal(revised.bucket.length,1);});

test('empty sand strokes leave bounded persistent marks without creating rewards',async()=>{const {scrapeGround,normalize}=await import('../.cache/model.mjs');const s=normalize({beach:generate(109),zone:1,bucket:[],album:[]}),before=JSON.stringify(s.beach.zones);for(let n=0;n<300;n++)scrapeGround(s.beach,1,-.4+(n%20)*.02,1.1+Math.floor(n/20)*.02);assert.equal(JSON.stringify(s.beach.zones),before);assert(s.beach.sandMarks[1].length<=128);assert(s.beach.sandMarks[1].length>0);assert.deepEqual(readSave(JSON.stringify(s)).beach.sandMarks,s.beach.sandMarks);assert.equal(scrapeGround(s.beach,1,Infinity,0).changed,false);assert.equal(scrapeGround(s.beach,0,.5,.5).changed,false);});
test('free sand strokes uncover pre-generated buried objects at their actual position',async()=>{const {scrapeGround}=await import('../.cache/model.mjs');const beach=generate(301),p=beach.zones[1].find(p=>p.item),id=p.item.id,kind=p.item.kind;for(let n=0;n<18;n++)scrapeGround(beach,1,p.x,p.y);assert.equal(p.item.state,'visible');assert.equal(p.item.id,id);assert.equal(p.item.kind,kind);});
