import {cp,readFile,writeFile,mkdir} from 'node:fs/promises';
import {newSave,createRun,cast,step,strike} from '../.cache/model.mjs';
const c=JSON.parse(await readFile('src/content/content.json','utf8')),dir='.cache/qa-preview';await mkdir(dir,{recursive:true});await cp('dist',dir,{recursive:true});const s=newSave(22371);s.run=createRun(22371,0);s.run.wait=1;
const calm=JSON.parse(JSON.stringify(s));calm.settings.reduced=true;const fixtures={reduced:calm,ready:s,fight:JSON.parse(JSON.stringify(s)),net:JSON.parse(JSON.stringify(s)),caught:JSON.parse(JSON.stringify(s))};
for(const key of ['fight','net','caught']){const r=fixtures[key].run;cast(r,.5,.5,.7);while(r.phase!=='bite')step(r,1/60);strike(r);if(key==='net'||key==='caught'){r.phase=key;r.x=.5;r.y=.68;r.stamina=.1;r.line=.1;}}
await writeFile(dir+'/fixture.js',`const fixtures=${JSON.stringify(fixtures)};let key=localStorage.getItem('qa-fishing');if(key&&fixtures[key])localStorage.setItem(${JSON.stringify(c.storageKey)},JSON.stringify(fixtures[key]));localStorage.removeItem('qa-fishing');document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');`);
await writeFile(dir+'/qa.js',`const box=document.createElement('div');box.style.cssText='position:fixed;bottom:100px;left:8px;z-index:20;max-width:85px';for(const key of ['ready','fight','net','caught','reduced']){const b=document.createElement('button');b.textContent='QA '+key;b.onclick=()=>{localStorage.setItem('qa-fishing',key);location.reload();};box.appendChild(b);}const b=document.createElement('button');b.textContent='QA 抛竿';b.onclick=async()=>{const canvas=document.getElementById('scene'),w=innerWidth,h=innerHeight,k=Math.min(w*(w>h?.6:.94),h*.85),ox=(w>h?w*.32:w*.5)-k/2,oy=h*.54-k*.5;for(const [type,x,y]of [['pointerdown',.5,.5],['pointermove',.5,.7],['pointerup',.5,.7]]){canvas.dispatchEvent(new PointerEvent(type,{pointerId:97,clientX:ox+x*k,clientY:oy+y*k,bubbles:true}));await new Promise(r=>setTimeout(r,90));}};box.appendChild(b);const n=document.createElement('button');n.textContent='QA 抄网';n.onclick=async()=>{const canvas=document.getElementById('scene'),w=innerWidth,h=innerHeight,k=Math.min(w*(w>h?.6:.94),h*.85),ox=(w>h?w*.32:w*.5)-k/2,oy=h*.54-k*.5;canvas.dispatchEvent(new PointerEvent('pointerdown',{pointerId:98,clientX:ox+(.5+(.28-.5)*1.12)*k,clientY:oy+(.5+(.84-Math.min(.64,.5+.12*h/(2*k*1.12)))*1.12)*k,bubbles:true}));canvas.dispatchEvent(new PointerEvent('pointermove',{pointerId:98,clientX:ox+.5*k,clientY:oy+(.5+(.68-Math.min(.64,.5+.12*h/(2*k*1.12)))*1.12)*k,bubbles:true}));await new Promise(r=>setTimeout(r,450));canvas.dispatchEvent(new PointerEvent('pointerup',{pointerId:98,clientX:ox+.5*k,clientY:oy+(.5+(.68-Math.min(.64,.5+.12*h/(2*k*1.12)))*1.12)*k,bubbles:true}));};box.appendChild(n);document.body.appendChild(box);for(const side of ['left','right']){const mask=document.createElement('div');mask.style.cssText='pointer-events:none;position:fixed;z-index:99;top:44px;width:124px;height:112px;background:rgba(180,40,50,.3);'+side+':0';document.body.appendChild(mask);}`);
let html=await readFile(dir+'/index.html','utf8');html=html.replace('<script src="./audio-data.js">','<script src="./fixture.js"></script><script src="./audio-data.js">').replace('</body>','<script src="./qa.js"></script><script src="./water-check.js"></script></body>');await writeFile(dir+'/index.html',html);console.log('QA preview ready; independent port only');

await cp('qa/water-check.js',dir+'/water-check.js');
