import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {makeSample,wash,pickGrain,finishPicked,emptySave,readSave} from '../.cache/model.mjs';const c=JSON.parse(readFileSync('src/content/content.json','utf8').replace(/^\uFEFF/,''));
test('seed and location produce immutable sample identity',()=>{assert.deepEqual(makeSample(42,0,c.locations[0],false),makeSample(42,0,c.locations[0],false));assert.equal(makeSample(1,0,c.locations[0],true).grains.filter(g=>g.gold).length,3);});
test('gentle wash reveals gold without creating or losing grains, collection is idempotent',()=>{const s=makeSample(42,0,c.locations[0],true),count=s.grains.length;for(let i=0;i<6000;i++)wash(s,1/60,.8,.6,c.locations[0],c.tuning);assert(s.mud<=c.tuning.collectMud);assert.equal(s.grains.length,count);assert(s.grains.every(g=>!g.gold||g.state==='pan'));const save=emptySave();for(const g of s.grains)if(g.state==='pan')assert(pickGrain(s,save,g.id,c.tuning));assert(finishPicked(s,save,c.tuning));assert.equal(save.count,3);assert(!finishPicked(s,save,c.tuning));assert.equal(save.count,3);});
test('extreme tilt has warning and visible border crossing before loss',()=>{const s=makeSample(2,0,c.locations[0],true);s.mud=.1;s.settled=1;wash(s,.05,0,1,c.locations[0],c.tuning);assert(s.grains.some(g=>g.warning>0));assert(!s.grains.some(g=>g.state==='lost'));for(let i=0;i<300;i++)wash(s,1/60,0,1,c.locations[0],c.tuning);assert(s.grains.some(g=>g.gold&&g.state==='lost'));assert(s.grains.filter(g=>g.state==='lost').every(g=>Math.hypot(g.x,g.y)>1));});
test('dirty sample cannot be banked; save round trip retains active sample',()=>{const save=emptySave(),s=makeSample(11,2,c.locations[2],false);assert(!finishPicked(s,save,c.tuning));save.active=s;assert.deepEqual(readSave(JSON.stringify(save)),save);assert.deepEqual(readSave('{broken'),emptySave());});
test('normal pools contain empty and populated samples across fixed seeds',()=>{const samples=Array.from({length:200},(_,i)=>makeSample(i*19173,1,c.locations[1],false));assert(samples.some(s=>!s.grains.some(g=>g.gold)));assert(samples.some(s=>s.grains.some(g=>g.gold)));});


test('sediment transport conserves mass and erosion removes only existing sand',async()=>{const {makeSediment,stepSediment}=await import('../.cache/model.mjs');const s=makeSediment(),mass=()=>s.density.reduce((a,b)=>a+b,0);for(let i=0;i<100;i++)stepSediment(s,.05,Math.sin(i)*.3,.1,.5,1);assert.ok(Math.abs(mass()-s.initial)<.001);for(let i=1;i<=100;i++)stepSediment(s,.05,.2,.1,.6,1-i/100);assert.ok(mass()<.001);assert.ok(s.density.every(d=>Number.isFinite(d)&&d>=0));});
test('water responds to direction and settles after the hand stops',async()=>{const {makeSlosh,stepSlosh}=await import('../.cache/model.mjs');const s=makeSlosh();for(let i=0;i<60;i++)stepSlosh(s,1/60,1,0,0);assert.ok(s.x<-.1);assert.notEqual(s.x,s.sandX);for(let i=0;i<600;i++)stepSlosh(s,1/60,0,0,0);assert.ok(Math.abs(s.x)+Math.abs(s.vx)+Math.abs(s.sandX)<.001);});


test('circular gesture tracks both directions across the angle seam',async()=>{const {makeOrbit,trackOrbit}=await import('../.cache/model.mjs');for(const sign of [-1,1]){const o=makeOrbit();for(let i=0;i<=240;i++){const a=sign*i/240*Math.PI*4;trackOrbit(o,Math.cos(a)*.6,Math.sin(a)*.6,i*20);}assert.ok(o.speed*sign>2);assert.ok(Math.abs(o.turn-sign*Math.PI*4)<.01);assert.ok(o.quality>.9);}});
test('horizontal strokes crossing center cannot count as circular turns',async()=>{const {makeOrbit,trackOrbit}=await import('../.cache/model.mjs');const o=makeOrbit();for(let i=0;i<300;i++)trackOrbit(o,Math.sin(i*.1)*.7,0,i*20);assert.equal(o.turn,0);assert.equal(o.speed,0);});
test('level pan settles the sample but does not magically remove sand',async()=>{const {makeSample,wash}=await import('../.cache/model.mjs');const {readFile}=await import('node:fs/promises');const c=JSON.parse(await readFile(new URL('../src/content/content.json',import.meta.url),'utf8'));const sample=makeSample(77,0,c.locations[0],true);for(let i=0;i<1200;i++)wash(sample,1/60,.7,0,c.locations[0],c.tuning);assert.equal(sample.mud,1);assert.ok(sample.settled>.95);for(let i=0;i<600;i++)wash(sample,1/60,.1,.6,c.locations[0],c.tuning);assert.ok(sample.mud<.8);assert.equal(sample.grains.filter(g=>g.gold&&g.state==='pan').length,3);});


test('individual pickups reject dirty samples and survive reload without duplication',()=>{const s=makeSample(92,0,c.locations[0],true),save=emptySave();const g=s.grains[0];assert.equal(pickGrain(s,save,g.id,c.tuning),null);s.mud=0;assert(pickGrain(s,save,g.id,c.tuning));save.active=s;const resumed=readSave(JSON.stringify(save));assert.equal(resumed.count,1);assert.equal(pickGrain(resumed.active,resumed,g.id,c.tuning),null);assert.equal(finishPicked(resumed.active,resumed,c.tuning),false);for(const grain of resumed.active.grains)if(grain.state==='pan')assert(pickGrain(resumed.active,resumed,grain.id,c.tuning));const active=resumed.active;assert(finishPicked(active,resumed,c.tuning));assert.equal(resumed.count,3);assert.equal(resumed.pans,1);assert.equal(finishPicked(active,resumed,c.tuning),false);assert.equal(resumed.active,null);assert(active.grains.every(g=>g.state==='bottle'));});
test('all content items have an introduction and a collection value',()=>{for(const item of c.items){assert.ok(item.description.length>10);assert.ok(item.value);assert.ok(item.valueNote.length>8);}});
import {immerse,emptyJourney,makeRecord,recordJourney,challengeMet,localDay,dailySeed} from '../.cache/model.mjs';
test('dry pan cannot wash sediment away and immersion replenishes a finite water supply',()=>{const s=makeSample(9,0,c.locations[0],true);s.water=0;for(let i=0;i<600;i++)wash(s,1/60,1,.6,c.locations[0],c.tuning);assert.equal(s.mud,1);assert.equal(s.settled,0);for(let i=0;i<90;i++)immerse(s,1/60,1);assert.equal(s.water,1);for(let i=0;i<600;i++)wash(s,1/60,1,.6,c.locations[0],c.tuning);assert(s.water<1&&s.water>0);assert(s.mud<1);});
test('sample point and amount change the seeded material; exact replay preserves every entity',()=>{const a=makeSample(789,5,c.locations[5],false,0,.45),b=makeSample(789,5,c.locations[5],false,1,1),again=makeSample(a.seed,a.location,c.locations[a.location],a.practice,a.point,a.amount,true);assert.notEqual(a.id,b.id);assert.notDeepEqual(a.grains,b.grains);assert.deepEqual(a.grains,again.grains);});
test('replayed sample can improve technique records without awarding duplicate collectibles',()=>{const save=emptySave(),s=makeSample(25,1,c.locations[1],true);s.mud=0;for(const g of s.grains)pickGrain(s,save,g.id,c.tuning);assert(finishPicked(s,save,c.tuning));recordJourney(s,save,c.challenges);const before={count:save.count,weight:save.weight,pans:save.pans,album:save.album.slice()},r=makeSample(s.seed,s.location,c.locations[1],s.practice,s.point,s.amount,true);r.mud=0;for(const g of r.grains)assert(pickGrain(r,save,g.id,c.tuning));assert(finishPicked(r,save,c.tuning));recordJourney(r,save,c.challenges);assert.deepEqual({count:save.count,weight:save.weight,pans:save.pans,album:save.album},before);assert.equal(save.journey.history.length,2);assert(save.journey.history[0].replay);});
test('all six sediment profiles can be cleaned and preserve finite entity ownership',()=>{for(let site=0;site<6;site++){const s=makeSample(49999,site,c.locations[site],true);for(let i=0;i<15000&&s.mud>c.tuning.collectMud;i++){if(s.water<.2)immerse(s,.05,1);wash(s,1/60,.8,i%600<160?0:.65,c.locations[site],c.tuning);}assert(s.mud<=c.tuning.collectMud,'site '+site);assert(s.grains.filter(g=>g.gold).every(g=>g.state==='pan'));assert(s.coarse<.01);assert(s.leaves<.01);}});
test('circular separation plus rinse removes coarse gravel, while gentle rinsing floats leaves',()=>{const s=makeSample(22,3,c.locations[3],true);const start=s.coarse;for(let i=0;i<500;i++)wash(s,1/60,.8,0,c.locations[3],c.tuning);assert.equal(s.coarse,start);for(let i=0;i<900;i++)wash(s,1/60,.8,.65,c.locations[3],c.tuning);assert(s.coarse<.01);const leaves=makeSample(22,4,c.locations[4],true);for(let i=0;i<500;i++)wash(leaves,1/60,.5,.6,c.locations[4],c.tuning);assert.equal(leaves.leaves,0);});
test('warning rescue requires an actual warned gold entity that is still picked up',()=>{const s=makeSample(73,2,c.locations[2],true),save=emptySave();s.mud=.15;s.settled=1;for(let i=0;i<12;i++)wash(s,1/60,0,1,c.locations[2],c.tuning);assert(s.grains.filter(g=>g.gold).every(g=>g.warned));for(let i=0;i<600;i++)wash(s,1/60,.8,.5,c.locations[2],c.tuning);s.mud=0;for(const g of s.grains)pickGrain(s,save,g.id,c.tuning);const r=makeRecord(s);assert.equal(r.rescued,3);assert.equal(r.retention,1);});
test('daily seed uses the local calendar, remains fixed within a day and changes across days',()=>{const date=new Date(2026,8,19,0,1);assert.equal(localDay(date),'2026-09-19');assert.equal(dailySeed(localDay(date)),dailySeed('2026-09-19'));assert.notEqual(dailySeed('2026-09-19'),dailySeed('2026-09-20'));});
const baseResult={id:'fixed',seed:73,location:0,point:1,amount:1,replay:false,practice:false,gold:0,retention:0,clean:0,largest:0,cycles:0,rescued:0,coarse:0,leaves:0,maxTilt:1,settled:0,kinds:[],seconds:50,date:'2026-09-19'};
const cases=[
 [{},null], [{gold:1},{gold:0}], [{clean:.96},{clean:.9}], [{gold:3,retention:1},{retention:.66}],
 [{settled:.95,gold:1},{settled:.5}], [{cycles:2},{cycles:1}], [{clean:.96,settled:.95},{clean:.8}], [{replay:true,retention:.8},{retention:.5}],
 [{kinds:[0]},{kinds:[1]}], [{maxTilt:.65,clean:.96},{maxTilt:.75}], [{rescued:1},{rescued:0}], [{gold:3,maxTilt:.8},{maxTilt:.9}],
 [{coarse:3},{coarse:2}], [{kinds:[2]},{kinds:[0]}], [{kinds:[7]},{kinds:[2]}], [{coarse:3,cycles:2,clean:.96},{cycles:1}],
 [{leaves:4,maxTilt:.7},{maxTilt:.95}], [{kinds:[16]},{kinds:[0]}], [{kinds:[9]},{kinds:[0]}], [{leaves:4,clean:.96,kinds:[8]},{leaves:2}],
 [{amount:.45},{amount:.8}], [{amount:1},{amount:.7}], [{point:1},{point:0}], [{clean:.96,gold:2,retention:1},{retention:.5}]
];
for(let i=0;i<c.challenges.length;i++)test('challenge '+c.challenges[i].id+' has reachable success and meaningful failure',()=>{const challenge=c.challenges[i],j=emptyJourney();j.points=['5:0'];j.history=[{...baseResult,retention:.5}];const yes={...baseResult,...cases[i][0],location:challenge.location},no={...yes,...cases[i][1]};if(i===0)no.location=1;assert(challengeMet(challenge,yes,j),challenge.name);assert(!challengeMet(challenge,no,j),challenge.name);});
test('all 18 collection types can occur in the configured finite sample pools',()=>{const kinds=new Set();for(let location=0;location<6;location++)for(let seed=1;seed<800;seed+=3)for(const g of makeSample(seed*13991,location,c.locations[location],false).grains)kinds.add(g.kind);assert.equal(kinds.size,18);assert.equal(c.challenges.length,24);for(let i=0;i<6;i++)assert.equal(c.challenges.filter(x=>x.location===i).length,4);});
test('records stay bounded and malformed duplicate entity identifiers do not load',()=>{const save=emptySave();for(let i=0;i<50;i++){const s=makeSample(i,0,c.locations[0],true);s.mud=0;for(const g of s.grains)pickGrain(s,save,g.id,c.tuning);finishPicked(s,save,c.tuning);recordJourney(s,save,c.challenges);}assert.equal(save.journey.history.length,20);assert.equal(save.journey.challenges.length,new Set(save.journey.challenges).size);assert(JSON.stringify(save).length<200*1024);const s=makeSample(90,0,c.locations[0],true);s.grains[1].id=s.grains[0].id;save.active=s;assert.equal(readSave(JSON.stringify(save)).active,null);});
test('every fixed challenge seed includes its required material at each sampling point',()=>{for(const challenge of c.challenges){for(let point=0;point<3;point++){const s=makeSample(challenge.seed,challenge.location,c.locations[challenge.location],false,point,.35),gold=s.grains.filter(g=>g.gold).length,counts={gold,retention:gold?1:0,rescued:gold,fine:s.grains.filter(g=>g.kind===0).length,flake:s.grains.filter(g=>g.kind===2||g.kind===6).length,heavy:s.grains.filter(g=>g.kind===7).length,mica:s.grains.filter(g=>g.kind===16).length,mineral:s.grains.filter(g=>!g.gold).length};for(const condition of challenge.conditions)if(condition.metric in counts)assert(counts[condition.metric]>=(condition.min||0),challenge.id+' point '+point);}}});
test('fixed sample reward claims survive recent-history eviction and save reload',()=>{const save=emptySave(),s=makeSample(99,1,c.locations[1],false,0,.5);s.claimKey='challenge:99:1:0';s.mud=0;for(const g of s.grains)pickGrain(s,save,g.id,c.tuning);finishPicked(s,save,c.tuning);save.ids=[];save.journey.history=[];const restored=readSave(JSON.stringify(save));assert(restored.claims[s.claimKey]&(1<<Math.round((.5-.35)/.05)));assert.equal(Object.keys(restored.claims).length,1);});
test('30 and 60 Hz integration stay close and malformed immersion input cannot poison water',()=>{const results=[];for(const hz of [30,60]){const s=makeSample(123,0,c.locations[0],true);for(let i=0;i<hz*20;i++)wash(s,1/hz,.8,.5,c.locations[0],c.tuning);results.push(s);}assert(Math.abs(results[0].mud-results[1].mud)<.003);assert(Math.abs(results[0].water-results[1].water)<.001);const s=results[0],before=s.water;immerse(s,.05,NaN);assert.equal(s.water,before);});
import {AudioBank} from '../.cache/model.mjs';
function audioFixture(deferred=false){let started=0,stopped=0,disconnected=0,decoded=0;const callbacks=[],ctx={state:'running',currentTime:0,destination:{},resume:async()=>{},decodeAudioData(bytes,yes,no){decoded++;assert(bytes.byteLength>4);if(deferred)callbacks.push(yes);else yes({duration:.3});},createBufferSource(){return{playbackRate:{value:1},connect(){},disconnect(){disconnected++;},start(){started++;},stop(){stopped++;},onended:null};},createGain(){return{gain:{setValueAtTime(){},linearRampToValueAtTime(){}},connect(){},disconnect(){disconnected++;}};}};return{ctx,callbacks,stats:()=>({started,stopped,disconnected,decoded})};}
test('audio bytes decode once, consecutive variants rotate and stop releases every voice',async()=>{const f=audioFixture(),data={a:Buffer.from('RIFF test1').toString('base64'),b:Buffer.from('RIFF test2').toString('base64')},bank=new AudioBank(data,{water:['a','b']},.1,()=>assert.fail('decode failed'),()=>f.ctx);await bank.enable();assert(bank.enabled);bank.play('water',.6);assert.equal(bank.last.water,0);bank.play('water',.7);assert.equal(bank.last.water,1);for(let i=0;i<20;i++)bank.play('water',1);assert.equal(bank.voices.size,6);bank.stop();assert.equal(bank.voices.size,0);assert.equal(f.stats().stopped,6);await bank.enable();assert.equal(f.stats().decoded,2);bank.mute();bank.play('water',1);assert.equal(f.stats().started,6);});
test('audio cancellation while decoding cannot enable or play a stale session',async()=>{const f=audioFixture(true),bank=new AudioBank({a:Buffer.from('RIFF sample').toString('base64')},{water:['a']},.1,()=>assert.fail(),()=>f.ctx);const loading=bank.enable();await Promise.resolve();assert.equal(f.callbacks.length,1);bank.mute();f.callbacks[0]({duration:.4});await loading;assert(!bank.enabled);bank.play('water',1);assert.equal(f.stats().started,0);});
test('audio capability/resume/decode failures retain a usable silent path',async()=>{for(const failure of ['factory','resume','decode']){const f=audioFixture();let errors=0;if(failure==='resume')f.ctx.resume=async()=>{throw Error('resume')};if(failure==='decode')f.ctx.decodeAudioData=(_b,_yes,no)=>no(Error('decode'));const bank=new AudioBank({a:Buffer.from('RIFF sample').toString('base64')},{water:['a']},.1,()=>errors++,()=>{if(failure==='factory')throw Error('unavailable');return f.ctx;});await bank.enable();assert(!bank.enabled);assert.equal(errors,1);bank.play('water',1);assert.equal(f.stats().started,0);}});
test('built-in sound clips are small PCM WAV resources rather than runtime media URLs',()=>{assert.equal(c.audio.assets.length,9);for(const asset of c.audio.assets){const bytes=readFileSync(asset.file);assert.equal(bytes.subarray(0,4).toString(),'RIFF');assert.equal(bytes.subarray(8,12).toString(),'WAVE');assert(bytes.length<100*1024);}});
test('coarse or organic debris blocks pickup even if fine sand is gone; finishing rinses can improve cleanliness',()=>{const s=makeSample(98,3,c.locations[3],true),save=emptySave();s.mud=.03;assert.equal(pickGrain(s,save,s.grains[0].id,c.tuning),null);s.coarse=0;s.mud=.05;s.settled=1;const before=makeRecord(s).clean;for(let i=0;i<80;i++)wash(s,1/60,.6,.45,c.locations[3],c.tuning);assert(makeRecord(s).clean>before);assert(pickGrain(s,save,s.grains[0].id,c.tuning));});

test('settled circles hand off to rinse guidance and refill takes priority',async()=>{const {washGuide}=await import('../.cache/model.mjs');const s=makeSample(9,0,c.locations[0],true);assert.equal(washGuide(s,0),'settle');for(let i=0;i<600;i++)wash(s,1/60,.7,0,c.locations[0],c.tuning);assert.equal(s.mud,1);assert.equal(washGuide(s,0),'rinse');assert.equal(washGuide(s,.5),'pour');s.water=.1;assert.equal(washGuide(s,.5),'refill');});
test('rim start waits for intent and permits tangential circle strokes',async()=>{const {rimIntent}=await import('../.cache/model.mjs');assert.equal(rimIntent(2,2),null);assert.equal(rimIntent(18,3),'wash');assert.equal(rimIntent(-18,2),'wash');assert.equal(rimIntent(1,22),'rim');assert.equal(rimIntent(0,-20),'wash');});
test('one short circle cannot fully stratify a loaded pan',()=>{const s=makeSample(42,0,c.locations[0],true);for(let i=0;i<180;i++)wash(s,1/60,.7,0,c.locations[0],c.tuning);assert(s.settled<.6);assert.equal(s.mud,1);});
test('ordinary rinsing retains every collectible crystal as well as gold',()=>{const s=makeSample(42,0,c.locations[0],true);for(let i=0;i<6000;i++){if(s.water<.2)immerse(s,1/60,1);wash(s,1/60,.8,.6,c.locations[0],c.tuning);}assert(s.grains.every(g=>g.state==='pan'));assert(s.grains.every(g=>Math.hypot(g.x,g.y)<.85));});

test('revealed crystals can be picked before the final rinse and cannot be picked twice',async()=>{const {canPickGrain}=await import('../.cache/model.mjs');const s=makeSample(42,0,c.locations[0],true),save=emptySave();s.mud=.28;const crystal=s.grains.find(g=>!g.gold),gold=s.grains.find(g=>g.gold);assert(canPickGrain(s,crystal,c.tuning));assert(!canPickGrain(s,gold,c.tuning));assert(pickGrain(s,save,crystal.id,c.tuning));assert(!pickGrain(s,save,crystal.id,c.tuning));assert(!finishPicked(s,save,c.tuning));});
test('ordinary rim movement stays safe while deliberate overtilt is still possible',async()=>{const {tiltFromDrag}=await import('../.cache/model.mjs');assert(tiltFromDrag(80,168)<.6);assert(tiltFromDrag(130,168)<.85);assert(tiltFromDrag(260,168)>.92);assert.equal(tiltFromDrag(-20,168),0);});
test('rinsing disturbs layers and asks for another settling cycle',async()=>{const {washGuide}=await import('../.cache/model.mjs');const s=makeSample(42,0,c.locations[0],true);s.settled=.75;for(let i=0;i<600;i++)wash(s,1/60,0,.6,c.locations[0],c.tuning);assert(s.settled<.3);assert(s.mud>c.tuning.collectMud);assert.equal(washGuide(s,.6),'recover');});
