import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {resolve,extname,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=resolve('minitool-dist'),results=[];
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+(new URL(req.url,'http://local').pathname==='/'?'/index.html':new URL(req.url,'http://local').pathname));assert(path.startsWith(root+sep));res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'})[extname(path)]||'application/octet-stream','Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'none'; object-src 'none'; base-uri 'none'"});res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});
try{for(const mode of ['file','csp','fallback'])for(const width of [375,390,430]){
 const ctx=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true}),page=await ctx.newPage(),errors=[],network=[];page.setDefaultTimeout(4500);
 await ctx.addInitScript(({fallback})=>{window.__album=[];window.__deny=true;window.xhs={miniTool:{writeTempFile:async({data})=>{window.__album.push({type:'write',prefix:data.slice(0,23),bytes:data.length});return{filePath:'/mock/roomish.jpg'};},saveImageToPhotosAlbum:async({filePath})=>{window.__album.push({type:'save',filePath});if(window.__deny){window.__deny=false;throw Error('permission denied');}return{};}}};window.fetch=()=>{throw Error('fetch is forbidden');};window.XMLHttpRequest=undefined;window.ResizeObserver=undefined;Object.fromEntries=undefined;Object.hasOwn=undefined;String.prototype.replaceAll=undefined;Array.prototype.flatMap=undefined;if(fallback){const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl2'?null:get.call(this,type,...args);};}},{fallback:mode==='fallback'});
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))network.push(r.url());});
 const click=async action=>{if(action.startsWith('tab-')&&!await page.locator(`[data-action="${action}"]:visible`).count())await page.locator('[data-action="open-studio"]:visible').click();if(action==='room-properties'&&!await page.locator('[data-action="room-properties"]:visible').count())await page.locator('[data-action="room-actions"]:visible').click();const dialog=page.locator(`#modal[open] [data-action="${action}"]:visible`);await(await dialog.count()?dialog:page.locator(`[data-action="${action}"]:visible`)).first().click();await page.waitForTimeout(130);};
 try{
  await page.goto(mode==='csp'?`http://127.0.0.1:${server.address().port}/`:pathToFileURL(resolve(root,'index.html')).href);await page.waitForSelector('#viewport canvas');await page.addStyleTag({content:':root{--safe-area-inset-top:28px;--safe-area-inset-bottom:16px}'});assert.ok(await page.locator('.brand-mark img').evaluate(e=>e.complete&&e.naturalWidth>0));
  const metrics=await page.evaluate(()=>window.ROOMISH_RENDER_STATS);if(mode==='fallback')assert.equal(metrics.renderer,'canvas2d');else{assert.notEqual(metrics.renderer,'canvas2d');assert.ok(metrics.calls<=100&&metrics.triangles<=100000&&metrics.pixels<=2000000);}
  await click('tab-layouts');await click('blank');await click('room-properties');await page.locator('#room-form [name="w"]').fill('6');assert.ok(await page.locator('#draft-notice').isVisible());await page.locator('#inspector [data-action="deselect"]:visible').first().click();await click('mobile-menu');await click('close-modal');await click('room-properties');assert.equal(await page.locator('#room-form [name="w"]').inputValue(),'6');await click('discard-draft');assert.equal(await page.locator('#room-form [name="w"]').inputValue(),'5');
  await page.locator('#room-form [name="w"]').fill('6');await page.locator('#room-form [name="w"]').focus();await page.setViewportSize({width,height:360});await page.waitForTimeout(150);assert.ok(!await page.locator('body').evaluate(e=>e.classList.contains('natural-landscape')));const done=await page.locator('[data-action="complete-settings"]:visible').boundingBox();assert.ok(done&&done.y+done.height<=361);await page.setViewportSize({width,height:844});await click('complete-settings');await page.waitForTimeout(300);
  await page.locator('#quick-history [data-action="undo"]').click();await page.waitForTimeout(300);let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('roomish-project-15-v1')).plans[0]);assert.equal(saved.rooms[0].w,5);await page.locator('#quick-history [data-action="redo"]').click();await page.waitForTimeout(300);
  await page.locator('.orientation-toggle').click();await page.waitForTimeout(150);await click('finish');await click('finish-tools');await click('capture');await page.locator('.export-preview').waitFor();await click('save-album');assert.ok(!await page.locator('[data-action="save-album"]').isDisabled());await click('save-album');const calls=await page.evaluate(()=>window.__album);assert.equal(calls.length,4);assert.equal(calls[0].prefix,'data:image/jpeg;base64,');assert.ok(calls[0].bytes<=1398100);assert.equal(calls[3].filePath,'/mock/roomish.jpg');await click('close-modal');
  await page.reload();await page.waitForSelector('#viewport canvas');saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('roomish-project-15-v1')).plans[0]);assert.equal(saved.rooms[0].w,6);assert.deepEqual(errors,[]);assert.deepEqual(network,[]);results.push({mode,width,passed:true,metrics,checks:['offline boot and logo','legacy API fallbacks','draft notice and discard','close/reopen draft','keyboard simulation','quick undo/redo','landscape export','album refusal and retry mock','saved state reload'],errors,network});
 }catch(e){results.push({mode,width,passed:false,error:e.message,errors,network});await page.screenshot({path:`release/check-failure-${mode}-${width}.png`});}console.log(JSON.stringify(results.at(-1)));await writeFile('release/acceptance-1.1.0.json',JSON.stringify(results,null,2));await ctx.close();
}}finally{await browser.close();await new Promise(r=>server.close(r));}assert.ok(results.every(r=>r.passed),'Release acceptance failed');
