import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const {chromium}=createRequire(import.meta.url)('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({channel:'chrome',headless:true}),out=new URL('./',import.meta.url),results=[];
try{for(const [width,height,mode]of [[390,844,'portrait'],[390,844,'forced'],[844,390,'natural'],[1280,900,'desktop']]){
 const context=await browser.newContext({viewport:{width,height},isMobile:mode!=='desktop',hasTouch:mode!=='desktop'}),page=await context.newPage();page.setDefaultTimeout(3000);page.on('dialog',d=>d.accept());
 const click=async a=>{if(a.startsWith('tab-')&&!await page.locator(`[data-action="${a}"]:visible`).count())await page.locator('[data-action="open-studio"]:visible').click();if(a==='room-properties'&&!await page.locator('[data-action="room-properties"]:visible').count())await page.locator('[data-action="room-actions"]:visible').click();const modal=page.locator(`#modal[open] [data-action="${a}"]:visible`);await (await modal.count()?modal:page.locator(`[data-action="${a}"]:visible`)).first().click();await page.waitForTimeout(180);};
 const fresh=async()=>{await page.goto('http://127.0.0.1:4311/');await page.waitForSelector('#viewport canvas');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForSelector('#viewport canvas');await page.addStyleTag({content:':root{--safe-area-inset-top:28px}'});if(mode==='forced')await page.locator('.orientation-toggle').click();await page.waitForTimeout(180);};
 const blank=async()=>{await click('tab-layouts');await click('blank');await click('room-properties');};
 const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('roomish-project-15-v1')).plans[0].rooms[0].w);
 const check=async(name,fn)=>{for(let attempt=1;attempt<=2;attempt++){await fresh();let data;try{data=await fn();}catch(e){data={pass:false,error:e.message};}const row={width,height,mode,name,attempt,...data};if(!row.pass){row.screenshot=`final-${mode}-${name}-${attempt}.png`;await page.screenshot({path:fileURLToPath(new URL(row.screenshot,out))});}results.push(row);console.log(JSON.stringify(row));await writeFile(new URL('final-flows.json',out),JSON.stringify(results,null,2));if(row.pass)break;}};
 await check('draft-not-implicitly-saved',async()=>{await blank();const before=await stored();await page.locator('#room-form [name="w"]').fill('6');await page.locator('#inspector [data-action="deselect"]:visible').first().click();await page.waitForTimeout(300);const afterClose=await stored();await click(mode==='desktop'?'inventory':'mobile-menu');await page.waitForTimeout(350);const afterMenu=await stored();return{pass:before===afterClose&&before===afterMenu,before,afterClose,afterMenu};});
 await check('draft-invalid-other-tools',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('');await page.locator('#inspector [data-action="deselect"]:visible').first().click();await click(mode==='desktop'?'inventory':'mobile-menu');return{pass:await page.locator('#modal').evaluate(e=>e.open),toast:await page.locator('#toast').textContent()};});
 await check('save-reload',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('6');if(mode==='desktop')await page.locator('#room-form button[type="submit"]').click();else await click('complete-settings');await page.waitForTimeout(350);await page.reload();await page.waitForSelector('#viewport canvas');return{pass:await stored()===6};});
 await check('desktop-collapsed-space',async()=>{if(mode!=='desktop')return{pass:true,note:'Not applicable'};await blank();await page.locator('#inspector [data-action="deselect"]:visible').first().click();const layout=await page.evaluate(()=>{const s=document.querySelector('.studio').getBoundingClientRect(),v=document.querySelector('.workspace').getBoundingClientRect();return{unusedRight:s.right-v.right,columns:getComputedStyle(document.querySelector('.studio')).gridTemplateColumns};});return{pass:layout.unusedRight<8,...layout};});
 await check('finish-inventory',async()=>{await click('finish');await click('finish-tools');await click('inventory');const open=await page.locator('#modal').evaluate(e=>e.open);await click('close-modal');return{pass:open&&!await page.locator('#modal').evaluate(e=>e.open)};});
 await context.close();
}}finally{await browser.close();}
