import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const {chromium}=createRequire(import.meta.url)('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=new URL('./',import.meta.url),results=[],browser=await chromium.launch({channel:'chrome',headless:true});
try{for(const [width,height,mode]of [[390,844,'portrait'],[390,844,'forced'],[844,390,'natural'],[1280,900,'desktop']]){
 const context=await browser.newContext({viewport:{width,height},isMobile:mode!=='desktop',hasTouch:mode!=='desktop'}),page=await context.newPage(),errors=[];page.setDefaultTimeout(3000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const click=async a=>{await page.locator(`[data-action="${a}"]:visible`).first().click();await page.waitForTimeout(100);};
 const fresh=async()=>{await page.goto('http://127.0.0.1:4311/');await page.waitForSelector('#viewport canvas');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForSelector('#viewport canvas');await page.waitForTimeout(150);await page.addStyleTag({content:':root{--safe-area-inset-top:28px}'});if(mode==='forced'){await page.locator('.orientation-toggle').click();await page.waitForTimeout(150);}};
 const blank=async()=>{await click('tab-layouts');await click('blank');await click('room-properties');};
 const state=()=>page.evaluate(()=>({modal:document.querySelector('#modal').open,classes:document.body.className,toast:document.querySelector('#toast').textContent,panel:getComputedStyle(document.querySelector('#inspector')).display,w:document.querySelector('#room-form [name="w"]')?.value,editRoomButtons:[...document.querySelectorAll('[data-action="room-properties"]')].filter(b=>b.checkVisibility()).length}));
 const check=async(name,fn)=>{for(let attempt=1;attempt<=2;attempt++){await fresh();let data;try{data=await fn();}catch(e){data={pass:false,error:e.message};}const row={width,height,mode,name,attempt,...data,errors:[...errors]};if(!row.pass){row.screenshot=`flow-${width}-${mode}-${name}-${attempt}.png`;await page.screenshot({path:fileURLToPath(new URL(row.screenshot,out))});}results.push(row);console.log(JSON.stringify(row));await writeFile(new URL('flows.json',out),JSON.stringify(results,null,2));if(row.pass)break;}};
 await check('inventory-close',async()=>{if(mode!=='desktop')await click('mobile-menu');await click('inventory');await page.keyboard.press('Escape');const s=await state();return{pass:!s.modal&&!s.classes.includes('modal-open'),state:s};});
 await check('dimension-save-reload',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('6');if(mode==='desktop')await page.locator('#room-form button[type="submit"]').click();else await click('complete-settings');await page.waitForTimeout(400);await page.reload();await page.waitForSelector('#viewport canvas');const width=await page.evaluate(()=>JSON.parse(localStorage.getItem('roomish-project-15-v1')).plans[0].rooms[0].w);return{pass:width===6,width};});
 await check('collapsed-draft-menu-trap',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('');await page.locator('#inspector [data-action="deselect"]:visible').first().click();if(mode!=='desktop')await click('mobile-menu');else await click('inventory');const s=await state();return{pass:s.modal,state:s};});
 await check('escape-closes-settings',async()=>{await blank();await page.keyboard.press('Escape');const s=await state();return{pass:s.panel==='none',state:s};});
 await check('desktop-reopen-settings',async()=>{if(mode!=='desktop')return{pass:true,note:'Desktop-only check'};await blank();await page.locator('#inspector [data-action="deselect"]:visible').first().click();await click('room-properties');const s=await state();return{pass:s.panel!=='none',state:s};});
 await check('finish-preview-tools',async()=>{await click('finish');await click('finish-tools');await click('inventory');const s=await state();await click('close-modal');return{pass:s.modal&&!(await state()).modal};});
 await check('walk-exit-tools',async()=>{await click('finish');await click('inside');let s=await state();const entered=s.classes.includes('walking');await click('walk-rooms');await click('close-modal');await click('exit-walk');s=await state();return{pass:entered&&!s.classes.includes('walking')&&!s.modal,state:s};});
 await context.close();
}}finally{await browser.close();}
