import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=new URL('./',import.meta.url),results=[];
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 for(const [width,height,mode]of [[375,844,'portrait'],[390,844,'portrait'],[430,844,'portrait'],[390,844,'forced'],[844,390,'natural'],[1280,900,'desktop']]){
  const context=await browser.newContext({viewport:{width,height},hasTouch:mode!=='desktop',isMobile:mode!=='desktop'}),page=await context.newPage(),errors=[];
  page.setDefaultTimeout(2500);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const click=async action=>{await page.locator(`[data-action="${action}"]:visible`).first().click();await page.waitForTimeout(100);};
  const fresh=async()=>{await page.goto('http://127.0.0.1:4311/');await page.waitForSelector('#viewport canvas');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForSelector('#viewport canvas');await page.waitForTimeout(200);await page.addStyleTag({content:':root{--safe-area-inset-top:28px;--safe-area-inset-bottom:16px}'});if(mode==='forced'){await page.locator('.orientation-toggle').click();await page.waitForTimeout(200);}};
  const blank=async()=>{await click('tab-layouts');await click('blank');await click('room-properties');};
  const snapshot=async()=>page.evaluate(()=>({panel:getComputedStyle(document.querySelector('#inspector')).display,drawer:document.body.classList.contains('drawer-open'),modal:document.querySelector('#modal').open,toast:document.querySelector('#toast').textContent,classes:document.body.className,w:document.querySelector('#room-form [name="w"]')?.value}));
  const check=async(name,fn)=>{await fresh();let data;try{data=await fn();}catch(e){data={pass:false,error:e.message};}const item={width,height,mode,name,...data,errors:[...errors]};if(!item.pass){const filename=`${width}-${mode}-${name}.png`;await page.screenshot({path:new URL(filename,out).pathname.replace(/^\/([A-Za-z]:)/,'$1')});item.screenshot=filename;}results.push(item);console.log(JSON.stringify(item));await writeFile(new URL('results.json',out),JSON.stringify(results,null,2));};
  await check('close-invalid-draft',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('');await page.locator('#inspector [data-action="deselect"]:visible').first().click();const closed=await snapshot();await click('room-properties');const opened=await snapshot();return{pass:closed.panel==='none'&&opened.panel!=='none'&&opened.w==='',closed,opened};});
  await check('collapse-reopen-through-menu',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('');await page.locator('#inspector [data-action="deselect"]:visible').first().click();const menu=page.locator('[data-action="room-actions"]:visible');if(!await menu.count())return{pass:true,note:'Floating room menu not present in this layout'};await menu.click();const state=await snapshot();return{pass:state.modal,state};});
  await check('close-library',async()=>{await click('tab-furniture');const close=page.locator('#library [data-action="close-panel"]:visible');if(!await close.count())return{pass:true,note:'Desktop library is persistent'};await close.click();return{pass:!(await snapshot()).drawer,state:await snapshot()};});
  await check('complete-settings',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('6');const done=page.locator('[data-action="complete-settings"]:visible');if(!await done.count())return{pass:true,note:'Desktop uses Apply, no completion control'};await done.click();const state=await snapshot();return{pass:state.panel==='none'&&state.w==='6',state};});
  await check('close-properties-desktop',async()=>{await blank();await page.locator('#inspector [data-action="deselect"]:visible').first().click();return{pass:(await snapshot()).panel==='none',state:await snapshot()};});
  await check('escape-dialog',async()=>{await click('inventory');await page.keyboard.press('Escape');const state=await snapshot();const modalClass=await page.locator('body').evaluate(e=>e.classList.contains('modal-open'));return{pass:!state.modal&&!modalClass,state,modalClass};});
  await check('saved-dimensions-reload',async()=>{await blank();await page.locator('#room-form [name="w"]').fill('6');await page.locator('#room-form button[type="submit"]').click();await page.waitForTimeout(350);const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('roomish-project-15-v1')));await page.reload();await page.waitForSelector('#viewport canvas');const reloaded=await page.evaluate(()=>JSON.parse(localStorage.getItem('roomish-project-15-v1')));return{pass:stored.plans[0].rooms[0].w===6&&reloaded.plans[0].rooms[0].w===6};});
  await check('host-overlap',async()=>{if(mode==='desktop')return{pass:true,note:'Host overlays not applicable'};const intersections=await page.evaluate(()=>{const w=innerWidth,areas=[{left:12,top:48,right:48,bottom:84},{left:w-48,top:48,right:w-12,bottom:84}];return [...document.querySelectorAll('button')].filter(b=>b.checkVisibility()).flatMap(b=>{const r=b.getBoundingClientRect();return areas.some(a=>r.left<a.right&&r.right>a.left&&r.top<a.bottom&&r.bottom>a.top)?[{action:b.dataset.action||b.className,rect:{x:r.x,y:r.y,w:r.width,h:r.height}}]:[];});});return{pass:!intersections.length,intersections,note:'Conservative simulated host rectangles, not device measurement'};});
  await context.close();
 }
}finally{await browser.close();}
