import {RhythmEngine,StageTimeline} from './engine.mjs';
import {outputTime,medianOffset} from './audio-clock.mjs';
import {parseChart} from './chart-io.mjs';
const C=await fetch(new URL('./content/content.json',import.meta.url)).then(r=>{if(!r.ok)throw Error(r.status);return r.json();});
let draftMode=false;if(new URLSearchParams(location.search).has('draft')){try{const raw=localStorage.getItem('tongfu-chart-draft-v1');if(raw){C.notes=parseChart(raw,C.track);C.practiceNotes=C.notes.filter(n=>n.time>=C.practiceRange.start&&n.time+n.duration<C.practiceRange.end);draftMode=true;}}catch{}}
let activePracticeRange=C.practiceRange;
const U=C.ui, $=s=>document.querySelector(s), app=$('#app');
document.title=C.title;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let settings={volume:.75,sfx:true,offset:0,visualOffset:0,guide:false,speed:1},best=0,records={},storageOK=true;
try{const stored=JSON.parse(localStorage.getItem('tongfu-rhythm-v1')||'{}');records=stored.records&&typeof stored.records==='object'?stored.records:{};if(stored.best)records[stored.chartRevision||2]=Math.max(Number(records[stored.chartRevision||2])||0,Number(stored.best)||0);best=Number(records[C.track.chartRevision])||0;const s=stored.settings||{};settings={volume:Number.isFinite(Number(s.volume??.75))?Math.max(0,Math.min(1,Number(s.volume??.75))):.75,sfx:s.sfx!==false,offset:stored.syncVersion===3?Math.max(-250,Math.min(250,Number(s.offset)||0)):0,visualOffset:Math.max(-250,Math.min(250,Number(s.visualOffset)||0)),guide:s.guide===true,speed:[0,1,2].includes(s.speed)?s.speed:1};}catch{storageOK=false;}
function save(){try{records[C.track.chartRevision]=best;localStorage.setItem('tongfu-rhythm-v1',JSON.stringify({best,records,chartRevision:C.track.chartRevision,syncVersion:3,settings}));}catch{storageOK=false;}
}
let ctx,buffer,musicGain,source,origin=0,position=0,mode='home',practice=false,engine,limit=0,raf=0,countdownUntil=0;
let stageTimeline,currentPhrase=-1,settled=new Set(),frozen=0,effects=[],lastFrame=0,held=new Map(),lastFeedback='',feedbackUntil=0,loadPromise,calibration=null,guideTones=[];
const asset=p=>new URL('../'+p,import.meta.url).href;
const artStyle=(index,frozenState=false)=>`background-image:url('${asset(C.cast[index].art)}');background-position:${frozenState?100:0}% center;${C.cast[index].homeMask?`--cutout-mask:url('${asset(C.cast[index].homeMask)}')`:''}`;
const format=t=>`${Math.floor(Math.max(0,t)/60)}:${String(Math.floor(Math.max(0,t)%60)).padStart(2,'0')}`;
function initAudio(){if(!ctx){ctx=new AudioContext({latencyHint:'interactive'});musicGain=ctx.createGain();musicGain.gain.value=settings.volume;musicGain.connect(ctx.destination);ctx.addEventListener('statechange',()=>{if(ctx.state!=='running')pause();});}return ctx.resume();}
async function loadAudio(){await initAudio();if(buffer)return;if(!loadPromise)loadPromise=fetch(asset(C.track.src)).then(r=>{if(!r.ok)throw Error(r.status);return r.arrayBuffer();}).then(b=>ctx.decodeAudioData(b)).then(b=>{buffer=b;}).catch(e=>{loadPromise=null;throw e;});await loadPromise;}
function tone(frequency=740,duration=.055,gain=.045,when=ctx?.currentTime){if(!ctx)return;const osc=ctx.createOscillator(),g=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(frequency,when);osc.frequency.exponentialRampToValueAtTime(frequency*.6,when+duration);g.gain.setValueAtTime(gain,when);g.gain.exponentialRampToValueAtTime(.001,when+duration);osc.connect(g).connect(ctx.destination);osc.onended=()=>{osc.disconnect();g.disconnect();};osc.start(when);osc.stop(when+duration);return osc;}
function stopSource(){for(const o of guideTones){try{o.stop();}catch{}}guideTones=[];if(source){try{source.stop();}catch{}source.disconnect();source=null;}}
function playFrom(pos,lead=3){stopSource();position=pos;countdownUntil=ctx.currentTime+lead;origin=countdownUntil-pos;source=ctx.createBufferSource();source.buffer=buffer;source.connect(musicGain);source.start(countdownUntil,pos);if(settings.guide){const seen=new Set();for(const n of engine.notes){if(n.time<pos||n.time>=limit||seen.has(n.time))continue;seen.add(n.time);guideTones.push(tone(n.source==='vocal'?1050:650,.035,.045,origin+n.time));}}mode='countdown';}
function songTime(at=performance.now()){if(mode==='paused')return position;if(mode==='countdown')return position;return Math.max(0,outputTime(ctx,at)-origin);}
function cleanup(){cancelAnimationFrame(raf);stopSource();held.clear();calibration=null;}
function showHome(){cleanup();mode='home';app.innerHTML=`<main class="shell home"><header class="mast"><a class="brand" href="./"><span class="seal">${C.seal}</span>${esc(C.brand)}</a><button class="icon-button" id="settings" aria-label="${U.settings}">☷</button></header><section class="hero"><div class="hero-veil"></div><div class="hero-copy"><p class="eyebrow">${C.eyebrow}</p><h1>${C.titleParts[0]}<span>${C.titleParts[1]}</span></h1><p class="tagline">${C.subtitle}</p></div><div class="year-stamp">${C.yearStamp}<span>${C.yearLabel}</span></div><div class="roster">${C.cast.map((p,i)=>`<div class="roster-person"><div class="sprite${p.homeMask?' cutout':''}" style="${artStyle(i)}"></div><span>${p.name}</span></div>`).join('')}</div><div class="hero-bottom"><span>✦ ${C.anniversary}</span><span>${C.heroCaption}</span></div></section><section class="home-body"><div class="track-card"><div class="record"><span>${C.recordLabel}</span></div><div class="track-copy"><h2>${C.track.title}<span>${C.track.artist}</span></h2><p>${draftMode?C.studio.draftTag:C.track.version} · ${C.track.bpm} BPM</p></div><div class="track-time">${C.displayDuration}<small>${U.durationLabel}</small></div></div><div class="stats-strip"><span>${C.notes.length} <small>${U.noteCount}</small></span><i></i><span>4 <small>${C.laneLabel}</small></span><i></i><span>${Math.floor(best).toLocaleString()} <small>${U.best}</small></span></div><button class="primary start" id="start">${U.start}<span>→</span></button><div class="secondary-row"><button class="text-button" id="practice">▷ ${U.practice}</button><button class="text-button" id="howto">${U.tutorialTitle} ↗</button></div><button class="text-button rap-practice" id="rap-practice">▷ ${U.rapPractice}</button><button class="text-button rap-practice" id="verse-practice">${U.versePractice}</button><a class="text-button studio-link" href="?studio=1">${U.studioLink} ↗</a><div class="tutorial">${U.tutorial.map((t,i)=>`<div><span class="tutorial-symbol symbol-${i}">${t.name}</span><p>${t.text}</p></div>`).join('')}</div><p class="keyboard-hint">${U.accessibility}</p><footer>${U.footer}</footer>${storageOK?'':`<p class="notice">${U.storageError}</p>`}</section></main>`;
$('#start').onclick=()=>begin(false);$('#practice').onclick=()=>begin(true);$('#rap-practice').onclick=()=>begin(true,C.rapPracticeRange);$('#verse-practice').onclick=showVersePractice;$('#settings').onclick=showSettings;$('#howto').onclick=()=>showInfo();}
function showVersePractice(){const d=openDialog(`<h2>${U.versePractice}</h2><p>${U.versePracticeHint}</p><label class="setting-label" for="verse-segment">${U.versePracticeSelect}</label><select id="verse-segment" class="verse-select">${C.verseFlow.practiceSegments.map((s,i)=>`<option value="${i}">${esc(s.title)}</option>`).join('')}</select><button class="primary" id="verse-start">${U.versePracticeStart}</button><button class="text-button" data-close>${U.close}</button>`);$('#verse-start').onclick=()=>{const range=C.verseFlow.practiceSegments[Number($('#verse-segment').value)];d.close();begin(true,range);};}
function showInfo(){openDialog(`<h2>${U.tutorialTitle}</h2>${U.tutorial.map(t=>`<p class="help-line"><strong>${t.name}</strong>${t.text}</p>`).join('')}<p class="muted">${U.accessibility}</p><button class="primary" data-close>${U.close}</button>`);}
function openDialog(body){const old=$('dialog');old?.remove();const d=document.createElement('dialog');d.innerHTML=`<div class="dialog-inner">${body}</div>`;app.append(d);d.showModal();d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('close',()=>{if(calibration?.tones)for(const o of calibration.tones){try{o.stop();}catch{}}calibration=null;d.remove();});return d;}
function showSettings(){if(mode==='playing'||mode==='countdown')pause();const d=openDialog(`<div class="dialog-heading"><h2>${U.settings}</h2><button class="icon-button" data-close aria-label="${U.close}">×</button></div><label class="setting-label">${U.volume}<output id="volume-value">${Math.round(settings.volume*100)}%</output></label><input aria-label="${U.volume}" id="volume" type="range" min="0" max="1" step=".01" value="${settings.volume}"><label class="switch-row">${U.sfx}<input type="checkbox" id="sfx" ${settings.sfx?'checked':''}></label><label class="setting-label">${U.offset}<output id="offset-value">${settings.offset} ms</output></label><input aria-label="${U.offset}" id="offset" type="range" min="-250" max="250" step="5" value="${settings.offset}"><p class="muted">${U.offsetHint}</p><label class="setting-label">${U.visualOffset}<output id="visual-value">${settings.visualOffset} ms</output></label><input aria-label="${U.visualOffset}" id="visual-offset" type="range" min="-250" max="250" step="5" value="${settings.visualOffset}"><p class="muted">${U.visualHint}</p><label class="switch-row">${U.guide}<input type="checkbox" id="guide" ${settings.guide?'checked':''}></label><p class="muted">${U.guideHint}</p><label class="setting-label">${U.speed}</label><div class="speed-options">${U.speedOptions.map((s,i)=>`<button data-speed="${i}" class="${settings.speed===i?'selected':''}">${s}</button>`).join('')}</div><button id="calibrate" class="secondary">${U.calibrate}</button><p id="calibration-status" class="muted">${U.calibrateHint}</p><button id="tap" class="primary" hidden>${U.tap} <span id="tap-count">0 / 8</span></button><button id="reset" class="text-button">${U.reset}</button>`);
$('#volume').oninput=e=>{settings.volume=Number(e.target.value);$('#volume-value').textContent=`${Math.round(settings.volume*100)}%`;if(musicGain)musicGain.gain.value=settings.volume;save();};$('#sfx').onchange=e=>{settings.sfx=e.target.checked;save();};$('#offset').oninput=e=>{settings.offset=Number(e.target.value);$('#offset-value').textContent=`${settings.offset} ms`;save();};d.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{settings.speed=Number(b.dataset.speed);d.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('selected',x===b));save();});$('#visual-offset').oninput=e=>{settings.visualOffset=Number(e.target.value);$('#visual-value').textContent=`${settings.visualOffset} ms`;save();};$('#guide').onchange=e=>{settings.guide=e.target.checked;save();};$('#reset').onclick=()=>{settings={volume:.75,sfx:true,offset:0,visualOffset:0,guide:false,speed:1};save();if(musicGain)musicGain.gain.value=.75;d.close();showSettings();};$('#calibrate').onclick=async()=>{await initAudio();if(calibration?.tones)for(const o of calibration.tones){try{o.stop();}catch{}}const start=ctx.currentTime+1;calibration={start,samples:[],used:new Set(),tones:[]};for(let i=0;i<12;i++)calibration.tones.push(tone(880,.065,.12,start+i*.65));$('#tap').hidden=false;$('#tap-count').textContent='0 / 8';};$('#tap').onpointerdown=e=>{e.preventDefault();if(!calibration)return;const index=Math.round((outputTime(ctx,e.timeStamp)-calibration.start)/.65);if(index<0||index>11||calibration.used.has(index))return;calibration.used.add(index);calibration.samples.push((outputTime(ctx,e.timeStamp)-calibration.start-index*.65)*1000);$('#tap-count').textContent=`${calibration.samples.length} / 8`;if(calibration.samples.length===8){const value=medianOffset(calibration.samples);if(value!==null){settings.offset=value;save();$('#offset').value=value;$('#offset-value').textContent=`${value} ms`;$('#calibration-status').textContent=U.calibrationDone;}else $('#calibration-status').textContent=U.calibrationRetry;for(const o of calibration.tones){try{o.stop();}catch{}}calibration=null;$('#tap').hidden=true;}};}
async function begin(isPractice,range=C.practiceRange){if(mode==='loading')return;mode='loading';const btn=$(isPractice?'#practice':'#start');if(btn){btn.disabled=true;btn.textContent=U.loading;}try{await loadAudio();}catch{mode='home';if(btn){btn.disabled=false;btn.textContent=U.retry;}openDialog(`<p>${U.loadError}</p><button data-close class="primary">${U.close}</button>`);return;}
practice=isPractice;activePracticeRange=range;limit=practice?range.end:buffer.duration;engine=new RhythmEngine(practice?C.notes.filter(n=>n.time>=range.start&&n.time+n.duration<range.end):C.notes,C.rules);currentPhrase=-1;stageTimeline=new StageTimeline(C.phrases,C.playability.sceneFreezeSeconds);settled=stageTimeline.settled;frozen=0;effects=[];lastFeedback='';held.clear();renderGame();playFrom(practice?activePracticeRange.start:0);lastFrame=performance.now();raf=requestAnimationFrame(frame);}
function renderGame(){app.innerHTML=`<main class="shell game"><header class="game-header"><div class="score-box"><small>${U.score}</small><strong id="score">000000</strong></div><div class="game-title">${C.gameTitle}<small>${draftMode?C.studio.draftTag:practice?(activePracticeRange.title||(activePracticeRange===C.rapPracticeRange?U.rapPracticeTag:U.practiceTag)):C.track.title}</small></div><button id="pause" class="icon-button" aria-label="${U.pause}">Ⅱ</button></header><div class="progress" role="progressbar" aria-label="${U.progress}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="progress-fill"></div></div><section class="stage"><div class="stage-shade"></div><div class="opponent-label"><small id="role"></small><h2 id="character-name"></h2></div><div class="round-label"><span id="phrase-title"></span><small><span id="frozen-count">0</span> ${U.people}${U.count}</small></div><div class="fighter" id="fighter"><div class="sprite" id="fighter-sprite"></div><span id="freeze-seal">${U.freeze}</span></div><canvas id="effects" aria-hidden="true"></canvas><div class="stage-caption" id="stage-caption"></div><div class="combo-box"><strong id="combo">0</strong><span>${U.combo}</span></div><div class="judgment" id="judgment" aria-live="off"></div></section><section class="playfield" aria-label="${U.judgment}"><canvas id="notes" aria-hidden="true"></canvas><div class="track-grid">${C.lanes.map((_,i)=>`<div class="lane-glow" data-glow="${i}"></div>`).join('')}</div><div class="judgment-line"></div><div class="key-row">${C.lanes.map((l,i)=>`<button class="lane-key" data-lane="${i}" style="--lane-color:${l.color}" aria-label="${l.label} ${l.key}"><span class="key-ring"></span><span class="key-label">${l.label}</span><kbd>${l.key}</kbd></button>`).join('')}</div></section><div class="game-bottom"><span id="elapsed">0:00</span><span>${draftMode?C.studio.previewHint:practice?(activePracticeRange.title?U.versePracticeHint:(activePracticeRange===C.rapPracticeRange?U.rapPracticeHint:U.practiceHint)):U.accessibility}</span><span>${format(limit-(practice?activePracticeRange.start:0))}</span></div><div class="countdown-overlay" id="countdown"><small>${U.ready}</small><strong id="countdown-number">3</strong></div><div class="pause-overlay" id="pause-panel" hidden><div class="pause-card"><span class="small-seal">${C.restSeal}</span><h2>${U.paused}</h2><p>${U.pauseHint}</p><button class="primary" id="resume">${U.resume}</button><button class="secondary" id="pause-settings">${U.settings}</button><div class="secondary-row"><button class="text-button" id="restart">${U.restart}</button><button class="text-button" id="home">${U.home}</button></div></div></div></main>`;
$('#pause').onclick=pause;$('#resume').onclick=resume;$('#restart').onclick=()=>{cleanup();begin(practice,activePracticeRange);};$('#home').onclick=showHome;$('#pause-settings').onclick=showSettings;
document.querySelectorAll('[data-lane]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(mode!=='playing')return;b.setPointerCapture(e.pointerId);press(Number(b.dataset.lane),'p'+e.pointerId,e.timeStamp);};b.onpointermove=e=>{const r=b.getBoundingClientRect();if(e.clientX<r.left-22||e.clientX>r.right+22||e.clientY<r.top-22||e.clientY>r.bottom+22)release('p'+e.pointerId,e.timeStamp);};b.onpointerup=e=>release('p'+e.pointerId,e.timeStamp);b.onpointercancel=e=>release('p'+e.pointerId,e.timeStamp);b.onlostpointercapture=e=>release('p'+e.pointerId,e.timeStamp);b.oncontextmenu=e=>e.preventDefault();});
setCharacter(0);}
function press(lane,id,at=performance.now()){if(mode!=='playing'||held.has(id)||[...held.values()].includes(lane))return;held.set(id,lane);const n=engine.hit(lane,songTime(at)-settings.offset/1000);if(!n&&settings.sfx)tone(180,.025,.012);updatePressed();processEvents();}
function release(id,at=performance.now()){if(!held.has(id))return;const lane=held.get(id);held.delete(id);if(mode==='playing')engine.release(lane,songTime(at)-settings.offset/1000);updatePressed();processEvents();}
function updatePressed(){document.querySelectorAll('[data-lane]').forEach(b=>b.classList.toggle('pressed',[...held.values()].includes(Number(b.dataset.lane))));document.querySelectorAll('[data-glow]').forEach(b=>b.classList.toggle('active',[...held.values()].includes(Number(b.dataset.glow))));}
function pause(){if(!['playing','countdown'].includes(mode))return;position=songTime();stopSource();mode='paused';held.clear();engine.suspend(position-settings.offset/1000);processEvents();updatePressed();$('#pause-panel').hidden=false;$('#countdown').hidden=true;}
async function resume(){await initAudio();$('#pause-panel').hidden=true;for(const n of engine.notes)if(n.status==='suspended')n.resumeDeadline=position-settings.offset/1000+.35;playFrom(position,3);}
function setCharacter(i){const phrase=C.phrases[i],p=C.cast[phrase.cast];$('#fighter-sprite').style.cssText=artStyle(p.pos);$('#fighter').className='fighter entering';$('#character-name').textContent=p.name;$('#role').textContent=p.role;$('#phrase-title').textContent=phrase.title;$('#stage-caption').textContent=p.line;$('#freeze-seal').textContent=U.freeze;}
function animateHit(el,strong=false){if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches)return;el.getAnimations().forEach(a=>a.cancel());el.animate([{filter:'brightness(1.65)',translate:'0 0'},{filter:'brightness(1.15)',translate:strong?'0 3px':'0 1px'},{filter:'brightness(1)',translate:'0 0'}],{duration:strong?210:110,easing:'ease-out'});}
function processEvents(){
 if(!engine)return;const events=engine.drain();if(!events.length)return;
 const priority={miss:1,break:2,resume:3,good:4,perfect:5,complete:6,double:7};
 const winner=events.reduce((a,b)=>priority[b.type]>priority[a.type]?b:a);
 const labels={break:U.breakHold,resume:U.resumeHold,double:U.double};
 lastFeedback=winner.type==='double'&&winner.tap?U.doubleTap:(labels[winner.type]||U[winner.type]);feedbackUntil=performance.now()+(winner.type==='double'?600:winner.type==='complete'?420:240);
 const judgment=$('#judgment');if(judgment){judgment.classList.toggle('miss',['miss','break'].includes(winner.type));judgment.dataset.kind=winner.type;animateHit(judgment,['complete','double'].includes(winner.type));}
 const hasDouble=events.some(e=>e.type==='double');
 for(const event of events){
  if(['miss','break','resume'].includes(event.type))continue;
  if(hasDouble&&event.type==='complete')continue;
  const strong=['double','complete'].includes(event.type),[x,y]=C.lanes[event.lane].target;
  effects.push({start:performance.now(),x,y,lane:event.lane,strong,kind:event.type});
  animateHit($(`[data-lane="${event.lane}"]`),strong);
  if(event.type==='double')for(const n of engine.notes.filter(n=>n.duration&&n.status==='done'&&Math.abs(n.time-engine.notes.find(n=>n.id===event.id).time)<.001))animateHit($(`[data-lane="${n.lane}"]`),true);
 }
 if(!['miss','break','resume'].includes(winner.type)){
  const fighter=$('#fighter');if(fighter&&!fighter.classList.contains('frozen'))animateHit($('#fighter-sprite'),['complete','double'].includes(winner.type));
  if(settings.sfx&&!settings.guide){const type=winner.type;tone(type==='double'?1100:type==='complete'?820:type==='perfect'?1300:760,type==='double'?.09:.035,type==='double'?.045:.026);if(type==='double')tone(550,.085,.025);}
 }
}
function canvasContext(id){const canvas=$(id),r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}const g=canvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,r.width,r.height);return {g,w:r.width,h:r.height};}
function roundRect(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,Math.max(1,h),r);}
function drawNotes(t){const {g,w,h}=canvasContext('#notes');const bottom=74,line=h-bottom,travel=[2.2,1.75,1.35][settings.speed],px=line/travel,laneW=w/4;
for(let i=0;i<4;i++){const x=laneW*(i+.5);g.strokeStyle='rgba(232,198,139,.12)';g.lineWidth=1;g.beginPath();g.moveTo(i*laneW,0);g.lineTo(i*laneW,h);g.stroke();g.fillStyle='rgba(243,199,129,.07)';g.beginPath();g.arc(x,line,19,0,Math.PI*2);g.fill();}
for(const e of effects){const age=(performance.now()-e.start)/(e.strong?300:170);if(age<0||age>1)continue;g.save();g.globalAlpha=(1-age)*.85;g.fillStyle=C.lanes[e.lane].color;roundRect(g,laneW*e.lane+8,line-5,laneW-16,10,5);g.fill();g.strokeStyle='#fff1c9';g.lineWidth=2;g.beginPath();g.arc(laneW*(e.lane+.5),line,16+age*(e.strong?24:12),0,Math.PI*2);g.stroke();g.restore();}
for(const n of engine.notes.filter(n=>n.status==='holding')){const progress=Math.max(0,Math.min(1,(songTime()-settings.offset/1000-n.time)/n.duration));g.strokeStyle=C.lanes[n.lane].color;g.lineWidth=4;g.beginPath();g.arc(laneW*(n.lane+.5),line,24,-Math.PI/2,-Math.PI/2+progress*Math.PI*2);g.stroke();}
for(const n of engine.notes){if(['done','miss','broken'].includes(n.status))continue;const y=line-(n.time-t)*px;if(y< -n.duration*px-30||y>h+n.duration*px)continue;const x=laneW*(n.lane+.5),color=C.lanes[n.lane].color;g.save();g.shadowColor=color;g.shadowBlur=n.status==='holding'?17:8;
if(n.duration){const tail=line-(n.time+n.duration-t)*px,head=['holding','suspended'].includes(n.status)?line:y;const top=Math.max(-10,tail);g.fillStyle=color+'55';roundRect(g,x-13,top,26,Math.max(1,head-top),7);g.fill();g.strokeStyle=color;g.lineWidth=2;g.beginPath();g.moveTo(x-13,top);g.lineTo(x-13,head);g.moveTo(x+13,top);g.lineTo(x+13,head);g.stroke();for(let tick=n.time;tick<=n.time+n.duration;tick+=.5){const ty=line-(tick-t)*px;if(ty>=top&&ty<=head){g.fillStyle=color;g.fillRect(x-9,ty,18,2);}}g.fillStyle=color;roundRect(g,x-20,tail-3,40,6,3);g.fill();}
const hy=['holding','suspended'].includes(n.status)?line:y;g.fillStyle=color;roundRect(g,x-29,hy-7,58,14,5);g.fill();g.fillStyle='#fff4d9';roundRect(g,x-20,hy-4,40,3,2);g.fill();if(n.duration){g.fillStyle='#15202a';g.beginPath();g.arc(x,hy,3,0,Math.PI*2);g.fill();}g.restore();}
}
// Vector hand anchored at the fingertips. No particle fog or generated bitmap.
function drawPointingHand(g,x,y,side,scale,alpha){
 g.save();g.translate(x,y);g.scale(side*scale,scale);g.globalAlpha=alpha;
 g.lineJoin='round';g.lineCap='round';g.lineWidth=1.7;g.strokeStyle='#35271f';
 // Cuff and forearm remain outside the body; index and middle fingers touch it.
 g.fillStyle='#394e66';g.beginPath();g.moveTo(-91,12);g.lineTo(-61,8);g.lineTo(-56,31);g.lineTo(-88,39);g.closePath();g.fill();g.stroke();
 g.fillStyle='#eed7ac';g.beginPath();g.moveTo(-64,9);g.lineTo(-57,8);g.lineTo(-51,30);g.lineTo(-58,33);g.closePath();g.fill();g.stroke();
 g.fillStyle='#edb98d';g.beginPath();g.moveTo(-57,11);g.quadraticCurveTo(-49,3,-35,1);g.lineTo(-6,-4);g.quadraticCurveTo(1,-5,1,0);g.quadraticCurveTo(1,3,-5,4);g.lineTo(-29,8);g.lineTo(-4,5);g.quadraticCurveTo(3,5,2,10);g.quadraticCurveTo(2,13,-4,13);g.lineTo(-28,15);g.quadraticCurveTo(-23,18,-28,24);g.quadraticCurveTo(-32,33,-44,32);g.lineTo(-53,28);g.closePath();g.fill();g.stroke();
 g.strokeStyle='#a26a4c';g.lineWidth=1.1;g.beginPath();g.moveTo(-42,12);g.quadraticCurveTo(-26,12,-31,22);g.moveTo(-39,23);g.lineTo(-31,25);g.moveTo(-12,0);g.lineTo(-7,-1);g.moveTo(-11,9);g.lineTo(-5,9);g.stroke();g.restore();
}
function drawEffects(now){
 const {g,w,h}=canvasContext('#effects'),canvas=$('#effects').getBoundingClientRect(),body=$('#fighter').getBoundingClientRect();
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 effects=effects.filter(e=>now-e.start<260);
 const active=engine.notes.filter(n=>n.status==='holding');
 for(let lane=0;lane<4;lane++){
  const target=C.pointing.targets[lane],x=body.left-canvas.left+body.width*target[0],y=body.top-canvas.top+body.height*target[1],color=C.lanes[lane].color;
  const hit=effects.filter(e=>e.lane===lane).slice(-1)[0],holding=active.find(n=>n.lane===lane),age=hit?now-hit.start:999;
  const lit=Boolean(holding)||age<210,side=lane<2?1:-1;
  // Small persistent body markers connect the four keys to their targets.
  g.save();g.globalAlpha=lit?1:.58;g.fillStyle=lit?'#fff3ce':'#18212a';g.strokeStyle=color;g.lineWidth=lit?2:1;
  g.beginPath();g.arc(x,y,lit?5:3.5,0,Math.PI*2);g.fill();g.stroke();
  if(lit){
   const progress=holding?Math.max(0,Math.min(1,(songTime()-settings.offset/1000-holding.time)/holding.duration)):1;
   g.lineWidth=2;g.beginPath();g.arc(x,y,10,-Math.PI/2,-Math.PI/2+Math.PI*2*progress);g.stroke();
   if(age<100&&!reduced){for(let k=0;k<4;k++){const angle=k*Math.PI/2+Math.PI/4;g.beginPath();g.moveTo(x+Math.cos(angle)*13,y+Math.sin(angle)*13);g.lineTo(x+Math.cos(angle)*18,y+Math.sin(angle)*18);g.stroke();}}
  }
  g.restore();
  if(holding||age<260){
   // Contact starts on the judged frame; only withdrawal is delayed visually.
   const retreat=holding||reduced?0:Math.max(0,(age-85)/175),alpha=holding?1:1-retreat;
   drawPointingHand(g,x-side*retreat*28,y+retreat*9,side,Math.max(.62,Math.min(.9,h/230)),alpha);
  }
 }
}
function frame(now){if(!['playing','countdown','paused'].includes(mode))return;const gap=now-lastFrame;lastFrame=now;if(mode==='playing'&&gap>900)pause();if(mode==='countdown'&&outputTime(ctx)>=countdownUntil){mode='playing';$('#countdown').hidden=true;}
if(mode==='countdown'){$('#countdown').hidden=false;$('#countdown-number').textContent=Math.max(1,Math.ceil(countdownUntil-outputTime(ctx)));}
const t=songTime(),judge=t-settings.offset/1000;if(mode==='playing'){engine.update(judge);processEvents();if(t>=limit){finish();return;}}
const stage=stageTimeline.update(engine,t,judge,mode==='playing');if(stage.entered!==null){currentPhrase=stage.entered;setCharacter(currentPhrase);}for(const result of stage.results){if(!result.visible)continue;const phrase=C.phrases[result.index];$('#fighter').classList.add(result.success?'frozen':'evaded');if(result.success)$('#fighter-sprite').style.cssText=artStyle(C.cast[phrase.cast].pos,true);$('#freeze-seal').textContent=result.success?U.freeze:U.evade;}frozen=stageTimeline.frozen;
const section=C.chartPlan.sections.find(s=>s.start<=t&&s.end>t);if(section)$('#phrase-title').textContent=section.label;
$('#score').textContent=String(Math.floor(engine.score)).padStart(6,'0');$('#combo').textContent=engine.combo;$('#frozen-count').textContent=frozen;$('#elapsed').textContent=format(t-(practice?activePracticeRange.start:0));$('#progress-fill').style.width=`${Math.min(100,Math.max(0,(t-(practice?activePracticeRange.start:0))/(limit-(practice?activePracticeRange.start:0))*100))}%`;$('.progress').setAttribute('aria-valuenow',String(Math.round(Math.max(0,(t-(practice?activePracticeRange.start:0))/(limit-(practice?activePracticeRange.start:0))*100))));if(now>=feedbackUntil){$('#judgment').classList.remove('miss');$('#judgment').dataset.kind='sustain';}$('#judgment').textContent=now<feedbackUntil?lastFeedback:engine.notes.filter(n=>n.status==='holding').length>=2?U.doubleHold:engine.notes.some(n=>n.status==='holding')?U.hold:'';
drawNotes(t-settings.visualOffset/1000);drawEffects(now);raf=requestAnimationFrame(frame);}
function finish(){engine.update(limit+C.rules.good+.01);processEvents();for(let i=0;i<C.phrases.length;i++){const p=C.phrases[i];if(p.start>=limit)continue;if(!settled.has(i)&&engine.phraseSuccess(p.start,Math.min(p.end,limit)))frozen++;}cleanup();mode='result';if(!practice&&!draftMode){best=Math.max(best,Math.floor(engine.score));save();}const grade=engine.accuracy>=95?3:engine.accuracy>=80?2:engine.accuracy>=55?1:0;
app.innerHTML=`<main class="shell result"><header class="mast"><span class="brand"><span class="seal">${C.seal}</span>${C.brand}</span><span class="muted">${draftMode?C.studio.draftTag:practice?(activePracticeRange.title||(activePracticeRange===C.rapPracticeRange?U.rapPracticeTag:U.practiceTag)):C.track.title}</span></header><section class="result-content"><p class="eyebrow">${practice?U.practiceEnd:U.songEnd}</p><div class="result-seal">${C.resultSeals[grade]}</div><h1>${U.gradeNames[grade]}</h1><div class="result-score">${Math.floor(engine.score).toLocaleString()}<small>${U.score}</small></div><div class="result-stats"><div><strong>${engine.accuracy.toFixed(1)}<small>%</small></strong><span>${U.accuracy}</span></div><div><strong>${engine.maxCombo}</strong><span>${U.maxCombo}</span></div><div><strong>${frozen}</strong><span>${U.frozenCount}</span></div></div><div class="judgment-summary"><span>${U.perfect}<b>${engine.counts.perfect}</b></span><span>${U.good}<b>${engine.counts.good}</b></span><span>${U.miss}<b>${engine.counts.miss}</b></span></div><div class="result-roster">${C.cast.map((p,i)=>`<div class="sprite" style="${artStyle(i)}"></div>`).join('')}</div><button class="primary" id="again">${practice?U.verseRepeat:U.again} →</button><button class="text-button" id="back">${U.home}</button><p class="muted">${practice?(activePracticeRange.title?U.versePracticeHint:(activePracticeRange===C.rapPracticeRange?U.rapPracticeHint:U.practiceHint)):`${U.best} · ${best.toLocaleString()}`}</p></section><footer>${U.footer}</footer></main>`;$('#again').onclick=()=>begin(practice,activePracticeRange);$('#back').onclick=showHome;}
document.addEventListener('keydown',e=>{if($('dialog')||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Space'&&['playing','paused','countdown'].includes(mode)){e.preventDefault();if(!e.repeat)(mode==='paused'?resume():pause());return;}const lane=C.lanes.findIndex(l=>'Key'+l.key===e.code);if(lane>=0&&mode==='playing'){e.preventDefault();if(!e.repeat)press(lane,'k'+e.code,e.timeStamp);}});
document.addEventListener('keyup',e=>release('k'+e.code,e.timeStamp));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>pause());window.addEventListener('pagehide',()=>{pause();save();});
if(new URLSearchParams(location.search).has('studio')){const {mountStudio}=await import('./studio.mjs');mountStudio(app,C);}else showHome();
