(function(){
'use strict';
var C=window.VERSE_LAB,$=function(id){return document.getElementById(id);},ctx,buffer,source,tones=[],playing=false,busy=false,epoch=0,origin=0,raf=0,cycle=0,notes=[],selected=1;
['title','intro','play','stop','hint','footer'].forEach(function(id){$(id).textContent=C[id];});
$('guide-label').textContent=C.guide;$('loop-label').textContent=C.loop;document.title=C.title;
C.versions.forEach(function(v,i){var o=document.createElement('option');o.value=i;o.textContent=v.label;$('version').appendChild(o);});$('version').value=selected;
C.keys.forEach(function(k,i){var b=document.createElement('button');b.textContent=k;b.setAttribute('data-lane',i);b.addEventListener('pointerdown',function(e){e.preventDefault();hit(i,e.timeStamp);});$('keys').appendChild(b);});
function state(s){$('status').textContent=C[s];$('status').dataset.state=s;}
function clock(at){return ctx?outputTime(ctx,at===undefined?performance.now():at)-origin:0;}
function stop(){epoch++;playing=false;cancelAnimationFrame(raf);if(source){source.onended=null;try{source.stop();}catch(e){}source.disconnect();source=null;}tones.forEach(function(o){try{o.stop();}catch(e){}o.disconnect();});tones=[];state('paused');}
function clickSound(t){var o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=1100;g.gain.setValueAtTime(.09,t);g.gain.exponentialRampToValueAtTime(.001,t+.035);o.connect(g).connect(ctx.destination);o.onended=function(){o.disconnect();g.disconnect();};o.start(t);o.stop(t+.04);tones.push(o);}
function schedule(){cycle++;notes=C.versions[selected].notes.map(function(n){return {time:n.time,lane:n.lane,label:n.label||'',done:false,miss:false};});origin=ctx.currentTime+.7;source=ctx.createBufferSource();source.buffer=buffer;source.connect(ctx.destination);source.start(origin);if($('guide').checked)notes.forEach(function(n){clickSound(origin+n.time);});playing=true;$('feedback').textContent='';state('playing');draw();}
async function start(){if(busy)return;stop();var token=epoch;busy=true;$('play').disabled=true;try{if(!ctx){var AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('AudioContext');ctx=new AC({latencyHint:'interactive'});ctx.addEventListener('statechange',function(){if(ctx.state!=='running'&&playing)stop();});}var resumed=ctx.resume();if(!buffer){var raw=atob(window.VERSE_AUDIO),bytes=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);var decoded=new Promise(function(resolve,reject){ctx.decodeAudioData(bytes.buffer,resolve,reject);});var r=await Promise.all([resumed,decoded]);buffer=r[1];window.VERSE_AUDIO=null;}else await resumed;if(token!==epoch||document.hidden)return;schedule();}catch(e){state('error');}finally{busy=false;$('play').disabled=false;}}
function draw(){if(!playing)return;var t=clock(),canvas=$('chart'),g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,y=h-38;g.clearRect(0,0,w,h);g.strokeStyle='#53616e';for(var i=1;i<4;i++){g.beginPath();g.moveTo(i*w/4,0);g.lineTo(i*w/4,h);g.stroke();}g.strokeStyle='#e9c489';g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke();notes.forEach(function(n){if(!n.done&&t>n.time+.155)n.miss=true;var dy=y-(n.time-t)/1.6*(h-60);if(dy<0||dy>h)return;g.fillStyle=n.done?'#7cdec3':n.miss?'#6d7580':'#e9c489';g.beginPath();g.arc((n.lane+.5)*w/4,dy,12,0,Math.PI*2);g.fill();if(n.label){g.fillStyle='#101925';g.font='bold 13px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(n.label,(n.lane+.5)*w/4,dy);}});$('position').textContent=Math.max(0,Math.min(C.duration,t)).toFixed(2)+' / '+C.duration.toFixed(2)+' s';$('position').dataset.cycle=cycle;if(t>=buffer.duration+.2){stop();if($('loop').checked){schedule();return;}state('ended');return;}raf=requestAnimationFrame(draw);}
function hit(lane,at){if(!playing)return;var t=clock(at),best=null;notes.forEach(function(n){if(n.lane===lane&&!n.done&&!n.miss&&Math.abs(n.time-t)<=.155&&(!best||Math.abs(n.time-t)<Math.abs(best.time-t)))best=n;});if(!best){$('feedback').textContent=C.empty;return;}best.done=true;var ms=Math.round((t-best.time)*1000);$('feedback').textContent=(Math.abs(ms)<=85?C.perfect:C.good)+' '+(ms>0?'+':'')+ms+' ms';}
$('play').addEventListener('click',start);$('stop').addEventListener('click',stop);
$('version').addEventListener('change',function(){selected=Number(this.value);if(playing)start();});$('guide').addEventListener('change',function(){if(playing)start();});
document.addEventListener('keydown',function(e){if(e.repeat||/INPUT|SELECT|BUTTON/.test(e.target.tagName))return;var i=C.keys.indexOf(e.key.toUpperCase());if(i>=0){e.preventDefault();hit(i,e.timeStamp);}});
document.addEventListener('visibilitychange',function(){if(document.hidden)stop();});window.addEventListener('pagehide',stop);state('ready');
}());
