import {createMoldEditor} from './mold-editor.js';
import {toppingFits,interiorSpot} from './contour.js';
import {createAtelier} from './scene.js';
import {cleanRecipeCollection,pourAmount,clamp} from './engine.js';
const content=await fetch(new URL('./content/content.json',import.meta.url)).then(r=>{if(!r.ok)throw Error('Content failed');return r.json()});
const {brand,ui,flavors,molds,toppings,workshop:w,craft}=content;
const $=s=>document.querySelector(s);
const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.4">${{arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',shelf:'<path d="M4 20V6h16v14M3 12h18M8 3v3m8-3v3M7 9h3m4 0h3M7 16h3m4 0h3"/>',sound:'<path d="M10 5 5 9H2v6h3l5 4V5Z"/><path d="M14 8q6 4 0 8m3-11q10 7 0 14"/>',mute:'<path d="M10 5 5 9H2v6h3l5 4V5Z"/><path d="m15 9 6 6m0-6-6 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',poke:'<path d="M8 12V5a2 2 0 0 1 4 0v7m0-3 5 1q3 0 3 4v3q0 4-4 4h-4q-2 0-3-2l-4-5q-2-3 1-3l2 1Z"/>'}[name]}</svg>`;
document.querySelector('#app').innerHTML=`<main class="atelier"><div class="stage" aria-label="${ui.sceneLabel}"></div><div class="scene-caption" aria-hidden="true">Jelly.</div><header class="topbar"><div class="brand"><img class="brand-mark" src="./src/assets/logo.png" alt=""><div><div class="brand-name">${brand.name}</div><div class="brand-sub">${brand.sub}</div></div></div><span class="top-note">${brand.edition}</span><div class="top-actions"><button class="round" id="sound" aria-label="${ui.soundOff}">${icon('mute')}</button><button class="shelf-button" id="shelf" aria-label="${ui.shelf}">${icon('shelf')}<span class="shelf-label">${ui.shelf}</span><span class="shelf-count">00</span></button></div></header><section class="hero-copy"><ol class="steps">${w.steps.map((s,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${s}</li>`).join('')}</ol><h1 id="step-title"></h1><p class="intro" id="step-description" aria-live="polite"></p><div class="flavor-note"><i class="note-dot"></i><span id="flavor-note"></span></div><button id="start-over" class="text-button">${w.startOver}</button></section><div class="vertical-note">${ui.materialLabel}</div><div class="scene-hint">${icon('poke')}<span id="hint"></span></div><section class="control-deck"><div class="choice-panel"><p class="flavor-label" id="choice-label"></p><div id="choices"></div><div id="detail"></div></div><div class="action-panel"><div class="main-actions" id="actions"></div><p class="key-hint" id="key-hint"></p></div></section><footer class="bottomline"><span>${brand.craft}</span><span>${brand.footer}</span><span>${ui.sample}</span></footer><div class="loading"><div class="loader-mark">Jelly.</div><p>${ui.loading}</p><small>${ui.loadingSub}</small></div></main><div class="toast" role="status" aria-live="polite"></div><dialog id="collection" aria-labelledby="collection-title"><div class="shelf-head"><h2 id="collection-title">${ui.shelf}<small>${ui.collectionLabel}</small></h2><button class="round" id="close-shelf" aria-label="${ui.close}">${icon('close')}</button></div><div class="shelf-grid"></div><p class="shelf-foot">${ui.shelfDetail}</p></dialog>`;
const fresh=()=>({mold:molds[0].id,first:flavors[0].id,second:flavors[1].id,split:.5,toppings:[]});
let recipe=fresh(),stage='mold',amount=0,selectedTopping=toppings[0].id,holding=false,atelier=null,savedId=null,collection=[],soundEnabled=false,audio=null,toastTimer;
try{const raw=localStorage.getItem('jelly-atelier-v2')??localStorage.getItem('jelly-atelier-v1')??'[]';collection=cleanRecipeCollection(JSON.parse(raw),content)}catch{collection=[]}
const flavor=id=>flavors.find(f=>f.id===id);
const moldInfo=id=>id==='custom'?content.draw:molds.find(m=>m.id===id);
const editor=createMoldEditor(content,outline=>{recipe.mold='custom';recipe.outline=outline;recipe.toppings=[];syncScene();render()});
const isPour=()=>stage==='pour1'||stage==='pour2';
function toast(message){clearTimeout(toastTimer);$('.toast').textContent=message;$('.toast').classList.add('visible');toastTimer=setTimeout(()=>$('.toast').classList.remove('visible'),2600)}
function updateSound(){$('#sound').innerHTML=icon(soundEnabled?'sound':'mute');$('#sound').setAttribute('aria-label',soundEnabled?ui.soundOn:ui.soundOff);$('#sound').setAttribute('aria-pressed',String(soundEnabled))}
function playSound(kind){if(!soundEnabled)return;try{audio??=new AudioContext();if(audio.state==='suspended')void audio.resume();const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(kind==='land'?170:420,now);osc.frequency.exponentialRampToValueAtTime(kind==='land'?56:110,now+.25);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.13,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.4);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+.42)}catch{soundEnabled=false;updateSound()}}
function persist(){try{localStorage.setItem('jelly-atelier-v2',JSON.stringify(collection));return true}catch{toast(ui.storageError);return false}}
function updateCount(){$('.shelf-count').textContent=String(collection.length).padStart(2,'0')}
function syncScene(){atelier?.setRecipe(recipe,stage,amount)}
function recipeText(r=recipe){return `${moldInfo(r.mold).name} · ${flavor(r.first).name} ${Math.round(r.split*100)}% + ${flavor(r.second).name} ${100-Math.round(r.split*100)}%`}
function button(id,text,primary=false){return `<button id="${id}" class="${primary?'primary':'soft-button'}">${primary?`<span>${text}</span>${icon('arrow')}`:text}</button>`}
function setStage(next){stopPour();stage=next;render();syncScene()}
function updateProgress(){const percent=Math.round(amount*100);if($('#fill-meter')){$('#fill-meter').value=amount;$('#fill-number').textContent=`${percent}%`;$('#fill-meter').setAttribute('aria-valuetext',`${percent}%`)}if($('#next-layer'))$('#next-layer').disabled=amount+1e-6<craft.minFirst;if($('#primary')&&isPour()){$('#primary span').textContent=holding?w.holding:w.hold;$('#primary').classList.toggle('pouring',holding);$('#primary').disabled=stage==='pour1'&&amount>=craft.maxFirst}}
function stopPour(){holding=false;atelier?.setPouring(false);updateProgress()}
function addLiquid(seconds){if(!isPour())return;const layer=stage==='pour1'?1:2;amount=pourAmount(amount,seconds,layer,craft);atelier?.setFill(amount,layer===1?amount:recipe.split);updateProgress();if(layer===1&&amount>=craft.maxFirst){stopPour();toast(w.firstLimit)}if(layer===2&&amount>=1){amount=1;setStage('decorate');toast(w.filled)}}
function startPour(){if(!isPour()||holding||stage==='pour1'&&amount>=craft.maxFirst)return;holding=true;atelier?.setPouring(true);updateProgress()}
function beginAgain(){stopPour();recipe=fresh();amount=0;savedId=null;atelier?.reset();setStage('mold')}
function place(point){if(stage!=='decorate')return;if(recipe.toppings.length>=craft.maxToppings){toast(w.toppingLimit);return}if(point.top===false||!toppingFits(recipe,point,content)){toast(w.placeHint);return}recipe.toppings.push({kind:selectedTopping,x:point.x,z:point.z});syncScene();render();playSound('poke')}
function autoPlace(){if(recipe.mold==='custom'){const point=interiorSpot(recipe.outline,recipe.toppings.length);if(point)place(point);else toast(content.draw.noSpace);return}const i=recipe.toppings.length;const a=i*2.399963,r=i?Math.min(.33,Math.sqrt(i)*.14):0;place({x:Math.cos(a)*r,z:Math.sin(a)*r})}
function render(){
  const focused=document.activeElement;const focusSelector=focused?.dataset.choice?'[data-choice="'+focused.dataset.choice+'"]':focused?.dataset.flavor?'[data-flavor="'+focused.dataset.flavor+'"]':focused?.id?'#'+focused.id:null;
  $('.atelier').dataset.state=stage;
  const titles={mold:w.moldTitle,pour1:w.pour1Title,pour2:w.pour2Title,decorate:w.decorateTitle,unmolding:w.unmoldTitle,ready:w.readyTitle};
  const hints={mold:w.moldHint,pour1:w.pour1Hint,pour2:w.pour2Hint,decorate:w.decorateHint,unmolding:w.unmoldHint,ready:w.readyHint};
  const stepIndex={mold:0,pour1:1,pour2:1,decorate:2,unmolding:3,ready:3}[stage];
  document.querySelectorAll('.steps li').forEach((li,i)=>{li.classList.toggle('active',i===stepIndex);li.classList.toggle('done',i<stepIndex);if(i===stepIndex)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current')});
  $('#step-title').textContent=titles[stage];$('#step-description').textContent=hints[stage];$('#hint').textContent=stage==='decorate'?w.placeHint:stage==='ready'?ui.instructions:stage==='mold'?ui.startHint:flavor(stage==='pour2'?recipe.second:recipe.first).note;
  $('#flavor-note').textContent=stage==='mold'?moldInfo(recipe.mold).note:recipeText();$('#start-over').hidden=stage==='mold'||stage==='unmolding';
  $('#choice-label').textContent=stage==='mold'?w.moldLabel:isPour()?w.colorLabel:stage==='decorate'?w.topLabel:w.finishLabel;
  $('#key-hint').textContent=isPour()?w.keyboardHint:'';
  if(stage==='mold'||stage==='decorate'){
    const items=stage==='mold'?molds:toppings,selected=stage==='mold'?recipe.mold:selectedTopping;
    $('#choices').innerHTML=`<div class="object-choices">${items.map(m=>`<button class="object-choice ${selected===m.id?'active':''}" data-choice="${m.id}" aria-pressed="${selected===m.id}"><span class="object-symbol" aria-hidden="true">${m.symbol}</span><span>${m.name}</span></button>`).join('')}</div>`;
    document.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{if(stage==='mold'){recipe.mold=b.dataset.choice;delete recipe.outline;}else selectedTopping=b.dataset.choice;syncScene();render()}));
    if(stage==='mold'){const drawButton=document.createElement('button');drawButton.id='custom-mold';drawButton.className='draw-entry';drawButton.textContent=recipe.mold==='custom'?content.draw.edit:content.draw.entry;drawButton.setAttribute('aria-pressed',String(recipe.mold==='custom'));drawButton.addEventListener('click',()=>editor.open(recipe.mold==='custom'?recipe.outline:null));$('#choices').append(drawButton);}
  }else if(isPour()){
    const selected=stage==='pour1'?recipe.first:recipe.second;
    $('#choices').innerHTML=`<div class="flavors">${flavors.map(f=>`<button class="flavor ${selected===f.id?'active':''}" data-flavor="${f.id}" aria-pressed="${selected===f.id}"><i class="flavor-disc" style="--swatch:${f.swatch}"></i><span class="flavor-text">${f.name}<small>${f.english}</small></span></button>`).join('')}</div>`;
    document.querySelectorAll('[data-flavor]').forEach(b=>b.addEventListener('click',()=>{stopPour();recipe[stage==='pour1'?'first':'second']=b.dataset.flavor;document.documentElement.style.setProperty('--accent',flavor(b.dataset.flavor).accent);syncScene();render()}));
  }else $('#choices').innerHTML=`<div class="recipe-strip"><i style="background:linear-gradient(to top,${flavor(recipe.first).swatch} ${recipe.split*100}%,${flavor(recipe.second).swatch} ${recipe.split*100}%)"></i><p>${recipeText()}<small>${recipe.toppings.length?`${recipe.toppings.length} ${w.toppingCount}`:w.noTopping}</small></p></div>`;
  $('#detail').innerHTML=isPour()?`<div class="fill-track"><span>${stage==='pour1'?w.first:w.second}</span><progress id="fill-meter" max="1" value="${amount}" aria-label="${w.progress}"></progress><output id="fill-number"></output></div>`:stage==='decorate'?`<div class="decoration-tools"><span>${recipe.toppings.length} / ${craft.maxToppings} ${w.toppingCount}</span>${button('auto-place',w.center)}${button('undo',w.undo)}</div>`:'';
  $('#actions').innerHTML=stage==='mold'?button('primary',w.moldAction,true):isPour()?`${button('dose',w.dose)}${stage==='pour1'?button('next-layer',w.nextLayer):''}${button('primary',w.hold,true)}`:stage==='decorate'?button('primary',ui.unmold,true):stage==='unmolding'?button('primary',ui.unmolding,true):`${button('replay',ui.replay)}${button('save',savedId?ui.saved:ui.save)}${button('primary',ui.ready,true)}`;
  $('#primary').disabled=stage==='unmolding'||!atelier;
  $('#primary').addEventListener('click',event=>{if(isPour()){if(event.detail===0)addLiquid(craft.keyboardDose/craft.pourRate);return}if(stage==='mold'){setStage('pour1');return}if(stage==='decorate'){setStage('unmolding');atelier.unmold(()=>setStage('ready'));return}if(stage==='ready')atelier.poke()});
  if(isPour()){
    const holdButton=$('#primary');holdButton.addEventListener('pointerdown',event=>{if(event.button!==0)return;event.preventDefault();holdButton.focus();holdButton.setPointerCapture(event.pointerId);startPour()});
    holdButton.addEventListener('lostpointercapture',stopPour);
    holdButton.addEventListener('keydown',event=>{if(event.code==='Space'||event.code==='Enter'){event.preventDefault();if(!event.repeat)startPour()}});
    holdButton.addEventListener('keyup',event=>{if(event.code==='Space'||event.code==='Enter'){event.preventDefault();stopPour()}});
    holdButton.addEventListener('blur',stopPour);
    $('#dose').addEventListener('click',()=>addLiquid(craft.keyboardDose/craft.pourRate));
    $('#next-layer')?.addEventListener('click',()=>{if(amount+1e-6<craft.minFirst){toast(w.minimum);return}recipe.split=clamp(amount,craft.minFirst,craft.maxFirst);setStage('pour2')});updateProgress();
  }
  $('#auto-place')?.addEventListener('click',autoPlace);$('#undo')?.addEventListener('click',()=>{recipe.toppings.pop();syncScene();render()});if($('#undo'))$('#undo').disabled=!recipe.toppings.length;
  $('#replay')?.addEventListener('click',beginAgain);$('#save')?.addEventListener('click',save);if($('#save'))$('#save').disabled=Boolean(savedId);
  if(focusSelector){const target=$(focusSelector);if(target&&!target.disabled&&!target.hidden)target.focus({preventScroll:true});}
}
function save(){if(stage!=='ready'||savedId)return;const id=`${Date.now()}-${Math.random().toString(36).slice(2,9)}`;const previous=collection;collection=cleanRecipeCollection([{id,flavor:recipe.first,createdAt:Date.now(),recipe},...collection],content);if(persist()){savedId=id;toast(ui.saved)}else collection=previous;updateCount();render()}
function renderShelf(){const grid=$('.shelf-grid');grid.replaceChildren();if(!collection.length){const p=document.createElement('p');p.className='shelf-empty';p.textContent=ui.shelfEmpty;grid.append(p);return}for(const item of collection){const card=document.createElement('div');card.className='shelf-item';const picture=document.createElement('div');picture.className=`mini-jelly mini-${item.recipe.mold}`;picture.style.background=`linear-gradient(to top,${flavor(item.recipe.first).swatch} ${item.recipe.split*100}%,${flavor(item.recipe.second).swatch} ${item.recipe.split*100}%)`;if(item.recipe.outline)picture.style.clipPath='polygon('+item.recipe.outline.map(p=>`${(p.x+1)*50}% ${(p.z+1)*50}%`).join(',')+')';picture.setAttribute('aria-hidden','true');const name=document.createElement('b');name.textContent=recipeText(item.recipe);const date=document.createElement('time');date.dateTime=new Date(item.createdAt).toISOString();date.textContent=new Date(item.createdAt).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'});const open=document.createElement('button');open.textContent=w.open;open.className='shelf-open';open.addEventListener('click',()=>{stopPour();atelier.reset();recipe=structuredClone(item.recipe);amount=1;savedId=item.id;$('#collection').close();setStage('ready')});const remove=document.createElement('button');remove.textContent=ui.remove;remove.addEventListener('click',()=>{const before=collection;collection=collection.filter(x=>x.id!==item.id);if(!persist())collection=before;else if(savedId===item.id){savedId=null;render()}updateCount();renderShelf()});card.append(picture,name,date,open,remove);grid.append(card)}}
$('#shelf').addEventListener('click',()=>{stopPour();renderShelf();$('#collection').showModal()});$('#close-shelf').addEventListener('click',()=>$('#collection').close());
$('#sound').addEventListener('click',()=>{soundEnabled=!soundEnabled;updateSound();if(soundEnabled)playSound('poke')});
$('#start-over').addEventListener('click',beginAgain);
window.addEventListener('pointerup',stopPour);window.addEventListener('pointercancel',stopPour);window.addEventListener('blur',stopPour);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopPour()});
function sceneError(message){stopPour();$('.loading').classList.remove('hidden');$('.loading').removeAttribute('aria-hidden');$('.loading p').textContent=message;$('.loading small').textContent='';if(!$('.loading button')){const retry=document.createElement('button');retry.textContent=ui.retry;retry.addEventListener('click',()=>location.reload());$('.loading').append(retry)}}
try{atelier=createAtelier($('.stage'),content,{onPoke:()=>playSound('poke'),onLand:()=>playSound('land'),onContextLost:()=>sceneError(ui.contextLost),onPlace:place,onPourFrame:dt=>{if(holding)addLiquid(dt)}});syncScene();render();requestAnimationFrame(()=>requestAnimationFrame(()=>{$('.loading').classList.add('hidden');$('.loading').setAttribute('aria-hidden','true')}))}catch(error){console.error(error);sceneError(ui.webglError)}
updateCount();updateSound();
