import {prepareOutline} from './contour.js';
import {createAtelier} from './scene.js';
export function createMoldEditor(content,onUse){
  const d=content.draw,dialog=document.createElement('dialog');dialog.id='mold-editor';dialog.setAttribute('aria-labelledby','draw-title');
  dialog.innerHTML=`<div class="draw-head"><div><h2 id="draw-title">${d.title}</h2><p>${d.hint}</p></div><button class="round" id="draw-cancel" aria-label="${d.cancel}">×</button></div><div class="draw-modes"><button id="draw-free" aria-pressed="true">${d.free}</button><button id="draw-points" aria-pressed="false">${d.points}</button><button id="draw-undo">${d.undo}</button><button id="draw-clear">${d.clear}</button></div><div class="draw-workspace"><div class="drawing-paper"><canvas id="outline-canvas" tabindex="0" role="img" aria-label="${d.hint} ${d.keyboard}"></canvas><span class="draw-paper-label">${d.empty}</span></div><div class="draw-preview-wrap"><div id="mold-preview" aria-label="${d.preview}"></div><span>${d.preview}</span></div></div><p class="draw-status" role="status" aria-live="polite"></p><p class="draw-keyboard">${d.keyboard}</p><div class="draw-actions"><button class="soft-button" id="draw-close">${d.close}</button><button class="primary" id="draw-use" disabled><span>${d.use}</span></button></div>`;
  document.body.append(dialog);const $=s=>dialog.querySelector(s),canvas=$('#outline-canvas'),context=canvas.getContext('2d');
  let raw=[],result=null,mode='free',active=null,before=[],preview=null,cursor={x:0,z:0},keyboard=false;
  const point=event=>{const r=canvas.getBoundingClientRect(),side=Math.min(r.width,r.height);return{x:Math.max(-.95,Math.min(.95,(event.clientX-r.left-r.width/2)/side*2)),z:Math.max(-.95,Math.min(.95,(event.clientY-r.top-r.height/2)/side*2))}};
  function paint(){const r=canvas.getBoundingClientRect();if(!r.width)return;canvas.width=Math.round(r.width*devicePixelRatio);canvas.height=Math.round(r.height*devicePixelRatio);context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,canvas.width,canvas.height);const side=Math.min(canvas.width,canvas.height);context.setTransform(side/2,0,0,side/2,canvas.width/2,canvas.height/2);context.strokeStyle='#b59a922a';context.lineWidth=.008;context.beginPath();context.arc(0,0,.85,0,Math.PI*2);context.stroke();
    if(raw.length){context.strokeStyle=result?.error?'#bc515d':'#773049';context.lineWidth=.018;context.lineCap='round';context.lineJoin='round';context.beginPath();raw.forEach((p,i)=>i?context.lineTo(p.x,p.z):context.moveTo(p.x,p.z));if(result?.ok)context.closePath();context.stroke();if(result?.ok){context.fillStyle='#cd91b72b';context.fill()}for(const [i,p]of raw.entries()){if(mode==='points'||i===0||i===raw.length-1){context.beginPath();context.arc(p.x,p.z,i===0?.036:.016,0,Math.PI*2);context.fillStyle=i===0?'#b27aa7':'#773049';context.fill()}}if(result?.crossing)for(const i of result.crossing){const a=raw[i],b=raw[(i+1)%raw.length];if(a&&b){context.strokeStyle='#eb4343';context.lineWidth=.04;context.beginPath();context.moveTo(a.x,a.z);context.lineTo(b.x,b.z);context.stroke()}}}
    if(keyboard){context.strokeStyle='#773049';context.lineWidth=.008;context.beginPath();context.arc(cursor.x,cursor.z,.035,0,Math.PI*2);context.stroke()}
    $('.draw-paper-label').hidden=raw.length>0;canvas.dataset.points=String(raw.length);canvas.dataset.valid=String(Boolean(result?.ok));$('#draw-use').disabled=!result?.ok;$('#draw-undo').disabled=!raw.length;
  }
  function validate(explicitClose=false){result=prepareOutline(raw,content.customRules,{explicitClose});$('.draw-status').textContent=result.ok?(innerWidth<=640?d.mobileReady:d.ready):d[result.error];dialog.dataset.valid=String(result.ok);if(result.ok){preview??=createAtelier($('#mold-preview'),content,{preview:true});preview.setRecipe({mold:'custom',outline:result.outline,first:content.flavors[0].id,second:content.flavors[1].id,split:.45,toppings:[]},'mold',1);$('.draw-preview-wrap').classList.add('has-preview')}else $('.draw-preview-wrap').classList.remove('has-preview');paint();}
  function invalidate(){result=null;$('#draw-use').disabled=true;$('.draw-preview-wrap').classList.remove('has-preview');$('.draw-status').textContent='';dialog.dataset.valid='false';paint()}
  canvas.addEventListener('pointerdown',event=>{if(event.button!==0||active!==null)return;keyboard=false;if(mode==='points'){if(raw.length>=content.customRules.maxInput)return;raw.push(point(event));validate(true);return}before=raw;raw=[point(event)];active=event.pointerId;canvas.setPointerCapture(active);invalidate()});
  canvas.addEventListener('pointermove',event=>{if(active!==event.pointerId)return;const p=point(event);if(raw.length<content.customRules.maxInput&&Math.hypot(p.x-raw.at(-1).x,p.z-raw.at(-1).z)>.008){raw.push(p);paint()}});
  canvas.addEventListener('pointerup',event=>{if(active!==event.pointerId)return;const p=point(event);if(raw.length<content.customRules.maxInput)raw.push(p);active=null;validate(false)});
  const cancelStroke=()=>{if(active!==null){active=null;raw=before;raw.length?validate(mode==='points'):invalidate()}};canvas.addEventListener('pointercancel',cancelStroke);canvas.addEventListener('lostpointercapture',cancelStroke);window.addEventListener('blur',cancelStroke);
  canvas.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','Enter'].includes(event.code))return;event.preventDefault();keyboard=true;mode='points';updateModes();if(event.code==='Space'||event.code==='Enter'){if(raw.length<content.customRules.maxInput){raw.push({...cursor});validate(true)}}else{cursor.x=Math.max(-.9,Math.min(.9,cursor.x+(event.code==='ArrowLeft'?-.05:event.code==='ArrowRight'?.05:0)));cursor.z=Math.max(-.9,Math.min(.9,cursor.z+(event.code==='ArrowUp'?-.05:event.code==='ArrowDown'?.05:0)));paint()}});
  function updateModes(){$('#draw-free').setAttribute('aria-pressed',String(mode==='free'));$('#draw-points').setAttribute('aria-pressed',String(mode==='points'))}
  for(const kind of ['free','points'])$('#draw-'+kind).addEventListener('click',()=>{cancelStroke();mode=kind;updateModes();paint()});
  $('#draw-clear').addEventListener('click',()=>{active=null;raw=[];invalidate()});$('#draw-undo').addEventListener('click',()=>{active=null;raw.pop();raw.length?validate(mode==='points'):invalidate()});$('#draw-close').addEventListener('click',()=>validate(true));$('#draw-cancel').addEventListener('click',()=>dialog.close());
  $('#draw-use').addEventListener('click',()=>{if(!result?.ok)return;onUse(result.outline.map(p=>({...p})));dialog.close()});dialog.addEventListener('close',()=>{active=null;preview?.dispose();preview=null;$('#mold-preview').replaceChildren()});
  const observer=new ResizeObserver(paint);observer.observe(canvas);
  return {open(outline){raw=outline?outline.map(p=>({...p})):[];result=null;dialog.showModal();if(raw.length){result={ok:true,outline:raw.map(p=>({...p}))};$('.draw-status').textContent=innerWidth<=640?d.mobileReady:d.ready;dialog.dataset.valid='true';preview=createAtelier($('#mold-preview'),content,{preview:true});preview.setRecipe({mold:'custom',outline:result.outline,first:content.flavors[0].id,second:content.flavors[1].id,split:.45,toppings:[]},'mold',1);$('.draw-preview-wrap').classList.add('has-preview');paint()}else invalidate();},dialog};
}
