import C from './content/content.json';
import {newSave,readSave,createRun,cast,strike,step,net,commit,daySeed,surge,clamp,type Run} from './model';
import {Scene,drawFish,whenFishReady} from './render';
import {AudioBank} from './audio-bank';
declare global{interface Window{POND_AUDIO?:{[key:string]:string}}}
const $=(id:string)=>document.getElementById(id)!,T=C.copy,panel=$('panel'),scene=new Scene($('scene') as HTMLCanvasElement);
let save=newSave(),saveFailed=false,future=false;try{const raw=localStorage.getItem(C.storageKey);future=Number(JSON.parse(raw||'null')?.version)>1;save=readSave(raw)||save;}catch{}
let paused=save.run.phase!=='ready',last=0,time=0,acc=0,raf=0,power=0,reeling=false,steer=0,lastPersist=0,lastSound=0,windowMs=0,windowFrames=0,slowWindows=0;
let drawAt=0;
let drag:{id:number;x:number;y:number;startX:number;startY:number;travel:number}|null=null;
const audio=new AudioBank(window.POND_AUDIO||{},C.audio.groups,C.audio.gain,()=>{$('status').textContent=T.silent;});
scene.reduced=save.settings.reduced;document.documentElement.style.setProperty('--host-reserved-x',(C.layout.hostWidth+C.layout.hostOffset+C.layout.hostMargin)+'px');$('title').textContent=C.title;
function persist(){if(future)return;try{localStorage.setItem(C.storageKey,JSON.stringify(save));saveFailed=false;}catch{saveFailed=true;}}
function stop(){drag=null;reeling=false;power=0;steer=0;audio.stop();}
function button(text:string,fn:()=>void,parent:HTMLElement){const b=document.createElement('button');b.textContent=text;b.addEventListener('click',fn);parent.appendChild(b);return b;}
function paragraph(text:string,parent:HTMLElement,cls=''){const p=document.createElement('p');p.textContent=text;p.className=cls;parent.appendChild(p);return p;}
function close(){panel.hidden=true;paused=false;last=0;acc=0;hint();}
function show(title:string,note:string,build:(body:HTMLElement)=>void,back=close,backLabel=T.close){stop();paused=true;persist();panel.textContent='';panel.setAttribute('aria-label',title);const h=document.createElement('h2');h.textContent=title;panel.appendChild(h);if(note)paragraph(note,panel);const body=document.createElement('div');body.className='body';panel.appendChild(body);build(body);const b=button(backLabel,back,panel);b.className='exit';panel.hidden=false;body.scrollTop=0;b.focus();}
function next(mode:Run['mode']='free',seed=(Date.now()>>>0),spot=save.run.spot,bait=save.run.bait,challenge=-1){save.run=createRun(seed,spot,bait,mode,challenge);persist();close();}
function change(fn:()=>void){if(save.run.phase==='ready'||save.run.phase==='miss'||save.run.phase==='caught')fn();else show(T.spots,T.cancel,body=>button(T.confirm,fn,body),journal,T.back);}
function journal(){show(T.journal,T.progress+' '+save.completed.length+'/24',body=>{
 button(T.spots,()=>show(T.spots,T.all,b=>C.spots.forEach((spot,i)=>button(spot.name+' · '+spot.hint,()=>change(()=>next('free',Date.now()>>>0,i)),b)),journal,T.back),body);
 button(T.bait,()=>show(T.bait,C.baits[save.run.bait],b=>C.baits.forEach((name,i)=>button(name,()=>change(()=>next('free',Date.now()>>>0,save.run.spot,i)),b)),journal,T.back),body);
 button(T.challenges,()=>show(T.challenges,T.progress+' '+save.completed.length+'/24',b=>C.challenges.forEach((ch,i)=>{const row=button((save.completed.includes(i)?'✓ ':'')+ch.name,()=>change(()=>next('challenge',ch.seed,Math.floor(i/4),ch.bait,i)),b);paragraph(ch.hint,row);}),journal,T.back),body);
 button(T.daily,()=>change(()=>next('daily',daySeed(),daySeed()%6)),body);paragraph(T.dailyNote,body);
 button(T.history,()=>show(T.history,T.practiceNote,b=>{if(!save.history.length)paragraph(T.empty,b);save.history.forEach(v=>button(C.fish[v.kind].name+' · '+v.length+' '+T.cm+' · '+T.replay,()=>change(()=>next('practice',v.seed,v.spot,v.bait)),b));},journal,T.back),body);
 button(T.settings,settings,body);
 });}
function settings(){show(T.settings,T.copyright,body=>{button(save.settings.sound?T.soundOn:T.soundOff,()=>{save.settings.sound=!save.settings.sound;if(save.settings.sound)void audio.enable();else audio.mute();persist();settings();},body);button(save.settings.assist?T.assistOn:T.assistOff,()=>{save.settings.assist=!save.settings.assist;persist();settings();},body);button(save.settings.reduced?T.reduceOn:T.reduceOff,()=>{save.settings.reduced=!save.settings.reduced;scene.reduced=save.settings.reduced;persist();settings();},body);},journal,T.back);}
function specimen(kind:number,body:HTMLElement){const canvas=document.createElement('canvas');canvas.width=560;canvas.height=280;canvas.className='specimen';body.appendChild(canvas);const ctx=canvas.getContext('2d')!;whenFishReady(()=>{ctx.clearRect(0,0,560,280);drawFish(ctx,kind,280,140,440,280);});}
function card(kind:number,caught=false){const f=C.fish[kind],record=save.records.find(v=>v.kind===kind);show(f.name,caught?T.caughtNote:T.album,body=>{specimen(kind,body);if(caught)paragraph(T.length+' '+save.run.length+' '+T.cm,body,'measure');paragraph(f.description,body);paragraph(T.family+' · '+C.families[f.family].name+' · '+C.families[f.family].hint,body);if(record)paragraph(record.count+' '+T.times+' · '+T.max+' '+record.max+' '+T.cm+' · '+record.spots.map(i=>C.spots[i].name).join(' / '),body);paragraph(T.discovery+' · '+C.spots.filter(s=>s.pool.includes(kind)).map(s=>s.name).join(' / '),body);paragraph(T.sources,body,'subtle');if(caught)button(T.practice,()=>next('practice',save.run.seed,save.run.spot,save.run.bait),body);},caught?releaseFish:album,caught?T.release:T.album);}
function releaseFish(){save.run.phase='release';save.run.time=0;close();persist();}
function album(){show(T.album,T.record+' '+save.records.length+'/18',body=>{body.className='body grid';C.fish.forEach((f,i)=>button(save.records.some(v=>v.kind===i)?f.name:T.unknown,()=>{if(save.records.some(v=>v.kind===i))card(i);else show(T.unknown,T.discovery,b=>paragraph(C.spots.filter(s=>s.pool.includes(i)).map(s=>s.name).join(' / '),b),album,T.album);},body));});}
button(T.journal,journal,$('tools'));button(T.album,album,$('tools'));
function hint(){const r=save.run;$('app').dataset.phase=r.phase;$('spot').textContent=C.spots[r.spot].name;const text=r.phase==='miss'?T[r.reason as 'early'|'late'|'break'|'slack']:r.phase==='release'?T.releaseHint:T[r.phase];if($('hint').textContent!==text)$('hint').textContent=text;let status=r.mode==='practice'?T.practiceNote:r.mode==='daily'?T.dailyNote:C.baits[r.bait];if(r.phase==='wait')status=r.accuracy>=.7?T.landingGood:T.landingFar;if(r.phase==='fight')status=r.tension>.85?T.loosen:r.tension<.15?T.loose:surge(r)?T.rush:T.rest;if(r.mode==='challenge'&&r.phase!=='fight')status=C.challenges[r.challenge].hint;if(saveFailed)status=T.saveError;$('status').textContent=status;}
function blocked(x:number,y:number){const edge=C.layout.hostWidth+C.layout.hostOffset+C.layout.hostMargin,st=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--safe-area-inset-top'))||0;return y<st+112&&(x<edge||x>innerWidth-edge);}
function down(id:number,x:number,y:number){if(paused||drag||blocked(x,y))return;const r=save.run,p=scene.point(x,y);if(save.settings.sound&&!audio.enabled)void audio.enable();if(r.phase==='miss'){next();return;}if(r.phase==='caught'){card(r.kind,true);return;}if(r.phase==='ready'&&(p.x<.12||p.x>.88||p.y<.25||p.y>.78))return;if(r.phase==='fight'&&y<innerHeight*.72)return;if(r.phase==='release'||r.phase==='cast'||r.phase==='net'&&Math.hypot(p.x-.28,p.y-.84)>.16)return;drag={id,x:p.x,y:p.y,startX:p.x,startY:p.y,travel:0};if(r.phase==='ready'){r.targetX=clamp(p.x,.18,.82);r.targetY=clamp(p.y,.35,.65);}if(r.phase==='fight')reeling=true;}
function move(id:number,x:number,y:number){if(!drag||drag.id!==id)return;const p=scene.point(x,y),r=save.run;drag.travel+=Math.hypot(p.x-drag.x,p.y-drag.y);drag.x=p.x;drag.y=p.y;if(r.phase==='ready'){power=clamp((p.y-drag.startY)*3);r.targetX=clamp(drag.startX+(p.x-drag.startX)*.7,.18,.82);}else if(r.phase==='fight'){steer=clamp((p.x-drag.startX)*4,-1,1);}else if(['wait','nibble','bite'].includes(r.phase)&&drag.startY-p.y>.08){strike(r);stop();persist();} }
function up(id:number,cancel=false){if(!drag||drag.id!==id)return;const r=save.run;if(!cancel&&r.phase==='ready')cast(r,r.targetX,r.targetY,power);stop();persist();if(cancel&&r.phase!=='ready')pause();}
function pause(){show(T.paused,'',()=>{},close,T.resume);}
const canvas=scene.canvas;if(typeof PointerEvent!=='undefined'){canvas.addEventListener('pointerdown',e=>{down(e.pointerId,e.clientX,e.clientY);if(drag)try{canvas.setPointerCapture(e.pointerId);}catch{}});canvas.addEventListener('pointermove',e=>move(e.pointerId,e.clientX,e.clientY));canvas.addEventListener('pointerup',e=>up(e.pointerId));canvas.addEventListener('pointercancel',e=>up(e.pointerId,true));canvas.addEventListener('lostpointercapture',e=>up(e.pointerId,true));}else{canvas.addEventListener('touchstart',e=>{if(e.touches.length===1){const t=e.touches[0];down(t.identifier,t.clientX,t.clientY);}},{passive:true});canvas.addEventListener('touchmove',e=>{if(drag){e.preventDefault();for(const t of Array.from(e.changedTouches))move(t.identifier,t.clientX,t.clientY);}},{passive:false});canvas.addEventListener('touchend',e=>{for(const t of Array.from(e.changedTouches))up(t.identifier);});canvas.addEventListener('touchcancel',()=>{if(drag)up(drag.id,true);});canvas.addEventListener('mousedown',e=>{if(!e.button)down(-1,e.clientX,e.clientY);});window.addEventListener('mousemove',e=>move(-1,e.clientX,e.clientY));window.addEventListener('mouseup',()=>up(-1));}
function frame(ms:number){if(document.hidden){raf=0;return;}const elapsed=last?ms-last:0,dt=Math.min(.05,elapsed/1000);last=ms;if(!paused){time+=dt;acc+=dt;while(acc>=1/60){const before=save.run.phase;step(save.run,1/60,reeling,steer,save.settings.assist);if(save.run.phase==='net'&&drag&&net(save.run,drag.x,drag.y,1/60)){commit(save);persist();stop();}if(save.run.phase!==before){audio.play('water',.5);persist();}acc-=1/60;}if(save.run.phase==='release'&&save.run.time>1.1)next();if(time-lastPersist>3){persist();lastPersist=time;}hint();if(reeling&&time-lastSound>.65){audio.play('reel',.24);lastSound=time;}if(elapsed>0&&elapsed<250){windowMs+=elapsed;windowFrames++;if(windowMs>2000){slowWindows=windowMs/windowFrames>40?slowWindows+1:0;if(slowWindows>=2&&!scene.low){scene.low=true;scene.resize();}windowMs=0;windowFrames=0;}}}if(ms-drawAt>=32){scene.draw(save.run,time,drag,reeling,power);drawAt=ms;}raf=requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{stop();scene.resize();if(save.run.phase!=='ready')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();persist();paused=true;if(raf)cancelAnimationFrame(raf);raf=0;}else{last=0;acc=0;pause();if(!raf)raf=requestAnimationFrame(frame);}});window.addEventListener('pagehide',()=>{stop();persist();cancelAnimationFrame(raf);raf=0;});window.addEventListener('pageshow',()=>{last=0;if(!raf)raf=requestAnimationFrame(frame);});document.addEventListener('keydown',e=>{if(panel.hidden)return;if(e.key==='Escape')close();if(e.key==='Tab'){const list=Array.from(panel.querySelectorAll<HTMLButtonElement>('button')),first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});hint();if(paused)pause();raf=requestAnimationFrame(frame);
