import {createRequire} from 'node:module';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=fileURLToPath(new URL('./screenshots/',import.meta.url));await mkdir(out,{recursive:true});
const c=JSON.parse(await readFile(new URL('../src/content/content.json',import.meta.url),'utf8')),create=require('../src/engine.js'),e=create(c);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),results=[],errors=[];
const hostScript=()=>{document.documentElement.style.setProperty('--safe-area-inset-top','24px');document.documentElement.style.setProperty('--safe-area-inset-bottom','16px');for(const side of ['left','right']){const d=document.createElement('div');d.className='qa-host';d.setAttribute('data-side',side);d.style.cssText='position:fixed;top:24px;'+side+':8px;width:64px;height:44px;border-radius:22px;background:#29362eaa;z-index:9999;pointer-events:auto';document.body.appendChild(d);}};
async function setup(width,height=844,seed){const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));if(seed)await page.addInitScript(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key:c.storageKey,s:seed});await page.goto('http://127.0.0.1:4327/');await page.evaluate(hostScript);return {context,page};}
async function click(page,action,extra=''){await page.locator('[data-action="'+action+'"]'+extra).first().click();}
async function check(page,label){
  const issues=await page.evaluate(()=>{const found=[],hosts=Array.from(document.querySelectorAll('.qa-host')).map(x=>x.getBoundingClientRect());if(document.documentElement.scrollWidth>window.innerWidth+1)found.push('horizontal overflow');const sheet=document.querySelector('.sheet');if(sheet){const r=sheet.getBoundingClientRect();if(r.top<78||r.bottom>innerHeight+1)found.push('sheet offscreen');const f=document.querySelector('.sheet-footer').getBoundingClientRect();if(f.bottom>innerHeight+1)found.push('footer offscreen');}
    for(const b of document.querySelectorAll(sheet?'.sheet button':'button')){if(b.disabled)continue;const rect=b.getBoundingClientRect(),r={left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom};for(let p=b.parentElement;p;p=p.parentElement){const st=getComputedStyle(p);if(['auto','hidden','scroll'].includes(st.overflowY)){const clip=p.getBoundingClientRect();r.top=Math.max(r.top,clip.top);r.bottom=Math.min(r.bottom,clip.bottom);}}if(r.right<=r.left||r.bottom<=r.top||r.bottom<0||r.top>innerHeight)continue;if(hosts.some(h=>r.left<h.right&&r.right>h.left&&r.top<h.bottom&&r.bottom>h.top))found.push('host collision: '+b.textContent);}
    return found;});assert.deepEqual(issues,[],label);results.push(label);
}
try{
  for(const width of [375,390,430]){
    const {context,page}=await setup(width);await check(page,width+' fresh');await page.screenshot({path:out+width+'-fresh.png',fullPage:true});
    await click(page,'shop');await check(page,width+' shop');await click(page,'item','[data-item="orchid"]');await check(page,width+' item');await click(page,'buyMode');await check(page,width+' placement');await click(page,'plot','[data-pos="0"]');
    await click(page,'goal','[data-id="firstplant"]');await click(page,'shop');await click(page,'item','[data-item="lantern"]');await click(page,'buyMode');await click(page,'plot','[data-pos="1"]');await click(page,'goal','[data-id="twoplants"]');await click(page,'goal','[data-id="firstcombo"]');
    await page.locator('[data-action="select"][data-uid="1"]').click();await click(page,'upgradeInfo');await check(page,width+' upgrade');await click(page,'upgrade');await click(page,'goal','[data-id="firstup"]');
    await click(page,'expand');await check(page,width+' expand');await click(page,'confirmExpand');
    await page.locator('[data-action="select"][data-uid="1"]').click();await click(page,'move');await check(page,width+' moving');await click(page,'plot','[data-pos="3"]');await click(page,'store');await click(page,'warehouse');await check(page,width+' warehouse');await click(page,'replace');await click(page,'plot','[data-pos="0"]');
    await click(page,'journal');await check(page,width+' journal');await click(page,'journalCombos');await check(page,width+' combos');await page.screenshot({path:out+width+'-combos.png'});await click(page,'close');
    await click(page,'album');await check(page,width+' album');await click(page,'close');await click(page,'guide');await check(page,width+' guide');await click(page,'resetAsk');await check(page,width+' reset');await click(page,'close');
    const before=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);await page.reload();const after=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);assert.equal(after.coins,before.coins);assert.deepEqual(after.objects,before.objects);results.push(width+' persists reload');
    await page.evaluate(hostScript);await check(page,width+' restored');await page.screenshot({path:out+width+'-playing.png',fullPage:true});await context.close();
  }
  const advanced=e.fresh(Date.now());advanced.coins=999999;advanced.xp=5000;advanced.expansion=7;
  for(const [id,pos] of [['pavilion',0],['banana',2],['bamboo',3],['pond',4],['lantern',6],['plum',7],['table',8],['orchid',9],['window',10],['rock',11],['library',12],['bamboo',15],['window',16],['gate',17],['plum',19],['flowers',24],['willow',26],['stonegarden',36]])assert.equal(e.act(advanced,{type:'buy',item:id,pos},Date.now()).ok,true,id);
  for(const [width,height] of [[390,844],[844,390],[1280,900]]){const {context,page}=await setup(width,height,advanced);await check(page,width+' advanced garden');await page.screenshot({path:out+width+'-advanced.png',fullPage:true});await click(page,'night');await check(page,width+' night');await click(page,'area','[data-area="2"]');await check(page,width+' grand scenery');await click(page,'shop');await click(page,'tier','[data-tier="6"]');await check(page,width+' tier6');await page.screenshot({path:out+width+'-shop.png'});await click(page,'close');await click(page,'warehouse');await check(page,width+' empty warehouse');await context.close();}
  const offline=e.fresh(Date.now()-10*3600000);e.act(offline,{type:'buy',item:'orchid',pos:0},offline.last);const {context:oc,page:op}=await setup(390,844,offline);await check(op,'offline modal');assert.match(await op.locator('.offline-amount').textContent(),/2,400/);await click(op,'collectOffline');assert.match(await op.locator('#wallet').textContent(),/2,500/);results.push('offline claim correct');await oc.close();
  const fault=await browser.newContext({viewport:{width:390,height:844}});await fault.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('unavailable');}}));const fp=await fault.newPage();await fp.goto('http://127.0.0.1:4327/');assert.match(await fp.locator('.storage-status').textContent(),/存储不可用/);await click(fp,'shop');await click(fp,'item','[data-item="orchid"]');await click(fp,'buyMode');await click(fp,'plot','[data-pos="0"]');assert.equal(await fp.locator('.placed').count(),1);results.push('storage unavailable keeps playable and warns');await fault.close();
  const corrupt=await browser.newContext();await corrupt.addInitScript(key=>localStorage.setItem(key,'not-json'),c.storageKey);const cp=await corrupt.newPage();await cp.goto('http://127.0.0.1:4327/');assert.match(await cp.locator('.storage-status').textContent(),/原存档未覆盖/);assert.equal(await cp.evaluate(key=>localStorage.getItem(key),c.storageKey),'not-json');results.push('corrupt save preserved');await corrupt.close();
  const multi=await browser.newContext({viewport:{width:390,height:844}}),p1=await multi.newPage(),p2=await multi.newPage();await p1.goto('http://127.0.0.1:4327/');await p2.goto('http://127.0.0.1:4327/');
  await click(p1,'shop');await click(p1,'item','[data-item="orchid"]');await click(p1,'buyMode');await click(p1,'plot','[data-pos="0"]');await p2.waitForFunction(()=>document.querySelectorAll('.placed').length===1);assert.equal(await p2.locator('#wallet').textContent(),'100');results.push('second tab observes purchase without overwriting');
  await p2.close();await p1.goto('http://127.0.0.1:4327/assets/scenery.webp');await p1.evaluate(key=>{const s=JSON.parse(localStorage.getItem(key));s.last=Date.now()-10*3600000;localStorage.setItem(key,JSON.stringify(s));},c.storageKey);await p1.goto('http://127.0.0.1:4327/');await click(p1,'collectOffline');await p1.reload();assert.equal(await p1.locator('.offline-amount').count(),0);assert.ok(Number((await p1.locator('#wallet').textContent()).replace(/,/g,''))>=2500);results.push('offline claim persists across reload without replay');await multi.close();
  const editSeed=e.fresh(Date.now());editSeed.coins=100000;editSeed.xp=5000;editSeed.expansion=7;const {context:ec,page:ep}=await setup(390,844,editSeed);await click(ep,'shop');await click(ep,'tier','[data-tier="3"]');await click(ep,'item','[data-item="pond"]');await click(ep,'buyMode');await click(ep,'rotate');await click(ep,'plot','[data-pos="0"]');let ed=await ep.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);assert.equal(ed.objects[0].rotated,true);assert.equal(ed.coins,97600);results.push('rotated multi-cell purchase');
  await click(ep,'shop');await click(ep,'item','[data-item="bridge"]');await click(ep,'buyMode');await click(ep,'cancel');ed=await ep.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);assert.equal(ed.coins,97600);assert.equal(ed.objects.length,1);results.push('cancel placement has no charge');
  await click(ep,'guide');await click(ep,'resetAsk');await click(ep,'reset');ed=await ep.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);assert.equal(ed.coins,200);assert.equal(ed.objects.length,0);results.push('explicit reset restores initial state');await ec.close();
  const fileContext=await browser.newContext();const filePage=await fileContext.newPage();filePage.on('pageerror',err=>errors.push(err.message));await filePage.goto(new URL('../dist/index.html',import.meta.url).href);assert.equal(await filePage.locator('#wallet').textContent(),'200');await click(filePage,'shop');assert.equal(await filePage.locator('.shop-card').count(),4);results.push('offline file URL classic scripts start and shop works');await fileContext.close();
  assert.deepEqual(errors,[]);await writeFile(new URL('./results.json',import.meta.url),JSON.stringify({passed:results.length,results,errors,checkedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({passed:results.length,errors},null,2));
}finally{await browser.close();}
