import {createRequire} from 'node:module';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=fileURLToPath(new URL('./screenshots-v3/',import.meta.url));await mkdir(out,{recursive:true});
const c=JSON.parse(await readFile(new URL('../src/content/content.json',import.meta.url),'utf8')),create=require('../src/engine.js'),e=create(c);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),results=[],errors=[];
const hostScript=()=>{document.documentElement.style.setProperty('--safe-area-inset-top','24px');document.documentElement.style.setProperty('--safe-area-inset-bottom','16px');for(const side of ['left','right']){const d=document.createElement('div');d.className='qa-host';d.setAttribute('data-side',side);d.style.cssText='position:fixed;top:24px;'+side+':8px;width:64px;height:44px;border-radius:22px;background:#29362eaa;z-index:9999;pointer-events:auto';document.body.appendChild(d);}};
async function setup(width,height=844,seed){const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));if(seed)await page.addInitScript(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key:c.storageKey,s:seed});await page.goto('http://127.0.0.1:4327/');await page.evaluate(hostScript);return {context,page};}
import {click} from './editor-actions.mjs';
async function check(page,label){
  const issues=await page.evaluate(()=>{const found=[],hosts=Array.from(document.querySelectorAll('.qa-host')).map(x=>x.getBoundingClientRect());if(document.documentElement.scrollWidth>window.innerWidth+1)found.push('horizontal overflow');const sheet=document.querySelector('.sheet');if(sheet){const r=sheet.getBoundingClientRect();if(r.top<78||r.bottom>innerHeight+1)found.push('sheet offscreen');const f=document.querySelector('.sheet-footer').getBoundingClientRect();if(f.bottom>innerHeight+1)found.push('footer offscreen');}
    for(const b of document.querySelectorAll(sheet?'.sheet button':'button')){if(b.disabled)continue;const rect=b.getBoundingClientRect(),r={left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom};for(let p=b.parentElement;p;p=p.parentElement){const st=getComputedStyle(p);if(['auto','hidden','scroll'].includes(st.overflowY)){const clip=p.getBoundingClientRect();r.top=Math.max(r.top,clip.top);r.bottom=Math.min(r.bottom,clip.bottom);}}if(r.right<=r.left||r.bottom<=r.top||r.bottom<0||r.top>innerHeight)continue;if(hosts.some(h=>r.left<h.right&&r.right>h.left&&r.top<h.bottom&&r.bottom>h.top))found.push('host collision: '+b.textContent);}
    return found;});assert.deepEqual(issues,[],label);results.push(label);
}
async function purchase(page,id,tier=1){await click(page,'shop');await click(page,'tier','[data-tier="'+tier+'"]');await click(page,'item','[data-item="'+id+'"]');await click(page,'buyMode');await click(page,'confirmPlace');}
async function state(page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);}
function advancedState(){const s=e.fresh(Date.now());s.coins=1e8;s.xp=5000;s.expansion=7;s.collection=c.items.map(i=>i.id);for(const [item,area] of [['pavilion',0],['bamboo',0],['banana',0],['orchid',0],['lantern',0],['table',0],['plum',0],['pond',1],['bridge',1],['willow',1],['waterside',1],['library',2],['window',2],['bamboo',2],['gate',2],['stonegarden',3],['pine',3],['rock',3]]){const p=e.suggest(s,item,area,false);if(!p)throw Error('seed cannot place '+item);assert.equal(e.act(s,Object.assign({type:'buy',item},p),Date.now()).ok,true);}s.objects.find(o=>o.item==='orchid').level=2;return s;}
try{
  for(const width of [375,390,430]){
    const {context,page}=await setup(width);await check(page,width+' empty garden');await page.screenshot({path:out+width+'-empty.png'});
    assert.equal(await page.locator('.plot').count(),0);results.push(width+' visible grid removed');
    await click(page,'shop');await check(page,width+' shop');await click(page,'item','[data-item="orchid"]');await check(page,width+' item');await click(page,'buyMode');await check(page,width+' coordinate preview');
    const scene=page.locator('#garden-viewport'),box=await scene.boundingBox();await scene.click({position:{x:3,y:box.height*.5}});assert.equal(await page.locator('[data-action="confirmPlace"]').isDisabled(),true);assert.equal((await state(page)).coins,200);results.push(width+' path blocked without debit');await click(page,'recommend');await click(page,'confirmPlace');assert.equal((await state(page)).objects.length,1);await check(page,width+' planted');
    await click(page,'goal','[data-id="firstplant"]');await purchase(page,'lantern');assert.ok((await state(page)).combos.includes('first'));await click(page,'goal','[data-id="twoplants"]');await click(page,'goal','[data-id="firstcombo"]');
    await click(page,'select','[data-uid="1"]');await check(page,width+' selection');await click(page,'upgradeInfo');await check(page,width+' upgrade');await click(page,'upgrade');await click(page,'goal','[data-id="firstup"]');
    await click(page,'stories');await check(page,width+' story inbox');await click(page,'storyOpen','[data-id="orchid"]');await check(page,width+' story first page');await click(page,'storyChoose','[data-choice="wait"]');await check(page,width+' story response');await click(page,'storyContinue');await click(page,'storyOpen','[data-id="orchid"]');assert.match(await page.locator('.story-page').textContent(),/等花的这些日子/);await click(page,'storyChoose','[data-choice="share"]');await click(page,'storyContinue');await click(page,'storyOpen','[data-id="orchid"]');assert.match(await page.locator('.story-page').textContent(),/果然又来了/);await click(page,'storyChoose','[data-choice="visit"]');assert.equal(await page.locator('.earned-keepsake').count(),1);await page.screenshot({path:out+width+'-story.png'});await click(page,'close');assert.equal(await page.locator('.keepsake').count(),1);results.push(width+' full story choices and keepsake');
    await click(page,'expand');await check(page,width+' expand');await click(page,'confirmExpand');await click(page,'select','[data-uid="1"]');await click(page,'move');await click(page,'recommend');await check(page,width+' moving');await click(page,'confirmPlace');await click(page,'store');await click(page,'warehouse');await check(page,width+' warehouse');await click(page,'replace');await click(page,'confirmPlace');assert.equal((await state(page)).objects[0].level,2);
    await click(page,'journal');await check(page,width+' goals');await click(page,'journalCombos');await check(page,width+' combination rules');await click(page,'close');await click(page,'album');await check(page,width+' collection');await click(page,'close');await click(page,'guide');await check(page,width+' guide');await click(page,'resetAsk');await check(page,width+' reset confirmation');await click(page,'close');
    await click(page,'home');await click(page,'view');await check(page,width+' appreciation');assert.equal(await page.locator('.dock').isVisible(),false);await page.screenshot({path:out+width+'-early.png'});await click(page,'view');
    const before=await state(page);await page.reload();const after=await state(page);assert.equal(after.coins,before.coins);assert.deepEqual(after.objects,before.objects);assert.deepEqual(after.stories,before.stories);results.push(width+' placement and story persistence');await context.close();
  }
  const advanced=advancedState();
  for(const [width,height] of [[390,844],[844,390],[1280,900]]){const {context,page}=await setup(width,height,advanced);await check(page,width+' mature garden');await page.screenshot({path:out+width+'-mature.png'});for(let area=1;area<4;area++){await click(page,'area','[data-area="'+area+'"]');await check(page,width+' court '+area);if(width===390)await page.screenshot({path:out+'court-'+area+'.png'});}await click(page,'night');await check(page,width+' night');await click(page,'view');await check(page,width+' appreciation mature');await click(page,'view');await click(page,'shop');await click(page,'tier','[data-tier="6"]');await check(page,width+' tier six');await click(page,'close');await click(page,'warehouse');await check(page,width+' empty warehouse');await click(page,'close');
    for(const story of c.stories){await click(page,'stories');await click(page,'storyOpen','[data-id="'+story.id+'"]');await check(page,width+' '+story.id+' dialogue');await click(page,'close');}await context.close();}
  const ss=advancedState();const {context:sc,page:sp}=await setup(390,844,ss);for(const t of c.stories){for(let stage=0;stage<3;stage++){await click(sp,'stories');await click(sp,'storyOpen','[data-id="'+t.id+'"]');await click(sp,'storyChoose','[data-choice="'+t.episodes[stage].choices[1].id+'"]');await click(sp,'close');}await click(sp,'stories');await click(sp,'storyOpen','[data-id="'+t.id+'"]');assert.equal(await sp.locator('.story-record').count(),3);await sp.locator('.story-record summary').first().click();assert.ok((await sp.locator('.story-record[open]').textContent()).length>50);await click(sp,'close');await click(sp,'area','[data-area="'+t.area+'"]');assert.equal(await sp.locator('.keepsake').count(),c.stories.indexOf(t)+1);results.push(t.id+' all stages and re-readable history');}await sc.close();
  const legacy=e.fresh(Date.now()-3600000);e.act(legacy,{type:'buy',item:'orchid',pos:0},legacy.last);legacy.version=1;delete legacy.stories;const {context:lc,page:lp}=await setup(390,844,legacy);const migrated=await state(lp);assert.equal(migrated.version,2);assert.equal(migrated.coins,100);assert.equal(migrated.objects.length,1);assert.ok(Number.isFinite(migrated.objects[0].x));assert.ok(migrated.bank>=300);results.push('v1 browser migration retains earnings and scenery');await lc.close();
  const offline=e.fresh(Date.now()-10*3600000),p=e.suggest(offline,'orchid',0,false);e.act(offline,Object.assign({type:'buy',item:'orchid'},p),offline.last);const {context:oc,page:op}=await setup(390,844,offline);await check(op,'offline modal');assert.match(await op.locator('.offline-amount').textContent(),/2,400/);await click(op,'collectOffline');assert.match(await op.locator('#wallet').textContent(),/2,500/);results.push('offline claim');await oc.close();
  const fault=await browser.newContext({viewport:{width:390,height:844}});await fault.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('unavailable');}}));const fp=await fault.newPage();await fp.goto('http://127.0.0.1:4327/');assert.match(await fp.locator('.storage-status').textContent(),/存储不可用/);await purchase(fp,'orchid');assert.equal(await fp.locator('.placed').count(),1);results.push('storage failure remains playable');await fault.close();
  const corrupt=await browser.newContext();await corrupt.addInitScript(key=>localStorage.setItem(key,'not-json'),c.storageKey);const cp=await corrupt.newPage();await cp.goto('http://127.0.0.1:4327/');assert.match(await cp.locator('.storage-status').textContent(),/原存档未覆盖/);assert.equal(await cp.evaluate(key=>localStorage.getItem(key),c.storageKey),'not-json');results.push('corrupt save retained');await corrupt.close();
  const multi=await browser.newContext({viewport:{width:390,height:844}}),p1=await multi.newPage(),p2=await multi.newPage();await p1.goto('http://127.0.0.1:4327/');await p2.goto('http://127.0.0.1:4327/');await purchase(p1,'orchid');await p2.waitForFunction(()=>document.querySelectorAll('.placed').length===1);assert.equal(await p2.locator('#wallet').textContent(),'100');results.push('cross tab synchronization');await p2.close();await p1.goto('http://127.0.0.1:4327/assets/scenery.webp');await p1.evaluate(key=>{const s=JSON.parse(localStorage.getItem(key));s.last=Date.now()-10*3600000;localStorage.setItem(key,JSON.stringify(s));},c.storageKey);await p1.goto('http://127.0.0.1:4327/');await click(p1,'collectOffline');await p1.reload();assert.equal(await p1.locator('.offline-amount').count(),0);assert.ok(Number((await p1.locator('#wallet').textContent()).replace(/,/g,''))>=2500);results.push('offline reload does not replay');await multi.close();
  const rotateSeed=e.fresh(Date.now());rotateSeed.coins=100000;rotateSeed.xp=5000;rotateSeed.expansion=7;const {context:rc,page:rp}=await setup(390,844,rotateSeed);await click(rp,'shop');await click(rp,'tier','[data-tier="3"]');await click(rp,'item','[data-item="pond"]');await click(rp,'buyMode');await click(rp,'rotate');await click(rp,'recommend');await click(rp,'confirmPlace');assert.equal((await state(rp)).objects[0].rotated,true);results.push('rotate then place');await click(rp,'shop');await click(rp,'item','[data-item="bridge"]');await click(rp,'buyMode');await click(rp,'cancel');assert.equal((await state(rp)).coins,97600);results.push('cancel no debit');await click(rp,'guide');await click(rp,'resetAsk');await click(rp,'reset');assert.equal((await state(rp)).objects.length,0);assert.equal((await state(rp)).coins,200);results.push('reset confirmed');await rc.close();
  const fileContext=await browser.newContext(),filePage=await fileContext.newPage();filePage.on('pageerror',error=>errors.push(error.message));await filePage.goto(new URL('../dist/index.html',import.meta.url).href);assert.equal(await filePage.locator('#wallet').textContent(),'200');await click(filePage,'shop');assert.equal(await filePage.locator('.shop-card').count(),c.items.filter(i=>i.tier===1&&i.id!=='manor').length);results.push('file URL offline scripts');await fileContext.close();
  assert.deepEqual(errors,[]);await writeFile(new URL('./results-v3.json',import.meta.url),JSON.stringify({passed:results.length,results,errors,checkedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({passed:results.length,errors},null,2));
}finally{await browser.close();}
