import {createRequire} from 'node:module';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';import {click} from './editor-actions.mjs';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),c=JSON.parse(await readFile(new URL('../src/content/content.json',import.meta.url),'utf8')),e=require('../src/engine.js')(c);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),results=[],errors=[],out=new URL('./screenshots-v7/',import.meta.url);await mkdir(out,{recursive:true});
const state=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);
try{for(const [width,height] of [[375,844],[390,844],[430,844],[844,390],[1280,800]]){
 const ctx=await browser.newContext({viewport:{width,height}}),p=await ctx.newPage();p.on('pageerror',x=>errors.push(x.message));const seed=Object.assign(e.fresh(Date.now()),{coins:5000,xp:5000,expansion:7,maps:[0,1],map:1});
 await p.addInitScript(({key,seed})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(seed));},{key:c.storageKey,seed});await p.goto('http://127.0.0.1:4327/');await p.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','24px');for(const side of ['left','right']){let d=document.createElement('div');d.style.cssText='position:fixed;top:24px;'+side+':8px;width:64px;height:44px;background:#2226;z-index:9999;';document.body.appendChild(d);}});
 await click(p,'maps');await click(p,'lakePreview');assert.equal((await state(p)).lakeEdition,undefined);await click(p,'lakeApply');assert.equal((await state(p)).lakeEdition,7);assert.ok((await p.locator('#garden-scene').getAttribute('style')).includes('lake-v7'));results.push(width+' lake preview does not mutate, explicit adoption persists');
 await click(p,'overview');await p.screenshot({path:decodeURIComponent(new URL(width+'-before.png',out).pathname.slice(1))});
 await click(p,'harbor');await click(p,'harborWork');assert.ok(await p.locator('#modal-root').innerText().then(x=>x.includes(c.finds[0].name)));await click(p,'findLocate','[data-id="rope"]');await p.locator('.find-spot[data-id="rope"]').click();assert.ok((await state(p)).found.includes('rope'));results.push(width+' repair routes to actual map rope search');
 await click(p,'harbor');await click(p,'harborWork');const coins=(await state(p)).coins;await click(p,'harborStep','[data-answer="0"]');assert.equal((await state(p)).harbor.mistake,true);assert.equal((await state(p)).coins,coins);for(let k=0;k<c.harbor.steps.length;k++)await click(p,'harborStep','[data-answer="'+c.harbor.steps[k].answer+'"]');assert.equal((await state(p)).harbor.repaired,true);assert.equal((await state(p)).coins,coins);await click(p,'harborBonus');assert.equal((await state(p)).coins,coins+c.harbor.bonus);results.push(width+' wrong answer keeps progress, manual repair and recovery reward work');
 await click(p,'harborGift');assert.equal((await state(p)).objects.filter(x=>x.gift==='harbor').length,1);await click(p,'harborGuest');if(width===390){await click(p,'harborGuestShelter');assert.equal((await state(p)).harbor.guest,'shelter');}else{await click(p,'harborGuestWork');await click(p,'harborGuestAnswer','[data-answer="1"]');assert.equal((await state(p)).harbor.guest,'');await click(p,'harborGuestAnswer','[data-answer="0"]');assert.equal((await state(p)).harbor.guest,'ferry');}results.push(width+' unique lamp and branch-specific visitor outcome');
 await click(p,'close');await click(p,'warehouse');const lamp=(await state(p)).objects.find(x=>x.gift==='harbor');await click(p,'replace','[data-uid="'+lamp.uid+'"]');await click(p,'confirmPlace');assert.equal(await p.locator('.gift-lamp:not(.ghost)').count(),1);await click(p,'overview');await p.screenshot({path:decodeURIComponent(new URL(width+'-after.png',out).pathname.slice(1))});await click(p,'view');await p.screenshot({path:decodeURIComponent(new URL(width+'-garden.png',out).pathname.slice(1))});await p.reload();assert.equal((await state(p)).harbor.repaired,true);assert.equal(await p.locator('.gift-lamp').count(),1);assert.equal(await p.locator('.harbor-landmark.repaired').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);results.push(width+' cosmetic placement, repaired art, reload and no horizontal overflow');
 await ctx.close();

}
 const ctx=await browser.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage(),seed=Object.assign(e.fresh(Date.now()),{coins:5000,xp:5000,expansion:7,maps:[0,1],map:1,lakeEdition:6});
 e.act(seed,{type:'buy',item:'bamboo',area:1,x:65,y:90},Date.now());
 await p.addInitScript(({key,seed})=>localStorage.setItem(key,JSON.stringify(seed)),{key:c.storageKey,seed});await p.goto('http://127.0.0.1:4327/');
 await click(p,'maps');await click(p,'lakePreview');assert.equal(await p.locator('[data-action="lakeApply"]').isEnabled(),false);assert.equal((await state(p)).objects[0].pos,12);await click(p,'close');await click(p,'harbor');const money=(await state(p)).coins;await click(p,'harborPay');assert.equal((await state(p)).coins,money-c.harbor.cost+c.harbor.bonus);await click(p,'harborGift');assert.equal((await state(p)).objects.length,2);results.push('legacy conflict preview blocks activation without moving old scenery; paid repair and gift also work on legacy map');await ctx.close();
}finally{await browser.close();await writeFile(new URL('./harbor-results-v7.json',import.meta.url),JSON.stringify({passed:results.length,results,errors},null,2));}
assert.equal(errors.length,0);console.log({passed:results.length,errors});

