import {createRequire} from 'node:module';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import {click} from './editor-actions.mjs';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),c=JSON.parse(await readFile(new URL('../src/content/content.json',import.meta.url),'utf8')),e=require('../src/engine.js')(c);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),results=[],errors=[],out=new URL('./screenshots-v6/',import.meta.url);await mkdir(out,{recursive:true});
const state=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),c.storageKey);
try{for(const [width,height] of [[375,844],[390,844],[430,844],[844,390],[1280,800]]){
 const ctx=await browser.newContext({viewport:{width,height}}),p=await ctx.newPage();p.on('pageerror',x=>errors.push(x.message));const seed=e.fresh(Date.now());seed.coins=100000;seed.xp=5000;seed.expansion=7;
 await p.addInitScript(({key,seed})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(seed));},{key:c.storageKey,seed});await p.goto('http://127.0.0.1:4327/');await p.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','24px');for(const side of ['left','right']){let d=document.createElement('div');d.style.cssText='position:fixed;top:24px;'+side+':8px;width:64px;height:44px;background:#2226;z-index:9999;';document.body.appendChild(d);}});
 await click(p,'starter');assert.equal((await state(p)).objects.length,4);await click(p,'replace','[data-uid="1"]');await click(p,'confirmPlace');assert.equal((await state(p)).objects[0].pos>=0,true);results.push(width+' movable manor from starter gift');
 await click(p,'blueprints');await click(p,'blueprintStart','[data-id="tea"]');let enabled=await p.locator('[data-action="confirmBlueprint"]').isEnabled();if(!enabled){const r=await p.locator('#garden-scene').boundingBox();await p.mouse.click(r.x+r.width*.32,r.y+r.height*.50);}assert.equal(await p.locator('[data-action="confirmBlueprint"]').isEnabled(),true);const coins=(await state(p)).coins;await click(p,'confirmBlueprint');assert.equal((await state(p)).coins,coins-e.price('table')-e.price('rock'));results.push(width+' atomic blueprint uses inventory');
 await click(p,'objects');await click(p,'selectFromList','[data-uid="2"]');await click(p,'care');await click(p,'careAnswer','[data-index="0"]');assert.equal((await state(p)).careCount||0,0);for(const step of c.care.steps)await click(p,'careAnswer','[data-index="'+step.answer+'"]');assert.equal((await state(p)).careCount,1);results.push(width+' care interaction wrong answer and one-time payout');
 await click(p,'quests');await click(p,'questOpen','[data-id="neighbour0"]');await click(p,'questChoice','[data-choice="b"]');assert.equal((await state(p)).quests.neighbour0.choice,'b');await click(p,'close');await click(p,'quests');await click(p,'questOpen','[data-id="neighbour1"]');assert.match(await p.locator('.prose').textContent(),/水壶/);await click(p,'close');results.push(width+' visitor choice echoed next chapter');
 await click(p,'home');await click(p,'view');await p.screenshot({path:fileURLToPath(new URL(width+'-estate.png',out))});await click(p,'view');
 for(const id of [1,2]){await click(p,'maps');await click(p,'unlockMap','[data-id="'+id+'"]');await click(p,'visitMap','[data-id="'+id+'"]');assert.equal((await state(p)).map,id);assert.equal(await p.locator('.placed').count(),0);const find=c.finds.find(f=>f.map===id);await click(p,'finds');await click(p,'findLocate','[data-id="'+find.id+'"]');await click(p,'find','[data-id="'+find.id+'"]');assert.ok((await state(p)).found.includes(find.id));await click(p,'shop');await click(p,'tier','[data-tier="'+(id===1?2:3)+'"]');await click(p,'item','[data-item="'+(id===1?'lotus':'osmanthus')+'"]');assert.equal(await p.locator('[data-action="buyMode"]').isEnabled(),true);await click(p,'close');await click(p,'view');await p.screenshot({path:fileURLToPath(new URL(width+'-map'+id+'.png',out))});await click(p,'view');}results.push(width+' two paid maps and exclusive scenery');
 await click(p,'maps');await click(p,'visitMap','[data-id="0"]');assert.equal(await p.locator('.placed').count(),5);await p.reload();assert.equal((await state(p)).map,0);assert.equal((await state(p)).maps.length,3);assert.equal((await state(p)).careCount,1);results.push(width+' independent layouts and persistence');
 await ctx.close();
}assert.deepEqual(errors,[]);await writeFile(new URL('./journey-results-v6.json',import.meta.url),JSON.stringify({passed:results.length,results,errors},null,2));console.log({passed:results.length,errors});}finally{await browser.close();}
