import c from './content/content.json';
import {makeSample,wash,immerse,isClean,pickGrain,finishPicked,readSave,clamp,rimIntent,washGuide,canPickGrain,tiltFromDrag} from './model';
import type {Sample,Grain} from './model';
import {recordJourney,makeRecord,dailySeed,localDay} from './journey';
import type {RecordEntry} from './journey';
import {Scene,panLayout} from './render';
import {accessoryLayout,samplePoints,drawGrain,whenSpecimensReady} from './objects';
import {makeOrbit,trackOrbit} from './orbit';
import {targetPolygon} from './pick-target';
import {AudioBank} from './audio-bank';
declare global {interface Window {CREEK_AUDIO?:{[key:string]:string}}}
const $=(id:string)=>document.getElementById(id)!,copy=c.copy,app=$('app'),hint=$('hint'),modal=$('modal'),objects=$('objects');
let save=readSave(null);try{save=readSave(localStorage.getItem(c.storageKey));}catch{}
let sample:Sample|null=save.active,stage=sample?(isClean(sample,c.tuning)?'inspect':sample.phase==='loading'?'immerse':sample.phase==='inspect'?'wash':sample.phase):'shore';
let location=sample?.location||0,point=0,paused=false,motion=0,tilt=0,depth=0,scoop=0,time=0,last=0,acc=0,lastSaved=0,liftAt=0,axisX=0,axisY=0,spin=0,orbit=makeOrbit(),saveFailed=false;
let mode:'free'|'daily'|'challenge'|'replay'='free',selectedChallenge=-1,replayRecord:RecordEntry|null=null,pending:Grain|null=null,newIds:string[]=[];
let drag:{id:number;x:number;y:number;startX:number;startY:number;travel:number;mode:'scoop'|'wash'|'tilt'|'dip'|'next'|'rim';rim?:'tilt'|'dip'}|null=null;
let audioError=false,lastSound=0;const audioBank=new AudioBank(window.CREEK_AUDIO||{},c.audio.groups,c.audio.gain,()=>{audioError=true;});
const scene=new Scene($('scene') as HTMLCanvasElement);scene.reduced=save.settings.reduced||!!(typeof window.matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches);
document.documentElement.style.setProperty('--host-reserved-x',(c.layout.hostWidth+c.layout.hostOffset+c.layout.hostMargin)+'px');
$('title').textContent=c.meta.title;$('eyebrow').textContent=c.meta.eyebrow;save.settings.reduced=scene.reduced;app.classList.toggle('reduced-motion',scene.reduced);
function persist(){save.active=sample&&!sample.collected?sample:null;try{localStorage.setItem(c.storageKey,JSON.stringify(save));saveFailed=false;}catch{saveFailed=true;}}
function stopInput(){drag=null;motion=0;tilt=0;depth=0;scoop=0;spin=0;axisX=0;axisY=0;orbit=makeOrbit();audioBank.stop();}
async function startAudio(){audioError=false;await audioBank.enable();if(!save.settings.sound)audioBank.mute();}
function sound(kind:'water'|'sand'|'pick'='water'){if(paused||time-lastSound<.28)return;lastSound=time;audioBank.play(kind,kind==='pick'?.3:kind==='sand'?.45:(sample?.water||0)*(.15+motion*.6+tilt*.3+depth*.25));}

function button(label:string,fn:()=>void,parent:HTMLElement){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>fn();parent.appendChild(b);return b;}
function paragraph(text:string,parent:Element,className=''){const p=document.createElement('p');p.textContent=text;p.className=className;parent.appendChild(p);return p;}
function clear(element:HTMLElement){while(element.firstChild)element.removeChild(element.firstChild);}
let pickSignature='';
function hotspots(){const signature=[innerWidth,innerHeight,paused,stage,!!drag,motion<.08,tilt<.05,sample?.id,Math.round(scene.pose.x),Math.round(scene.pose.y),scene.pose.sy.toFixed(2),sample?.grains.map(g=>g.id+':'+g.state+':'+canPickGrain(sample!,g,c.tuning)+':'+g.x.toFixed(2)+':'+g.y.toFixed(2)).join('|')].join('/');if(signature===pickSignature&&objects.childElementCount)return;pickSignature=signature;clear(objects);if(paused||stage==='picking'||stage==='loading')return;const p=scene.pose.r>1?scene.pose:panLayout(innerWidth,innerHeight),a=accessoryLayout(innerWidth,innerHeight);
 for(const [label,x,fn] of [[copy.bottle,a.bottle,showBottle],[copy.mineralBox,a.tray,()=>showBottle(false)],[copy.journal,a.book,showJournal]] as [string,number,()=>void][]){const b=button('',fn,objects);b.className='object-target bottle-target';b.setAttribute('aria-label',label);b.style.left=x+'px';b.style.top=a.y+'px';}
 if((stage==='inspect'||stage==='wash')&&sample&&!drag&&tilt<.05&&motion<.08)for(const g of sample.grains){if(!canPickGrain(sample,g,c.tuning))continue;const b=button('',()=>pickup(g.id),objects);b.className='object-target grain-target';b.setAttribute('aria-label',copy.pickup+' '+(g.id+1));b.style.left=p.x+g.x*p.r+'px';b.style.top=p.y+g.y*p.r*p.sy+'px';const size=Math.max(44,g.size*p.r*2.2);b.style.clipPath=targetPolygon(p.x+g.x*p.r,p.y+g.y*p.r*p.sy,sample.grains.filter(v=>canPickGrain(sample!,v,c.tuning)).map(v=>({x:p.x+v.x*p.r,y:p.y+v.y*p.r*p.sy})),size);b.style.width=size+'px';b.style.height=size+'px';}
}
function render(){app.dataset.stage=stage;hint.innerHTML='<h2></h2><p></p>';const titles:{[s:string]:string}={shore:copy.pick,result:copy.result,inspect:copy.foundTitle,loading:copy.loading,immerse:copy.immerse,picking:copy.picked,wash:copy.wash},hints:{[s:string]:string}={shore:copy.scoop,result:copy.resultHint,inspect:copy.ready,loading:copy.loadingHint,immerse:copy.immerseHint,picking:pending?.gold?copy.picked:copy.mineralPicked,wash:save.settings.assist?copy.assistHint:copy.washing};hint.querySelector('h2')!.textContent=titles[stage];hint.querySelector('p')!.textContent=hints[stage];$('eyebrow').textContent=c.locations[location].name;hotspots();updateStatus();}
function updateStatus(){if(stage==='wash'&&sample){const guide=washGuide(sample,tilt),titles={recover:copy.guideRecover,settle:copy.guideSettle,rinse:copy.guideRinse,pour:copy.guidePour,refill:copy.guideRefill},details={recover:copy.guideRecoverHint,settle:copy.guideSettleHint,rinse:copy.guideRinseHint,pour:copy.guidePourHint,refill:copy.guideRefillHint};const title=hint.querySelector('h2')!,detail=hint.querySelector('p')!,summary=details[guide]+' · '+(guide==='settle'?copy.guideSettled+' '+Math.round(sample.settled*100)+'%':guide==='refill'?copy.guideWater+' '+Math.round(sample.water*100)+'%':copy.guideSand+' '+((1-sample.mud)*100).toFixed(1)+'%');if(title.textContent!==titles[guide])title.textContent=titles[guide];if(detail.textContent!==summary)detail.textContent=summary;}let text='';if(saveFailed)text=copy.saveError;else if(audioError)text=copy.muteError;else if(stage==='shore')text=scoop>=.99?copy.fullScoop:scoop>=.35?copy.smallScoop:mode==='replay'?copy.replayReady:c.locations[location].hint+' · '+copy.journalHint;else if(stage==='result'&&sample){const r=makeRecord(sample);text=r.gold+' '+copy.gold+' · '+copy.retention+' '+Math.round(r.retention*100)+'% · '+copy.clean+' '+Math.round(r.clean*100)+'% · '+(newIds.length?copy.newTechnique:copy.noNew);}else if(stage==='wash'&&sample&&!drag&&sample.grains.some(g=>canPickGrain(sample!,g,c.tuning)))text=copy.exposed;else if(stage==='inspect')text=sample?.replay?copy.replayNote:copy.bottleHint;else if(stage==='immerse')text=sample&&sample.water>.85?copy.filled:copy.immerseHint;else if(stage==='wash'&&sample)text=sample.grains.some(g=>g.state==='pan'&&g.warning>.05)?copy.warning:depth>.2?(sample.water>.85?copy.filled:copy.immerseHint):sample.water<.18?copy.refill:Math.abs(spin)>5.5?copy.orbitFast:tilt>.1?copy.orbitRest:sample.settled<.6?copy.orbitSettle:copy.orbitWash;if(sample?.practice&&!sample.replay&&stage==='wash')text=copy.tutorial+' · '+text;if(selectedChallenge>=0&&stage==='shore')text=c.challenges[selectedChallenge].hint;if(mode==='daily'&&stage==='shore')text=copy.daily+' · '+localDay()+' · '+copy.scoop;const status=$('status');if(status.textContent!==text)status.textContent=text;}
let returnFocus:HTMLElement|null=null;
function closeModal(){modal.hidden=true;paused=false;app.classList.remove('paused');last=0;render();if(returnFocus&&document.contains(returnFocus))returnFocus.focus();}
function openModal(title:string,text:string){returnFocus=document.activeElement as HTMLElement;stopInput();persist();paused=true;clear(objects);app.classList.add('paused');modal.hidden=false;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label',title);modal.innerHTML='<h2></h2><p></p><div class="modal-body"></div>';modal.querySelector('h2')!.textContent=title;modal.querySelector('p')!.textContent=text;}
function illustration(g:Grain){const canvas=document.createElement('canvas');canvas.width=240;canvas.height=160;canvas.className='discovery-art';const ctx=canvas.getContext('2d')!;ctx.translate(120,80);drawGrain(ctx,g,51);whenSpecimensReady(()=>{ctx.clearRect(-120,-80,240,160);drawGrain(ctx,g,51);});return canvas;}
function finalize(){if(!sample||!finishPicked(sample,save,c.tuning))return;newIds=recordJourney(sample,save,c.challenges);persist();}
function pickup(id:number){if(!sample||!['wash','inspect'].includes(stage)||paused)return;const g=pickGrain(sample,save,id,c.tuning);if(!g)return;pending=g;scene.flight={grain:g,start:time};stage='picking';finalize();persist();sound('pick');render();}
function showDiscovery(g:Grain,picked=false,classroom=false){
 const item=c.items[g.kind],note=item.knowledge,L=c.mineralGuide.labels;
 openModal(item.name,classroom?L.overview: picked?(sample?.replay?copy.practicePicked:g.gold?copy.picked:copy.mineralPicked):copy.collectionInfo);
 const body=modal.querySelector('.modal-body') as HTMLElement;body.className='discovery-body';body.appendChild(illustration(g));
 paragraph(note.identity+' · '+note.subtitle,body,'specimen-identity');
 for(const [label,text] of [[L.appearance,note.appearance],[L.origin,note.origin],[L.lookalike,note.lookalike],[L.use,note.use],[L.location,c.discoveryHints[g.kind]]]){const section=document.createElement('section'),h=document.createElement('h3');h.textContent=label;section.appendChild(h);paragraph(text,section);body.appendChild(section);}
 paragraph(copy.valueTitle+' · '+item.value+' · '+item.valueNote,body);paragraph(copy.valueNote,body);paragraph(L.art,body,'specimen-caption');
 const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=L.source;details.appendChild(summary);
 for(const id of note.sources){const source=c.mineralGuide.sources.find(s=>s.id===id);if(source)paragraph(source.title+' · '+source.url,details,'specimen-source');}body.appendChild(details);
 button(picked?copy.continuePick:classroom?L.browse:g.gold?copy.bottle:copy.mineralBox,picked?closeModal:classroom?showMineralGuide:()=>showBottle(g.gold),modal).focus();body.scrollTop=0;
}
function showMineralGuide(){const L=c.mineralGuide.labels;openModal(L.browse,L.overviewNote);const body=modal.querySelector('.modal-body') as HTMLElement;for(let i=8;i<c.items.length;i++){const item=c.items[i],b=button(item.name,()=>showDiscovery({id:i,kind:i,gold:false,x:0,y:0,size:.04,weight:0,state:'bottle',warning:0},false,true),body);b.className='album-row';}button(copy.backJournal,showJournal,modal).focus();}
function showBottle(goldOnly=true){const label=goldOnly?copy.bottle:copy.mineralBox,foundCount=save.album.filter(k=>(k<8)===goldOnly).length;openModal(label,(goldOnly?save.count+' '+copy.gold+' · '+save.weight.toFixed(2)+' '+copy.units+' · ':'')+foundCount+'/'+(goldOnly?8:10));const body=modal.querySelector('.modal-body')!;c.items.forEach((item,i)=>{if(item.gold!==goldOnly)return;const found=save.album.includes(i);const row=button(found?item.name:copy.unknown,()=>{if(found)showDiscovery({id:i,kind:i,gold:item.gold,x:0,y:0,size:.04,weight:0,state:'bottle',warning:0});else{openModal(copy.unknown,c.discoveryHints[i]);button(label,()=>showBottle(goldOnly),modal).focus();}},body as HTMLElement);row.className='album-row';});button(copy.close,closeModal,modal).focus();}
function journalBody(){const body=modal.querySelector('.modal-body') as HTMLElement;body.className='modal-body journal-body';return body;}
function journalBack(){button(copy.backJournal,showJournal,modal).focus();}
function showJournal(){openModal(copy.journal,copy.panCount+' '+save.pans+' · '+copy.progress+' '+save.journey.challenges.length+'/24');const body=journalBody();for(const [label,fn] of [[copy.sites,showSites],[copy.challenges,showChallenges],[copy.records,showRecords],[copy.collectionSeries,showSeries],[c.mineralGuide.labels.browse,showMineralGuide],[copy.settings,showSettings]] as [string,()=>void][]){button(label,fn,body);}if(stage==='shore'){button(copy.daily,()=>{const seed=dailySeed(localDay());location=seed%6;mode='daily';selectedChallenge=-1;replayRecord=null;closeModal();},body);paragraph(copy.dayNote,body);}else paragraph(copy.chooseAfter,body);button(copy.close,closeModal,modal).focus();}
function showSites(){openModal(copy.sites,stage==='shore'?copy.pointsHint:copy.chooseAfter);const body=journalBody();c.locations.forEach((site,i)=>{const row=button(site.name+' · '+(save.journey.sites.includes(i)?copy.complete:copy.choose),()=>{if(stage!=='shore')return;location=i;mode='free';selectedChallenge=-1;replayRecord=null;closeModal();},body);row.className='site-row';row.disabled=stage!=='shore';const image=document.createElement('span');image.className='site-thumbnail';image.style.backgroundPosition=(i%2)*100+'% '+Math.floor(i/2)*50+'%';row.insertBefore(image,row.firstChild);paragraph(site.hint,row);});journalBack();}
function showChallenges(){openModal(copy.challenges,copy.progress+' '+save.journey.challenges.length+'/24');const body=journalBody();c.challenges.forEach((challenge,i)=>{const row=button((save.journey.challenges.includes(challenge.id)?'✓ ':'')+c.locations[challenge.location].name+' · '+challenge.name,()=>{if(stage!=='shore')return;location=challenge.location;selectedChallenge=i;mode='challenge';replayRecord=null;closeModal();},body);row.disabled=stage!=='shore';paragraph(challenge.hint,row);});journalBack();}
function showRecords(){openModal(copy.records,copy.clean+' '+Math.round(save.journey.bestClean*100)+'% · '+copy.largest+' '+save.journey.largest.toFixed(2)+' '+copy.units+' · '+copy.noLoss+' '+save.journey.noLoss);const body=journalBody();if(!save.journey.history.length)paragraph(copy.historyEmpty,body);save.journey.history.forEach((r,i)=>{const row=button(c.locations[r.location].name+' · '+r.gold+' '+copy.gold+' · '+copy.retention+' '+Math.round(r.retention*100)+'%'+(r.replay?' · '+copy.replay:''),()=>{if(stage!=='shore')return;replayRecord=r;location=r.location;point=r.point;mode='replay';selectedChallenge=-1;closeModal();},body);row.disabled=stage!=='shore';paragraph(r.date+' · '+copy.clean+' '+Math.round(r.clean*100)+'% · '+copy.replay+' #'+(i+1),row);});paragraph(copy.replayNote,body);journalBack();}
function showSeries(){openModal(copy.collectionSeries,save.album.length+'/18');const body=journalBody();c.collections.forEach(series=>{const found=series.sites?save.journey.sites.length:series.kinds.filter(k=>save.album.includes(k)).length,total=series.sites||series.kinds.length;paragraph(series.name+' · '+found+'/'+total,body,'series-row');});journalBack();}
function showSettings(){openModal(copy.settings,copy.settingsNote);const body=journalBody();paragraph(c.audio.credits,body);button(save.settings.sound?copy.soundOn:copy.soundOff,()=>{save.settings.sound=!save.settings.sound;if(save.settings.sound)void startAudio().then(showSettings);else{audioBank.mute();stopInput();showSettings();}persist();},body);button(save.settings.reduced?copy.reduceOn:copy.reduceOff,()=>{save.settings.reduced=!save.settings.reduced;scene.reduced=save.settings.reduced;app.classList.toggle('reduced-motion',scene.reduced);persist();showSettings();},body);button(save.settings.assist?copy.assistOn:copy.assistOff,()=>{save.settings.assist=!save.settings.assist;persist();showSettings();},body);journalBack();}
function local(x:number,y:number){const p=stage==='shore'||scene.pose.r<=1?panLayout(innerWidth,innerHeight):scene.pose;return{p,x:(x-p.x)/p.r,y:(y-p.y)/(p.r*p.sy)};}
function down(x:number,y:number,id:number,target:EventTarget|null){if(paused||stage==='loading'||stage==='picking')return;if(drag)return;if((target as HTMLElement).closest('button,#modal'))return;const n=local(x,y);if(Math.hypot(n.x,n.y)>1.08)return;const action=stage==='result'?'next':stage==='shore'?'scoop':stage==='immerse'?'dip':(n.y<-.62||n.y>.62&&Math.abs(n.x)<.7)?'rim':'wash';if(action==='scoop'){const points=samplePoints(innerWidth,innerHeight);point=mode==='replay'&&replayRecord?replayRecord.point:points.reduce((best,p,i)=>Math.hypot(x-p.x,y-p.y)<Math.hypot(x-points[best].x,y-points[best].y)?i:best,0);}tilt=0;depth=0;drag={id,x,y,startX:x,startY:y,travel:0,mode:action,rim:n.y<0?'dip':'tilt'};if(save.settings.sound&&!audioBank.enabled)void startAudio();if(action==='wash'||action==='rim'){orbit=makeOrbit();trackOrbit(orbit,n.x,n.y,performance.now());}}
function move(x:number,y:number,id:number){if(!drag||drag.id!==id)return;const distance=Math.hypot(x-drag.x,y-drag.y);drag.travel+=distance;if(drag.mode==='rim'){const intent=rimIntent(x-drag.startX,y-drag.startY);if(!intent)return;drag.mode=intent==='rim'?drag.rim!:'wash';}if(drag.mode==='scoop'){scoop=clamp(scoop+distance/(Math.min(innerWidth,innerHeight)*c.tuning.scoopTravel),0,1);sound('sand');}else if(drag.mode==='wash'){const n=local(x,y);trackOrbit(orbit,n.x,n.y,performance.now());spin=orbit.speed;const circle=clamp(Math.abs(spin)/3,0,1);motion=clamp(circle*.85*(.4+.6*orbit.quality)+(save.settings.assist?Math.min(.6,distance/n.p.r*3):distance/n.p.r*.15),0,1);axisX=clamp(n.x,-1,1)*Math.max(circle,motion)*.65;axisY=clamp(n.y,-1,1)*Math.max(circle,motion)*.65;}else if(drag.mode==='tilt'){const p=panLayout(innerWidth,innerHeight);tilt=tiltFromDrag(y-drag.startY,p.r);}else if(drag.mode==='dip'){depth=clamp((y-drag.startY-6)/(Math.min(innerHeight,innerWidth)*.22),0,1);}drag.x=x;drag.y=y;}
function up(id:number,cancel=false){if(!drag||drag.id!==id)return;const complete=drag.mode==='scoop'&&scoop>=.35&&!cancel,next=drag.mode==='next'&&drag.travel<12&&!cancel,dipped=drag.mode==='dip'&&sample&&sample.water>.5&&!cancel,amount=mode==='replay'&&replayRecord?replayRecord.amount:Math.round(scoop*20)/20,pit={x:drag.x/innerWidth,y:drag.y/innerHeight,amount:scoop},inertia=drag.mode==='wash'&&stage!=='inspect'&&!cancel?motion:0,keepSpin=cancel?0:spin;stopInput();motion=inertia;spin=keepSpin;if(next){sample=null;stage='shore';if(mode==='replay')mode='free';persist();render();}else if(complete){const seed=mode==='daily'?dailySeed(localDay()):mode==='challenge'&&selectedChallenge>=0?c.challenges[selectedChallenge].seed:mode==='replay'&&replayRecord?replayRecord.seed:(Date.now()^Math.floor(Math.random()*0x7fffffff))>>>0;sample=makeSample(seed,location,c.locations[location],mode==='replay'&&replayRecord?replayRecord.practice:save.pans===0&&mode==='free',point,clamp(amount,.35,1),mode==='replay');if(mode==='daily'||mode==='challenge'){sample.claimKey=(mode==='daily'?'daily:'+localDay():'challenge:'+seed)+':'+location+':'+point;if((save.claims[sample.claimKey]||0)&(1<<Math.round((sample.amount-.35)/.05)))sample.replay=true;}if(save.ids.includes(sample.id))sample.replay=true;sample.phase='loading';sample.water=0;stage='loading';liftAt=time;scene.pits.push(pit);scene.pits=scene.pits.slice(-12);newIds=[];persist();render();}else if(dipped&&sample){stage='wash';sample.phase='wash';persist();render();}else{persist();if(stage==='inspect')hotspots();}}
if(typeof PointerEvent!=='undefined'){app.addEventListener('pointerdown',e=>{if(e.button!==0)return;down(e.clientX,e.clientY,e.pointerId,e.target);if(drag&&drag.id===e.pointerId){try{app.setPointerCapture(e.pointerId);}catch{}}});app.addEventListener('pointermove',e=>move(e.clientX,e.clientY,e.pointerId));app.addEventListener('pointerup',e=>up(e.pointerId));app.addEventListener('pointercancel',e=>up(e.pointerId,true));app.addEventListener('lostpointercapture',e=>up(e.pointerId,true));}else{app.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const t=e.touches[0];down(t.clientX,t.clientY,t.identifier,e.target);},{passive:true});app.addEventListener('touchmove',e=>{if(!drag)return;const t=Array.from(e.touches).find(t=>t.identifier===drag!.id);if(t){move(t.clientX,t.clientY,t.identifier);e.preventDefault();}},{passive:false});app.addEventListener('touchend',e=>{for(const t of Array.from(e.changedTouches))up(t.identifier);});app.addEventListener('touchcancel',()=>{if(drag)up(drag.id,true);});app.addEventListener('mousedown',e=>{if(e.button===0)down(e.clientX,e.clientY,-1,e.target);});window.addEventListener('mousemove',e=>move(e.clientX,e.clientY,-1));window.addEventListener('mouseup',()=>up(-1));}
let raf=0,drawAt=0,pausedDrawn=false,pickClock=0,windowMs=0,windowFrames=0,slowWindows=0;
function frame(ms:number){if(document.hidden){raf=0;return;}const elapsed=last?ms-last:0,dt=Math.min(.05,elapsed/1000);last=ms;if(!paused){pausedDrawn=false;time+=dt;if(stage==='loading'&&time-liftAt>1.2&&sample){stage='immerse';sample.phase='immerse';render();}if(stage==='picking'&&scene.flight&&time-scene.flight.start>.6){scene.flight=null;stage=sample?.collected?'result':sample&&isClean(sample,c.tuning)?'inspect':'wash';const picked=pending;pending=null;if(picked)showDiscovery(picked,true);}motion*=Math.exp(-dt*2);spin*=Math.exp(-dt*1.8);axisX*=Math.exp(-dt*5);axisY*=Math.exp(-dt*5);acc+=dt;while(acc>=1/60){if(sample){if(depth>.05&&(stage==='wash'||stage==='immerse'))immerse(sample,1/60,depth);else if(stage==='wash'||(stage==='inspect'&&drag))wash(sample,1/60,motion,tilt,c.locations[location],c.tuning);}acc-=1/60;}if(stage==='wash'&&sample&&isClean(sample,c.tuning)){stopInput();stage='inspect';sample.phase='inspect';finalize();if(sample.collected)stage='result';persist();render();}if(motion>.05||tilt||depth)sound();if(time-lastSaved>3){persist();lastSaved=time;}updateStatus();pickClock+=dt;if(pickClock>.2){hotspots();pickClock=0;}if(elapsed>0&&elapsed<250){windowMs+=elapsed;windowFrames++;if(windowMs>2000){slowWindows=windowMs/windowFrames>40?slowWindows+1:0;if(slowWindows>=2&&!scene.low){scene.low=true;scene.resize(innerWidth,innerHeight);}windowMs=0;windowFrames=0;}}}
 if(ms-drawAt>=32&&(!paused||!pausedDrawn)){scene.draw(time,c.locations[location],sample,stage,motion,tilt,scoop,depth,drag?{x:drag.x,y:drag.y}:null,axisX,axisY,save.count,spin,save.album.filter(k=>k>=8).length);drawAt=ms;pausedDrawn=paused;}raf=requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{stopInput();scene.resize(innerWidth,innerHeight);hotspots();pausedDrawn=false;});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopInput();persist();paused=true;if(raf)cancelAnimationFrame(raf);raf=0;}else{last=0;if(modal.hidden){openModal(copy.paused,copy.pausedNote);button(copy.resume,closeModal,modal).focus();}if(!raf)raf=requestAnimationFrame(frame);}});window.addEventListener('pagehide',()=>{stopInput();persist();if(raf)cancelAnimationFrame(raf);raf=0;});window.addEventListener('pageshow',()=>{last=0;if(!raf)raf=requestAnimationFrame(frame);});
document.addEventListener('keydown',e=>{if(modal.hidden)return;if(e.key==='Escape'){closeModal();return;}if(e.key==='Tab'){const nodes=Array.from(modal.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
scene.resize(innerWidth,innerHeight);if(sample&&stage==='inspect'){finalize();if(sample.collected)stage='result';}render();raf=requestAnimationFrame(frame);

