export class AudioBank {
 context:AudioContext|null=null;enabled=false;epoch=0;buffers=new Map<string,AudioBuffer>();pending=new Map<string,Promise<AudioBuffer>>();voices=new Set<{source:AudioBufferSourceNode;gain:GainNode}>();last:{[key:string]:number}={};
 constructor(public data:{[key:string]:string},public groups:{[key:string]:string[]},public volume:number,public failed:()=>void,public factory:()=>AudioContext=()=>{const A=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!A)throw Error('audio unavailable');return new A();}){}
 async enable():Promise<void>{const token=++this.epoch;try{if(!this.context)this.context=this.factory();await this.context.resume();if(token!==this.epoch)return;if(this.context.state!=='running')throw Error('audio suspended');for(const id of Object.keys(this.data)){await this.decode(id);if(token!==this.epoch)return;}this.enabled=true;}catch{if(token===this.epoch){this.enabled=false;this.failed();}}}
 decode(id:string):Promise<AudioBuffer>{const cached=this.buffers.get(id);if(cached)return Promise.resolve(cached);const waiting=this.pending.get(id);if(waiting)return waiting;const request=new Promise<AudioBuffer>((resolve,reject)=>{try{if(!this.context||!this.data[id])throw Error('missing audio');const raw=atob(this.data[id]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);this.context.decodeAudioData(bytes.buffer,resolve,reject);}catch(error){reject(error);}}).then(buffer=>{this.buffers.set(id,buffer);this.pending.delete(id);return buffer;},error=>{this.pending.delete(id);throw error;});this.pending.set(id,request);return request;}
 play(kind:string,strength:number):void{const ctx=this.context,ids=this.groups[kind];if(!this.enabled||!ctx||ctx.state!=='running'||!ids?.length||this.voices.size>=6)return;const i=((this.last[kind]??-1)+1)%ids.length;this.last[kind]=i;const buffer=this.buffers.get(ids[i]);if(!buffer)return;const source=ctx.createBufferSource(),gain=ctx.createGain(),now=ctx.currentTime;source.buffer=buffer;source.playbackRate.value=.98+Math.random()*.04;const level=this.volume*Math.max(0,Math.min(1,strength));gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(level,now+.015);gain.gain.setValueAtTime(level,now+Math.max(.02,buffer.duration-.07));gain.gain.linearRampToValueAtTime(0,now+buffer.duration);source.connect(gain);gain.connect(ctx.destination);const voice={source,gain};this.voices.add(voice);source.onended=()=>{this.voices.delete(voice);source.disconnect();gain.disconnect();};source.start();}
 stop():void{this.epoch++;for(const v of this.voices){try{v.source.stop();}catch{}v.source.disconnect();v.gain.disconnect();}this.voices.clear();}
 mute():void{this.stop();this.enabled=false;}
}
