import type {Sample,Save} from './model';
export interface RecordEntry {id:string;seed:number;location:number;point:number;amount:number;replay:boolean;practice:boolean;gold:number;retention:number;clean:number;largest:number;cycles:number;rescued:number;coarse:number;leaves:number;maxTilt:number;settled:number;kinds:number[];seconds:number;date:string}
export interface Journey {history:RecordEntry[];challenges:string[];sites:number[];points:string[];bestClean:number;largest:number;noLoss:number}
export interface Condition {metric:string;min?:number;max?:number}
export interface Challenge {id:string;location:number;name:string;hint:string;conditions:Condition[];seed:number}
export function emptyJourney():Journey{return{history:[],challenges:[],sites:[],points:[],bestClean:0,largest:0,noLoss:0};}
export function localDay(date=new Date()):string{return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');}
export function dailySeed(day:string):number{let n=2166136261;for(let i=0;i<day.length;i++){n^=day.charCodeAt(i);n=Math.imul(n,16777619);}return n>>>0;}
export function makeRecord(s:Sample):RecordEntry{const gold=s.grains.filter(g=>g.gold),kept=gold.filter(g=>g.state==='bottle');return{id:s.id,seed:s.seed,location:s.location,point:s.point,amount:s.amount,replay:s.replay,practice:s.practice,gold:kept.length,retention:gold.length?kept.length/gold.length:0,clean:1-s.mud,largest:kept.reduce((m,g)=>Math.max(m,g.weight),0),cycles:s.cycles,rescued:kept.filter(g=>g.warned).length,coarse:s.initialCoarse-s.coarse,leaves:s.initialLeaves-s.leaves,maxTilt:s.maxTilt,settled:s.maxSettled,kinds:s.grains.filter(g=>g.state==='bottle').map(g=>g.kind),seconds:s.elapsed,date:localDay()};}
export function challengeMet(challenge:Challenge,r:RecordEntry,j:Journey):boolean{if(challenge.location!==r.location)return false;const prior=j.history.filter(h=>h.id===r.id);const metrics:{[key:string]:number}={sample:1,gold:r.gold,clean:r.clean,retention:r.retention,cycles:r.cycles,rescued:r.rescued,coarse:r.coarse,leaves:r.leaves,maxTilt:r.maxTilt,settled:r.settled,amount:r.amount,fine:r.kinds.filter(k=>k===0).length,flake:r.kinds.filter(k=>k===2||k===6).length,heavy:r.kinds.filter(k=>k===7).length,mica:r.kinds.filter(k=>k===16).length,mineral:r.kinds.filter(k=>k>=8).length,points:new Set(j.points.filter(p=>p.startsWith(r.location+':')).concat(r.location+':'+r.point)).size,improved:r.replay&&prior.length?r.retention-Math.max(...prior.map(h=>h.retention)):0};return challenge.conditions.every(c=>Number.isFinite(metrics[c.metric])&&(c.min===undefined||metrics[c.metric]>=c.min)&&(c.max===undefined||metrics[c.metric]<=c.max));}
export function recordJourney(s:Sample,save:Save,challenges:Challenge[]):string[]{const j=save.journey,r=makeRecord(s),newIds=challenges.filter(c=>!j.challenges.includes(c.id)&&challengeMet(c,r,j)).map(c=>c.id);j.challenges.push(...newIds);j.history.unshift(r);j.history=j.history.slice(0,20);if(!s.replay){if(!j.sites.includes(s.location))j.sites.push(s.location);const point=s.location+':'+s.point;if(!j.points.includes(point))j.points.push(point);j.bestClean=Math.max(j.bestClean,r.clean);j.largest=Math.max(j.largest,r.largest);if(r.gold&&r.retention===1)j.noLoss++;}return newIds;}
export function readJourney(value:unknown):Journey{const j=emptyJourney(),v=value as Partial<Journey>|null;if(!v)return j;j.challenges=Array.isArray(v.challenges)?v.challenges.filter(x=>typeof x==='string').slice(0,24):[];j.sites=Array.isArray(v.sites)?v.sites.filter(x=>Number.isInteger(x)&&x>=0&&x<6):[];j.points=Array.isArray(v.points)?v.points.filter(x=>typeof x==='string'&&/^[0-5]:[0-2]$/.test(x)).slice(0,18):[];for(const key of ['bestClean','largest','noLoss'] as const)if(Number.isFinite(v[key])&&v[key]!>=0)j[key]=v[key]!;j.history=Array.isArray(v.history)?v.history.filter(r=>r&&typeof r.id==='string'&&Number.isInteger(r.seed)&&Number.isInteger(r.location)&&r.location>=0&&r.location<6&&Number.isInteger(r.point)&&r.point>=0&&r.point<3&&Array.isArray(r.kinds)&&r.kinds.every(k=>Number.isInteger(k)&&k>=0&&k<18)&&['amount','gold','retention','clean','largest','cycles','rescued','coarse','leaves','maxTilt','settled','seconds'].every(k=>Number.isFinite((r as unknown as {[k:string]:number})[k]))).slice(0,20):[];return j;}
