import {shimmer,reeds} from './atmosphere';
import type {Sample,Location} from './model';
import {rng,clamp,canPickGrain} from './model';
import type {Grain} from './model';
import {accessoryLayout,samplePoints,drawJournal,drawGrain} from './objects';
import C from './content/content.json';
import {EnvironmentMotion} from './environment-motion';
import {makeSlosh,stepSlosh} from './slosh';
import {makeSediment,stepSediment,GRID} from './sediment';
export function panLayout(w:number,h:number){return{x:w*.5,y:h>w?h*.54:h*.55,r:Math.min(w*.43,h*.33),sy:.77};}
export class Scene{
 low=false;reduced=false;pose=panLayout(1,1);visualTilt=0;visualDepth=0;visualX=0;visualY=0;siteId='';requestedSite='shallows';pits:{x:number;y:number;amount:number}[]=[];flight:{grain:Grain;start:number}|null=null;sediment=makeSediment();sampleId='';mask=document.createElement('canvas');layer=document.createElement('canvas');sedimentClock=0;waterAngle=0;sandAngle=0;waterSpin=0;environment=new EnvironmentMotion();slosh=makeSlosh();lastTime=0;accumulator=0;lastStage='shore';entered=0;g:CanvasRenderingContext2D;w=1;h=1;dpr=1;back:HTMLCanvasElement|null=null;creek=new Image();pan=new Image();sandImage=new Image();sand:{x:number;y:number;r:number;shade:number;angle:number}[]=[];
 constructor(public canvas:HTMLCanvasElement){this.g=canvas.getContext('2d')!;this.mask.width=GRID;this.mask.height=GRID;this.layer.width=512;this.layer.height=512;this.creek.onload=()=>{this.back=null;};this.creek.src=C.visuals.creek;this.pan.src=C.visuals.pan;this.sandImage.src=C.visuals.sand;const r=rng(5831);for(let i=0;i<2600;i++){const a=r()*6.28,d=Math.sqrt(r())*.82;this.sand.push({x:Math.cos(a)*d,y:Math.sin(a)*d,r:.0015+r()**3*.014,shade:Math.floor(r()*7),angle:r()*6.28});}}
 drawBottle(totalGold:number,minerals=0){const g=this.g,w=this.w,h=this.h;const accessories=accessoryLayout(w,h),bx=accessories.bottle,by=accessories.y,bw=25,bh=56;g.save();g.translate(bx,by);g.fillStyle='rgba(198,228,209,0.165)';g.strokeStyle='rgba(220,234,214,0.612)';g.lineWidth=1.4;g.beginPath();g.moveTo(-7,-bh*.55);g.lineTo(-7,-bh*.32);g.quadraticCurveTo(-bw*.5,-bh*.2,-bw*.5,0);g.lineTo(-bw*.5,bh*.42);g.quadraticCurveTo(0,bh*.57,bw*.5,bh*.42);g.lineTo(bw*.5,0);g.quadraticCurveTo(bw*.5,-bh*.2,7,-bh*.32);g.lineTo(7,-bh*.55);g.closePath();g.fill();g.stroke();g.fillStyle='#927244';g.fillRect(-9,-bh*.65,18,8);g.fillStyle='#e2bc64';for(let i=0;i<Math.min(36,totalGold);i++)g.fillRect(-8+(i*7%17),bh*.36-Math.floor(i/7)*3,2,2);g.strokeStyle='rgba(255,251,234,0.533)';g.beginPath();g.moveTo(-8,-5);g.lineTo(-8,18);g.stroke();g.restore();drawJournal(g,w,h);g.save();g.translate(accessories.tray,accessories.y+4);g.fillStyle='rgba(32,45,35,0.8)';g.strokeStyle='rgba(143,151,115,0.467)';g.lineWidth=3;g.beginPath();g.ellipse(0,0,28,17,-.18,0,Math.PI*2);g.fill();g.stroke();for(let i=0;i<Math.min(4,minerals);i++){g.fillStyle=C.items[8+i*2].color;g.beginPath();g.ellipse(-15+i*9,Math.sin(i*4)*5,4,3,i,0,Math.PI*2);g.fill();}g.restore();g.font='11px sans-serif';g.textAlign='center';g.fillStyle='#e1ddbd';g.fillText(C.copy.bottle,accessories.bottle,accessories.y+48);}
 resize(w:number,h:number){this.w=w;this.h=h;this.dpr=Math.min(devicePixelRatio||1,this.low?1:1.5,Math.sqrt(1500000/(w*h)));this.canvas.width=w*this.dpr;this.canvas.height=h*this.dpr;this.back=null;}
 background(site:Location){const c=document.createElement('canvas');const scaleLimit=Math.min(1,1024/Math.max(this.w,this.h));c.width=Math.max(1,Math.round(this.w*scaleLimit));c.height=Math.max(1,Math.round(this.h*scaleLimit));const g=c.getContext('2d')!;g.fillStyle='#455247';g.fillRect(0,0,c.width,c.height);if(this.creek.complete&&this.creek.naturalWidth){const sw=this.creek.width,sh=this.creek.height,scale=Math.max(c.width/sw,c.height/sh),dw=sw*scale,dh=sh*scale;g.drawImage(this.creek,(c.width-dw)/2,(c.height-dh)/2,dw,dh);}this.siteId=site.id;this.back=c;}

 draw(time:number,site:Location,s:Sample|null,stage:string,motion:number,tilt:number,scoop:number,depth:number,cursor:{x:number;y:number}|null=null,axisX=0,axisY=0,totalGold=0,spin=0,totalMinerals=0){const g=this.g,w=this.w,h=this.h;g.setTransform(this.dpr,0,0,this.dpr,0,0);if(this.requestedSite!==site.id){this.requestedSite=site.id;this.creek.src=C.locations.find(l=>l.id===site.id)!.image;this.pits=[];}if(!this.back||(this.siteId!==site.id&&this.creek.complete&&this.creek.naturalWidth))this.background(site);if(s&&s.id!==this.sampleId){this.sediment=makeSediment();this.sampleId=s.id;this.waterAngle=0;this.sandAngle=0;this.waterSpin=0;stepSediment(this.sediment,.05,0,0,0,s.mud);}const dt=Math.max(0,Math.min(.05,time-this.lastTime));this.lastTime=time;this.waterSpin+=(spin-this.waterSpin)*(1-Math.exp(-dt*3.5));this.waterAngle+=this.waterSpin*dt*.32;this.sandAngle+=this.waterSpin*dt*.11;this.accumulator+=dt;while(this.accumulator>=1/60){stepSlosh(this.slosh,1/60,axisX,axisY,tilt);this.accumulator-=1/60;}this.sedimentClock+=dt;if(s&&this.sedimentClock>=.05){stepSediment(this.sediment,.05,this.slosh.vx,this.slosh.vy,tilt,s.mud);this.sedimentClock=0;}if(stage!==this.lastStage){this.lastStage=stage;this.entered=time;}const locationIndex=C.locations.findIndex(l=>l.id===site.id),live=this.environment.draw(this.creek,{x:0,y:0,w:this.creek.naturalWidth||1024,h:this.creek.naturalHeight||1536},C.environmentMotion[locationIndex],time,this.low,this.reduced);if(this.canvas.dataset.environment!==this.environment.mode)this.canvas.dataset.environment=this.environment.mode;g.drawImage(this.back!,0,0,w,h);const imageW=this.creek.naturalWidth||1024,imageH=this.creek.naturalHeight||1536,bgScale=Math.max(w/imageW,h/imageH),left=(w-imageW*bgScale)/2,top=(h-imageH*bgScale)/2;if(live)g.drawImage(live,left,top,imageW*bgScale,imageH*bgScale);g.save();g.beginPath();C.locations[locationIndex].waterEdge.forEach(([x,y],i)=>{if(i)g.lineTo(left+x*imageW*bgScale,top+y*imageH*bgScale);else g.moveTo(left+x*imageW*bgScale,top+y*imageH*bgScale);});g.closePath();g.clip();shimmer(g,w,h,h*.12,w*C.atmosphere.sun,time*(this.reduced?.25:1),C.atmosphere.strength,true,this.low);g.restore();reeds(g,w,h,time,C.atmosphere.reeds,this.low,this.reduced);const p=panLayout(w,h);
 const vignette=g.createLinearGradient(0,0,0,h);vignette.addColorStop(0,'rgba(19,37,26,0.4)');vignette.addColorStop(.22,'rgba(19,37,26,0.0)');vignette.addColorStop(.65,'rgba(19,37,26,0.0)');vignette.addColorStop(1,'rgba(7,24,15,0.851)');g.fillStyle=vignette;g.fillRect(0,0,w,h);
 if(stage==='shore'){for(const pit of this.pits){const x=pit.x*w,y=pit.y*h;g.save();g.translate(x,y);g.scale(1,.42);const shadow=g.createRadialGradient(-3,-4,2,0,0,26*pit.amount);shadow.addColorStop(0,'rgba(26,32,26,0.69)');shadow.addColorStop(.7,'rgba(64,62,41,0.4)');shadow.addColorStop(1,'rgba(187,170,114,0.0)');g.fillStyle=shadow;g.beginPath();g.arc(0,0,28*pit.amount,0,Math.PI*2);g.fill();g.restore();}samplePoints(w,h).forEach((point,i)=>{g.strokeStyle='rgba(230,223,173,0.333)';g.lineWidth=1;g.beginPath();g.ellipse(point.x,point.y,24+Math.sin(time*.7+i)*2,9,0,0,Math.PI*2);g.stroke();g.font='11px sans-serif';g.fillStyle='#f2ead1';g.textAlign='center';g.shadowColor='#172019';g.shadowBlur=5;g.fillText(C.locations.find(l=>l.id===site.id)!.points[i],point.x,point.y+26);g.shadowBlur=0;});this.drawBottle(totalGold,totalMinerals);if(scoop>0&&cursor){const x=cursor.x,y=cursor.y;g.save();g.translate(x,y);g.rotate(-.45);g.shadowColor='rgba(19,41,30,0.533)';g.shadowBlur=9;g.shadowOffsetY=6;const wood=g.createLinearGradient(0,0,12,0);wood.addColorStop(0,'#694b2c');wood.addColorStop(.45,'#b1945b');wood.addColorStop(1,'#4b3c2b');g.fillStyle=wood;g.fillRect(-5,15,10,105);const steel=g.createLinearGradient(-30,-20,30,20);steel.addColorStop(0,'#dddac5');steel.addColorStop(.4,'#898b78');steel.addColorStop(1,'#343f37');g.fillStyle=steel;g.beginPath();g.moveTo(-26,-35);g.quadraticCurveTo(-37,14,-15,28);g.quadraticCurveTo(0,36,15,28);g.quadraticCurveTo(37,14,26,-35);g.closePath();g.fill();g.shadowBlur=0;for(let i=0;i<130*scoop;i++){const a=this.sand[i];g.fillStyle=['#9b8a63','#d3bd91','#665f47','#bbaa81'][i%4];g.fillRect(a.x*28,a.y*28-5,2,2);}g.restore();g.strokeStyle='rgba(233,219,163,0.467)';g.lineWidth=1;g.beginPath();g.ellipse(x,y,45+scoop*16,15+scoop*8,0,0,6.28);g.stroke();}return;}
 if(!s)return;g.save();const rise=stage==='loading'&&!this.reduced?Math.max(0,1-(time-this.entered)/.55):0;const response=1-Math.exp(-dt*9);this.visualTilt+=(tilt-this.visualTilt)*response;this.visualDepth+=(depth-this.visualDepth)*response;this.visualX+=(axisX-this.visualX)*response;this.visualY+=(axisY-this.visualY)*response;const lean=this.visualTilt,px=p.x+(this.reduced?0:this.visualX*14),py=p.y+(this.reduced?0:this.visualY*9)+lean*p.r*.48+rise*rise*h*.35+this.visualDepth*h*.13,sy=p.sy-lean*.38;this.pose={x:px,y:py,r:p.r,sy};g.translate(px,py);g.scale(1,sy);g.rotate(this.visualX*.025);g.shadowColor='rgba(7,22,15,0.816)';g.shadowBlur=22;g.shadowOffsetY=23;g.fillStyle='#17201b';g.beginPath();g.ellipse(0,0,p.r*.97,p.r*.97,0,0,6.28);g.fill();g.shadowBlur=0;g.shadowOffsetY=0;
 if(this.pan.complete&&this.pan.naturalWidth)g.drawImage(this.pan,-p.r*1.055,-p.r*1.055,p.r*2.11,p.r*2.11);else{g.fillStyle='#42453b';g.beginPath();g.arc(0,0,p.r,0,6.28);g.fill();}
 g.save();g.beginPath();g.arc(0,0,p.r*.99,0,6.28);g.clip();
 for(const a of s.grains){if(a.state!=='pan'||stage==='loading')continue;g.save();g.translate(a.x*p.r,a.y*p.r);drawGrain(g,a,a.size*p.r,time);g.restore();}
 if(s.mud>.008&&this.sandImage.complete&&this.sandImage.naturalWidth){const mask=this.mask.getContext('2d')!,layer=this.layer.getContext('2d')!;mask.clearRect(0,0,GRID,GRID);for(let i=0;i<this.sediment.density.length;i++){const density=this.sediment.density[i];if(density<.004)continue;mask.fillStyle=`rgba(255,255,255,${Math.min(1,density*2.4*s.amount)})`;mask.fillRect(i%GRID,Math.floor(i/GRID),1,1);}layer.clearRect(0,0,512,512);layer.globalCompositeOperation='source-over';const tex=this.sandImage;for(let row=0;row<32;row++){const yy=row/32,offset=Math.sin(yy*15+time*3)*motion*3+this.slosh.sandX*64;layer.drawImage(tex,0,yy*tex.height,tex.width,tex.height/32,offset,yy*512+this.slosh.sandY*30,512,17);}layer.globalCompositeOperation='destination-in';layer.drawImage(this.mask,0,0,512,512);layer.globalCompositeOperation='source-over';g.save();g.rotate(this.sandAngle);g.globalAlpha=stage==='loading'?clamp((time-this.entered)/1.15,0,1):1;g.drawImage(this.layer,-p.r,-p.r,p.r*2,p.r*2);g.restore();
 for(const grain of this.sand){if(grain.r<.009)continue;const x=grain.x*Math.cos(this.sandAngle)-grain.y*Math.sin(this.sandAngle)+this.slosh.sandX,y=grain.x*Math.sin(this.sandAngle)+grain.y*Math.cos(this.sandAngle)+this.slosh.sandY;const ix=Math.floor((x+1)*.5*GRID),iy=Math.floor((y+1)*.5*GRID);if(ix<0||ix>=GRID||iy<0||iy>=GRID||this.sediment.density[iy*GRID+ix]<.2)continue;g.fillStyle=['#b7a47c','#72654d','#958765','#c3b89b','#4c4c39','#857553','#c9c3aa'][grain.shade];g.beginPath();g.ellipse(x*p.r+Math.sin(time*4+grain.angle)*motion*3,y*p.r,grain.r*p.r,grain.r*p.r*.6,grain.angle+time*motion*.3,0,6.28);g.fill();}}
 for(const a of s.grains){if(!canPickGrain(s,a,C.tuning)||stage==='loading')continue;g.save();g.translate(a.x*p.r,a.y*p.r);drawGrain(g,a,a.size*p.r,time);g.restore();}
 for(let i=0;i<Math.ceil(s.coarse*3);i++){const a=i*2.399,rr=p.r*(.3+(i%3)*.17),size=p.r*(.09+(i%2)*.02),yy=Math.sin(a)*rr+(s.initialCoarse-s.coarse)*p.r*.2;g.save();g.translate(Math.cos(a)*rr,yy);drawGrain(g,{id:i,kind:17,gold:false,x:0,y:0,size:.1,weight:0,state:'pan',warning:0},size);g.restore();}
 for(let i=0;i<Math.ceil(s.leaves);i++){const a=i*2.399+this.waterAngle*.3;g.save();g.translate(Math.cos(a)*p.r*.55,Math.sin(a)*p.r*.55);g.rotate(a);g.fillStyle=i%2?'rgba(103,81,45,0.733)':'rgba(140,118,59,0.733)';g.beginPath();g.ellipse(0,0,p.r*.1,p.r*.04,0,0,Math.PI*2);g.fill();g.strokeStyle='rgba(179,160,90,0.533)';g.beginPath();g.moveTo(-p.r*.1,0);g.lineTo(p.r*.1,0);g.stroke();g.restore();}
 g.save();const surfaceRadius=p.r*(.3+.6*Math.sqrt(s.water)),surfaceY=this.slosh.y*p.r*.25+lean*(p.r-surfaceRadius)*.9;g.beginPath();g.arc(this.slosh.x*p.r*.2,surfaceY,surfaceRadius,0,Math.PI*2);g.clip();g.globalAlpha=Math.min(1,s.water*3);
 if(this.back){g.save();g.globalAlpha=(.035+motion*.025)*Math.min(1,s.water*3);g.drawImage(this.back,0,0,this.back.width,this.back.height,-p.r+this.slosh.x*p.r*.3,-p.r+this.slosh.y*p.r*.3,p.r*2,p.r*2);g.restore();}
 g.fillStyle='rgba(143,119,75,'+(s.mud*(1-s.settled)*.3)+')';g.fillRect(-p.r,-p.r,p.r*2,p.r*2);const sheen=g.createLinearGradient(-p.r,-p.r,p.r,p.r);sheen.addColorStop(0,'rgba(217,232,197,0.188)');sheen.addColorStop(.4,'rgba(139,187,170,0.031)');sheen.addColorStop(1,'rgba(14,50,45,0.208)');g.fillStyle=sheen;g.fillRect(-p.r,-p.r,p.r*2,p.r*2);
 for(let i=0;i<7;i++){const phase=(time*(.2+motion*.4)+i/7)%1,rr=p.r*(.18+phase*.76);g.strokeStyle=`rgba(238,245,214,${(1-phase)*(.06+motion*.2+tilt*.05)})`;g.lineWidth=.7+(1-phase)*1.1;g.beginPath();g.ellipse(this.slosh.x*p.r,this.slosh.y*p.r,rr,rr*(.72+Math.sin(time*2+i)*.05),this.waterAngle+i*.2,this.waterAngle+i*.9,this.waterAngle+i*.9+Math.PI*1.5);g.stroke();}
 // Small moving highlights carry the circular current without spinning the metal pan.
 if(Math.abs(this.waterSpin)>.08){for(let i=0;i<16;i++){const a=this.waterAngle*(1+i%3*.06)+i*2.399,r=p.r*(.3+(i%5)*.095),tail=Math.min(.35,Math.abs(this.waterSpin)*.05);g.strokeStyle=`rgba(236,244,216,${.07+Math.min(.18,Math.abs(this.waterSpin)*.05)})`;g.lineWidth=i%3?1:1.8;g.beginPath();g.arc(this.slosh.x*p.r,this.slosh.y*p.r,r,a,a+tail);g.stroke();}}
 // A travelling meniscus responds to direction reversals independently of the pan.
 g.strokeStyle='rgba(229,234,211,0.42)';g.lineWidth=1.4;g.beginPath();for(let i=0;i<=40;i++){const a=i/40*Math.PI*2,rr=surfaceRadius*(.98+Math.sin(a*3-time*3)*motion*.013);const x=Math.cos(a)*rr+this.slosh.x*p.r*.25,y=Math.sin(a)*rr+surfaceY;if(i)g.lineTo(x,y);else g.moveTo(x,y);}g.stroke();g.restore();g.restore();g.restore();
 // Water and fine sediment leave the lowered lip through one continuous outlet.
 if(lean>.08&&s.water>.01){const lip=py+p.r*sy*.94,flow=Math.min(1,s.water*4)*lean,width=p.r*(.045+lean*.12),length=p.r*(.26+lean*.36),bend=Math.sin(time*2.4)*2;g.save();const sheet=g.createLinearGradient(0,lip,0,lip+length);sheet.addColorStop(0,'rgba(211,231,205,'+flow*.52+')');sheet.addColorStop(.45,'rgba(159,193,168,'+flow*.35+')');sheet.addColorStop(1,'rgba(175,210,181,0)');g.fillStyle=sheet;g.beginPath();g.moveTo(px-width,lip);g.bezierCurveTo(px-width*.8,lip+length*.25,px-width*.18+bend,lip+length*.7,px-width*.15+8,lip+length);g.lineTo(px+width*.15+8,lip+length);g.bezierCurveTo(px+width*.25+bend,lip+length*.7,px+width*.85,lip+length*.25,px+width,lip);g.closePath();g.fill();
 for(let i=0;i<28;i++){const u=(time*(1.5+lean)+i/28)%1,x=px+Math.sin(i*12.9)*width*(1-u*.8)+u*u*8,y=lip+u*u*length;g.globalAlpha=(1-u)*flow;g.fillStyle=i%3&&s.mud>.06?'#9f8b60':'#e4f0db';g.beginPath();g.ellipse(x,y,i%3?.8:1.2,1.2+u*2,0,0,6.28);g.fill();}for(let i=0;i<3;i++){const u=(time*.9+i/3)%1;g.globalAlpha=(1-u)*flow*.6;g.strokeStyle='#d2e2cc';g.lineWidth=1;g.beginPath();g.ellipse(px+8,lip+length,8+u*38,2+u*10,0,0,6.28);g.stroke();}g.restore();}
 if(stage==='loading'){const t=clamp((time-this.entered)/1.15,0,1);for(let i=0;i<60;i++){const q=(t*2+i/60)%1,x=px-p.r*.35+q*p.r*.3+Math.sin(i*13)*8,y=py-p.r*1.2+q*q*p.r*1.15;g.fillStyle=i%3?'#a49670':'#d4c39b';g.fillRect(x,y,2+(i%3),2+(i%2));}g.save();g.translate(px-p.r*.36,py-p.r*1.18);g.rotate(.3+t*.6);g.fillStyle='#8e8d78';g.beginPath();g.moveTo(-24,-18);g.lineTo(23,-18);g.quadraticCurveTo(26,25,0,31);g.quadraticCurveTo(-26,25,-24,-18);g.fill();g.fillStyle='#8b704b';g.fillRect(-4,-85,8,70);g.restore();}
 if(depth>.05){g.save();g.strokeStyle='rgba(231,239,224,0.467)';g.lineWidth=1.6;for(let i=0;i<4;i++){const life=(time*.6+i/4)%1;g.globalAlpha=(1-life)*depth;g.beginPath();g.ellipse(px,py+p.r*.45,p.r*(.5+life*.8),p.r*(.18+life*.3),0,0,Math.PI*2);g.stroke();}g.restore();}

 if(stage==='wash'&&s.water>=.18&&s.settled<.6&&motion<.13&&tilt<.08){g.save();g.translate(px,py);g.scale(1,sy);const angle=this.reduced?-.7:time*.8,radius=p.r*.57;g.strokeStyle='rgba(245,229,181,.3)';g.lineWidth=1;g.setLineDash([3,8]);g.beginPath();g.arc(0,0,radius,0,Math.PI*2);g.stroke();g.setLineDash([]);g.fillStyle='rgba(255,239,196,.65)';g.beginPath();g.arc(Math.cos(angle)*radius,Math.sin(angle)*radius,3,0,Math.PI*2);g.fill();g.restore();}
 if(stage==='wash'&&(s.water<.18||s.settled>=.6)&&tilt<.12){const refill=s.water<.18,yy=py+p.r*sy*(refill?-.8:.82);g.save();g.strokeStyle='rgba(245,229,181,.58)';g.lineWidth=1.4;g.beginPath();g.ellipse(p.x,yy,p.r*.27,6,0,refill?Math.PI:0,refill?Math.PI*2:Math.PI);g.stroke();const bounce=this.reduced?0:Math.sin(time*3)*3;g.font='12px sans-serif';g.textAlign='center';g.shadowColor='#12261c';g.shadowBlur=7;g.fillStyle='#fff0c9';g.fillText(refill?C.copy.guideTop:C.copy.guideRim,p.x,yy+28+bounce);g.restore();}
 this.drawBottle(totalGold,totalMinerals);

 if(this.flight){const f=this.flight,t=this.reduced?1:clamp((time-f.start)/.58,0,1),dest=accessoryLayout(w,h),x0=p.x+f.grain.x*p.r,y0=p.y+f.grain.y*p.r*p.sy,x1=f.grain.gold?dest.bottle:dest.tray;g.save();g.translate(x0+(x1-x0)*t,y0+(dest.y-y0)*t-Math.sin(t*Math.PI)*p.r*.6);drawGrain(g,f.grain,f.grain.size*p.r*(1+Math.sin(t*Math.PI)*1.8));g.restore();}

 }
}

