import test from 'node:test';import assert from 'node:assert/strict';import {generate,exposed,pick,readSave} from '../.cache/model.mjs';
test('forest is stable across reloads and contains reachable discoveries',()=>{for(let seed=1;seed<=1000;seed++){const a=generate(seed);assert.deepEqual(a,generate(seed));for(const p of a.patches){assert.ok(p.mushrooms.length);p.leaves.forEach(l=>l.x=-1);assert.ok(p.mushrooms.every(m=>exposed(p,m)));}}});
test('covered mushrooms cannot be collected and discovered ones submit once',()=>{const s={forest:generate(5),patch:0,basket:[]},p=s.forest.patches[0],m=p.mushrooms[0];p.leaves=[{x:m.x,y:m.y-.018,r:.2,angle:0,shade:0}];assert.equal(pick(s,m),false);p.leaves[0].x=-1;assert.equal(pick(s,m),true);assert.equal(pick(s,m),false);assert.equal(s.basket.length,1);assert.deepEqual(readSave(JSON.stringify(s)),s);});
test('damaged saves rejected',()=>{assert.equal(readSave('{'),null);assert.equal(readSave('{"forest":{}}'),null);});

test('harvest needs both sideways directions before upward lift',async()=>{const {moveGrip}=await import('../.cache/model.mjs');const g={left:0,right:0,lastX:.5,startY:.5};assert.equal(moveGrip(g,.54,.4,.05),false);assert.equal(moveGrip(g,.5,.5,.05),false);assert.equal(moveGrip(g,.5,.44,.05),true);});
test('released leaves slow to a stop rather than teleport or bounce back',async()=>{const {settleLeaves}=await import('../.cache/model.mjs');const p={mushrooms:[],leaves:[{x:.5,y:.5,r:.1,angle:0,shade:0,vx:.4,vy:0}]};for(let i=0;i<90;i++)settleLeaves(p,1/60);assert(p.leaves[0].x>.5&&p.leaves[0].x<.56);assert.equal(p.leaves[0].vx,0);});
test('objects outside the active patch and duplicate basket entries cannot be collected',()=>{const s={forest:generate(7),patch:0,basket:[]};s.forest.patches[0].leaves=[];const real=s.forest.patches[0].mushrooms[0];assert.equal(pick(s,{...real,id:'foreign'}),false);assert.equal(pick(s,real),true);s.basket.push({...s.basket[0]});assert.equal(readSave(JSON.stringify(s)),null);});

test('observation preserves the mushroom and basket, records once and survives reload',async()=>{const {observe,patchProgress}=await import('../.cache/model.mjs');const s={forest:generate(91),patch:0,basket:[]},p=s.forest.patches[0],m=p.mushrooms[0];p.leaves=[];assert.equal(observe(s,m),true);assert.equal(observe(s,m),true);assert.equal(m.picked,false);assert.equal(s.basket.length,0);assert.deepEqual(s.observations,[m.kind]);assert.equal(patchProgress(p).observed,1);const restored=readSave(JSON.stringify(s));assert.equal(restored.forest.patches[0].mushrooms[0].observed,true);assert.equal(pick(s,m),true);assert.equal(patchProgress(p).observed,1);assert.equal(patchProgress(p).collected,1);});
test('covered and foreign mushrooms cannot be observed',async()=>{const {observe}=await import('../.cache/model.mjs');const s={forest:generate(2),patch:0,basket:[]},p=s.forest.patches[0],m=p.mushrooms[0];p.leaves=[{x:m.x,y:m.y-m.size,r:.3,angle:0,shade:0}];assert.equal(observe(s,m),false);p.leaves=[];assert.equal(observe(s,{...m}),false);assert.equal(s.observations,undefined);});
test('invalid observation and reading history are rejected',()=>{for(const extra of [{observations:[99]},{observations:'all'},{readNotes:[false]}])assert.equal(readSave(JSON.stringify({forest:generate(1),patch:0,basket:[],...extra})),null);});

import {readFileSync} from 'node:fs';
import {normalize,observe,startRun,challengeProgress,checkChallenges,dailySeed,localDate,encounter} from '../.cache/model.mjs';
const content=JSON.parse(readFileSync(new URL('../src/content/content.json',import.meta.url),'utf8'));
for(const ch of content.challenges)test('challenge success/failure/idempotency: '+ch.id,()=>{const s=normalize({forest:generate(ch.seed),patch:ch.location*3,basket:[],mode:'challenge',challenge:ch.id});assert.equal(challengeProgress(s,ch.id),0);assert.equal(checkChallenges(s),false);for(let i=ch.location*3;i<ch.location*3+3;i++){s.patch=i;const p=s.forest.patches[i];p.leaves.forEach(l=>{l.x=-1;l.moved=true;});for(const m of p.mushrooms){observe(s,m);pick(s,m);}}assert.equal(challengeProgress(s,ch.id),ch.target);assert.equal(checkChallenges(s),true);assert.equal(checkChallenges(s),false);assert.deepEqual(s.completed,[ch.id]);s.mode='free';assert.equal(checkChallenges(s),false);});
test('all 24 collectible types are reachable, six habitats each have 10–16 occupied clusters',()=>{const kinds=new Set();for(let seed=0;seed<100;seed++){const f=generate(seed);assert.equal(f.patches.length,18);for(let loc=0;loc<6;loc++){let slots=0;for(const p of f.patches.slice(loc*3,loc*3+3)){slots+=new Set(p.mushrooms.filter(m=>m.kind<24).map(m=>m.slot)).size;p.mushrooms.forEach(m=>kinds.add(m.kind));assert(p.mushrooms.length<=35);assert(p.leaves.length<=60);}assert(slots>=10&&slots<=16);}}assert.equal([...kinds].filter(k=>k<24).length,24);});
test('real poisonous observations never become harvest rewards',()=>{const s=normalize({forest:generate(1),patch:1,basket:[]}),p=s.forest.patches[1],m=p.mushrooms.find(m=>m.kind>=24);p.leaves=[];assert.equal(observe(s,m),true);assert.equal(pick(s,m),false);assert.equal(s.basket.length,0);assert.equal(s.records.reduce((n,r)=>n+r.count,0),0);});
test('old three-scene saves preserve harvests, moved leaves and active location',()=>{const f=generate(1),m={...f.patches[0].mushrooms[0],picked:true};const old={forest:{seed:1,patches:[f.patches[0],f.patches[3],f.patches[6]]},patch:1,basket:[m]};old.forest.patches[1].leaves[0].x=.99;const s=readSave(JSON.stringify(old));assert.equal(s.forest.patches.length,18);assert.equal(s.patch,3);assert.equal(s.forest.patches[3].leaves[0].x,.99);assert.equal(s.records[m.kind].count,1);});
test('daily seeds use local calendar dates and replay does not add lifetime harvests',()=>{const date=new Date(2026,8,19,0,1);assert.equal(localDate(date),'2026-09-19');assert.equal(dailySeed(localDate(date)),dailySeed('2026-09-19'));assert.notEqual(dailySeed('2026-09-19'),dailySeed('2026-09-20'));const s=normalize({forest:generate(5),patch:0,basket:[]});s.forest.patches[0].leaves=[];pick(s,s.forest.patches[0].mushrooms[0]);const before=s.records.reduce((n,r)=>n+r.count,0);startRun(s,5,'replay');s.forest.patches[0].leaves=[];assert(pick(s,s.forest.patches[0].mushrooms[0]));assert.equal(s.records.reduce((n,r)=>n+r.count,0),before);});
test('50 full exploration loops keep bounded records and state below 200 KiB',()=>{const s=normalize({forest:generate(5),patch:0,basket:[]});for(let run=0;run<50;run++){startRun(s,run,'free');for(let i=0;i<18;i++){s.patch=i;const p=s.forest.patches[i];p.leaves.forEach(l=>l.x=-1);p.mushrooms.forEach(m=>{observe(s,m);pick(s,m);});encounter(s);}}assert(s.basket.length<=72);assert(s.history.length<=20);assert.equal(s.records.length,24);assert.equal(s.encounters.length,6);assert(Buffer.byteLength(JSON.stringify(s))<200*1024);assert(readSave(JSON.stringify(s)));});
test('future and corrupt expanded save metadata are rejected',()=>{const s=normalize({forest:generate(1),patch:0,basket:[]});assert.equal(readSave(JSON.stringify({...s,version:99})),null);assert.equal(readSave(JSON.stringify({...s,records:[]})),null);assert.equal(readSave(JSON.stringify({...s,layout:[{kind:99,x:0,y:0}]})),null);});
test('leaving and returning to today restores exact objects instead of awarding twice',()=>{const s=normalize({forest:generate(1),patch:0,basket:[]}),seed=dailySeed(localDate());startRun(s,seed,'daily');s.forest.patches[0].leaves=[];const m=s.forest.patches[0].mushrooms[0];pick(s,m);const count=s.records[m.kind].count;startRun(s,99,'free');const raw=JSON.stringify(s);assert(Buffer.byteLength(raw)<200*1024);assert(readSave(raw));startRun(s,seed,'daily');assert(s.forest.patches[0].mushrooms[0].picked);assert.equal(s.records[m.kind].count,count);assert.equal(pick(s,s.forest.patches[0].mushrooms[0]),false);});

test('six shape families each contain four distinct collectible atlas frames',()=>{for(const family of ['round','bell','fan','cup','ball','coral'])assert.equal(content.species.slice(0,24).filter(s=>s.family===family).length,4);assert.equal(new Set(content.species.slice(0,24).map(s=>s.atlas+':'+s.frame)).size,24);});
import {viewLeaf,brushDirt,dirtPoints} from '../.cache/model.mjs';
test('crouching changes foreground occlusion without moving the stored forest',()=>{const m={id:'view',x:.5,y:.5,size:.05,kind:0,picked:false},l={x:.5,y:.447,r:.08,angle:0,shade:0},p={mushrooms:[m],leaves:[l]},before=JSON.stringify(p);assert(!exposed(p,m,0));assert(exposed(p,m,1));assert(viewLeaf(l,1).y>l.y);assert.equal(JSON.stringify(p),before);});
test('brushing clears only dirt touched by actual moving strokes',()=>{assert.equal(brushDirt(0,{x:1,y:1},{x:1.2,y:1}),0);assert.equal(brushDirt(0,{x:0,y:0},{x:0,y:0}),0);let mask=0;for(const p of dirtPoints())mask=brushDirt(mask,{x:p.x-.04,y:p.y},{x:p.x+.04,y:p.y});assert.equal(mask,4095);assert.equal(brushDirt(mask,{x:NaN,y:0},{x:0,y:0}),mask);});

test('natural forest layouts stay reachable, separated and deterministic across seeds',async()=>{const {forestPositions}=await import('../.cache/model.mjs');for(let seed=1;seed<=200;seed++){const points=forestPositions(seed,0,0);assert.deepEqual(points,forestPositions(seed,0,0));assert.equal(points.length,6);for(let i=0;i<6;i++){assert(points[i].x>=.16&&points[i].x<=.84&&points[i].y>=.23&&points[i].y<=.79);for(let j=0;j<i;j++)assert(Math.hypot(points[i].x-points[j].x,points[i].y-points[j].y)>.16);}}assert.notDeepEqual(forestPositions(8,0,0),forestPositions(8,0,1));});

test('loose forest litter is movable, bounded and does not make discoveries unreachable',()=>{const f=generate(402);for(const p of f.patches){assert(p.leaves.some(l=>l.r<.055));assert(p.leaves.length<=60);p.leaves.forEach(l=>l.x=-1);assert(p.mushrooms.every(m=>exposed(p,m)));}assert(readSave(JSON.stringify({forest:f,patch:0,basket:[]})));});
