import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
import {createServer} from 'node:http';
const root=fileURLToPath(new URL('.',import.meta.url)),workspace=resolve(root,'../..');
const compiler=join(workspace,'node_modules/.pnpm/rolldown@1.2.5/node_modules/rolldown/dist/index.mjs'),tsc=join(workspace,'node_modules/.pnpm/typescript@6.0.3/node_modules/typescript/bin/tsc');
async function bundle(input,out,format){const {rolldown}=await import(pathToFileURL(compiler).href);const b=await rolldown({input:join(root,input),transform:{target:'chrome61'}});await b.write({file:join(root,out),format,name:'WildPond',sourcemap:false});await b.close();}
const cmd=process.argv[2];
if(cmd==='lint'){const r=spawnSync(process.execPath,[tsc,'--project',join(root,'tsconfig.json')],{stdio:'inherit'});if(r.status)process.exit(r.status);JSON.parse(await readFile(join(root,'src/content/content.json'),'utf8'));console.log('TypeScript and content passed');}
else if(cmd==='test'){await mkdir(join(root,'.cache'),{recursive:true});await bundle('src/model.ts','.cache/model.mjs','es');await bundle('src/audio-bank.ts','.cache/audio-bank.mjs','es');await bundle('src/tackle.ts','.cache/tackle.mjs','es');const r=spawnSync(process.execPath,['--test','tests/model.test.mjs','tests/audio.test.mjs','tests/tackle.test.mjs'],{cwd:root,stdio:'inherit'});if(r.status)process.exit(r.status);}
else if(cmd==='build'){await mkdir(join(root,'dist/assets'),{recursive:true});await bundle('src/app.ts','dist/app.js','iife');await copyFile(join(root,'index.html'),join(root,'dist/index.html'));await copyFile(join(root,'src/style.css'),join(root,'dist/style.css'));for(const file of ['ponds.webp','fish.webp'])await copyFile(join(root,'assets',file),join(root,'dist/assets',file));const c=JSON.parse(await readFile(join(root,'src/content/content.json'),'utf8')),bank={};for(const a of c.audio.assets){const b=await readFile(join(root,a.file));if(b.length>102400)throw Error('Audio over clip budget');bank[a.id]=b.toString('base64');}await writeFile(join(root,'dist/audio-data.js'),'window.POND_AUDIO='+JSON.stringify(bank)+';');console.log('Classic offline build passed');}
else if(cmd==='preview'){const base=resolve(root,process.env.PREVIEW_DIR||'dist'),port=Number(process.env.PORT||4325);createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),p=resolve(base,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!p.startsWith(base+sep)){res.writeHead(403);res.end();return;}const b=await readFile(p);res.writeHead(200,{'Content-Type':{'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.webp':'image/webp'}[extname(p)]||'application/octet-stream','Cache-Control':'no-store'});res.end(b);}catch{res.writeHead(404);res.end();}}).listen(port,'127.0.0.1',()=>console.log('http://127.0.0.1:'+port));}
else throw Error('Unknown command');
