import {clone,uid,round,bounds,roomAt,validRoom,placement,itemFrom,findSpot,makePlan,inventory,History,validatePlan,csvCell,validOpening,walls,wallOpenings} from './core.js';
import {RoomScene} from './scene.js';

const app=document.getElementById('app');
const catalog=await fetch(new URL('./content/content.json',import.meta.url)).then(r=>{if(!r.ok)throw new Error('Content unavailable');return r.json();});
const U=catalog.ui,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 10 12 3l9 7v11H3Z M9 21v-7h6v7',sofa:'M5 12V7a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v5 M3 11h3v5h12v-5h3v9H3Z M5 20v2m14-2v2',paint:'m4 16 9-9 5 5-9 9H4Z M12 6l3-3 6 6-3 3',grid:'M3 3h8v8H3z M14 3h7v8h-7z M3 14h8v7H3z M14 14h7v7h-7z',spark:'m12 2 2.8 7.2L22 12l-7.2 2.8L12 22l-2.8-7.2L2 12l7.2-2.8Z',undo:'M9 4 4 9l5 5 M4 9h10a6 6 0 0 1 0 12',redo:'m15 4 5 5-5 5 M20 9H10a6 6 0 0 0 0 12',arrow:'M4 12h16m-6-6 6 6-6 6',close:'m6 6 12 12M6 18 18 6',plus:'M12 4v16M4 12h16',check:'m4 12 5 5L20 6',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',box:'m12 3 9 5v9l-9 5-9-5V8Z M3 8l9 5 9-5 M12 13v9',top:'M3 3h18v18H3z M13 3v10h8 M3 14h10v7',walk:'M13 5a2 2 0 1 0 0-4 2 2 0 0 0 0 4 M10 8l3-1 3 5 4 1 M7 13l3-5-1 8-4 6 M10 15l5 2 1 5',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',moon:'M20 15A8 8 0 0 1 9 4a9 9 0 1 0 11 11Z',list:'M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',copy:'M8 8h13v13H8z M16 8V3H3v13h5',rotate:'M20 8a8 8 0 1 0 0 9M20 3v6h-6',trash:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M10 10v7m4-7v7',search:'M15 15l6 6 M18 10a8 8 0 1 0-16 0 8 8 0 0 0 16 0',folder:'M3 5h7l2 3h9v13H3Z',help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4M12 18v1 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',compare:'M12 2v20 M9 5H3v14h6m6-14h6v14h-6'};
const icon=(key)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[key]||paths.home}"/></svg>`;
const button=(action,label,ico='',className='',extra='')=>`<button type="button" data-action="${action}" class="${className}" title="${esc(label)}" aria-label="${esc(label)}" ${extra}>${ico?icon(ico):''}<span>${esc(label)}</span></button>`;
const KEY='roomish-project-15-v1';let db={active:null,plans:[],baselines:{}},blockedStorage=false;
try{const raw=localStorage.getItem(KEY);if(raw){const loaded=JSON.parse(raw);if(!Array.isArray(loaded.plans)||loaded.plans.length>30)throw new Error();loaded.plans=loaded.plans.map(p=>validatePlan(p,catalog));loaded.baselines=Object.fromEntries(Object.entries(loaded.baselines||{}).map(([id,p])=>[id,validatePlan(p,catalog)]));db=loaded;}}catch{blockedStorage=true;}
let plan=db.plans.find(p=>p.id===db.active)||makePlan(catalog.templates[0],catalog);if(!db.plans.length)plan.name=U.project;
let baseline=clone(db.baselines[plan.id]||plan),history=new History(),tab='furniture',category=U.all,query='',selected=null,selectionBeforeWalk=null,surface='floor',finished=false,comparing=false,showBefore=false,night=false,view='overview',drawer=false,roomPropertiesOpen=false,doorRoomId=null,doorPointer=null,doorEditingId=null,doorNavigation=false,doorDrag=null,doorPreviousEdit=false,snap=true,scene,thumbs=new Map(),timer,saveTimer;
app.innerHTML=`<div class="app-shell"><header class="topbar"><a class="brand" href="#" aria-label="${catalog.title}"><span class="brand-mark"><img src="./src/logo-roomish.png" width="40" height="40" alt=""></span><span>${U.brand}<small>${catalog.title}</small></span></a><div class="project-heading"><input id="plan-name" maxlength="60" aria-label="${U.name}" value="${esc(plan.name)}"><span id="save-state">${U.local}</span></div><div class="top-actions">${button('undo',U.undo,'undo','icon-button')}${button('redo',U.redo,'redo','icon-button')}<span class="separator"></span>${button('plans',U.plans,'folder','quiet desktop-label')}${button('finish',U.finish,'check','primary')}</div></header><main class="studio"><aside class="library" id="library"><div class="library-intro"><span class="eyebrow">${U.introLabel}</span><h1>${catalog.title}<span>.</span></h1><p>${catalog.subtitle}</p></div><nav class="tabs" id="tabs"></nav><section id="library-content" class="library-content"></section><div class="library-footer">${icon('check')}<span>${U.savedLabel}</span>${button('help',U.help,'help','icon-button')}</div></aside><section class="workspace"><div id="viewport"></div><div class="scene-heading"><span class="eyebrow">${U.sceneLabel}</span><h2 id="scene-title">${U.dayTitle}</h2><p id="scene-subtitle">${U.density}</p></div><div class="mobile-view-access">${button('toggle-views',U.viewMenu,'box','quiet')}${button('overview',U.overview,'home','quiet')}</div><div class="view-toolbar">${button('overview',U.overview,'box','active')}${button('top',U.top,'top')}${button('inside',U.inside,'walk')}</div><div id="room-nav" class="room-nav"></div><div id="layout-controls" class="layout-controls" hidden></div><div class="scene-tools">${button('light',U.night,'moon','tool-round')}${button('compare',U.compare,'compare','tool-round')}${button('reset',U.reset,'rotate','tool-round')}${button('capture',U.exportImage,'download','tool-round')}</div><div id="comparison" class="comparison" hidden></div><div id="walk-controls" class="walk-controls" hidden></div><div id="finish-card" class="finish-card" hidden></div><div class="scene-bottom"><div id="stats" class="stats"></div><div id="hint" class="interaction-hint">${U.hint}</div></div><div id="placing" class="placing" hidden></div><div class="mobile-launch" id="mobile-launch"></div></section><aside id="inspector" class="inspector"></aside><div id="mobile-dock"><div id="mobile-context"></div></div></main><footer class="app-footer"><span>${U.footer}</span><div>${button('mode',U.beginner,'','mode-button')}${button('inventory',U.inventory,'list','quiet')}</div></footer></div><dialog id="modal"><div id="modal-content"></div></dialog><input type="file" id="import-file" accept=".json,application/json" hidden><div id="toast" class="toast" role="status" aria-live="polite"></div>`;

function toast(key){clearTimeout(timer);$('#toast').textContent=U[key]||key;$('#toast').classList.add('visible');timer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function persist(){clearTimeout(saveTimer);if(blockedStorage){$('#save-state').textContent=U.unsaved;return;}try{plan.updatedAt=Date.now();db.active=plan.id;db.plans=db.plans.filter(p=>p.id!==plan.id);db.plans.unshift(clone(plan));db.plans=db.plans.slice(0,30);db.baselines[plan.id]=clone(baseline);const keep=new Set(db.plans.map(p=>p.id));db.baselines=Object.fromEntries(Object.entries(db.baselines).filter(([id])=>keep.has(id)));localStorage.setItem(KEY,JSON.stringify(db));$('#save-state').textContent=U.saved;}catch{$('#save-state').textContent=U.unsaved;toast('unsaved');}}
function saveSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,220);}
function commit(fn,message){if(scene?.walk||showBefore){toast('notReady');return;}history.record(plan);fn(plan);refresh();saveSoon();if(message)toast(message);}
function refresh(rebuild=true){if(rebuild)scene?.rebuild(showBefore?baseline:plan);if(selected?.kind==='item'&&!plan.items.some(i=>i.id===selected.id))selected=null;if(selected?.kind==='room'&&!plan.rooms.some(r=>r.id===selected.id))selected=null;scene?.select(selected);renderLibrary();renderInspector();renderChrome();}
$('#mobile-dock').appendChild($('#mobile-launch'));
function renderChrome(){
  const mobileEditing=!!scene?.editRooms&&!finished&&!scene?.walk&&!showBefore;
  document.body.classList.toggle('mobile-selected',!!selected&&!drawer&&!finished&&!scene?.walk);
  document.body.classList.toggle('mobile-room-selected',selected?.kind==='room');
  document.body.classList.toggle('mobile-properties',roomPropertiesOpen&&!drawer);
  document.body.classList.toggle('mobile-placing',!!scene?.pending||!!doorRoomId);
  const context=$('#mobile-context');
  if(doorRoomId)context.innerHTML='<span class="dock-caption">'+esc(doorNavigation?U.doorCameraHint:doorEditingId?U.moveDoorHint:U.placeDoorHint)+'</span>'+button('cancel-door',U.endPlacing,'check','primary');
  else if(scene?.pending)context.innerHTML='<span class="dock-caption">'+esc(scene.pending.name)+'</span>'+button('cancel-place',U.cancel,'close','quiet');
  else if(drawer)context.innerHTML=button('close-panel',U.collapseRoomEditor,'close','quiet');
  else if(selected?.kind==='item'&&!finished&&!scene?.walk)context.innerHTML=button('rotate',U.rotate,'rotate','quiet')+button('duplicate',U.duplicate,'copy','quiet')+button('delete',U.remove,'trash','quiet')+button('mobile-settings',U.moreSettings,'grid','quiet');
  else if(selected?.kind==='room'&&!finished&&!scene?.walk)context.innerHTML='<div class="dock-selection"><strong>'+esc(selectedRoom().name)+'</strong>'+button('focus-selected-room',U.focusSelectedRoom,'home','quiet')+'</div>'+button('add-door',U.addDoor,'plus','quiet')+button('room-properties',roomPropertiesOpen?U.collapseRoomEditor:U.roomSettings,'grid','quiet')+(mobileEditing?button('finish-layout',U.finishLayout,'check','primary'):'');
  else context.innerHTML=mobileEditing?button('add-room-shortcut',U.addRoom,'plus','primary')+button('finish-layout',U.finishLayout,'check','quiet'):'';
  if(mobileEditing&&selected?.kind==='room'&&!doorRoomId&&!drawer)context.innerHTML+=button('add-room-shortcut',U.addRoom,'plus','quiet');

  const editing=!!scene?.editRooms&&!finished&&!scene?.walk&&!showBefore;
  document.body.classList.toggle('layout-editing',editing);
  document.body.classList.toggle('room-properties-open',editing&&roomPropertiesOpen&&selected?.kind==='room');
  const controls=$('#layout-controls');controls.hidden=!editing;
  controls.innerHTML=editing?button('add-room-shortcut',U.addRoom,'plus','primary')+button('room-properties',roomPropertiesOpen?U.collapseRoomEditor:U.editRoomProperties,'grid','quiet',selected?.kind==='room'?'':'disabled')+button('focus-selected-room',U.focusSelectedRoom,'home','quiet',selected?.kind==='room'?'':'disabled')+button('add-door',U.addDoor,'plus','quiet',selected?.kind==='room'?'':'disabled')+button('finish-layout',U.finishLayout,'check','quiet'):'';

  const inv=inventory(showBefore?baseline:plan,catalog);$('#stats').innerHTML=`<span><strong>${plan.rooms.length}</strong> ${U.rooms}</span><span><strong>${plan.items.length}</strong> ${U.objects}</span><span>${inv.measured?`<strong>${inv.area}</strong> m² <small>${inv.measured===plan.rooms.length?U.area:U.partial}</small>`:U.unmeasured}</span>`;
  $('#plan-name').value=plan.name;$('#plan-name').disabled=showBefore||scene?.walk||false;const undo=$('[data-action="undo"]'),redo=$('[data-action="redo"]');undo.disabled=!history.past.length||showBefore||scene?.walk;redo.disabled=!history.future.length||showBefore||scene?.walk;
  $('[data-action="mode"]').innerHTML=`<i class="status-dot"></i>${plan.mode==='beginner'?U.beginner:U.advanced}`;
  $('#room-nav').innerHTML=plan.rooms.map(r=>`<button data-action="room" data-id="${r.id}" class="${selected?.id===r.id?'active':''}">${esc(r.name)}</button>`).join('')+((scene?.editRooms||tab==='layouts')&&!finished&&!scene?.walk&&!showBefore?button('add-room-shortcut',U.addRoom,'plus','room-add-shortcut'):'');
  $('#tabs').innerHTML=[['furniture','sofa'],['materials','paint'],['layouts','grid'],['styles','spark']].map(([t,i])=>button(`tab-${t}`,U[t],i,tab===t?'active':'')).join('');
  $('#mobile-launch').innerHTML=[['furniture','sofa'],['materials','paint'],['layouts','grid'],['styles','spark']].map(([t,i])=>button(`tab-${t}`,U[t],i,tab===t&&drawer?'active':'')).join('');
  $('#hint').textContent=scene?.walk?U.walkHint:scene?.pending?U.placeHint:U.hint;
  document.body.classList.toggle('finished',finished);document.body.classList.toggle('walking',!!scene?.walk);document.body.classList.toggle('drawer-open',drawer);document.body.classList.toggle('before-view',showBefore);
  $('.view-toolbar').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.action===(scene?.walk?'inside':view)));
  $('#scene-title').textContent=finished?U.snapshotTitle:night?U.nightTitle:U.dayTitle;$('#scene-subtitle').textContent=finished?U.snapshotSubtitle:U.density;
  $('[data-action="finish"]').innerHTML=icon(finished?'arrow':'check')+`<span>${finished?U.back:U.finish}</span>`;
  $('#finish-card').hidden=!finished||!!scene?.walk;$('#finish-card').innerHTML=`<p>${U.snapshotTip}</p><div>${button('inventory',U.inventory,'list','primary')}${button('capture',U.exportImage,'download','quiet')}${button('copy-plan',U.saveCopy,'copy','quiet')}</div>`;
  $('#comparison').hidden=!comparing;$('#comparison').innerHTML=button('show-before',U.before,'',showBefore?'active':'')+button('show-after',U.after,'',!showBefore?'active':'')+button('compare',U.close,'close','icon-button');
  $('#walk-controls').hidden=!scene?.walk;$('#walk-controls').innerHTML=button('walk-corner',U.viewCorner,'eye')+button('walk-center',U.viewCenter,'eye')+button('exit-walk',U.back,'arrow','primary');
}
function floorplanSVG(t){const rs=t.rooms.map((r,i)=>({x:r[1],z:r[2],w:r[3],d:r[4],name:r[0],i})),b=bounds(rs);return `<svg viewBox="${b.x-.3} ${b.z-.3} ${b.w+.6} ${b.d+.6}" class="plan-svg" aria-hidden="true">${rs.map(r=>`<rect x="${r.x+.04}" y="${r.z+.04}" width="${r.w-.08}" height="${r.d-.08}" rx=".08" fill="${['#d1b896','#dfd4c0','#a6b5a4','#ccd2c6','#c1cba7'][r.i%5]}" stroke="#f9f6ed" stroke-width=".1"/><text x="${r.x+r.w/2}" y="${r.z+r.d/2}" dominant-baseline="middle" text-anchor="middle" font-size=".34" fill="#514c40">${esc(r.name)}</text>`).join('')}</svg>`;}
function renderLibrary(){
  const el=$('#library-content');
  if(tab==='furniture'){
    el.innerHTML=`<label class="search-field">${icon('search')}<input id="search" placeholder="${U.search}" value="${esc(query)}" autocomplete="off"></label><div class="categories">${[U.all,...catalog.categories].map(c=>`<button data-action="category" data-id="${c}" class="${category===c?'active':''}">${c}</button>`).join('')}</div><div class="catalog-heading"><span>${U.furniture}</span><small>${catalog.furniture.length} ${U.objectsLabel}</small></div><div id="furniture-grid" class="furniture-grid">${furnitureCards()}</div>`;
  }else if(tab==='materials'){
    const r=selectedRoom();el.innerHTML=`<div class="section-heading"><h3>${U.materials}</h3><p>${U.materialHelp}</p></div><select id="material-room" aria-label="${U.room}">${plan.rooms.map(x=>`<option value="${x.id}" ${x.id===r.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="segmented">${button('surface-floor',U.floor,'',surface==='floor'?'active':'')}${button('surface-wall',U.wall,'',surface==='wall'?'active':'')}</div><div class="material-grid">${catalog.materials.map(m=>`<button class="material-card ${r[surface]===m.id?'selected':''}" data-action="material" data-id="${m.id}"><span class="swatch ${m.pattern}" style="--swatch:${m.color}"></span><span>${m.name}</span>${r[surface]===m.id?icon('check'):''}</button>`).join('')}</div>`;
  }else if(tab==='layouts'){
    el.innerHTML=`<div class="section-heading"><h3>${U.layouts}</h3><p>${U.templateHelp}</p></div><div class="layout-actions">${button('add-room',U.addRoom,'plus','primary')}${button('blank',U.blank,'grid','quiet')}</div><div class="clear-row">${button('clear',U.clear,'trash','quiet')}</div><label class="check-row"><input type="checkbox" id="room-edit" ${scene?.editRooms?'checked':''}>${U.roomEdit}</label><p class="micro">${U.roomHelp}</p><div class="template-grid">${catalog.templates.map(t=>`<button class="template-card" data-action="template" data-id="${t.id}">${floorplanSVG(t)}<strong>${t.name}</strong><small>${t.tag}</small></button>`).join('')}</div>`;
  }else{
    el.innerHTML=`<div class="section-heading"><h3>${U.styles}</h3><p>${U.styleHelp}</p></div><div class="style-cards">${catalog.styles.map((s,i)=>`<button class="style-card ${plan.style===s.id?'selected':''}" data-action="style" data-id="${s.id}" style="--style-bg:${s.background}"><span class="style-number">0${i+1}</span><div class="style-art"><i style="background:${s.colors[0]}"></i><i style="background:${s.colors[1]}"></i><i style="background:${s.colors[2]}"></i></div><strong>${s.name}</strong><small>${s.tag}</small><span class="style-arrow">${icon('arrow')}</span></button>`).join('')}</div><div class="experiment"><span class="eyebrow">${U.experimentLabel}</span><p>${U.footer}</p>${button('copy-plan',U.saveCopy,'copy','quiet')}${button('baseline',U.baseline,'compare','quiet')}</div>`;
  }
}
function furnitureCards(){const list=catalog.furniture.filter(f=>(category===U.all||f.category===category)&&f.name.includes(query));return list.length?list.map(f=>`<button class="furniture-card" draggable="true" data-action="furniture" data-id="${f.id}"><div class="furniture-image">${thumbs.has(f.id)?`<img src="${thumbs.get(f.id)}" alt="${f.name}" draggable="false">`:icon('sofa')}<span class="add-dot">+</span></div><strong>${f.name}</strong><small>${f.w} × ${f.d} m</small></button>`).join(''):`<p class="empty">${U.noResults}</p>`;}
function selectedRoom(){return plan.rooms.find(r=>r.id===(selected?.kind==='room'?selected.id:plan.items.find(i=>i.id===selected?.id)?.roomId))||plan.rooms[0];}
const field=(label,key,value,min,max,step=.001)=>`<label class="field"><span>${label}</span><input type="number" name="${key}" value="${value??''}" min="${min}" max="${max}" step="${step}"></label>`;
function renderInspector(){
  const el=$('#inspector');el.classList.toggle('has-selection',!!selected);
  if(!selected){el.innerHTML=`<div class="inspector-empty"><div class="line-house">${icon('home')}</div><span class="eyebrow">${U.emptyLabel}</span><h3>${U.selectHint}</h3><p>${U.footer}</p><div class="mini-swatches">${catalog.palette.slice(0,4).map(c=>`<i style="background:${c}"></i>`).join('')}</div></div>`;return;}
  const advanced=plan.mode==='advanced';
  if(selected.kind==='item'){
    const o=plan.items.find(i=>i.id===selected.id);if(!o)return;const f=catalog.furniture.find(f=>f.id===o.catalogId);
    el.innerHTML=`<div class="inspector-header"><span>${U.selection}</span>${button('deselect',U.close,'close','icon-button')}</div><div class="selected-image"><img src="${thumbs.get(f.id)||''}" alt="${f.name}"></div><span class="eyebrow">${esc(selectedRoom().name)}</span><h3>${f.name}</h3><p class="micro">${o.w} × ${o.d} × ${o.h} m</p><div class="object-actions">${button('rotate',U.rotate,'rotate')}${button('duplicate',U.duplicate,'copy')}${button('delete',U.remove,'trash')}</div><h4>${U.color}</h4><div class="palette">${catalog.palette.map(c=>`<button data-action="color" data-id="${c}" aria-label="${U.color} ${c}" class="${o.color===c?'selected':''}" style="background:${c}"></button>`).join('')}<input id="custom-color" type="color" value="${o.color}" aria-label="${U.color}"></div>${advanced?`<form id="item-form"><div class="field-grid">${field(U.width+' m','w',o.w,.1,8)}${field(U.depth+' m','d',o.d,.1,8)}${field(U.height+' m','h',o.h,.01,4,.001)}${field(U.angle+' °','angle',o.angle,-360,360,1)}${field('X','x',o.x,-60,60)}${field('Z','z',o.z,-60,60)}</div><button class="primary" type="submit">${U.apply}</button></form><label class="check-row"><input id="snap" type="checkbox" ${snap?'checked':''}>${U.snap}</label>`:''}`;
  }else{
    const r=selectedRoom();el.innerHTML=`<div class="room-flow-actions">${button('add-next-room',U.addNextRoom,'plus','primary')}${button('deselect',U.collapseRoomEditor,'close','quiet')}</div><div class="inspector-header"><span>${U.room}</span>${button('deselect',U.close,'close','icon-button')}</div><h3>${esc(r.name)}</h3><p class="micro">${r.measured?round(r.w*r.d)+' m² · '+U.real:U.unmeasured}</p><form id="room-form"><label class="field"><span>${U.name}</span><input name="name" value="${esc(r.name)}" maxlength="30" required></label><div class="field-grid">${field(U.roomWidthMeters,'w',r.w,1.5,16)}${field(U.roomDepthMeters,'d',r.d,1.5,16)}${advanced?field('X','x',r.x,-60,60)+field('Z','z',r.z,-60,60):''}</div><label class="check-row"><input name="measured" type="checkbox" ${r.measured?'checked':''}>${U.measured}</label><p class="micro">${U.measureHelp}</p><button type="submit" class="primary">${U.apply}</button></form><div class="object-actions">${button('add-door',U.addDoor,'plus')}${button('tab-materials',U.materials,'paint')}${button('focus-room',U.inside,'walk')}${button('delete-room',U.remove,'trash')}</div><details ${advanced?'open':''}><summary>${U.openings}</summary><p class="micro">${U.openingTip}</p><form id="opening-form"><div class="field-grid"><label class="field"><span>${U.surface}</span><select name="side">${['north','south','west','east'].map(s=>`<option value="${s}">${U[s]}</option>`).join('')}</select></label><label class="field"><span>${U.openings}</span><select name="type"><option value="door">${U.door}</option><option value="window">${U.window}</option></select></label>${field(U.offset,'offset',round(r.w/2),.2,16)}${field(U.width,'w',.9,.4,8)}${field(U.height,'h',2.1,.3,4)}${field(U.sill,'sill',0,0,3)}</div><button class="quiet" type="submit">${U.apply}</button></form><div class="opening-list">${plan.openings.filter(o=>o.roomId===r.id).map(o=>`<div><span>${U[o.side]} · ${U[o.type]} ${o.w}×${o.h}</span>${button('edit-opening',U.apply,'paint','icon-button',`data-id="${o.id}"`)}${button('delete-opening',U.deleteOpening,'trash','icon-button',`data-id="${o.id}"`)}</div>`).join('')}</div></details>${advanced?`<details><summary>${U.advanced}</summary><form id="global-form"><div class="field-grid">${field(U.wallHeight+' m','wallHeight',plan.wallHeight,2.2,4.5)}${field(U.wallThickness+' m','wallThickness',plan.wallThickness,.08,.4,.01)}${field(U.textureScale,'textureScale',r.textureScale,.25,4,.25)}${field(U.textureAngle,'textureAngle',r.textureAngle,0,360,15)}</div>${field(U.buildingArea+' m²','buildingArea',plan.buildingArea,.1,10000)}<label class="check-row"><input name="wallHeightMeasured" type="checkbox" ${plan.wallHeightMeasured?'checked':''}>${U.confirmedHeight}</label><button type="submit" class="primary">${U.apply}</button></form></details>`:''}`;
  }
}
function choose(value){if(showBefore||scene?.walk)return;if(!saveRoomDraft())return false;selected=value;roomPropertiesOpen=false;if(value?.surface)surface=value.surface;scene?.select(value);renderInspector();renderChrome();if(tab==='materials')renderLibrary();}
function openModal(title,body){$('#modal-content').innerHTML=`<div class="modal-header"><h2>${title}</h2>${button('close-modal',U.close,'close','icon-button')}</div>${body}`;if(!$('#modal').open)$('#modal').showModal();}
function inventoryModal(){const inv=inventory(plan,catalog),rows=[...inv.furniture,...inv.materials];let sum=0;for(const r of rows)if(!r.unknown&&Number.isFinite(plan.prices[r.key]))sum+=r.quantity*plan.prices[r.key];openModal(U.inventory,`<p class="micro">${U.constructionNote}<br>${U.wallQuantityHint}</p><div class="inventory-tools">${button('csv',U.exportCSV,'download','primary')}${button('json',U.exportJSON,'download','quiet')}</div><div class="table-scroll"><table><thead><tr><th>${U.name}</th><th>${U.location}</th><th>${U.size}</th><th>${U.quantity}</th><th>${U.unitPrice}</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${r.name}</strong>${r.color?`<i class="color-dot" style="background:${r.color}"></i>`:''}</td><td>${r.rooms.map(esc).join('、')}</td><td>${r.surface?U[r.surface]:r.size+' m'}</td><td>${r.unknown?U.pending:r.quantity+(r.surface?' m²':'')}</td><td><input type="number" min="0" max="10000000" step=".01" class="price-input" data-price="${esc(r.key)}" value="${plan.prices[r.key]??''}" aria-label="${r.name} ${U.unitPrice}"></td></tr>`).join('')}</tbody></table></div><div class="inventory-total"><span>${U.subtotal}</span><strong id="price-total">¥ ${round(sum).toLocaleString()}</strong></div><p class="micro">${U.priceHelp}</p>`);}
function plansModal(){persist();openModal(U.savedPlans,`<div class="inventory-tools">${button('copy-plan',U.saveCopy,'copy','primary')}${button('import',U.importJSON,'folder','quiet')}${button('json',U.exportJSON,'download','quiet')}</div><div class="plan-list">${db.plans.map(p=>`<div class="saved-plan"><div><strong>${esc(p.name)}</strong><small>${p.rooms.length} ${U.rooms} · ${p.items.length} ${U.objects}</small></div>${button('open-plan',U.open,'arrow','quiet',`data-id="${p.id}"`)}${button('delete-plan',U.remove,'trash','icon-button',`data-id="${p.id}" ${p.id===plan.id?'disabled':''}`)}</div>`).join('')}</div>`);}
function loadPlan(p){scene?.setPending(null);scene?.exit();if(scene){scene.readonly=false;scene.editRooms=false;}$('#placing').hidden=true;plan=clone(p);baseline=clone(db.baselines[p.id]||p);selected=null;history=new History();showBefore=false;comparing=false;finished=false;view='overview';refresh();scene?.fit();persist();$('#modal').close();toast('loaded');}
function download(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('exported');}
let exportImageData='',albumSaving=false;
async function previewExportImage(capture){
  exportImageData='';
  const data=typeof capture==='string'?capture:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(capture);});
  const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=data;});
  const scale=Math.min(1,1024/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#f5f2eb';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);
  let quality=.92;exportImageData=canvas.toDataURL('image/jpeg',quality);while(exportImageData.length>1398100&&quality>.4){quality-=.1;exportImageData=canvas.toDataURL('image/jpeg',quality);}if(exportImageData.length>1398100){exportImageData='';throw new Error('Image exceeds export budget');}
  openModal(U.exportImage,'<img class="export-preview" alt="'+esc(catalog.title)+'" src="'+exportImageData+'"><p class="micro">'+esc(U.imageHelp)+'</p>'+button('save-album',U.saveAlbum,'download','primary'));
}
$('#modal').addEventListener('close',()=>{exportImageData='';const preview=$('.export-preview');if(preview)preview.removeAttribute('src');});
function safeFilename(){return plan.name.replace(/[<>:"/\\|?*]/g,'_').slice(0,60)||'roomish';}
function updateRoom(candidate){if(!validRoom(plan,candidate)){toast('invalidRoom');scene?.rebuild(plan);return;}commit(p=>{const old=p.rooms.find(r=>r.id===candidate.id),dx=candidate.x-old.x,dz=candidate.z-old.z;Object.assign(old,candidate);for(const o of p.items.filter(o=>o.roomId===old.id)){o.x=round(o.x+dx);o.z=round(o.z+dz);}p.openings=p.openings.filter(o=>validOpening(p,o));},'roomSaved');}
function enterRoom(r,corner=false){scene?.setPending(null);if(!scene?.walk)selectionBeforeWalk=selected?{...selected}:null;if(scene?.enter(r,corner)){selected={kind:'room',id:r.id};drawer=false;renderChrome();}}
function pending(def){if(showBefore||scene?.walk)return;scene?.setPending(def);drawer=false;$('#placing').hidden=!def;$('#placing').innerHTML=def?`<span>${def.name} · ${U.placeHint}</span>${button('cancel-place',U.cancel,'close','icon-button')}`:'';renderChrome();}
function place(def,p){if(plan.items.length>=160)return toast('limit');const o=itemFrom(def,roomAt(plan,p.x,p.z)||plan.rooms[0],snap?round(p.x*10)/10:p.x,snap?round(p.z*10)/10:p.z),r=placement(plan,o,catalog);if(!r)return toast('invalidPlacement');o.roomId=r.id;commit(s=>s.items.push(o),'added');pending(null);choose({kind:'item',id:o.id});}
function duplicate(){const o=plan.items.find(i=>i.id===selected?.id);if(!o)return;const def={...catalog.furniture.find(f=>f.id===o.catalogId),w:o.w,d:o.d,h:o.h,color:o.color},n=findSpot(plan,def,selectedRoom(),catalog);if(!n)return toast('invalidPlacement');if(plan.items.length>=160)return toast('limit');commit(p=>p.items.push(n));choose({kind:'item',id:n.id});}

function saveRoomDraft(){
  const f=$('#room-form');if(!f||selected?.kind!=='room')return true;
  const old=plan.rooms.find(r=>r.id===selected.id);if(!old)return true;
  const fd=new FormData(f),n={...old,name:String(fd.get('name')).trim(),w:Number(fd.get('w')),d:Number(fd.get('d')),measured:fd.has('measured')};
  if(fd.has('x'))n.x=Number(fd.get('x'));if(fd.has('z'))n.z=Number(fd.get('z'));
  if(JSON.stringify(old)===JSON.stringify(n))return true;
  if(!f.checkValidity()||!n.name||!validRoom(plan,n)){roomPropertiesOpen=true;drawer=false;renderChrome();f.reportValidity();toast('invalidRoom');return false;}
  updateRoom(n);return true;
}
function cancelDoor(){if(doorRoomId&&scene){scene.readonly=false;scene.editRooms=doorPreviousEdit;}doorNavigation=false;doorEditingId=null;doorRoomId=null;doorPointer=null;$('#placing').hidden=true;document.body.classList.remove('placing-door','door-camera-mode');}
function placeDoorAt(e){
  const r=plan.rooms.find(r=>r.id===doorRoomId),hit=scene?.hit?.(e),p=hit?.object?.userData?.kind==='wall'&&hit.point?hit.point:scene?.point(e);if(!r||!p)return;
  const choices=[['north',Math.hypot(p.x-Math.max(r.x,Math.min(r.x+r.w,p.x)),p.z-r.z),p.x-r.x,r.w],['south',Math.hypot(p.x-Math.max(r.x,Math.min(r.x+r.w,p.x)),p.z-r.z-r.d),p.x-r.x,r.w],['west',Math.hypot(p.x-r.x,p.z-Math.max(r.z,Math.min(r.z+r.d,p.z))),p.z-r.z,r.d],['east',Math.hypot(p.x-r.x-r.w,p.z-Math.max(r.z,Math.min(r.z+r.d,p.z))),p.z-r.z,r.d]].sort((a,b)=>a[1]-b[1]);
  const [side,distance,offset,length]=choices[0];if(distance>.55){toast('doorWallHint');return;}
  const old=plan.openings.find(o=>o.id===doorEditingId),width=old?.w||.9,margin=width/2+.08;const o={id:old?.id||uid(),roomId:r.id,side,type:'door',offset:round(Math.max(margin,Math.min(length-margin,offset))),w:width,h:old?.h||2.1,sill:0};
  if(!validOpening(plan,o)){toast('doorBlocked');return;}
  const moving=!!doorEditingId;commit(p=>{const existing=p.openings.find(x=>x.id===o.id);if(existing)Object.assign(existing,o);else p.openings.push(o);},moving?'doorMoved':'doorAdded');if(moving){cancelDoor();renderChrome();}
}
function doorPoint(e){const hit=scene?.hit?.(e);return hit?.object?.userData?.kind==='wall'&&hit.point?hit.point:scene?.point(e);}
function pickedDoor(e){
  if(!scene||finished||scene.walk||showBefore||scene.pending)return null;const p=doorPoint(e);if(!p)return null;
  let best=null,distance=.3;
  for(const o of plan.openings){if(o.type!=='door')continue;const r=plan.rooms.find(r=>r.id===o.roomId);if(!r)continue;const horizontal=o.side==='north'||o.side==='south',along=horizontal?p.x-r.x:p.z-r.z,across=horizontal?Math.abs(p.z-r.z-(o.side==='south'?r.d:0)):Math.abs(p.x-r.x-(o.side==='east'?r.w:0));const d=Math.hypot(across,Math.max(0,Math.abs(along-o.offset)-o.w/2));if(d<distance){best=o;distance=d;}}
  return best;
}
function draggedDoor(e){
  const p=doorPoint(e),old=doorDrag.original,r=plan.rooms.find(r=>r.id===old.roomId);if(!p||!r)return null;
  const walls=[['north',Math.abs(p.z-r.z),p.x-r.x,r.w],['south',Math.abs(p.z-r.z-r.d),p.x-r.x,r.w],['west',Math.abs(p.x-r.x),p.z-r.z,r.d],['east',Math.abs(p.x-r.x-r.w),p.z-r.z,r.d]].sort((a,b)=>a[1]-b[1]);
  const [side,distance,offset,length]=walls[0],margin=old.w/2+.08;if(distance>.8||length<2*margin)return null;
  const candidate={...old,side,offset:round(Math.max(margin,Math.min(length-margin,offset)))};return validOpening(plan,candidate)?candidate:null;
}
$('#viewport').addEventListener('pointerdown',e=>{
  if(e.button!==0)return;const door=pickedDoor(e);
  if(door){if(!saveRoomDraft())return;e.stopImmediatePropagation();e.preventDefault();doorDrag={original:{...door},candidate:null,x:e.clientX,y:e.clientY};$('#viewport').setPointerCapture(e.pointerId);document.body.classList.add('dragging-door');return;}
  if(doorRoomId)doorPointer={id:e.pointerId,x:e.clientX,y:e.clientY};
},true);
$('#viewport').addEventListener('pointermove',e=>{
  if(!doorDrag)return;e.stopImmediatePropagation();e.preventDefault();if(Math.hypot(e.clientX-doorDrag.x,e.clientY-doorDrag.y)<6)return;
  doorDrag.candidate=draggedDoor(e);document.body.classList.toggle('door-drag-invalid',!doorDrag.candidate);
  const preview=clone(plan);if(doorDrag.candidate)Object.assign(preview.openings.find(o=>o.id===doorDrag.original.id),doorDrag.candidate);scene.rebuild(preview);
},true);
$('#viewport').addEventListener('pointerup',e=>{
  if(doorDrag){e.stopImmediatePropagation();e.preventDefault();const drag=doorDrag,moved=Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>=6;doorDrag=null;document.body.classList.remove('dragging-door','door-drag-invalid');if($('#viewport').hasPointerCapture(e.pointerId))$('#viewport').releasePointerCapture(e.pointerId);if(moved&&drag.candidate)commit(p=>Object.assign(p.openings.find(o=>o.id===drag.original.id),drag.candidate),'doorMoved');else{scene.rebuild(plan);if(moved)toast('doorBlocked');else toast('dragDoorHint');}return;}
  const start=doorPointer;doorPointer=null;if(doorRoomId&&start&&start.id===e.pointerId&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<6)placeDoorAt(e);
},true);
$('#viewport').addEventListener('pointercancel',()=>{doorPointer=null;if(doorDrag){doorDrag=null;scene.rebuild(plan);document.body.classList.remove('dragging-door','door-drag-invalid');}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&doorRoomId)cancelDoor();});

app.addEventListener('click',async e=>{
  const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;if(!['undo','redo','cancel-door','cancel-place'].includes(action)&&!saveRoomDraft())return;if(doorRoomId&&!['door-camera','toggle-views','overview','top','reset'].includes(action))cancelDoor();if(!['toggle-views'].includes(action))document.body.classList.remove('views-open');
  if(action.startsWith('tab-')){tab=action.slice(4);drawer=true;if(scene&&tab!=='layouts'){scene.editRooms=false;scene.select(selected);}renderLibrary();renderChrome();return;}
  if(['material','style','color','rotate','duplicate','delete','delete-room','delete-opening','add-room','add-next-room','add-room-shortcut','blank','template','mode'].includes(action)&&(scene?.walk||showBefore))return toast('notReady');
  switch(action){
    case 'category':category=id;renderLibrary();break;
    case 'furniture':pending(catalog.furniture.find(f=>f.id===id));break;
    case 'cancel-place':pending(null);break;
    case 'deselect':case 'close-panel':roomPropertiesOpen=false;drawer=false;renderChrome();break;
    case 'mobile-settings':roomPropertiesOpen=!roomPropertiesOpen;drawer=false;renderChrome();break;
    case 'toggle-views':document.body.classList.toggle('views-open');break;
    case 'focus-selected-room':if(selected?.kind==='room'&&!scene?.walk&&!showBefore){drawer=false;roomPropertiesOpen=false;renderChrome();scene?.fit(view==='top'?'top':'overview',selectedRoom());}break;
    case 'door-camera':if(doorRoomId){doorNavigation=!doorNavigation;scene.readonly=doorNavigation;scene.editRooms=!doorNavigation;doorPointer=null;if(scene.controls)scene.controls.enabled=true;document.body.classList.toggle('door-camera-mode',doorNavigation);renderChrome();}break;
    case 'manage-doors':{if(selected?.kind!=='room')break;const doors=plan.openings.filter(o=>o.roomId===selected.id&&o.type==='door');openModal(U.moveDoor,doors.length?doors.map((o,i)=>'<div class="saved-plan"><div><strong>'+esc(U.door)+' '+(i+1)+'</strong><small>'+esc(U[o.side])+' · '+o.w+' × '+o.h+' m</small></div>'+button('move-door',U.repositionDoor,'arrow','quiet','data-id="'+o.id+'"')+'</div>').join(''):'<p class="micro">'+U.noDoors+'</p>');break;}
    case 'move-door':{const o=plan.openings.find(o=>o.id===id&&o.type==='door');if(!o||finished||scene?.walk||showBefore)break;$('#modal').close();scene.setPending(null);selected={kind:'room',id:o.roomId};doorRoomId=o.roomId;doorEditingId=o.id;doorNavigation=false;roomPropertiesOpen=false;drawer=false;scene.editRooms=true;scene.select(selected);document.body.classList.add('placing-door');$('#placing').hidden=false;$('#placing').innerHTML='<span>'+esc(U.moveDoorHint)+'</span>'+button('cancel-door',U.cancel,'close','icon-button');renderChrome();break;}
    case 'cancel-door':renderChrome();break;
    case 'add-door':if(selected?.kind==='room'&&!finished&&!scene?.walk&&!showBefore){scene.setPending(null);doorPreviousEdit=scene.editRooms;doorRoomId=selected.id;drawer=false;roomPropertiesOpen=false;scene.editRooms=false;scene.readonly=true;renderChrome();scene.fit(view==='top'?'top':'overview',selectedRoom());$('#placing').hidden=false;$('#placing').innerHTML='<span>'+esc(U.placeDoorHint)+'</span>'+button('cancel-door',U.cancel,'close','icon-button');document.body.classList.add('placing-door');renderChrome();}break;
    case 'room-properties':if(selected?.kind==='room'){roomPropertiesOpen=!roomPropertiesOpen;drawer=false;renderChrome();}break;
    case 'finish-layout':scene.editRooms=false;roomPropertiesOpen=false;drawer=false;choose(null);renderLibrary();renderChrome();break;
    case 'room':if(scene?.walk)enterRoom(plan.rooms.find(r=>r.id===id));else{choose({kind:'room',id});if(finished)scene?.fit('overview',selectedRoom());}break;
    case 'material':{const r=selectedRoom();commit(p=>p.rooms.find(x=>x.id===r.id)[surface]=id,'changed');break;}
    case 'surface-floor':case 'surface-wall':surface=action.slice(8);renderLibrary();break;
    case 'style':{const s=catalog.styles.find(s=>s.id===id);commit(p=>{p.style=s.id;p.rooms.forEach(r=>{r.floor=['bath','kitchen'].includes(r.kind)?'tile':s.floor;r.wall=s.wall;});p.items.forEach((o,i)=>{const f=catalog.furniture.find(f=>f.id===o.catalogId);if(['sofa','chair','bed','pouf','rug'].includes(f.model))o.color=s.colors[i%3];});},'changed');break;}
    case 'color':commit(p=>p.items.find(i=>i.id===selected.id).color=id);break;
    case 'rotate':{const o=plan.items.find(i=>i.id===selected?.id),n={...o,angle:(o.angle+90)%360};if(!placement(plan,n,catalog))toast('invalidPlacement');else commit(p=>Object.assign(p.items.find(i=>i.id===o.id),n));break;}
    case 'duplicate':duplicate();break;
    case 'delete':commit(p=>p.items=p.items.filter(i=>i.id!==selected.id));choose(null);break;
    case 'delete-room':if(plan.rooms.length===1)return toast('emptyRoom');if(confirm(U.deleteAsk)){const rid=selected.id;commit(p=>{p.rooms=p.rooms.filter(r=>r.id!==rid);p.items=p.items.filter(o=>o.roomId!==rid);p.openings=p.openings.filter(o=>o.roomId!==rid&&validOpening(p,o));},'roomDeleted');choose(null);}break;
    case 'delete-opening':commit(p=>p.openings=p.openings.filter(o=>o.id!==id));break;
    case 'edit-opening':{const o=plan.openings.find(o=>o.id===id),form=$('#opening-form');if(o&&form){form.dataset.editId=id;for(const k of ['side','type','offset','w','h','sill'])form.elements[k].value=o[k];form.scrollIntoView({block:'nearest',behavior:'smooth'});}break;}
    case 'clear':if(confirm(U.clearAsk)){commit(p=>p.items=[]);choose(null);}break;
    case 'add-next-room':case 'add-room-shortcut':case 'add-room':{if(plan.rooms.length>=20)return toast('limit');const form=$('#room-form');if(form&&selected?.kind==='room'){if(!form.reportValidity())return;const current=selectedRoom(),fields=form.elements,candidate={...current,name:fields.namedItem('name').value.trim(),w:Number(fields.namedItem('w').value),d:Number(fields.namedItem('d').value),measured:fields.namedItem('measured').checked};if(fields.namedItem('x'))candidate.x=Number(fields.namedItem('x').value);if(fields.namedItem('z'))candidate.z=Number(fields.namedItem('z').value);if(!candidate.name||!validRoom(plan,candidate))return toast('invalidRoom');if(JSON.stringify(current)!==JSON.stringify(candidate))updateRoom(candidate);}const bo=bounds(plan.rooms),r={id:uid(),name:U.newRoomName,x:round(bo.x+bo.w),z:bo.z,w:3,d:3,kind:'living',floor:'oak',wall:'cream',measured:false,textureScale:1,textureAngle:0};if(!validRoom(plan,r))return toast('invalidRoom');commit(p=>p.rooms.push(r));scene.editRooms=true;scene.fit('top');view='top';choose({kind:'room',id:r.id});drawer=false;refresh();$('#inspector').scrollTop=0;break;}
    case 'blank':persist();loadPlan({...makePlan({name:U.newPlanName,rooms:[[U.newRoomName,0,0,5,4,'empty']]},catalog),items:[],openings:[]});scene.editRooms=true;scene.fit('top');view='top';drawer=false;choose({kind:'room',id:plan.rooms[0].id});tab='layouts';refresh();break;
    case 'template':persist();loadPlan(makePlan(catalog.templates.find(t=>t.id===id),catalog));drawer=false;renderChrome();break;
    case 'mode':commit(p=>p.mode=p.mode==='beginner'?'advanced':'beginner');break;
    case 'undo':if(!showBefore&&!scene?.walk){plan=history.undo(plan);refresh();saveSoon();}break;
    case 'redo':if(!showBefore&&!scene?.walk){plan=history.redo(plan);refresh();saveSoon();}break;
    case 'overview':case 'top':if(scene?.walk)scene.exit();view=action;scene?.fit(action);renderChrome();break;
    case 'reset':scene?.fit(view);renderChrome();break;
    case 'inside':case 'focus-room':if(showBefore){showBefore=false;scene?.rebuild(plan);}enterRoom(selectedRoom());break;
    case 'walk-corner':enterRoom(selectedRoom(),true);break;
    case 'walk-center':enterRoom(selectedRoom());break;
    case 'exit-walk':scene?.exit();selected=selectionBeforeWalk;scene?.select(selected);renderInspector();renderChrome();break;
    case 'light':night=!night;scene?.lighting(night);b.innerHTML=icon(night?'sun':'moon');b.title=night?U.day:U.night;b.setAttribute('aria-label',b.title);renderChrome();break;
    case 'finish':if(scene?.walk)scene.exit();pending(null);finished=!finished;drawer=false;scene.readonly=finished;choose(null);renderChrome();scene?.fit();break;
    case 'compare':if(scene?.walk)scene.exit();pending(null);comparing=!comparing;showBefore=false;scene?.rebuild(plan);scene.readonly=finished;renderChrome();break;
    case 'show-before':showBefore=true;scene?.rebuild(baseline);scene.readonly=true;renderChrome();break;
    case 'show-after':showBefore=false;scene?.rebuild(plan);scene.readonly=finished;renderChrome();break;
    case 'baseline':baseline=clone(plan);persist();toast('memory');break;
    case 'copy-plan':persist();plan=clone(plan);plan.id=uid();plan.name=(plan.name+U.planSuffix).slice(0,60);baseline=clone(plan);blockedStorage=false;history=new History();persist();$('#modal').close();refresh();toast('copied');break;
    case 'plans':plansModal();break;
    case 'open-plan':loadPlan(db.plans.find(p=>p.id===id));break;
    case 'delete-plan':if(confirm(U.planDeleteAsk)){db.plans=db.plans.filter(p=>p.id!==id);delete db.baselines[id];persist();plansModal();}break;
    case 'close-modal':$('#modal').close();break;
    case 'inventory':inventoryModal();break;
    case 'json':download(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}),safeFilename()+'.json');break;
    case 'csv':{const inv=inventory(plan,catalog),rows=[[U.name,U.location,U.size,U.quantity,U.unitPrice],...[...inv.furniture,...inv.materials].map(r=>[r.name,r.rooms.join('、'),r.surface?U[r.surface]:r.size+' m',r.unknown?U.pending:r.quantity+(r.surface?' m²':''),plan.prices[r.key]??''])];download(new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),safeFilename()+'.csv');break;}
    case 'capture':try{b.disabled=true;await previewExportImage(await scene.capture());}catch{toast('downloadFailed');}finally{b.disabled=false;}break;
    case 'save-album':{const bridge=window.xhs&&window.xhs.miniTool;if(!bridge||typeof bridge.writeTempFile!=='function'||typeof bridge.saveImageToPhotosAlbum!=='function'){toast('albumUnavailable');break;}if(!exportImageData||albumSaving)break;albumSaving=true;b.disabled=true;const data=exportImageData;try{const result=await bridge.writeTempFile({data});if(!result||typeof result.filePath!=='string'||!result.filePath)throw new Error('Missing image path');await bridge.saveImageToPhotosAlbum({filePath:result.filePath});toast('savedAlbum');}catch{toast('albumFailed');}finally{albumSaving=false;b.disabled=false;}break;}
    case 'import':$('#import-file').click();break;
    case 'help':openModal(U.help,`<div class="help-art">${icon('home')}</div><p class="help-copy">${U.helpText}</p><p class="micro">${U.constructionNote}</p>`);break;
  }
});
app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;$('#furniture-grid').innerHTML=furnitureCards();}});
app.addEventListener('change',e=>{
  const t=e.target;if(t.id==='plan-name'){const name=t.value.trim();if(name)commit(p=>p.name=name);else t.value=plan.name;}
  if(t.id==='custom-color')commit(p=>p.items.find(i=>i.id===selected.id).color=t.value);
  if(t.id==='material-room'){choose({kind:'room',id:t.value});renderLibrary();}
  if(t.id==='snap'){snap=t.checked;scene.snap=snap;}
  if(t.id==='room-edit'){scene.editRooms=t.checked;roomPropertiesOpen=false;drawer=false;if(t.checked){scene.fit('top');view='top';choose({kind:'room',id:selectedRoom().id});}scene.select(selected);renderChrome();}
  if(t.dataset.price){const v=t.value===''?null:Number(t.value);if(v!==null&&(!Number.isFinite(v)||v<0||v>10000000))return toast('invalidNumber');commit(p=>{if(v===null)delete p.prices[t.dataset.price];else p.prices[t.dataset.price]=v;});const inv=inventory(plan,catalog);$('#price-total').textContent='¥ '+round([...inv.furniture,...inv.materials].reduce((s,r)=>s+(r.unknown?0:r.quantity*(plan.prices[r.key]||0)),0)).toLocaleString();}
});
app.addEventListener('submit',e=>{e.preventDefault();if(scene?.walk||showBefore)return toast('notReady');const f=e.target,fd=new FormData(f),num=k=>Number(fd.get(k));
  if(f.id==='item-form'){const o=plan.items.find(o=>o.id===selected.id),n={...o,...Object.fromEntries(['w','d','h','angle','x','z'].map(k=>[k,num(k)]))},r=placement(plan,n,catalog);if(!r)return toast('invalidPlacement');n.roomId=r.id;commit(p=>Object.assign(p.items.find(i=>i.id===n.id),n));}
  if(f.id==='room-form'){const r=selectedRoom();updateRoom({...r,name:String(fd.get('name')).trim()||r.name,w:num('w'),d:num('d'),x:fd.has('x')?num('x'):r.x,z:fd.has('z')?num('z'):r.z,measured:fd.has('measured')});}
  if(f.id==='opening-form'){const o={id:f.dataset.editId||uid(),roomId:selectedRoom().id,side:String(fd.get('side')),type:String(fd.get('type')),offset:num('offset'),w:num('w'),h:num('h'),sill:num('sill')};if(!validOpening(plan,o))return toast('invalidPlacement');commit(p=>{const existing=p.openings.find(x=>x.id===o.id);if(existing)Object.assign(existing,o);else p.openings.push(o);},'changed');}
  if(f.id==='global-form'){const n={...plan,wallHeight:num('wallHeight'),wallThickness:num('wallThickness')};if(!n.openings.every(o=>validOpening(n,o)))return toast('invalidPlacement');commit(p=>{p.wallHeight=n.wallHeight;p.wallHeightMeasured=fd.has('wallHeightMeasured');p.wallThickness=n.wallThickness;p.buildingArea=fd.get('buildingArea')===''?null:num('buildingArea');Object.assign(p.rooms.find(r=>r.id===selectedRoom().id),{textureScale:num('textureScale'),textureAngle:num('textureAngle')});});}
});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw new Error();const p=validatePlan(JSON.parse(await file.text()),catalog);persist();p.id=uid();blockedStorage=false;loadPlan(p);toast('imported');}catch{toast('importError');}e.target.value='';});
app.addEventListener('dragstart',e=>{const card=e.target.closest('[data-action="furniture"]');if(card){e.dataTransfer.setData('text/plain',card.dataset.id);e.dataTransfer.effectAllowed='copy';}});
$('#viewport').addEventListener('dragover',e=>e.preventDefault());$('#viewport').addEventListener('drop',e=>{e.preventDefault();const def=catalog.furniture.find(f=>f.id===e.dataTransfer.getData('text/plain'));if(def&&!showBefore&&!scene?.walk){const p=scene.point(e);if(p)place(def,p);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){pending(null);drawer=false;if(scene?.walk)scene.exit();renderChrome();}if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('#modal').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(!showBefore&&!scene?.walk){plan=e.shiftKey?history.redo(plan):history.undo(plan);refresh();saveSoon();}}if(e.key==='Delete'&&selected?.kind==='item'&&!finished)commit(p=>p.items=p.items.filter(o=>o.id!==selected.id));});
window.addEventListener('pagehide',persist);
try{
  scene=new RoomScene($('#viewport'),catalog,{select:choose,message:toast,place,move:drag=>{if(drag.kind==='item'){const r=placement(plan,drag.candidate,catalog);if(!r){toast('invalidPlacement');scene.rebuild(plan);}else commit(p=>Object.assign(p.items.find(i=>i.id===drag.id),drag.candidate,{roomId:r.id}));}else updateRoom(drag.candidate);}});
  scene.rebuild(plan);scene.fit();thumbs=scene.thumbnails();refresh(false);if(blockedStorage)toast('storageCorrupt');else persist();
}catch(error){console.error(error);$('#viewport').innerHTML=`<div class="webgl-error">${icon('home')}<p>${U.webglError}</p>${button('json',U.exportJSON,'download','primary')}</div>`;refresh(false);}
