import {spawn} from 'node:child_process';import {mkdir,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),port=9332;
const child=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run',`--remote-debugging-port=${port}`,`--user-data-dir=${join(root,'promo/sylus/.browser-profile')}`,'about:blank'],{stdio:'ignore'});
const wait=ms=>new Promise(r=>setTimeout(r,ms));let ws,sequence=0;const pending=new Map(),report=[];
function command(method,params={}){return new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await command('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function until(expression){for(let i=0;i<140;i++){if(await evaluate(expression))return;await wait(100);}throw Error('Timed out: '+expression);}
async function assert(expression,message){if(!await evaluate(expression))throw Error(message);}
async function click(selector){await assert(`!!document.querySelector(${JSON.stringify(selector)})`,'Missing '+selector);await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);}
async function change(selector,value){await evaluate(`(()=>{const t=document.querySelector(${JSON.stringify(selector)});if(!t)throw Error('Missing input');${typeof value==='boolean'?`t.checked=${value}`:`t.value=${JSON.stringify(value)}`};t.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function screenshot(name){if(!['studio-call-editor-390','studio-chat-editor-390','studio-moment-editor-390','studio-group-390','studio-return-chat-390','studio-home-390','studio-incoming-390','studio-connected-390','studio-chat-390','studio-moment-390','studio-people-390','studio-person-edit','studio-picker','studio-moment-with-photos','studio-landscape-connected','studio-moment-menu','studio-moment-composer'].includes(name))return;const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(root,'qa/output',name+'.png'),Buffer.from(r.data,'base64'));}
async function upload(selector,files){const {root:doc}=await command('DOM.getDocument');const {nodeId}=await command('DOM.querySelector',{nodeId:doc.nodeId,selector});await command('DOM.setFileInputFiles',{nodeId,files});await wait(100);}
async function viewport(w,h){await command('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:true,screenWidth:w,screenHeight:h});await command('Page.reload',{ignoreCache:true});await until("!!document.querySelector('.studio-hero')");await evaluate("document.documentElement.style.setProperty('--safe-area-inset-top','24px')");}
async function check(name,w){await until('[...document.images].every(i=>i.complete)');await assert('[...document.images].every(i=>i.naturalWidth>0)','Broken image');const r=await evaluate(`(()=>{const W=innerWidth,H=innerHeight,rootStyle=getComputedStyle(document.documentElement),hostBottom=(parseFloat(rootStyle.getPropertyValue('--safe-area-inset-top'))||0)+(parseFloat(rootStyle.getPropertyValue('--host-control-zone'))||48);const rects=[{left:0,right:76,top:0,bottom:hostBottom},{left:W-76,right:W,top:0,bottom:hostBottom}];const hits=[...document.querySelectorAll('button,input,select,textarea,.page-head h1,.social-head b')].filter(el=>{const r=el.getBoundingClientRect();return r.width&&r.height&&r.bottom>0&&r.top<H&&rects.some(o=>r.left<o.right&&r.right>o.left&&r.top<o.bottom&&r.bottom>o.top)}).map(el=>el.getAttribute('aria-label')||el.textContent.slice(0,25));return {width:W,overflow:document.documentElement.scrollWidth>W,hits}})()`);if(r.overflow||r.hits.length||r.width!==w)throw Error(name+': '+JSON.stringify(r));
  await evaluate(`(()=>{for(const side of ['left','right']){const d=document.createElement('div');d.className='qa-host';d.textContent=side==='left'?'‹':'•••';d.style.cssText='position:fixed;top:24px;'+side+':8px;width:56px;height:38px;border-radius:22px;background:#18251eaa;color:white;display:grid;place-items:center;z-index:99999;pointer-events:none;font:20px sans-serif;';document.body.append(d)}})()`);await screenshot(name);await evaluate("document.querySelectorAll('.qa-host').forEach(x=>x.remove())");report.push({name,...r});console.log(name+' ✓');}
try{await mkdir(join(root,'qa/profile'),{recursive:true});let target;for(let i=0;i<80;i++){try{target=(await fetch(`http://127.0.0.1:${port}/json/list`).then(r=>r.json())).find(x=>x.type==='page');if(target)break;}catch{}await wait(100);}if(!target)throw Error('Chrome unavailable');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});ws.onmessage=event=>{const m=JSON.parse(event.data);const p=pending.get(m.id);if(!p)return;pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);};await command('Page.enable');await command('Runtime.enable');

 await command('Emulation.setDeviceMetricsOverride',{width:390,height:760,deviceScaleFactor:3,mobile:true});
 await command('Page.navigate',{url:'http://127.0.0.1:4317'});await until("!!document.querySelector('.studio-hero')");
 await evaluate("localStorage.clear()");await command('Page.reload');await until("!!document.querySelector('.studio-hero')");
 await click('[data-tab=chat]');await change('[data-message-text="0"]','喂');
 await evaluate(`(()=>{const s=JSON.parse(localStorage.getItem('call-stories:studio-v2'));s.people.find(p=>p.id==='basketball').name='秦彻';s.people.find(p=>p.id==='self').name='我';s.people.find(p=>p.id==='self').avatar='peach';s.chat.title='秦彻';s.chat.timeParts={format:'weekday',weekday:5,month:9,day:18,hour:18,minute:20};s.chat.messages=[['basketball','下楼。'],['self','你怎么来了？'],['basketball','有人说今天不想一个人吃饭。'],['self','我就随口一说。'],['basketball','嗯。我顺路。'],['self','从N109区顺到我家？'],['basketball','还顺路买了你想吃的栗子。'],['self','……你等我五分钟。'],['basketball','不急。外套穿上。']].map(([personId,text])=>({personId,text}));s.call.personId='basketball';s.call.ringtone=false;s.moment.authorId='self';s.moment.text='某人嘴里的顺路。\\n绕半座城，还要排二十分钟的队。';s.moment.timeParts={format:'minutes',amount:5,month:9,day:18,weekday:5,hour:19,minute:0};s.moment.likes=['basketball'];s.moment.comments=[{personId:'basketball',text:'栗子还堵不住你的嘴？'},{personId:'self',text:'那你下次别绕路。'},{personId:'basketball',text:'下次想吃什么？'}];localStorage.setItem('call-stories:studio-v2',JSON.stringify(s))})()`);
 await command('Page.reload');await until("!!document.querySelector('.studio-hero')");await click('[data-tab=person]');await click('[data-edit-person=basketball]');await upload('[data-upload=person]',[join(root,'promo/sylus/portrait.png')]);await click('[data-action=back-people]');await click('[data-edit-person=self]');await upload('[data-upload=person]',[join(root,'promo/sylus/heroine-avatar.png')]);await click('[data-action=back-people]');
 async function shot(name){await until('[...document.images].every(i=>i.complete)');await evaluate(`(()=>{let s=document.getElementById('promo-style');if(!s){s=document.createElement('style');s.id='promo-style';s.textContent=':root{--host-control-zone:0px}.export-actions{display:none!important}.social-screen{min-height:100vh!important}.avatar img{object-position:center 20%}';document.head.append(s)}})()`);const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(root,'promo/sylus',name+'.png'),Buffer.from(r.data,'base64'));}
 await click('[data-tab=chat]');await click('[data-action=preview-chat]');await shot('01-chat-girl');await click('[data-action=edit-chat]');await click('[data-tab=moment]');await click('[data-action=preview-moment]');await shot('02-moments-girl');await click('[data-action=edit-moment]');await click('[data-tab=story]');await click('[data-action=edit-call]');await click('[data-action=start]');await shot('03-incoming');
 console.log('Created three promotional screenshots');
}finally{ws?.close();child.kill();}
