import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.argv[2] || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('artifacts', { recursive: true });
const base = 'http://127.0.0.1:4311';
await page.goto(base);
await page.waitForSelector('[data-action=start]');
await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
const results = [];
for (const width of [375, 390, 430]) {
  await page.setViewportSize({ width, height: 844 });
  await page.evaluate(() => document.documentElement.style.setProperty('--safe-area-inset-top', '44px'));
  for (const route of ['focus', 'garden', 'journal']) {
    await page.locator(`nav [data-action=${route}]`).click();
    const metrics = await page.evaluate(() => ({ width: innerWidth, content: document.documentElement.scrollWidth, brandTop: document.querySelector('.brand').getBoundingClientRect().top }));
    assert(metrics.content <= width, `Horizontal overflow: ${width}/${route}`);
    assert(metrics.brandTop >= 44, `Unsafe header: ${width}/${route}`);
    results.push({ width, route, ...metrics });
  }
  await page.locator('nav [data-action=focus]').click();
  await page.locator('[data-action=seeds]').click();
  assert(await page.locator('.modal').evaluate(el => el.getBoundingClientRect().top) >= 44);
  await page.keyboard.press('Escape');
  await page.screenshot({ path: `artifacts/mobile-${width}.png`, fullPage: true });
}
await page.clock.install();
await page.locator('#task').fill('读完一章 <书>');
await page.locator('[data-action=start]').click();
await page.clock.fastForward(5 * 60000);
await page.locator('[data-action=pause]').click();
const paused = await page.locator('#timer').textContent();
await page.clock.fastForward(10 * 60000);
assert.equal(await page.locator('#timer').textContent(), paused);
await page.reload();
await page.waitForSelector('[data-action=pause]');
assert.equal(await page.locator('#timer').textContent(), paused);
await page.locator('[data-action=pause]').click();
await page.clock.fastForward(20 * 60000 + 1000);
await page.waitForSelector('[role=dialog]');
let saved = await page.evaluate(() => JSON.parse(localStorage.getItem('tomato-garden-v1')));
assert.equal(saved.total, 25); assert.equal(saved.records.length, 1); assert(saved.records[0].complete);
await page.locator('[data-action=rest]').click();
await page.clock.fastForward(5 * 60000 + 1000);
await page.waitForSelector('[role=dialog]');
saved = await page.evaluate(() => JSON.parse(localStorage.getItem('tomato-garden-v1')));
assert.equal(saved.total, 25);
await page.locator('.close').click();
await page.locator('[data-action=start]').click();
await page.clock.fastForward(2 * 60000 + 15000);
await page.locator('[data-action=finish]').click();
await page.locator('[data-action=confirm-finish]').click();
saved = await page.evaluate(() => JSON.parse(localStorage.getItem('tomato-garden-v1')));
assert.equal(saved.total, 27); assert.equal(saved.records.length, 2); assert.equal(saved.records[1].complete, false);
await page.reload();
await page.waitForSelector('[data-action=start]');
saved = await page.evaluate(() => JSON.parse(localStorage.getItem('tomato-garden-v1')));
assert.equal(saved.total, 27);
await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('tomato-garden-v1')); s.total = 400; s.progress.tomato = 150; localStorage.setItem('tomato-garden-v1', JSON.stringify(s)); });
await page.reload();
await page.locator('[data-action=collect]').click();
await page.locator('[data-action=select][data-id=sunflower]').click();
assert.equal(await page.locator('.plant-caption h2').textContent(), '向日葵种子');
saved = await page.evaluate(() => JSON.parse(localStorage.getItem('tomato-garden-v1')));
assert.equal(saved.collection.length, 1); assert.equal(saved.progress.tomato, 0);
await page.locator('nav [data-action=garden]').click();
await page.screenshot({ path: 'artifacts/garden.png', fullPage: true });
await page.locator('nav [data-action=journal]').click();
assert((await page.locator('.records').textContent()).includes('读完一章 <书>'));
await page.screenshot({ path: 'artifacts/journal.png', fullPage: true });
assert.equal(errors.length, 0, errors.join('\n'));
await writeFile('artifacts/browser-results.json', JSON.stringify({ results, checks: ['pause', 'refresh restore', 'completion', 'no duplicate reward', 'rest no growth', 'partial settlement', 'collection', 'unlocked selection', 'escaped task text', 'modal safe area'], errors }, null, 2));
await browser.close();
console.log('Browser checks passed: 375 / 390 / 430px, 44px safe area, timer and growth flows.');
