import test from 'node:test';import assert from 'node:assert/strict';import {createSound} from '../src/sound.js';import {jellyImpact,liquidStream} from '../src/sound-texture.js';
test('audio initializes on interaction, reuses the pour buffer, and stops all sources on mute and suspension',t=>{
 let contexts=0,buffers=0;const nodes=[];const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}});
 function node(){const n={threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),gain:param(),connect(){},disconnect(){},start(){},stop(time){assert.ok(Number.isFinite(time));this.stopped=true}};nodes.push(n);return n;}
 const old=globalThis.AudioContext;globalThis.AudioContext=class{constructor(){contexts++;this.currentTime=1;this.sampleRate=8000;this.state='running';this.destination={}}createDynamicsCompressor(){return node()}createGain(){return node()}createBufferSource(){const n=node();n.source=true;return n}createBuffer(ch,length,rate){buffers++;const data=new Float32Array(length);return {duration:length/rate,getChannelData:()=>data}}suspend(){this.state='suspended';return Promise.resolve()}resume(){return Promise.resolve()}};t.after(()=>{if(old)globalThis.AudioContext=old;else delete globalThis.AudioContext});
 const sound=createSound({volume:.3,pourVolume:.25,maxVoices:2});sound.setEnabled(true);assert.equal(contexts,0);sound.impact();assert.equal(contexts,1);sound.startPour();sound.startPour();assert.equal(nodes.filter(n=>n.source).length,2);const count=buffers;sound.stopPour();sound.startPour();assert.equal(buffers,count);sound.setEnabled(false);assert.ok(nodes.filter(n=>n.source).every(n=>n.stopped));const before=nodes.length;sound.impact();sound.startPour();assert.equal(nodes.length,before);sound.setEnabled(true);sound.startPour();sound.suspend();assert.ok(nodes.filter(n=>n.source).every(n=>n.stopped));
});
test('generated liquid and jelly sounds are deterministic, finite, click-free at endpoints and below clipping',()=>{for(const make of [jellyImpact,liquidStream]){const a=make(8000),b=make(8000);assert.deepEqual(a,b);let peak=0,power=0;for(const x of a){assert.ok(Number.isFinite(x));peak=Math.max(peak,Math.abs(x));power+=x*x;}assert.ok(peak<1&&peak>.02);assert.ok(power>0);assert.equal(Math.abs(a[0]),0);assert.ok(Math.abs(a.at(-1))<.001);}});
test('duang rings out after the initial press and fades rather than ending with a hard transient',()=>{const a=jellyImpact(8000);const rms=(start,end)=>Math.sqrt(a.slice(start,end).reduce((v,x)=>v+x*x,0)/(end-start));assert.ok(rms(1600,2400)>.01);assert.ok(rms(5000,5800)<rms(1600,2400));});
