import C from './content/content.json';import {generate,readSave,reveal,digAt,scrapeGround,tick,catchItem,release,normalize,checkChallenges,challengeProgress,daySeed,rockProgress,rockCenter,covered,type Save,type Spot,type Find} from './model';import {Scene,specimen,whenSpecimensReady} from './render';import {AudioBank} from './audio-bank';
declare global{interface Window{BEACH_AUDIO?:{[key:string]:string}}}
const $=(id:string)=>document.getElementById(id)!,canvas=$('scene') as HTMLCanvasElement,scene=new Scene(canvas),panel=$('panel'),T=C.copy;let s:Save,future=false;try{const raw=localStorage.getItem(C.storageKey);future=Number(JSON.parse(raw||'null')?.version)>2;s=normalize(readSave(raw)||{beach:generate(Date.now()>>>0),zone:0,bucket:[],album:[]});}catch{s=normalize({beach:generate(Date.now()>>>0),zone:0,bucket:[],album:[]});}let tool=C.profiles[s.zone].tool,paused=false,raf=0,last=0,time=0,acc=0,drawAt=0,saveFailed=false,windowMs=0,frames=0,slow=0,held:Find|null=null;
let flight:{item:Find;start:number}|null=null;
let drag:{id:number;x:number;y:number;startX:number;startY:number;travel:number;digs:number;spot:Spot|null;progress:number}|null=null;
const audio=new AudioBank(window.BEACH_AUDIO||{},C.audio.groups,C.audio.gain,()=>{$('hint').textContent=T.silent;});scene.reduced=!!s.settings?.reduced;
$('title').textContent=C.title;document.documentElement.style.setProperty('--host-reserved-x',(C.layout.hostWidth+C.layout.hostOffset+C.layout.hostMargin)+'px');
function hint(text?:string){$('eyebrow').textContent=C.zones[s.zone];$('hint').textContent=text||[T.hint,T.sandHint,T.poolHint,T.kelpHint,T.sandHint,T.mixedHint][s.zone];if(s.mode==='practice')$('hint').textContent=T.practice+' · '+$('hint').textContent;if(saveFailed)$('hint').textContent=T.saveError;}
function save(){checkChallenges(s);if(future)return;try{localStorage.setItem(C.storageKey,JSON.stringify(s));saveFailed=false;}catch{saveFailed=true;hint();}}
function stop(){drag=null;held=null;audio.stop();}function button(text:string,fn:()=>void,parent:HTMLElement){const b=document.createElement('button');b.textContent=text;b.addEventListener('click',fn);parent.appendChild(b);return b;}function para(text:string,parent:HTMLElement){const p=document.createElement('p');p.textContent=text;parent.appendChild(p);return p;}
function close(){panel.hidden=true;paused=false;last=0;acc=0;ui();hint();}function show(title:string,note:string,build:(b:HTMLElement)=>void,back=close,label=T.close){stop();save();paused=true;panel.textContent='';panel.setAttribute('aria-label',title);const h=document.createElement('h2');h.textContent=title;panel.appendChild(h);para(note,panel);const body=document.createElement('div');body.className='body';panel.appendChild(body);build(body);const b=button(label,back,panel);b.className='exit';panel.hidden=false;body.scrollTop=0;b.focus();}
function newBeach(seed:number,mode:Save['mode']){if(s.mode==='daily')s.dailyCache={beach:s.beach,zone:s.zone};s.history=[s.beach.seed,...(s.history||[]).filter(v=>v!==s.beach.seed)].slice(0,20);if(mode==='daily'&&s.dailyCache?.beach.seed===seed){s.beach=s.dailyCache.beach;s.zone=s.dailyCache.zone;s.mode='daily';}else{s.beach=generate(seed);s.mode=mode==='daily'&&s.dailySeeds!.includes(seed)?'practice':mode;s.zone=0;}tool=C.profiles[s.zone].tool;if(mode==='daily'&&!s.dailySeeds!.includes(seed))s.dailySeeds=s.dailySeeds!.concat(seed).slice(-400);save();close();}
function journal(){show(T.journal,T.progress+' '+s.completed!.length+'/24',body=>{button(T.places,()=>show(T.places,'',b=>C.zones.forEach((name,i)=>button(name,()=>{s.zone=i;tool=C.profiles[s.zone].tool;save();close();},b)),journal,T.back),body);button(T.challenges,()=>show(T.challenges,T.progress+' '+s.completed!.length+'/24',b=>C.challenges.forEach(ch=>{const row=button((s.completed!.includes(ch.id)?'✓ ':'')+ch.name+' · '+Math.min(challengeProgress(s,ch.id),ch.target)+'/'+ch.target,()=>{newBeach(ch.seed,'practice');s.zone=Math.floor(ch.id/4);tool=C.profiles[s.zone].tool;save();close();hint(ch.hint);},b);para(ch.hint,row);}),journal,T.back),body);button(T.daily,()=>{const seed=daySeed();if(s.beach.seed===seed){close();return;}newBeach(seed,'daily');},body);para(T.dailyNote,body);button(T.next,()=>show(T.newTitle,T.newNote,b=>button(T.confirm,()=>newBeach(Date.now()>>>0,'free'),b),journal,T.cancel),body);button(T.history,()=>show(T.history,T.practice,b=>(s.history||[]).forEach(seed=>button('#'+seed,()=>newBeach(seed,'practice'),b)),journal,T.back),body);button(T.settings,settings,body);});}
function settings(){show(T.settings,T.source,body=>{button(s.settings!.sound?T.soundOn:T.soundOff,()=>{s.settings!.sound=!s.settings!.sound;if(s.settings!.sound)void audio.enable();else audio.mute();save();settings();},body);button(s.settings!.assist?T.assistOn:T.assistOff,()=>{s.settings!.assist=!s.settings!.assist;save();settings();},body);button(s.settings!.reduced?T.reduceOn:T.reduceOff,()=>{s.settings!.reduced=!s.settings!.reduced;scene.reduced=s.settings!.reduced;save();settings();},body);},journal,T.back);}
function card(m:Find,back=bucket){const item=C.species[m.kind];show(item.name,T.inspect,b=>{const c=document.createElement('canvas');c.className='specimen';c.width=400;c.height=240;b.appendChild(c);whenSpecimensReady(()=>{const ctx=c.getContext('2d')!;ctx.clearRect(0,0,400,240);specimen(ctx,m,200,120,180);});para(item.description,b);para(item.note,b);para(T.where+' · '+C.zones.filter((_,i)=>C.profiles[i].pool.includes(m.kind)).join(' / '),b);if(item.living&&m.state==='caught')button(T.release,()=>{m.state='released';for(const z of s.beach.zones)for(const p of z)if(p.item?.id===m.id)p.item.state='released';for(const v of s.bucket)if(v.id===m.id)v.state='released';save();close();hint(T.released);},b);},back,T.close);}
function bucket(){show(T.bucket,s.album.length+'/24 '+T.record,body=>{if(!s.bucket.some(m=>m.state==='caught'))para(T.empty,body);s.bucket.filter(m=>m.state==='caught').forEach(m=>button(C.species[m.kind].name,()=>card(m),body));button(T.album,album,body);button(T.release,()=>{release(s);save();bucket();},body);});}
function album(){show(T.album,s.album.length+'/24',body=>{body.className='body grid';C.species.forEach((item,i)=>button(s.album.includes(i)?item.name:T.unknown,()=>{if(s.album.includes(i))card({id:'album:'+i,kind:i,x:0,y:0,depth:0,state:'released',age:0},album);else show(T.unknown,T.where,b=>para(C.zones.filter((_,z)=>C.profiles[z].pool.includes(i)).join(' / '),b),album,T.album);},body));},bucket,T.bucket);}
function ui(){$('tools').textContent='';for(const [name,i]of [[T.hand,0],[T.shovel,1],[T.net,2]] as [string,number][]){const b=button((tool===i?'● ':'')+name,()=>{stop();tool=i;ui();hint();},$('tools'));b.setAttribute('aria-pressed',String(tool===i));}button(T.journal,journal,$('tools'));button(T.bucket,bucket,$('tools'));}
function blocked(x:number,y:number){const edge=C.layout.hostWidth+C.layout.hostOffset+C.layout.hostMargin,top=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--safe-area-inset-top'))||0;return y<top+C.layout.hostHeight+C.layout.hostOffset+C.layout.hostMargin&&(x<edge||x>innerWidth-edge);}
function visibleAt(x:number,y:number){return s.beach.zones[s.zone].map(p=>p.item).filter((m):m is Find=>!!m&&m.state==='visible'&&!s.beach.zones[s.zone].some(p=>p.item===m&&['rock','kelp'].includes(C.profiles[s.zone].type)&&covered(p,m))&&Math.hypot(m.x-x,m.y-y)<.045).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];}
function pickup(m:Find){if(!catchItem(s,m))return;audio.play('pick',.65);save();flight={item:{...m},start:time};}
function down(id:number,x:number,y:number){if(paused||drag||flight||blocked(x,y))return;const p=scene.point(x,y),zone=s.beach.zones[s.zone];const sandy=['sand','mixed'].includes(C.profiles[s.zone].type);if(sandy? p.x<-.5||p.x>1.5||p.y<-.7||p.y>1.7 :p.x<0||p.x>1||p.y<0||p.y>1)return;if(s.settings!.sound&&!audio.enabled)void audio.enable();const spot=zone.filter(v=>{const q=['rock','kelp'].includes(C.profiles[s.zone].type)?rockCenter(v):v;return Math.hypot(q.x-p.x,q.y-p.y)<v.r*1.2;}).sort((a,b)=>{const q=rockCenter(a),r=rockCenter(b);return Math.hypot(q.x-p.x,q.y-p.y)-Math.hypot(r.x-p.x,r.y-p.y);})[0]||null,m=visibleAt(p.x,p.y);if(tool===0&&m){if(!C.species[m.kind].living||m.kind>=6){pickup(m);return;}held=m;hint(T.grab);}drag={id,x:p.x,y:p.y,startX:p.x,startY:p.y,travel:0,digs:0,spot,progress:spot?.open?1:0};if(tool===2&&spot?.water)spot.explored=true;if(tool===2&&spot?.water&&m){held=m;hint(T.grab);}else if(tool===1&&spot&&!spot.water&&!['rock','kelp'].includes(C.profiles[s.zone].type)&&s.settings!.assist){if(digAt(spot,p.x,p.y)){scene.throwSand(p.x,p.y);audio.play('sand',.7);drag.digs++;}}}
function move(id:number,x:number,y:number){if(!drag||drag.id!==id)return;const p=scene.point(x,y),distance=Math.hypot(p.x-drag.x,p.y-drag.y);drag.travel+=distance;const profile=C.profiles[s.zone].type;if(!held&&tool===0&&(profile==='rock'||profile==='kelp')&&drag.spot){if(!drag.spot.open&&Math.abs(p.x-drag.startX)>.008)drag.spot.shift=p.x<drag.startX?-1:1;drag.progress=rockProgress(drag.spot,p.x-drag.startX,!!s.settings?.assist);}
if(tool===1&&['sand','mixed'].includes(profile)&&drag.travel>C.digging.strokeTravel){const result=scrapeGround(s.beach,s.zone,p.x,p.y);drag.travel=0;scene.throwSand(p.x,p.y);audio.play('sand',.35);drag.digs++;hint(result.spot?.item?.state==='visible'?T.ready:result.spot?result.spot.dig>=5.9?T.bottom:T.sandHint:T.emptyScrape);}

if(tool===2&&!held){const m=visibleAt(p.x,p.y),home=s.beach.zones[s.zone].find(v=>v.item===m);if(m&&home?.water){held=m;home.explored=true;audio.play('water',.5);hint(T.grab);}}
drag.x=p.x;drag.y=p.y;}
function up(id:number,cancel=false){if(drag?.id!==id)return;const m=held,x=scene.ox+drag.x*scene.k,y=scene.oy+drag.y*scene.k,drop=x>innerWidth-112&&y>innerHeight-155;if(!cancel&&!held&&tool===0&&drag.spot&&['rock','kelp'].includes(C.profiles[s.zone].type)){drag.spot.open=drag.progress>=.6;drag.spot.explored=drag.spot.explored||drag.spot.open;reveal(drag.spot,0);if(drag.spot.open)hint(drag.spot.item?.state==='visible'?T.rockFound:T.rockEmpty);else hint(T.rockClosed);audio.play('water',.45);}drag=null;held=null;if(m&&!cancel&&drop)pickup(m);else if(m)hint(T.cancelDrag);save();}
if(typeof PointerEvent!=='undefined'){canvas.addEventListener('pointerdown',e=>{down(e.pointerId,e.clientX,e.clientY);if(drag)try{canvas.setPointerCapture(e.pointerId);}catch{}});canvas.addEventListener('pointermove',e=>move(e.pointerId,e.clientX,e.clientY));canvas.addEventListener('pointerup',e=>up(e.pointerId));canvas.addEventListener('pointercancel',e=>up(e.pointerId,true));canvas.addEventListener('lostpointercapture',e=>up(e.pointerId,true));}else{canvas.addEventListener('touchstart',e=>{if(e.touches.length===1){const t=e.touches[0];down(t.identifier,t.clientX,t.clientY);}},{passive:true});canvas.addEventListener('touchmove',e=>{if(drag){e.preventDefault();for(const t of Array.from(e.changedTouches))move(t.identifier,t.clientX,t.clientY);}},{passive:false});canvas.addEventListener('touchend',e=>{for(const t of Array.from(e.changedTouches))up(t.identifier);});canvas.addEventListener('touchcancel',()=>{if(drag)up(drag.id,true);});canvas.addEventListener('mousedown',e=>{if(!e.button)down(-1,e.clientX,e.clientY);});window.addEventListener('mousemove',e=>move(-1,e.clientX,e.clientY));window.addEventListener('mouseup',()=>up(-1));}
function pause(){show(T.pause,'',()=>{},close,T.resume);}window.addEventListener('resize',()=>{stop();scene.resize();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();save();paused=true;cancelAnimationFrame(raf);raf=0;}else{last=0;acc=0;pause();if(!raf)raf=requestAnimationFrame(frame);}});window.addEventListener('pagehide',()=>{stop();save();cancelAnimationFrame(raf);raf=0;});window.addEventListener('pageshow',()=>{last=0;if(!raf)raf=requestAnimationFrame(frame);});document.addEventListener('keydown',e=>{if(panel.hidden)return;if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=Array.from(panel.querySelectorAll<HTMLButtonElement>('button')),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
function frame(ms:number){if(document.hidden){raf=0;return;}const elapsed=last?ms-last:0,dt=Math.min(.05,elapsed/1000);last=ms;if(!paused){time+=dt;if(flight&&time-flight.start>(scene.reduced?.05:.5)){const m=flight.item;flight=null;card(m,close);}acc+=dt;while(acc>=1/60){tick(s.beach.zones[s.zone],1/60,s.settings!.assist);acc-=1/60;}if(elapsed>0&&elapsed<250){windowMs+=elapsed;frames++;if(windowMs>2000){slow=windowMs/frames>40?slow+1:0;if(slow>=2&&!scene.low){scene.low=true;scene.resize();}windowMs=0;frames=0;}}}if(ms-drawAt>=32){scene.draw(s.beach.zones[s.zone],s.zone,time,drag?.spot?{spot:drag.spot,progress:drag.progress}:null,drag,tool,held,flight?{item:flight.item,progress:Math.min(1,(time-flight.start)/.5)}:null,s.beach.sandMarks?.[s.zone]||[]);drawAt=ms;}raf=requestAnimationFrame(frame);}hint();ui();raf=requestAnimationFrame(frame);
