import C from './content/content.json';
export interface Find{id:string;kind:number;x:number;y:number;depth:number;state:'hidden'|'visible'|'caught'|'released';age:number;size?:number}
export interface Spot{x:number;y:number;r:number;open:boolean;dig:number;item:Find|null;cells?:number[];shift?:number;explored?:boolean;water?:boolean}
export interface SandMark{x:number;y:number;depth:number}
export interface Beach{seed:number;zones:Spot[][];layout?:number;sandMarks?:SandMark[][]}
export interface Save{beach:Beach;zone:number;bucket:Find[];album:number[];version?:number;records?:{kind:number;count:number;places:number[]}[];completed?:number[];history?:number[];mode?:'free'|'daily'|'practice';settings?:{sound:boolean;assist:boolean;reduced:boolean};dailySeeds?:number[];dailyCache?:{beach:Beach;zone:number}}
// Appearance is derived from terrain, never from the hidden reward.
export function surface(p:Spot){const r=random(Math.round(p.x*1e6)^Math.imul(Math.round(p.y*1e6),31));return{frame:Math.floor(r()*C.stoneFrames.length),angle:(r()-.5)*2.5,scale:.83+r()*.45,aspect:.63+r()*.3,wet:.2+r()*.25,clue:r()<.48,phase:r()*6.28};}
export function rockProgress(p:Spot,dx:number,assist=false){const travel=Math.max(0,Math.abs(dx)-.008)/(p.r*(assist?1.15:1.85));return Math.max(0,Math.min(1,p.open?1-travel:travel));}
export function rockCenter(p:Spot,progress=p.open?1:0){return{x:p.x+(p.shift===-1?-1:1)*p.r*1.65*progress,y:p.y};}
export function covered(p:Spot,m:Find){return !p.open&&m.depth===0&&!p.water&&Math.hypot((m.x-p.x)/p.r,(m.y-p.y)/(p.r*.8))<1;}
export function random(seed:number){let s=seed>>>0;s=Math.imul(s^(s>>>16),0x21f0aaad);s=Math.imul(s^(s>>>15),0x735a2d97);s=(s^(s>>>15))>>>0;return()=>((s=Math.imul(s,1664525)+1013904223)>>>0)/4294967296;}
export function generate(seed:number):Beach{const r=random(seed),placement=random(seed^0x71ac493b),placed:{x:number;y:number}[][]=Array.from({length:6},()=>[]);return{seed,layout:2,zones:Array.from({length:6},(_,z)=>Array.from({length:16},(_,i)=>{r();r();let x=.5,y=.5,best=-1;for(let attempt=0;attempt<24;attempt++){const px=.12+placement()*.76,py=.13+placement()*.74,clearance=placed[z].reduce((n,p)=>Math.min(n,Math.hypot(px-p.x,py-p.y)),2);if(clearance>best){best=clearance;x=px;y=py;}if(clearance>.145)break;}placed[z].push({x,y});const profile=C.profiles[z],water=profile.type==='pool'||profile.type==='mixed'&&i%4===3||profile.type==='kelp'&&i%4===3,kind=profile.pool[Math.floor(r()*profile.pool.length)];return{x,y,r:.052+r()*.064,open:false,dig:0,cells:Array(49).fill(0),shift:0,explored:false,water,item:i===0||r()<.67?{id:`${seed}:${z}:${i}`,kind:i===0&&z===0?0:kind,x,y,depth:profile.type==='rock'||profile.type==='kelp'||water?0:3+Math.floor(r()*4),state:water&&profile.type!=='kelp'?'visible':'hidden',age:0,size:.8+r()*.5}:null};}))};}
export function exposure(p:Spot){if(!p.item)return 0;if(p.item.depth===0)return p.open||p.water?1:0;if(!p.cells)return Math.min(1,p.dig/p.item.depth);let total=0,seen=0;for(let y=2;y<=4;y++)for(let x=2;x<=4;x++){total++;if(p.cells[y*7+x]>=p.item.depth)seen++;}return seen/total;}
export function reveal(spot:Spot,zone:number){const m=spot.item;if(m&&m.state==='hidden'&&(zone===0?spot.open:spot.item?.depth===0?spot.open:exposure(spot)>=.55)){m.state='visible';return true;}return false;}
export function dig(spot:Spot){spot.dig=Math.min(6,spot.dig+1);if(spot.cells)spot.cells.fill(spot.dig);spot.explored=true;reveal(spot,1);}
export function digAt(p:Spot,x:number,y:number){if(!Number.isFinite(x+y)||p.water)return false;if(!p.cells)p.cells=Array(49).fill(p.dig);let changed=false;for(let iy=0;iy<7;iy++)for(let ix=0;ix<7;ix++){const cx=p.x+(ix-3)*p.r/3,cy=p.y+(iy-3)*p.r/3;if(Math.hypot(cx-x,cy-y)<p.r*.66&&p.cells[iy*7+ix]<6){p.cells[iy*7+ix]++;changed=true;}}p.dig=p.cells.reduce((a,b)=>a+b,0)/49;p.explored=true;reveal(p,1);return changed;}
export function tick(spots:Spot[],dt:number,assist=false){dt=Math.min(.05,Math.max(0,dt));for(const s of spots){const m=s.item;if(!m||m.state!=='visible')continue;m.age+=dt;if(m.kind<6&&m.age>.65){const t=(m.age-.65)*(assist?.65:1),pause=Math.sin(t*.7)>-.2;m.x=s.x+(pause?Math.sin(t*1.2):Math.sin(Math.floor(t)*1.2))*.06;if(m.kind>=4)m.y=s.y+Math.sin(t*.8)*.024;}}}
export function catchItem(s:Save,m:Find){if(m.state!=='visible'||s.bucket.some(v=>v.id===m.id))return false;const belongs=s.beach.zones.some(z=>z.some(p=>p.item===m));if(!belongs)return false;m.state='caught';s.bucket.push({...m});if(!s.album.includes(m.kind))s.album.push(m.kind);if(s.records&&s.mode!=='practice'){let record=s.records.find(r=>r.kind===m.kind);if(!record){record={kind:m.kind,count:0,places:[]};s.records.push(record);}record.count=Math.min(999999,record.count+1);if(!record.places.includes(s.zone))record.places.push(s.zone);}s.bucket=s.bucket.slice(-96);return true;}
export function release(s:Save){for(const m of s.bucket)if(C.species[m.kind].living)m.state='released';for(const zone of s.beach.zones)for(const spot of zone)if(spot.item?.state==='caught'&&C.species[spot.item.kind].living)spot.item.state='released';}
export function challengeProgress(s:Save,index:number){const spots=s.beach.zones[Math.floor(index/4)]||[],objective=C.challenges[index].objective,caught=spots.filter(p=>p.item?.state==='caught'||p.item?.state==='released');
 const count=(fn:(p:Spot)=>boolean)=>spots.filter(fn).length;
 switch(objective){case 'open':return count(p=>p.open);case 'crab':return caught.filter(p=>p.item!.kind<4).length;case 'release':return count(p=>p.item?.state==='released');case 'dig':return count(p=>p.dig>0);case 'reveal':return count(p=>!!p.item&&p.item.state!=='hidden');case 'deep':return count(p=>!!p.cells&&p.cells.some(v=>v===6));case 'empty':return count(p=>!p.item&&p.dig>0);case 'explore':return count(p=>!!p.explored);case 'shrimp':return caught.filter(p=>[4,5].includes(p.item!.kind)).length;case 'glass':return caught.filter(p=>p.item!.kind>=18&&p.item!.kind<=21).length;case 'collect':return caught.length;case 'water':return caught.filter(p=>p.water).length;case 'shell':return caught.filter(p=>p.item!.kind>=12&&p.item!.kind<18).length;case 'spiral':return caught.filter(p=>[13,16].includes(p.item!.kind)).length;case 'small':return caught.filter(p=>(p.item!.size||1)<.95).length;case 'kinds':return new Set(caught.map(p=>p.item!.kind)).size;case 'both':return Number(caught.some(p=>p.water))+Number(caught.some(p=>!p.water));default:return 0;}}
export function checkChallenges(s:Save){if(!s.completed)s.completed=[];for(let i=0;i<24;i++)if(!s.completed.includes(i)&&challengeProgress(s,i)>=C.challenges[i].target)s.completed.push(i);}
export function daySeed(d=new Date()){const key=d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate();let n=2166136261;for(let i=0;i<key.length;i++)n=Math.imul(n^key.charCodeAt(i),16777619);return n>>>0;}
export function normalize(s:Save):Save{if(s.version!==2&&s.beach.zones.length===3){const map=[0,1,3,10,6,4,12,16,18,13];for(const m of s.bucket)m.kind=map[m.kind]||0;for(const z of s.beach.zones)for(const p of z)if(p.item)p.item.kind=map[p.item.kind]||0;s.album=s.album.map(i=>map[i]||0);}if(s.beach.layout!==2){const terrain=generate(s.beach.seed);for(let z=0;z<s.beach.zones.length;z++)for(let i=0;i<s.beach.zones[z].length;i++){const p=s.beach.zones[z][i],q=terrain.zones[z][i];if(p.item){p.item.x+=q.x-p.x;p.item.y+=q.y-p.y;}p.x=q.x;p.y=q.y;p.r=q.r;}s.beach.layout=2;}s.version=2;s.settings=s.settings||{...C.settings};s.history=s.history||[];s.dailySeeds=s.dailySeeds||[];s.completed=s.completed||[];s.records=s.records||s.album.map(kind=>({kind,count:s.bucket.filter(m=>m.kind===kind).length||1,places:[]}));s.mode=s.mode||'free';if(s.beach.zones.length===3){const next=generate(s.beach.seed);for(let i=0;i<3;i++)next.zones[i]=s.beach.zones[i];s.beach=next;}return s;}
export function readSave(raw:string|null):Save|null{try{const s=JSON.parse(raw||'null') as Save;if(s?.beach?.sandMarks&&(!Array.isArray(s.beach.sandMarks)||s.beach.sandMarks.length!==s.beach.zones.length||s.beach.sandMarks.some(z=>!Array.isArray(z)||z.length>C.digging.markLimit||z.some(m=>!Number.isFinite(m.x+m.y+m.depth)||m.depth<0||m.depth>6||m.x<-.5||m.x>1.5||m.y<-.7||m.y>1.7))))return null;if(!s||s.version&&s.version>2||!s.beach||!Number.isInteger(s.beach.seed)||![3,6].includes(s.beach.zones.length)||!Number.isInteger(s.zone)||s.zone<0||s.zone>=s.beach.zones.length||!Array.isArray(s.bucket)||s.bucket.length>10000||!Array.isArray(s.album)||s.album.some(k=>!Number.isInteger(k)||k<0||k>23))return null;for(const z of s.beach.zones){if(![12,16].includes(z.length))return null;for(const p of z){if(!Number.isFinite(p.x+p.y+p.r+p.dig)||p.dig<0||p.dig>6||typeof p.open!=='boolean'||p.cells&&(!Array.isArray(p.cells)||p.cells.length!==49||p.cells.some(n=>!Number.isFinite(n)||n<0||n>6)))return null;}}for(const m of [...s.bucket,...s.beach.zones.reduce<Find[]>((a,z)=>a.concat(z.reduce<Find[]>((b,p)=>p.item?b.concat(p.item):b,[])),[])])if(typeof m.id!=='string'||!Number.isFinite(m.x+m.y+m.depth+m.age)||!Number.isInteger(m.kind)||m.kind<0||m.kind>23||!['hidden','visible','caught','released'].includes(m.state))return null;if(s.records&&(!Array.isArray(s.records)||s.records.length>24||s.records.some(r=>!Number.isInteger(r.kind)||r.kind<0||r.kind>23||!Number.isFinite(r.count)||!Array.isArray(r.places))))return null;if(s.completed&&(!Array.isArray(s.completed)||s.completed.some(i=>!Number.isInteger(i)||i<0||i>23)))return null;if(s.dailySeeds&&(!Array.isArray(s.dailySeeds)||s.dailySeeds.length>400||s.dailySeeds.some(v=>!Number.isInteger(v))))return null;if(s.dailyCache&&!readSave(JSON.stringify({...s,beach:s.dailyCache.beach,zone:s.dailyCache.zone,dailyCache:undefined})))return null;if(s.settings&&(['sound','assist','reduced'] as const).some(k=>typeof s.settings![k]!=='boolean'))return null;if(s.records&&new Set(s.records.map(r=>r.kind)).size!==s.records.length)return null;if(s.history&&(!Array.isArray(s.history)||s.history.length>20||s.history.some(i=>!Number.isInteger(i))))return null;return s;}catch{return null;}}

export function scrapeGround(beach:Beach,zone:number,x:number,y:number):{changed:boolean;spot:Spot|null}{
 if(!Number.isFinite(x+y)||zone<0||zone>=beach.zones.length||x<-.5||x>1.5||y<-.7||y>1.7||!['sand','mixed'].includes(C.profiles[zone].type))return{changed:false,spot:null};
 const spot=beach.zones[zone].filter(p=>!p.water&&Math.hypot(p.x-x,p.y-y)<p.r*1.2).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0]||null;
 const changed=spot?digAt(spot,x,y):false;
 if(!beach.sandMarks)beach.sandMarks=Array.from({length:beach.zones.length},()=>[]);
 const marks=beach.sandMarks[zone],near=marks.find(m=>Math.hypot(m.x-x,m.y-y)<C.digging.markRadius*.7);
 if(near)near.depth=Math.min(6,near.depth+.7);else{marks.push({x,y,depth:1});if(marks.length>C.digging.markLimit)marks.shift();}
 return{changed:changed||!spot,spot};
}
