import {EnvironmentMotion} from './environment-motion';
import {shimmer,contactRings} from './atmosphere';
import C from './content/content.json';import {exposure,surface,rockCenter,type SandMark,type Spot,type Find} from './model';
const bg=new Image(),objects=new Image(),stones=new Image(),props=new Image();bg.src=C.visuals.coasts;objects.src=C.visuals.specimens;stones.src=C.visuals.stones;props.src=C.visuals.props;
export function specimen(c:CanvasRenderingContext2D,m:Find,x:number,y:number,w:number){if(!objects.complete||!objects.naturalWidth)return;const f=C.species[m.kind].frame,ratio=f[3]/f[2];c.drawImage(objects,f[0],f[1],f[2],f[3],x-w/2,y-w*ratio/2,w,w*ratio);}
function prop(c:CanvasRenderingContext2D,id:number,x:number,y:number,w:number,h=w,ax=.5,ay=.5){if(!props.complete||!props.naturalWidth)return;const sw=props.width/2,sh=props.height/2;c.drawImage(props,id%2*sw,Math.floor(id/2)*sh,sw,sh,x-w*ax,y-h*ay,w,h);}
const wetStones=new Map<number,HTMLCanvasElement>();
function wetStone(frame:number){if(!stones.complete||!stones.naturalWidth)return null;let tile=wetStones.get(frame);if(tile)return tile;const f=C.stoneFrames[frame];tile=document.createElement('canvas');tile.width=256;tile.height=Math.round(256*f.h/f.w);const g=tile.getContext('2d')!;g.drawImage(stones,f.x,f.y,f.w,f.h,0,0,tile.width,tile.height);g.globalCompositeOperation='source-atop';const light=g.createLinearGradient(0,0,190,tile.height);light.addColorStop(0,'rgba(230,211,165,.12)');light.addColorStop(.38,'rgba(34,43,32,.23)');light.addColorStop(1,'rgba(13,29,23,.5)');g.fillStyle=light;g.fillRect(0,0,tile.width,tile.height);const sheen=g.createRadialGradient(70,24,3,95,42,130);sheen.addColorStop(0,'rgba(235,235,210,.27)');sheen.addColorStop(.17,'rgba(209,225,206,.09)');sheen.addColorStop(.48,'rgba(174,189,164,0)');sheen.addColorStop(1,'rgba(13,26,19,.21)');g.fillStyle=sheen;g.fillRect(0,0,tile.width,tile.height);wetStones.set(frame,tile);return tile;}
export class Scene{environment=new EnvironmentMotion();c:CanvasRenderingContext2D;w=1;h=1;k=1;ox=0;oy=0;low=false;reduced=false;particles:{x:number;y:number;vx:number;vy:number;life:number}[]=[];last=0;poses=new Map<Spot,number>();previous:Spot[]|null=null;constructor(public canvas:HTMLCanvasElement){this.c=canvas.getContext('2d')!;this.resize();}resize(){this.w=innerWidth;this.h=innerHeight;const d=Math.min(devicePixelRatio||1,this.low?1:1.5,Math.sqrt((this.low?800000:1500000)/(this.w*this.h)));this.canvas.width=this.w*d;this.canvas.height=this.h*d;this.c.setTransform(d,0,0,d,0,0);this.k=Math.min(this.w*(this.w>this.h?.65:.93),this.h*.68);this.ox=(this.w>this.h?this.w*.35:this.w*.5)-this.k/2;this.oy=(this.h-this.k)/2;}
point(x:number,y:number){return{x:(x-this.ox)/this.k,y:(y-this.oy)/this.k};}
throwSand(x:number,y:number){for(let i=0;i<(this.low?10:26);i++){if(this.particles.length>150)this.particles.shift();this.particles.push({x,y,vx:Math.sin(i*12)*.1,vy:-.1-Math.random()*.12,life:.3+Math.random()*.3});}}
item(m:Find){const c=this.c;c.save();c.globalAlpha=.28;c.fillStyle='#19261c';c.beginPath();c.ellipse(m.x+.009,m.y+.018,.029,.011,0,0,6.28);c.fill();c.globalAlpha=1;specimen(c,m,m.x,m.y,.095*(m.size||1));c.restore();}
draw(spots:Spot[],zone:number,time:number,drag:{spot:Spot;progress:number}|null,cursor:{x:number;y:number}|null,tool:number,held:Find|null=null,flight:{item:Find;progress:number}|null=null,marks:SandMark[]=[]){const c=this.c,dt=Math.min(.05,time-this.last);this.last=time;const profile=C.profiles[zone].type;if(this.previous!==spots){this.poses.clear();this.previous=spots;}c.fillStyle='#aaa18a';c.fillRect(0,0,this.w,this.h);if(bg.complete&&bg.naturalWidth){const sw=bg.width/3,sh=bg.height/2,sx=zone%3*sw,sy=Math.floor(zone/3)*sh,scale=Math.max(this.w/sw,this.h/sh),cw=this.w/scale,ch=this.h/scale;const live=this.environment.draw(bg,{x:sx,y:sy,w:sw,h:sh},C.environmentMotion[zone],time,this.low,this.reduced);if(this.canvas.dataset.environment!==this.environment.mode)this.canvas.dataset.environment=this.environment.mode;if(live)c.drawImage(live,(sw-cw)*C.environmentFraming[zone]/sw*live.width,(sh-ch)/2/sh*live.height,cw/sw*live.width,ch/sh*live.height,0,0,this.w,this.h);else c.drawImage(bg,sx+(sw-cw)*C.environmentFraming[zone],sy+(sh-ch)/2,cw,ch,0,0,this.w,this.h);const water=C.water[zone],map=(x:number,y:number)=>({x:(x*sw-(sw-cw)*C.environmentFraming[zone])*scale,y:(y*sh-(sh-ch)/2)*scale});c.save();c.beginPath();water.edge.forEach(([x,y],i)=>{const q=map(x,y);if(i)c.lineTo(q.x,q.y);else c.moveTo(q.x,q.y);});c.closePath();c.clip();const clock=time*(this.reduced?.25:1);shimmer(c,this.w,this.h,0,map(water.sun,0).x,clock,water.strength,water.warm,this.low);c.restore();}

const shade=c.createLinearGradient(0,0,0,this.h);shade.addColorStop(0,'rgba(18,31,23,.25)');shade.addColorStop(.4,'rgba(20,35,28,0)');shade.addColorStop(1,'rgba(14,26,20,.42)');c.fillStyle=shade;c.fillRect(0,0,this.w,this.h);c.save();c.translate(this.ox,this.oy);c.scale(this.k,this.k);
for(const m of marks){const r=C.digging.markRadius;c.save();c.translate(m.x,m.y);const hollow=c.createRadialGradient(0,0,0,0,0,r);hollow.addColorStop(0,'rgba(57,57,41,'+(.30+m.depth*.045)+')');hollow.addColorStop(.6,'rgba(83,76,53,.18)');hollow.addColorStop(1,'rgba(83,76,53,0)');c.fillStyle=hollow;c.scale(1,.68);c.fillRect(-r,-r,r*2,r*2);c.strokeStyle='rgba(225,205,158,'+(.28+m.depth*.02)+')';c.lineWidth=.002;c.beginPath();c.arc(0,.004,r*.72,.12,2.6);c.stroke();c.restore();}
for(const p of spots.slice().sort((a,b)=>a.y-b.y)){
 const look=surface(p),target=drag?.spot===p?drag.progress:p.open?1:0,previous=this.poses.has(p)?this.poses.get(p)!:p.open?1:0,progress=this.reduced?target:previous+(target-previous)*(1-Math.exp(-dt*14));this.poses.set(p,progress);
 const isRock=(!p.water&&profile==='rock')||profile==='kelp';
 if(isRock&&progress>.015){c.save();c.translate(p.x,p.y);const hollow=c.createRadialGradient(0,0,0,0,0,p.r*1.06);hollow.addColorStop(0,'rgba(33,39,28,.75)');hollow.addColorStop(.7,'rgba(50,53,36,.55)');hollow.addColorStop(1,'rgba(71,68,45,0)');c.fillStyle=hollow;c.beginPath();c.ellipse(0,.005,p.r*1.06,p.r*.78,look.angle*.3,0,6.28);c.fill();for(let j=0;j<22;j++){const a=j*2.399+look.phase,r=p.r*(.25+(j%7)*.085);c.fillStyle=j%3?'rgba(156,145,110,.42)':'rgba(30,44,29,.7)';c.beginPath();c.ellipse(Math.cos(a)*r,Math.sin(a)*r*.66,.0025,.0017,a,0,6.28);c.fill();}c.restore();}

 if(p.dig>0&&p.cells){for(let y=0;y<7;y++)for(let x=0;x<7;x++){const depth=p.cells[y*7+x];if(!depth)continue;const cx=p.x+(x-3)*p.r/3,cy=p.y+(y-3)*p.r/3,g=c.createRadialGradient(cx,cy,0,cx,cy,p.r*.4);g.addColorStop(0,'rgba(48,48,34,'+(depth*.045)+')');g.addColorStop(.75,'rgba(80,74,49,.06)');g.addColorStop(1,'rgba(90,80,54,0)');c.fillStyle=g;c.beginPath();c.ellipse(cx,cy,p.r*.4,p.r*.33,0,0,6.28);c.fill();}}
 const m=p.item;if(m&&m!==held&&(m.state==='visible'||m.state==='hidden'&&(p.dig>0||isRock&&progress>.12))){c.save();if(m.state==='hidden'&&isRock){c.beginPath();const sign=p.shift===-1?-1:1;c.rect(sign>0?p.x-p.r:p.x+p.r-progress*p.r*2,p.y-p.r,progress*p.r*2,p.r*2);c.clip();}else if(m.state==='hidden'&&p.cells){c.beginPath();for(let y=0;y<7;y++)for(let x=0;x<7;x++)if(p.cells[y*7+x]>=m.depth){const cx=p.x+(x-3)*p.r/3,cy=p.y+(y-3)*p.r/3;c.moveTo(cx+p.r*.24,cy);c.ellipse(cx,cy,p.r*.24,p.r*.21,0,0,6.28);}c.clip();}this.item(m);c.restore();}
 if(isRock){const center=rockCenter(p,progress),lift=Math.sin(progress*Math.PI),radius=p.r*look.scale;c.save();c.translate(center.x,p.y-lift*p.r*.38);c.rotate(look.angle+progress*(p.shift===-1?-1:1)*.35);const shadow=c.createRadialGradient(.008,.02,0,.008,.02,radius*1.2);shadow.addColorStop(0,'rgba(12,23,16,.65)');shadow.addColorStop(.65,'rgba(20,29,18,.32)');shadow.addColorStop(1,'rgba(30,32,20,0)');c.fillStyle=shadow;c.beginPath();c.ellipse(.008,.02+lift*.015,radius*1.2,radius*.8,0,0,6.28);c.fill();c.scale(1,Math.max(.16,1-lift*.8));const tile=wetStone(look.frame);if(profile==='rock'&&tile){c.drawImage(tile,-radius,-radius*look.aspect,radius*2,radius*look.aspect*2);if(progress>.55){c.globalAlpha=(progress-.55)*.48;c.drawImage(tile,-radius,-radius*look.aspect,radius*2,radius*look.aspect*2);c.globalAlpha=1;}}else prop(c,0,0,0,radius*2.5,radius*2);c.restore();
 if(lift>.18){c.strokeStyle='rgba(218,229,207,.42)';c.lineWidth=.0015;for(let j=0;j<3;j++){const q=(time*1.7+j/3)%1;c.beginPath();c.moveTo(center.x+p.r*(j-1)*.45,p.y+q*q*p.r*.65);c.lineTo(center.x+p.r*(j-1)*.45,p.y+q*q*p.r*.65+.008);c.stroke();}}
 }
 if(!p.dig&&!p.water&&profile!=='rock'&&profile!=='kelp'){
 c.save();c.translate(p.x,p.y);c.rotate(look.angle);const damp=c.createRadialGradient(0,0,p.r*.08,0,0,p.r*.95);damp.addColorStop(0,'rgba(79,77,54,.1)');damp.addColorStop(1,'rgba(79,77,54,0)');c.fillStyle=damp;c.fillRect(-p.r,-p.r,p.r*2,p.r*2);
 if(look.clue){c.fillStyle='rgba(36,44,34,.42)';for(let j=0;j<(look.phase>3?2:1);j++){c.beginPath();c.ellipse((j-.5)*.009,0,.0032,.0021,0,0,6.28);c.fill();}c.strokeStyle='rgba(205,186,143,.26)';c.lineWidth=.001;c.beginPath();c.ellipse(0,.001,.008,.004,0,0,3.14);c.stroke();}
 else if(look.phase>4){c.strokeStyle='rgba(55,64,45,.17)';c.lineWidth=.0013;for(let j=0;j<2;j++){c.beginPath();for(let k=0;k<12;k++){const x=-p.r*.5+k*p.r/14,y=Math.sin(k*.6+look.phase)*.003+j*.006;if(k)c.lineTo(x,y);else c.moveTo(x,y);}c.stroke();}}
 c.restore();}

}
if(cursor&&(tool===2||drag?.spot.water)){const q={x:cursor.x,y:cursor.y};c.save();c.scale(1/this.k,1/this.k);contactRings(c,q.x*this.k,q.y*this.k,(time*.8)%1.8,.65,.65);c.restore();}
for(const a of this.particles){a.life-=dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.vy+=dt*.55;c.globalAlpha=Math.max(0,a.life*2);c.fillStyle='#d8c393';c.fillRect(a.x,a.y,.005,.004);}this.particles=this.particles.filter(p=>p.life>0);c.globalAlpha=1;if(held&&cursor)specimen(c,held,cursor.x,cursor.y,.095*(held.size||1));
if(cursor&&!held){if(tool===2)prop(c,2,cursor.x,cursor.y,.25,.25,.675,.28);else if(tool===1)prop(c,3,cursor.x,cursor.y,.2,.2,.36,.72);else{c.strokeStyle='rgba(248,236,194,.65)';c.lineWidth=.003;c.beginPath();c.ellipse(cursor.x,cursor.y,.027,.022,0,0,6.28);c.stroke();}}
c.restore();const bx=this.w-52,by=this.h-85;if(flight){const u=flight.progress,ease=1-Math.pow(1-u,3),sx=this.ox+flight.item.x*this.k,sy=this.oy+flight.item.y*this.k;specimen(c,flight.item,sx+(bx-sx)*ease,sy+(by-sy)*ease-Math.sin(u*Math.PI)*65,40*(1-u*.35));}prop(c,1,bx,by,96,96);}}


export function whenSpecimensReady(draw:()=>void){if(objects.complete&&objects.naturalWidth)draw();else objects.addEventListener('load',draw,{once:true});}
