import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {simulate,createFlight,stepFlight,readRecord,commitRecord,createBeach,rockOutline,aimGesture} from '../.cache/model.mjs';
const c=JSON.parse(readFileSync(new URL('../src/content/content.json',import.meta.url),'utf8')),p=c.physics;
test('same release deterministic; angle and stone alter real outcomes',()=>{const a=simulate(c.stones[0],.8,17,0,p),b=simulate(c.stones[0],.8,17,0,p);assert.deepEqual(a,b);assert(a.jumps>=4);const steep=simulate(c.stones[0],.8,35,0,p);assert(steep.jumps<a.jumps);assert(simulate(c.stones[4],.8,17,0,p).distance<a.distance);});
test('parameter sweep terminates, stays finite and hit IDs unique',()=>{for(const stone of c.stones)for(const power of [0,.2,.5,.8,1])for(const angle of [8,17,25,35]){const f=simulate(stone,power,angle,.38,p);assert(f.done&&f.time<=p.maxTime+p.step);assert(Number.isFinite(f.distance));assert(f.y>=0);assert(f.jumps<40);assert.equal(new Set(f.hits.map(x=>x.index)).size,f.hits.length);}});
test('contacts do not add mechanical energy',()=>{const f=createFlight(c.stones[0],1,17,0,p);while(!f.done){const before=(f.vx*f.vx+f.vy*f.vy+f.vz*f.vz)/2+p.gravity*f.y;const hit=stepFlight(f,p.step,p);if(hit&&hit.bounce){const after=(f.vx*f.vx+f.vy*f.vy+f.vz*f.vz)/2+p.gravity*f.y;assert(after<=before+.02);}}});
test('fixed simulation at 30 and 60 rendering cadence is equal',()=>{const run=frame=>{const f=createFlight(c.stones[1],.78,18,0,p);let acc=0;while(!f.done){acc+=frame;while(acc>=p.step&&!f.done){stepFlight(f,p.step,p);acc-=p.step;}}return f;};assert.deepEqual(run(1/30),run(1/60));});
test('bad inputs bounded, records recover and commits are idempotent',()=>{assert.deepEqual(readRecord('{'),readRecord(null));const f=simulate(c.stones[0],NaN,Infinity,NaN,p);assert(Number.isFinite(f.distance));const rec=commitRecord(readRecord(null),'one',f);assert.equal(rec.throws,1);assert.deepEqual(commitRecord(rec,'one',f),rec);});
test('current beach geometry covers reachable shore across phone orientations',()=>{for(const [w,h] of [[375,812],[390,844],[430,932],[667,375],[844,390],[932,430]]){const stones=createBeach(w,h,c.stones,c.beach);const visible=stones.filter(x=>x.x>24&&x.x<w-24&&x.y>h*.55&&x.y<h-90);assert(visible.length>20);for(const stone of visible)assert(rockOutline(stone).every(v=>Number.isFinite(v.x)&&Number.isFinite(v.y)));}});

test('every beach stone has stable selectable geometry and finite flight',()=>{for(const [w,h] of [[375,812],[390,844],[430,932],[844,390]]){const a=createBeach(w,h,c.stones,c.beach);assert.deepEqual(a,createBeach(w,h,c.stones,c.beach));assert(a.length>100);assert(a.some(x=>x.stone.size===c.beach.boulderSize));assert.equal(new Set(a.map(x=>x.stone.id)).size,a.length);for(const x of a){assert.equal(rockOutline(x).length,48);{const f=simulate(x.stone,.7,18,0,p);assert(f.done&&Number.isFinite(f.distance));}}}});

test('hold time controls power independently of aiming, taps do not throw',()=>{const a=(x,y,t)=>aimGesture(x,y,t,390,844,c.gesture);assert.equal(a(0,0,.05).canThrow,false);assert(a(0,0,.7).canThrow);assert(a(0,0,1.3).power>a(0,0,.5).power);assert.equal(a(0,0,c.gesture.cycleSeconds/2).power,1);assert.equal(a(0,0,c.gesture.cycleSeconds).power,0);assert(Math.abs(a(0,0,.7).power-a(0,0,.7+c.gesture.cycleSeconds*3).power)<1e-12);assert.equal(a(90,-50,.7).power,a(0,0,.7).power);assert(a(-90,0,.7).heading<0);assert(a(90,0,.7).heading>0);assert(a(0,-40,.7).angle>a(0,40,.7).angle);assert.equal(a(0,-999,.7).angle,c.gesture.angleMax);assert.equal(a(0,999,.7).angle,c.gesture.angleMin);});

test('all sizes can be picked, while heavy stones launch slower and splash harder',()=>{for(const [w,h] of [[375,812],[390,844],[430,932],[844,390]]){const a=createBeach(w,h,c.stones,c.beach);assert(a.every(x=>x.stone.size>0));assert(a.some(x=>x.stone.mass>.5));}const light={...c.stones[0],mass:.075,size:1},heavy={...light,mass:1.5,size:2.7};const a=createFlight(light,.8,18,0,p),b=createFlight(heavy,.8,18,0,p);assert(b.vz<a.vz*.5);const fa=simulate(light,.8,18,0,p),fb=simulate(heavy,.8,18,0,p);assert(fa.jumps>fb.jumps);assert.equal(fb.jumps,0);assert.equal(fb.reason,'heavy');assert(fb.hits[0].splash>fa.hits[0].splash);assert(fb.hits[0].z<fa.hits[0].z);});

test('each charge cycle gives repeated identical release opportunities without auto release',()=>{for(let cycle=0;cycle<6;cycle++){const values=Array.from({length:321},(_,i)=>aimGesture(70,-20,cycle*c.gesture.cycleSeconds+i/100,390,844,c.gesture));assert(values.some(x=>x.power>=p.sweetMin&&x.power<=p.sweetMax));assert(values[160].power>.999);assert(values[320].power<.001);assert(values.every(x=>x.heading===values[0].heading&&x.angle===values[0].angle));}});

test('spin decays through air and contacts; stable thin stone makes shrinking skip intervals',()=>{const f=createFlight(c.stones[0],.8,17,0,p),initial=f.spin;let previous=initial;while(!f.done){stepFlight(f,p.step,p);assert(f.spin<=previous+1e-12);previous=f.spin;}assert(f.spin<initial);const b=f.hits.filter(x=>x.bounce);assert(b.length>=3);const intervals=b.slice(1).map((x,i)=>x.time-b[i].time);for(let i=1;i<intervals.length;i++)assert(intervals[i]<=intervals[i-1]+p.step*2);const spinning=simulate(c.stones[0],.8,17,0,p),weak=simulate(c.stones[0],.8,17,0,{...p,spinRate:1});assert(spinning.jumps>weak.jumps);assert(spinning.distance>weak.distance);});

test('launch elevation is separate from stone face trim; steeper entry reduces skips',()=>{const low=createFlight(c.stones[0],.8,12,0,p),high=createFlight(c.stones[0],.8,35,0,p);assert.equal(low.plateAngle,high.plateAngle);assert(high.vy>low.vy);assert(simulate(c.stones[0],.8,35,0,p).jumps<simulate(c.stones[0],.8,17,0,p).jumps);});
test('recent throws keep exact stones and release settings through bounded reloads',()=>{let r=readRecord(null);for(let i=0;i<60;i++){const f=simulate({...c.stones[i%c.stones.length],id:c.stones[i%c.stones.length].id+'-'+i},.8,17,.12,p);r=commitRecord(r,'history-'+i,f);}assert.equal(r.history.length,20);const back=readRecord(JSON.stringify(r));assert.deepEqual(back.history,r.history);assert.deepEqual(back.learned,r.learned);assert(JSON.stringify(r).length<50000);const latest=r.history[0];const f=simulate(latest.stone,latest.power,latest.angle,latest.heading,p);assert.equal(f.distance,latest.distance);assert.equal(f.jumps,latest.jumps);});
test('every stone notebook goal is reachable with its actual stone physics',()=>{for(const goal of c.practiceGoals){const stone=c.stones.find(s=>s.id===goal.stone);let success=false;for(let power=.15;power<=1&&!success;power+=.05)for(let angle=8;angle<=35&&!success;angle++){const f=simulate(stone,power,angle,0,p);const r=commitRecord(readRecord(null),'trial',f);success=r.learned.includes(goal.id);}assert(success,goal.name);} });
