import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {makePlan,clone} from '../../src/core.js';
const {chromium}=createRequire(import.meta.url)('C:/Users/77958/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=resolve('dist'),out=resolve('artifacts/interaction-audit-20260917'),results=[],catalog=JSON.parse(await readFile('src/content/content.json','utf8'));
const server=createServer(async(req,res)=>{try{const p=resolve(root,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!p.startsWith(root+'/')&&!p.startsWith(root+'\\'))throw Error();let bytes=await readFile(p);if(p===resolve(root,'src/app.js'))bytes=Buffer.concat([bytes,Buffer.from('\nwindow.__audit={get scene(){return scene},get plan(){return plan}};')]);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png'})[extname(p)]||'application/octet-stream'});res.end(bytes);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({channel:'chrome',headless:true});
try{
for(const width of [375]){
 const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),cdp=await context.newCDPSession(page),checks=[],errors=[];let stage='boot';page.setDefaultTimeout(4000);page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));
 const click=async action=>{await page.locator(`[data-action="${action}"]:visible`).first().tap();await page.waitForTimeout(100)};
 const state=()=>page.evaluate(()=>JSON.parse(JSON.stringify(window.__audit.plan)));
 const pass=name=>{checks.push(name);console.log(JSON.stringify({width,pass:name}))};
 const point=async(x,z,y=0)=>page.evaluate(async({x,z,y})=>{const T=await import('./src/vendor/package/build/three.module.js'),{viewportRect}=await import('./src/orientation.js'),s=window.__audit.scene,r=viewportRect(s.renderer.domElement),p=new T.Vector3(x,y,z).project(s.camera),lx=r.left+(p.x+1)*r.width/2,ly=r.top+(1-p.y)*r.height/2;if(document.body.classList.contains('forced-landscape')){const root=document.querySelector('#app').getBoundingClientRect();return{x:root.right-ly,y:root.top+lx}}return{x:lx,y:ly}},{x,z,y});
 const tap=async pt=>{await page.touchscreen.tap(pt.x,pt.y);await page.waitForTimeout(180)};
 const drag=async(a,b)=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...a}]});for(let i=1;i<=16;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:a.x+(b.x-a.x)*i/16,y:a.y+(b.y-a.y)*i/16}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(250)};
 try{
  await page.goto(url);await page.waitForFunction(()=>window.__audit?.scene);await page.addStyleTag({content:':root{--safe-area-inset-top:28px;--safe-area-inset-bottom:16px}'});
  await click('tab-layouts');await click('blank');await click('room-properties');await page.locator('#room-form [name="w"]').fill('6');await page.locator('#room-form [name="d"]').fill('5');await page.locator('#room-form [name="name"]').fill('触摸验收客厅');await click('complete-settings');let p=await state(),r=p.rooms[0];assert.equal(r.w,6);assert.equal(r.d,5);pass('create custom room and save dimensions');await click('focus-selected-room');await page.waitForTimeout(200);
  stage='resize room';await drag(await point(r.x+r.w,r.z+r.d/2,.09),await point(r.x+r.w+.6,r.z+r.d/2,.09));p=await state();assert.ok(p.rooms[0].w>r.w+.2,'east handle did not resize');await click('undo');assert.equal((await state()).rooms[0].w,r.w);pass('touch wall resize and undo');
  stage='move room';await drag(await point(r.x+2,r.z+2,.03),await point(r.x+2.6,r.z+2.5,.03));p=await state();assert.ok(Math.hypot(p.rooms[0].x-r.x,p.rooms[0].z-r.z)>.2,'room did not move');await click('undo');assert.deepEqual((await state()).rooms[0],r);pass('touch room move and undo');
  stage='door add and drag';await click('add-door');await tap(await point(r.x+r.w,r.z+1.3,.04));p=await state();assert.equal(p.openings.length,1);const door=p.openings[0];assert.equal(door.side,'east');await drag(await point(r.x+r.w,r.z+door.offset,.025),await point(r.x+r.w,r.z+door.offset+.6,.025));p=await state();assert.ok(Math.abs(p.openings[0].offset-door.offset)>.25,'door did not move');await click('cancel-door');await click('undo');assert.equal((await state()).openings[0].offset,door.offset);pass('touch add door, drag along wall and undo');
  stage='shared doorway';await click('add-room-shortcut');await page.locator('[data-action="add-room-side"][data-id="east"]').tap();p=await state();assert.equal(p.rooms.length,2);const shared=await page.evaluate(async()=>{const c=await import('./src/core.js'),p=window.__audit.plan;return c.walls(p).filter(w=>w.rooms.length===2).map(w=>({rooms:w.rooms,doors:c.wallOpenings(p,w).length}))});assert.ok(shared.some(w=>w.doors===1));pass('adjacent rooms reference one shared opening');await page.screenshot({path:out+`/shared-door-${width}.png`});
  stage='furniture place and move';await click('finish-layout');await click('tab-furniture');await page.locator('[data-action="furniture"][data-id="pouf"]').tap();await tap(await point(r.x+2,r.z+2));p=await state();assert.equal(p.items.length,1);const original=clone(p.items[0]);await drag(await point(original.x,original.z,.4),await point(original.x+.6,original.z+.3,.4));p=await state();assert.ok(Math.hypot(p.items[0].x-original.x,p.items[0].z-original.z)>.2);const moved=clone(p.items[0]);await click('undo');assert.deepEqual((await state()).items[0],original);await click('mobile-menu');await click('redo');assert.deepEqual((await state()).items[0],moved);pass('touch furniture placement, movement, undo and redo');
  stage='furniture rotate';await click('rotate');assert.equal((await state()).items[0].angle,90);await click('undo');assert.equal((await state()).items[0].angle,0);pass('furniture rotation and undo');
  stage='landscape furniture drag';await page.locator('.orientation-toggle').tap();await page.waitForTimeout(200);const before=(await state()).items[0];await drag(await point(before.x,before.z,.4),await point(before.x+.5,before.z+.4,.4));const after=(await state()).items[0];assert.ok(Math.hypot(after.x-before.x,after.z-before.z)>.2);pass('forced landscape touch coordinates');await page.screenshot({path:out+`/landscape-drag-${width}.png`});
  stage='reload';const saved=await state();await page.waitForTimeout(350);await page.reload();await page.waitForFunction(()=>window.__audit?.scene);const recovered=await state();assert.deepEqual(recovered.rooms,saved.rooms);assert.deepEqual(recovered.items,saved.items);assert.deepEqual(recovered.openings,saved.openings);pass('reload preserves custom room furniture and door');assert.deepEqual(errors,[]);results.push({width,passed:true,checks,errors});
 }catch(e){await page.screenshot({path:out+`/failure-${width}.png`});results.push({width,passed:false,stage,error:e.message,checks,errors});console.log(JSON.stringify(results.at(-1)));}await context.close();
}
}finally{await browser.close();await new Promise(r=>server.close(r));await writeFile(out+'/retry375-report.json',JSON.stringify({results,limitations:['Chrome touch emulation, not physical phone','Shared doorway geometry checked; reverse visual inspection not exhaustive','No native keyboard, album or thermal measurements']},null,2));console.log(JSON.stringify(results,null,2));}
