import {cp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {generate,normalize} from '../.cache/model.mjs';
const dir='.cache/release-preview';await mkdir(dir,{recursive:true});await cp('dist',dir,{recursive:true});const c=JSON.parse(await readFile('src/content/content.json','utf8'));const state=normalize({forest:generate(9137),patch:0,basket:[]});
const fixture=`if(!localStorage.getItem('${c.storageKey}'))localStorage.setItem('${c.storageKey}',${JSON.stringify(JSON.stringify(state))});
const diagnostic=document.createElement('output');diagnostic.id='qa-audio';diagnostic.style.cssText='position:fixed;z-index:90;bottom:0;right:0;font-size:9px;background:#233;color:white';let decoded=0,started=0,stopped=0;function report(){diagnostic.textContent='decode '+decoded+' / start '+started+' / stop '+stopped;}document.body.appendChild(diagnostic);report();const AC=window.AudioContext||window.webkitAudioContext;if(AC){const decode=AC.prototype.decodeAudioData;AC.prototype.decodeAudioData=function(data,ok,fail){return decode.call(this,data,b=>{decoded++;report();if(sessionStorage.getItem('qa-delay')==='1')setTimeout(()=>ok(b),600);else if(sessionStorage.getItem('qa-fail')==='1')fail(new Error('QA decode failure'));else ok(b);},fail);};const create=AC.prototype.createBufferSource;AC.prototype.createBufferSource=function(){const n=create.call(this),start=n.start.bind(n),stop=n.stop.bind(n);n.start=(...a)=>{started++;report();return start(...a);};n.stop=(...a)=>{stopped++;report();return stop(...a);};return n;};}
`;
const qa=`const controls=document.createElement('div');controls.id='qa-controls';controls.style.cssText='position:fixed;z-index:80;bottom:0;left:0;display:flex';document.body.appendChild(controls);function add(name,fn){const b=document.createElement('button');b.textContent=name;b.style.cssText='font-size:9px;padding:2px 5px;min-height:28px';b.onclick=fn;controls.appendChild(b);}const sleep=ms=>new Promise(r=>setTimeout(r,ms));let id=1000;function state(){return JSON.parse(localStorage.getItem('${c.storageKey}'));}function event(type,x,y){const w=innerWidth,h=innerHeight,scale=Math.min(w*.91,h*.63),ox=h>w?(w-scale)/2:w*.38-scale/2,oy=(h-scale)/2;document.getElementById('scene').dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,pointerType:'touch',isPrimary:true,button:0,buttons:type==='pointerup'?0:1,clientX:ox+x*scale,clientY:oy+y*scale}));}async function uncover(){const s=state();for(const l of [...s.forest.patches[s.patch].leaves].reverse()){id++;event('pointerdown',l.x,l.y);event('pointermove',-.12,1.1);event('pointerup',-.12,1.1);await sleep(15);}}
add('QA 刷净',async()=>{for(let row=0;row<8;row++){id++;event('pointerdown',.32,.23+row*.04);for(let j=0;j<=16;j++){event('pointermove',.32+j*.025,.23+row*.04);await sleep(12);}event('pointerup',.72,.23+row*.04);}});
add('QA 入篮',()=>{const w=innerWidth,h=innerHeight,scale=Math.min(w*.91,h*.63),ox=h>w?(w-scale)/2:w*.38-scale/2,oy=(h-scale)/2,b=h>w?{x:w*.77,y:h*.81}:{x:w*.79,y:h*.53};id++;event('pointerdown',.5,.5);event('pointermove',(b.x-ox)/scale,(b.y-oy)/scale);event('pointerup',(b.x-ox)/scale,(b.y-oy)/scale);});
add('QA 观察',async()=>{await uncover();const s=state(),m=s.forest.patches[s.patch].mushrooms.find(m=>!m.picked&&m.kind<24);if(m){id++;event('pointerdown',m.x,m.y-m.size);event('pointerup',m.x,m.y-m.size);}});
add('QA 采集',async()=>{await uncover();const s=state(),m=s.forest.patches[s.patch].mushrooms.find(m=>!m.picked&&m.kind<24);if(m){id++;const x=m.x,y=m.y-m.size;event('pointerdown',x,y);for(const [dx,dy] of [[.05,0],[-.05,0],[.05,0],[0,-.12]]){event('pointermove',x+dx,y+dy);await sleep(90);}event('pointerup',x,y-.12);}});
add('QA 毒菌',async()=>{await uncover();const s=state(),m=s.forest.patches[s.patch].mushrooms.find(m=>m.kind>=24);if(m){id++;event('pointerdown',m.x,m.y-m.size);event('pointerup',m.x,m.y-m.size);}});
add('QA 解码取消',()=>{const s=state(),l=s.forest.patches[s.patch].leaves[0];id++;event('pointerdown',l.x,l.y);event('pointermove',l.x+.07,l.y);event('pointerup',l.x+.07,l.y);Array.from(document.querySelectorAll('#tools button')).find(b=>b.textContent==='林间手记').click();});
add('QA 遇见',()=>{const s=state(),e=s.forest.patches[s.patch].encounter;id++;event('pointerdown',e.x,e.y);event('pointerup',e.x,e.y);});
add('QA 延迟',()=>{sessionStorage.setItem('qa-delay','1');location.reload();});add('QA 失败',()=>{sessionStorage.removeItem('qa-delay');sessionStorage.setItem('qa-fail','1');location.reload();});add('QA 正常',()=>{sessionStorage.removeItem('qa-delay');sessionStorage.removeItem('qa-fail');location.reload();});
add('QA 取消',async()=>{const s=state(),l=s.forest.patches[s.patch].leaves[0];id++;event('pointerdown',l.x,l.y);event('pointermove',l.x+.05,l.y);event('pointercancel',l.x+.05,l.y);});
add('QA host',()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');for(const side of ['left','right']){const d=document.createElement('div');d.textContent='HOST';d.style.cssText='position:fixed;pointer-events:none;z-index:90;top:44px;width:124px;height:112px;background:#cc334466;'+side+':0';document.body.appendChild(d);}});
`;
await writeFile(dir+'/fixture.js',fixture);await writeFile(dir+'/qa.js',qa);const html=await readFile(dir+'/index.html','utf8');await writeFile(dir+'/index.html',html.replace('<script src="audio-data.js">','<script src="fixture.js"></script><script src="audio-data.js">').replace('</body>','<script src="qa.js"></script></body>'));
