import C from './content/content.json';
import {generate,readSave,normalize,localDate,dailySeed,startRun,challengeProgress,checkChallenges,encounter,pick,observe,patchProgress,exposed,leafHit,moveGrip,settleLeaves,viewLeaf,brushDirt,type Save,type Mushroom,type Leaf,type Grip} from './model';
import {Scene,type Flight,type Inspection} from './render';
const $=(id:string)=>document.getElementById(id)!,copy=C.copy,canvas=$('scene') as HTMLCanvasElement,scene=new Scene(canvas),panel=$('panel') as HTMLDialogElement;
let s:Save;try{s=readSave(localStorage.getItem(C.storageKey))||{forest:generate(Date.now()>>>0),patch:0,basket:[],practice:true};}catch{s={forest:generate(Date.now()>>>0),patch:0,basket:[],practice:true};}
normalize(s);
s.settings=s.settings||{assist:false,sound:false,reduced:false};const settings=s.settings;scene.reduced=settings.reduced;
let inspection:Inspection|null=null;
let paused=false,fly:Flight|null=null,drag:{id:number;x:number;y:number;time:number;lastTime:number;travel:number;grip:Grip;leaf?:Leaf;origin?:{x:number;y:number;angle:number};m?:Mushroom;event?:boolean}|null=null,raf=0,last=0,drawAt=0,time=0,saveError=false,audio:AudioContext|null=null;
const voices=new Set<AudioBufferSourceNode>(),buffers=new Map<string,AudioBuffer>(),decoding=new Map<string,Promise<AudioBuffer>>();let audioToken=0,leafSoundIndex=0;
$('title').textContent=C.title;$('eyebrow').textContent=C.habitats[Math.floor(s.patch/3)];$('hint').textContent=s.practice?copy.practice:copy.hint;
function hint(text:string){$('hint').textContent=saveError?copy.savedError:text;}
let futureSave=false;try{futureSave=(JSON.parse(localStorage.getItem(C.storageKey)||'null')?.version||0)>C.version;}catch{}
function save(){if(futureSave){hint(copy.futureSave);return;}try{localStorage.setItem(C.storageKey,JSON.stringify(s));saveError=false;}catch{saveError=true;hint(copy.savedError);}}
function stopSound(){audioToken++;voices.forEach(n=>{try{n.stop();}catch{}n.disconnect();});voices.clear();}
async function unlockSound(){if(!settings.sound)return;try{const A=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!A)throw Error();audio=audio||new A();if(audio.state!=='running')await audio.resume();}catch{settings.sound=false;hint(copy.silent);}}
function noise(kind:'leaf'|'pick'|'water'){if(!settings.sound||!audio||audio.state!=='running'||voices.size>=3)return;const ctx=audio,token=audioToken,id=kind==='leaf'?'leaf-'+(leafSoundIndex++%2):kind;const play=(buffer:AudioBuffer)=>{if(token!==audioToken||!settings.sound||document.hidden||paused||voices.size>=3||ctx.state!=='running')return;const node=ctx.createBufferSource(),gain=ctx.createGain();node.buffer=buffer;node.playbackRate.value=kind==='leaf'?.9+Math.random()*.15:1;gain.gain.value=kind==='water'?.08:.22;node.connect(gain);gain.connect(ctx.destination);voices.add(node);node.onended=()=>{node.disconnect();gain.disconnect();voices.delete(node);};node.start();};const cached=buffers.get(id);if(cached){play(cached);return;}let promise=decoding.get(id);if(!promise){promise=new Promise<AudioBuffer>((resolve,reject)=>{try{const raw=(window as unknown as {FOREST_AUDIO:Record<string,string>}).FOREST_AUDIO[id],str=atob(raw),bytes=new Uint8Array(str.length);for(let i=0;i<str.length;i++)bytes[i]=str.charCodeAt(i);ctx.decodeAudioData(bytes.buffer,b=>{buffers.set(id,b);resolve(b);},reject);}catch(e){reject(e);}});decoding.set(id,promise);promise.then(()=>decoding.delete(id),()=>decoding.delete(id));}void promise.then(play,()=>{if(token===audioToken)hint(copy.silent);});}
async function toggleSound(){settings.sound=!settings.sound;if(settings.sound)await unlockSound();else stopSound();save();showSettings();}
function cancelDrag(){if(inspection){inspection.at=undefined;inspection.carrying=false;}if(drag?.leaf&&drag.origin){Object.assign(drag.leaf,drag.origin);drag.leaf.vx=0;drag.leaf.vy=0;}drag=null;}
function close(){if(panel.close)panel.close();else panel.removeAttribute('open');paused=false;last=0;ui();}
function button(label:string,fn:()=>void,parent:HTMLElement){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;parent.appendChild(b);return b;}
function show(title:string,text:string){paused=true;cancelDrag();stopSound();panel.textContent='';const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=text;panel.append(h,p);if(!panel.open){if(panel.showModal)panel.showModal();else panel.setAttribute('open','');}}
function finishModal(label=copy.close,action=close){const footer=document.createElement('div');footer.className='modal-actions';button(label,action,footer);panel.appendChild(footer);panel.scrollTop=0;}
function discovery(m:Mushroom,fresh=false,observing=false){const k=C.species[m.kind];if(k.observeOnly){noteCard(k.noteId,m.kind);return;}show(k.name,observing?copy.knownObservation:fresh?copy.newDiscovery:copy.details);const art=document.createElement('canvas');art.className='specimen';scene.card(art,m.kind);panel.appendChild(art);const p=document.createElement('p');p.textContent=k.description;panel.appendChild(p);paragraph(copy.traitsLabel+' · '+k.traits);paragraph(copy.habitatLabel+' · '+C.locations.filter(l=>l.pool.includes(m.kind)).map(l=>l.name).join('、'));const record=s.records![m.kind];if(record?.count){const label=(n:number)=>n<.045?copy.smallSize:n>.06?copy.largeSize:copy.mediumSize;paragraph(copy.variants+' · '+[label(record.min),label(record.max)].filter((v,i,a)=>a.indexOf(v)===i).join('、'));}if(record?.count)paragraph(copy.total+' '+record.count+' · '+copy.observedHere+' '+record.places.map(i=>C.locations[i].name).join('、'));const value=document.createElement('p');value.className='value';value.textContent=copy.value+' '+k.value+' · '+copy.valueNote;panel.appendChild(value);const note=document.createElement('small');note.textContent=copy.disclaimer;panel.appendChild(note);finishModal(observing?copy.look:copy.close);}
function basket(){show(copy.basket,copy.total+' '+s.records!.reduce((n,r)=>n+r.count,0)+' '+copy.count+' · '+s.records!.filter(r=>r.count>0).length+'/24 '+copy.of);button(copy.arrange,arrange,panel);const grid=document.createElement('div');grid.className='collection';C.species.slice(0,24).forEach((k,i)=>{const record=s.records![i],b=button(record.count?k.name+' · '+record.count:copy.unknown,()=>record.count?discovery({id:'record',x:0,y:0,size:record.max,kind:i,picked:true}):clue(i),grid);if(record.count){const art=document.createElement('canvas');scene.card(art,i);b.insertBefore(art,b.firstChild);}});panel.appendChild(grid);if(!s.records!.some(r=>r.count))paragraph(copy.empty);finishModal();}
function clue(kind:number){const k=C.species[kind];show(copy.unknown,copy.collectionHint);paragraph(C.locations.filter(l=>l.pool.includes(kind)).map(l=>l.name+' · '+l.hint).join('\n'));finishModal();}
function showSettings(){show(copy.settings,copy.intro);button(settings.assist?copy.assistOn:copy.assistOff,()=>{settings.assist=!settings.assist;save();showSettings();},panel);button(settings.reduced?copy.reducedOn:copy.reducedOff,()=>{settings.reduced=!settings.reduced;scene.reduced=settings.reduced;save();showSettings();},panel);button(settings.sound?copy.soundOn:copy.soundOff,()=>void toggleSound(),panel);const note=document.createElement('p');note.textContent=copy.soundNote+' '+C.audio.credits;panel.appendChild(note);finishModal();}

function paragraph(text:string){const p=document.createElement('p');p.textContent=text;panel.appendChild(p);return p;}
function observations(){show(copy.observe,copy.observeIntro);const kinds=new Set([...(s.observations||[]),...s.records!.map((r,i)=>r.count?i:-1)]);const grid=document.createElement('div');grid.className='collection';C.species.forEach((k,i)=>{const b=button(kinds.has(i)?k.name:copy.unknown,()=>kinds.has(i)?discovery({id:'journal',x:0,y:0,size:.05,kind:i,picked:false},false,true):clue(i),grid);if(i>=24)b.disabled=!kinds.has(i);if(kinds.has(i)){const a=document.createElement('canvas');scene.card(a,i);b.insertBefore(a,b.firstChild);}});panel.appendChild(grid);finishModal();}
function knowledge(){show(copy.knowledge,copy.knowledgeIntro);C.fieldNotes.forEach(n=>button(n.name+' · '+((s.readNotes||[]).includes(n.id)?copy.reading:copy.unread),()=>noteCard(n.id),panel));finishModal();}
function noteCard(id:string,kind?:number){const n=C.fieldNotes.find(v=>v.id===id);if(!n)return;s.readNotes=s.readNotes||[];if(!s.readNotes.includes(id))s.readNotes.push(id);save();show(n.name,n.latin);if(kind!==undefined){const art=document.createElement('canvas');art.className='specimen';scene.card(art,kind);panel.appendChild(art);paragraph(copy.toxicArt).className='fine-print';}const status=paragraph(n.status);status.className='nature-label';paragraph(n.appearance);paragraph(n.ecology);paragraph(n.fact);const d=document.createElement('details');const summary=document.createElement('summary');summary.textContent=copy.source;d.appendChild(summary);n.sources.forEach(source=>{const p=document.createElement('p');p.textContent=source.title+'\n'+source.url;d.appendChild(p);});panel.appendChild(d);paragraph(copy.knowledgeIntro).className='fine-print';finishModal(kind!==undefined?copy.look:copy.knowledge,kind!==undefined?close:knowledge);}
function progress(){show(copy.progress,copy.progressNote);C.locations.forEach((loc,i)=>{const patches=s.forest.patches.slice(i*3,i*3+3),count=patches.reduce((n,p)=>n+patchProgress(p).observed,0);button(loc.name+' · '+copy.observed+' '+count,()=>chooseSector(i),panel);});button(copy.nature+' · '+s.encounters!.length+'/6',natureBook,panel);finishModal();}
function natureBook(){show(copy.nature,copy.natureHint);C.events.forEach((e,i)=>{button(s.encounters!.includes(i)?e.name:copy.unknown,()=>{show(e.name,s.encounters!.includes(i)?e.text:C.locations[i].hint);finishModal();},panel);});finishModal();}
function journal(){show(copy.journal,copy.intro);button(copy.modes,modes,panel);button(copy.challenges+' · '+s.completed!.length+'/24',challenges,panel);button(copy.observe,observations,panel);button(copy.knowledge,knowledge,panel);button(copy.progress,progress,panel);button(copy.summary,summary,panel);button(copy.settings,showSettings,panel);finishModal();}
function places(all=false){show(copy.places,C.locations[Math.floor(s.patch/3)].hint);const available=all?6:Math.min(6,2+Math.max(s.records!.filter(r=>r.count>0).length,s.observations!.length-1));C.locations.slice(0,available).forEach((loc,i)=>button(loc.name,()=>chooseSector(i),panel));if(available<6)button(copy.allPlaces,()=>places(true),panel);finishModal();}
function chooseSector(loc:number){show(C.locations[loc].name,C.locations[loc].hint);C.locations[loc].sectors.forEach((name,i)=>{const p=patchProgress(s.forest.patches[loc*3+i]);button(name+' · '+(p.complete?copy.allCollected:copy.observed+' '+p.observed),()=>go(loc*3+i),panel);});finishModal();}
function go(patch:number){inspection=null;fly=null;pendingDiscovery=null;s.patch=patch;save();close();hint(C.locations[Math.floor(patch/3)].hint);}
function launch(mode:string,seed:number,challenge=''){inspection=null;startRun(s,seed,mode,challenge);save();close();hint(challenge?C.challenges.find(c=>c.id===challenge)!.hint:copy.hint);}
function modes(){show(copy.modes,copy.modeIntro);button(copy.free,()=>confirmRun('free',(Date.now()^Math.floor(Math.random()*0xffff))>>>0),panel);button(copy.daily,()=>{show(copy.daily,localDate()+' · '+(s.dailyDone===localDate()?copy.dailyComplete:copy.todayNote));button(copy.confirm,()=>launch('daily',dailySeed(localDate())),panel);finishModal(copy.cancel);},panel);button(copy.challenges,challenges,panel);button(copy.replay,history,panel);finishModal();}
function confirmRun(mode:string,seed:number){show(copy.newTitle,copy.newBody);button(copy.confirm,()=>launch(mode,seed),panel);finishModal(copy.cancel);}
function history(){show(copy.replay,copy.replayNote);const entries=[{seed:s.forest.seed,date:localDate(),mode:s.mode!},...s.history!].filter((h,i,a)=>a.findIndex(v=>v.seed===h.seed)===i);entries.forEach(h=>button(h.date+' · '+copy.seed+' '+h.seed,()=>confirmRun('replay',h.seed),panel));finishModal();}
function challenges(all=false){show(copy.challenges,copy.challengeNone);const recommended=C.challenges.filter(c=>!s.completed!.includes(c.id)).slice(0,3);const list=all||recommended.length===0?C.challenges:recommended;list.forEach(c=>button((s.completed!.includes(c.id)?'✓ ':'')+C.locations[c.location].name+' · '+c.name,()=>{show(c.name,c.hint);paragraph(copy.challengeHint+' · '+(s.mode==='challenge'&&s.challenge===c.id?challengeProgress(s,c.id):0)+'/'+c.target);button(copy.challengeStart,()=>launch('challenge',c.seed,c.id),panel);finishModal();},panel));if(!all&&recommended.length)button(copy.allChallenges,()=>challenges(true),panel);finishModal();}
function afterAction(){if(checkChallenges(s))hint(copy.completeHint);if(s.mode==='daily'&&s.forest.patches.some(p=>p.mushrooms.some(m=>m.picked||m.observed)))s.dailyDone=s.runDate||localDate();save();ui();}
function summary(){const ms=s.forest.patches.reduce((a,p)=>a.concat(p.mushrooms),[] as Mushroom[]),taken=ms.filter(m=>m.picked);show(copy.summary,copy.summaryNote);paragraph(copy.seed+' '+s.forest.seed+' · '+(s.mode==='daily'?copy.daily:s.mode==='challenge'?copy.challenges:s.mode==='replay'?copy.replay:copy.free));paragraph(copy.found+' '+taken.length+' · '+copy.observed+' '+ms.filter(m=>m.observed).length);const c=C.challenges.find(c=>c.id===s.challenge);if(c)paragraph(c.name+' · '+challengeProgress(s,c.id)+'/'+c.target);button(copy.arrange,arrange,panel);button(copy.next,()=>confirmRun('free',Date.now()>>>0),panel);finishModal();}
function arrange(){show(copy.arrange,copy.arrangeHint);const themes=document.createElement('div');themes.className='themes';C.collections.forEach((t,i)=>button(t.name,()=>{s.theme=i;s.layout=undefined;save();arrange();},themes));panel.appendChild(themes);const theme=C.collections[s.theme??4],kinds=s.records!.map((r,i)=>r.count?i:-1).filter(i=>i>=0&&(theme.family==='all'||theme.family==='cluster'&&s.records![i].count>=2||theme.family==='local'&&s.records![i].places.includes(Math.floor(s.patch/3))||theme.family==='large'&&s.records![i].max>.06||C.species[i].family===theme.family)).slice(0,12);if(!s.layout){const arranged=theme.family==='cluster'?kinds.reduce((a,kind)=>a.concat(Array(Math.min(3,s.records![kind].count)).fill(kind)),[] as number[]).slice(0,12):kinds;s.layout=arranged.map((kind,i)=>({kind,x:.20+(i%3)*.30,y:.22+Math.floor(i/3)*.17}));}const board=document.createElement('div');board.className='arrangement';panel.appendChild(board);const backdrop=document.createElement('canvas');backdrop.width=360;backdrop.height=360;backdrop.className='basket-backdrop';scene.sprite(backdrop.getContext('2d')!,'props',4,0,0,360,360);board.appendChild(backdrop);let selectedItem:{kind:number;x:number;y:number}|null=null;board.onclick=e=>{if(!selectedItem||e.target!==board)return;const r=board.getBoundingClientRect();selectedItem.x=Math.max(.12,Math.min(.88,(e.clientX-r.left)/r.width));selectedItem.y=Math.max(.12,Math.min(.88,(e.clientY-r.top)/r.height));save();arrange();};s.layout.forEach(item=>{const art=document.createElement('canvas');scene.card(art,item.kind);art.setAttribute('aria-label',C.species[item.kind].name);art.setAttribute('role','button');art.tabIndex=0;art.onclick=()=>{selectedItem=item;art.style.outline='1px solid #e7d8b3';};art.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();item.x=Math.max(.12,Math.min(.88,item.x+(e.key==='ArrowLeft'?-.04:e.key==='ArrowRight'?.04:0)));item.y=Math.max(.12,Math.min(.88,item.y+(e.key==='ArrowUp'?-.04:e.key==='ArrowDown'?.04:0)));art.style.left=item.x*100+'%';art.style.top=item.y*100+'%';save();}};art.style.left=(item.x*100)+'%';art.style.top=(item.y*100)+'%';board.appendChild(art);let active:number|null=null,origin={x:item.x,y:item.y};art.onpointerdown=e=>{active=e.pointerId;origin={x:item.x,y:item.y};art.setPointerCapture(e.pointerId);};art.onpointermove=e=>{if(active!==e.pointerId)return;const r=board.getBoundingClientRect();item.x=Math.max(.12,Math.min(.88,(e.clientX-r.left)/r.width));item.y=Math.max(.12,Math.min(.88,(e.clientY-r.top)/r.height));art.style.left=item.x*100+'%';art.style.top=item.y*100+'%';};art.onpointerup=()=>{active=null;save();};art.onpointercancel=()=>{active=null;Object.assign(item,origin);art.style.left=item.x*100+'%';art.style.top=item.y*100+'%';};});if(!s.layout.length)paragraph(copy.emptyTheme);finishModal();}
function ui(){const tools=$('tools');tools.textContent='';const goal=C.challenges.find(c=>c.id===s.challenge);$('objective').textContent=goal&&goal.location===Math.floor(s.patch/3)?goal.name+' · '+challengeProgress(s,goal.id)+'/'+goal.target:'';button(inspection?copy.putBack:scene.targetCrouch?copy.stand:copy.crouch,()=>{cancelDrag();if(inspection){inspection=null;hint(copy.hint);}else{scene.targetCrouch=scene.targetCrouch?0:1;hint(scene.targetCrouch?copy.crouchHint:copy.standHint);}ui();},tools);button(copy.places,places,tools);button(copy.journal,journal,tools);button(copy.basket+' · '+s.records!.reduce((n,r)=>n+r.count,0),basket,tools);$('eyebrow').textContent=C.locations[Math.floor(s.patch/3)].sectors[s.patch%3];const nav=$('sectors');nav.textContent='';button('‹',()=>go(Math.floor(s.patch/3)*3+(s.patch+2)%3),nav).setAttribute('aria-label',copy.previousSector);const label=document.createElement('span');label.textContent=(s.patch%3+1)+'/3';nav.appendChild(label);button('›',()=>go(Math.floor(s.patch/3)*3+(s.patch+1)%3),nav).setAttribute('aria-label',copy.nextSector);const b=scene.basketPosition(),target=$('basket-target');target.style.left=(b.x-b.r)+'px';target.style.top=(b.y-b.r)+'px';target.style.width=b.r*2+'px';target.style.height=b.r*2+'px';target.setAttribute('aria-label',copy.basketHint);}
$('basket-target').onclick=()=>{if(inspection){if(inspection.mask===4095)finishInspection();else hint(copy.brushReturn);}else basket();};
function down(id:number,x:number,y:number){if(settings.sound)void unlockSound();const safe=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--safe-area-inset-top'))||0,host=C.layout.hostWidth+C.layout.hostOffset+C.layout.hostMargin;if(paused||drag||fly||y<safe||(y<safe+C.layout.hostHeight+C.layout.hostOffset+C.layout.hostMargin&&(x<host||x>innerWidth-host)))return;if(inspection){const p={x:(x-scene.ox)/scene.scale-.5,y:(y-scene.oy)/scene.scale-.5};if(Math.hypot(p.x,p.y)>.4)return;inspection.carrying=inspection.mask===4095;drag={id,x:p.x,y:p.y,time:performance.now(),lastTime:performance.now(),travel:0,grip:{left:0,right:0,lastX:p.x,startY:p.y}};return;}const p=scene.point(x,y),patch=s.forest.patches[s.patch];const leaf=[...patch.leaves].reverse().find(l=>leafHit(viewLeaf(l,scene.crouch),p.x,p.y));drag={id,x:p.x,y:p.y,time:performance.now(),lastTime:performance.now(),travel:0,grip:{left:0,right:0,lastX:p.x,startY:p.y}};if(patch.encounter&&Math.hypot(p.x-patch.encounter.x,p.y-patch.encounter.y)<.08){drag.event=true;hint(copy.natureHint);}else if(leaf){drag.leaf=leaf;drag.origin={x:leaf.x,y:leaf.y,angle:leaf.angle};leaf.vx=0;leaf.vy=0;hint(copy.hint);}else{drag.m=[...patch.mushrooms].sort((a,b)=>b.y-a.y).find(m=>!m.picked&&Math.hypot((m.x-p.x)/(m.size*1.3),(m.y-m.size*.9-p.y)/(m.size*1.5))<1&&exposed(patch,m,scene.crouch));hint(drag.m?(C.species[drag.m.kind].observeOnly?copy.toxicHint:settings.assist?copy.assistHint:copy.holding):copy.emptyGround);}}
function move(id:number,x:number,y:number){if(!drag||drag.id!==id||paused)return;if(inspection){const p={x:(x-scene.ox)/scene.scale-.5,y:(y-scene.oy)/scene.scale-.5};if(inspection.carrying)inspection.at={x,y};else{const before=inspection.mask;inspection.mask=brushDirt(inspection.mask,{x:drag.x,y:drag.y},p);if(before!==inspection.mask){if(!settings.reduced)scene.brush(before,inspection.mask);noise('leaf');}hint(inspection.mask===4095?copy.brushReady:copy.brushHint);}drag.x=p.x;drag.y=p.y;return;}const p=scene.point(x,y),dx=p.x-drag.x,dy=p.y-drag.y,now=performance.now(),dt=Math.max(.012,(now-drag.lastTime)/1000);drag.travel+=Math.hypot(dx,dy);if(drag.leaf){drag.leaf.x=Math.max(-.13,Math.min(1.13,drag.leaf.x+dx));drag.leaf.y=Math.max(-.13,Math.min(1.13,drag.leaf.y+dy));drag.leaf.angle+=dx*(drag.leaf.type==='branch'?2.5:1.2);drag.leaf.vx=Math.max(-.5,Math.min(.5,dx/dt));drag.leaf.vy=Math.max(-.5,Math.min(.5,dy/dt));}else if(drag.m){const ready=moveGrip(drag.grip,p.x,p.y,drag.m.size);if(drag.grip.left>=drag.m.size*.3&&drag.grip.right>=drag.m.size*.3)hint(copy.loose);if(ready&&!C.species[drag.m.kind].observeOnly)harvest(drag.m);}if(drag){drag.x=p.x;drag.y=p.y;drag.lastTime=now;}}
let ambientAt=0;
let pendingDiscovery:{m:Mushroom;fresh:boolean}|null=null;
function harvest(m:Mushroom){if(C.species[m.kind].observeOnly||!exposed(s.forest.patches[s.patch],m,scene.crouch))return;inspection={m,mask:0};drag=null;noise('pick');hint(copy.brushHint);ui();}
function finishInspection(){if(!inspection||inspection.mask!==4095)return;const m=inspection.m,fresh=!s.records![m.kind].count;if(pick(s,m,scene.crouch)){const origin=inspection.at||{x:scene.ox+scene.scale*.5,y:scene.oy+scene.scale*.5};inspection=null;fly={m:{...m},t:0,origin};pendingDiscovery={m:{...m},fresh};hint(C.species[m.kind].name+' · '+copy.found);noise('pick');afterAction();}drag=null;}
function up(id:number,cancel=false){if(drag?.id!==id)return;if(inspection){const at=inspection.at,b=scene.basketPosition();if(!cancel&&inspection.carrying&&at&&Math.hypot(at.x-b.x,at.y-b.y)<b.r*1.3)finishInspection();else{inspection.at=undefined;inspection.carrying=false;hint(inspection.mask===4095?copy.brushReady:copy.brushReturn);}drag=null;return;}if(cancel){cancelDrag();hint(copy.hint);}else if(drag.event&&drag.travel<.02){encounter(s);const e=C.events[s.forest.patches[s.patch].encounter!.kind];drag=null;afterAction();show(e.name,e.text);finishModal();}else if(drag.m&&drag.travel<.018&&performance.now()-drag.time<350){const m=drag.m;drag=null;if(observe(s,m,scene.crouch)){afterAction();discovery(m,false,true);}}else if(drag.m&&C.species[drag.m.kind].observeOnly){const m=drag.m;drag=null;if(observe(s,m,scene.crouch)){afterAction();discovery(m,false,true);}}else if(settings.assist&&drag.m&&performance.now()-drag.time>=C.tuning.holdMs)harvest(drag.m);else{if(drag.leaf){if(drag.origin&&Math.hypot(drag.leaf.x-drag.origin.x,drag.leaf.y-drag.origin.y)>.06)drag.leaf.moved=true;noise('leaf');hint(copy.leafMoved);afterAction();}drag=null;}save();}
if(typeof PointerEvent!=='undefined'){canvas.onpointerdown=e=>{if(e.button!==0)return;down(e.pointerId,e.clientX,e.clientY);if(drag)try{canvas.setPointerCapture(e.pointerId);}catch{}};canvas.onpointermove=e=>move(e.pointerId,e.clientX,e.clientY);canvas.onpointerup=e=>up(e.pointerId);canvas.onpointercancel=e=>up(e.pointerId,true);canvas.onlostpointercapture=e=>up(e.pointerId,true);}else{canvas.ontouchstart=e=>{if(e.touches.length!==1)return;const t=e.changedTouches[0];down(t.identifier,t.clientX,t.clientY);};canvas.ontouchmove=e=>{e.preventDefault();for(const t of Array.from(e.changedTouches))move(t.identifier,t.clientX,t.clientY);};canvas.ontouchend=e=>up(e.changedTouches[0].identifier);canvas.ontouchcancel=e=>up(e.changedTouches[0].identifier,true);canvas.onmousedown=e=>down(-1,e.clientX,e.clientY);window.onmousemove=e=>move(-1,e.clientX,e.clientY);window.onmouseup=()=>up(-1);}
panel.oncancel=e=>{e.preventDefault();close();};window.onresize=()=>{cancelDrag();scene.resize();ui();};
let frameSamples=0,frameTotal=0,slowWindows=0;
function frame(now:number){if(document.hidden){raf=0;return;}const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(!paused&&dt>0){frameSamples++;frameTotal+=dt;if(frameTotal>=2){slowWindows=frameTotal/frameSamples>.04?slowWindows+1:0;if(slowWindows>=2&&!scene.low){scene.low=true;scene.resize();ui();}frameSamples=0;frameTotal=0;}}if(!paused){time+=dt;if(time-ambientAt>8){ambientAt=time;noise('water');}const patch=s.forest.patches[s.patch];if(!inspection)settleLeaves({leaves:patch.leaves.filter(l=>l!==drag?.leaf)},dt);if(fly){fly.t+=dt*2.1;if(fly.t>=1){fly=null;const event=pendingDiscovery;pendingDiscovery=null;if(event?.fresh)discovery(event.m,true);}}}if(now-drawAt>=32){scene.draw(s.forest.patches[s.patch],drag?.m?.id||null,drag?.m?Math.sin((drag.grip.left+drag.grip.right)*35)*.16:0,fly,s.patch,time,s.basket,drag?.leaf||null,inspection);drawAt=now;}raf=requestAnimationFrame(frame);}
document.onvisibilitychange=()=>{if(document.hidden){cancelDrag();save();stopSound();if(audio)void audio.suspend();if(raf)cancelAnimationFrame(raf);raf=0;}else{last=0;if(settings.sound&&audio)void audio.resume().catch(()=>hint(copy.silent));if(!raf)raf=requestAnimationFrame(frame);}};window.addEventListener('storage',e=>{if(e.key===C.storageKey&&e.newValue){try{futureSave=(JSON.parse(e.newValue).version||0)>C.version;}catch{}const next=readSave(e.newValue);if(next){cancelDrag();inspection=null;fly=null;pendingDiscovery=null;s=normalize(next);Object.assign(settings,s.settings||{});s.settings=settings;scene.reduced=settings.reduced;if(panel.open)close();ui();}}});window.onpagehide=()=>{cancelDrag();save();stopSound();if(raf)cancelAnimationFrame(raf);raf=0;};window.onpageshow=()=>{last=0;if(!raf)raf=requestAnimationFrame(frame);};ui();raf=requestAnimationFrame(frame);
