import C from './content/content.json';
export interface Mushroom{id:string;x:number;y:number;size:number;kind:number;picked:boolean;observed?:boolean;slot?:number}
export interface Leaf{x:number;y:number;r:number;angle:number;shade:number;vx?:number;vy?:number;type?:string;moved?:boolean}
export interface Encounter{kind:number;x:number;y:number;seen:boolean}
export interface Patch{mushrooms:Mushroom[];leaves:Leaf[];encounter?:Encounter;location?:number;sector?:number}
export interface Forest{seed:number;patches:Patch[]}
export interface RecordEntry{count:number;min:number;max:number;places:number[]}
export interface History{seed:number;date:string;mode:string}
export interface Save{version?:number;forest:Forest;patch:number;basket:Mushroom[];observations?:number[];readNotes?:string[];settings?:{assist:boolean;sound:boolean;reduced:boolean};records?:RecordEntry[];completed?:string[];history?:History[];encounters?:number[];mode?:string;challenge?:string;dailyDone?:string;runDate?:string;dailyCache?:{date:string;forest:Forest;patch:number;basket:Mushroom[]};layout?:{kind:number;x:number;y:number}[];theme?:number;practice?:boolean}
export function random(seed:number){let s=seed>>>0;return()=>((s=Math.imul(s,1664525)+1013904223)>>>0)/4294967296;}
export function localDate(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
export function dailySeed(date:string){let h=2166136261;for(const ch of 'forest-2:'+date)h=Math.imul(h^ch.charCodeAt(0),16777619);return h>>>0;}
export function forestPositions(seed:number,location:number,sector:number){const r=random((seed^Math.imul(location+1,73856093)^Math.imul(sector+1,19349663))>>>0),b=C.forestLayout,result:{x:number;y:number}[]=[];for(let i=0;i<6;i++){let best={x:.5,y:.5},distance=-1;for(let trial=0;trial<80;trial++){const candidate={x:b.left+r()*(b.right-b.left),y:b.top+r()*(b.bottom-b.top)},gap=result.length?Math.min(...result.map(p=>Math.hypot(p.x-candidate.x,p.y-candidate.y))):1;if(gap>distance){best=candidate;distance=gap;}if(gap>=b.gap)break;}result.push(best);}return result;}
export function generate(seed:number):Forest{const r=random(seed),patches:Patch[]=[];
 for(let loc=0;loc<6;loc++){const count=10+Math.floor(r()*7),occupied=Array.from({length:18},(_,i)=>i); // Fisher-Yates keeps generation stable across engines
 for(let i=17;i>0;i--){const j=Math.floor(r()*(i+1));[occupied[i],occupied[j]]=[occupied[j],occupied[i]];}
 const slots=new Set(occupied.slice(0,count));for(let sector=0;sector<3;sector++){if(!Array.from(slots).some(i=>Math.floor(i/6)===sector)){const replace=Array.from(slots).find(i=>Array.from(slots).filter(j=>Math.floor(j/6)===Math.floor(i/6)).length>1)!;slots.delete(replace);slots.add(sector*6);}}
 for(let sector=0;sector<3;sector++){const mushrooms:Mushroom[]=[],leaves:Leaf[]=[];const pool=C.locations[loc].pool,positions=forestPositions(seed,loc,sector);
 for(let i=0;i<6;i++){const x=positions[i].x+(r()-.5)*.012,y=positions[i].y+(r()-.5)*.012;
 if(slots.has(sector*6+i)){const n=1+Math.floor(r()*3),kind=pool[(sector*2+i)%pool.length];for(let j=0;j<n;j++)mushrooms.push({id:`${seed}:${loc}:${sector}:${i}:${j}`,x:x+(j-1)*.052,y:y+(j%2)*.035,size:(i===0?.039:i===1?.067:.045+r()*.018),kind,picked:false,slot:i});}
 for(let k=0;k<3;k++)leaves.push({x:x+(r()-.5)*.04+(k===1?.025:0),y:y-.02-k*.024+(r()-.5)*.05,r:.085+r()*.026,angle:r()*6.28,shade:r(),type:C.locations[loc].occluder});}
 const litter=random(seed^Math.imul(loc+1,8317)^Math.imul(sector+1,17389));const q=(n:number)=>Math.round(n*10000)/10000;const loose:Leaf[]=[];for(let j=0;j<C.forestLitter.count;j++)loose.push({x:q(.04+litter()*.92),y:q(.12+litter()*.78),r:q(C.forestLitter.minRadius+litter()*C.forestLitter.radiusRange),angle:q(litter()*6.28),shade:q(litter()),type:j%5===0?'needle':'leaf'});leaves.unshift(...loose);
 // Only observational additions; fictional collection remains exactly 24 base species.
 if(sector===1)mushrooms.push({id:`${seed}:${loc}:real`,x:.50,y:.48,size:.052,kind:24+loc%3,picked:false,slot:6});
 patches.push({location:loc,sector,mushrooms,leaves,encounter:{kind:loc,x:.85,y:.88,seen:false}});}}
 return{seed,patches};}
export function leafHit(l:Leaf,x:number,y:number){const dx=x-l.x,dy=y-l.y,c=Math.cos(l.angle),s=Math.sin(l.angle),ratio=l.type==='branch'?.18:.57;return((dx*c+dy*s)/l.r)**2+((-dx*s+dy*c)/(l.r*ratio))**2<1;}
export function exposed(p:Patch,m:Mushroom,crouch=0){let free=0;for(let i=0;i<16;i++){const a=i*2.4,r=m.size*Math.sqrt((i+.5)/16),x=m.x+Math.cos(a)*r,y=m.y-m.size*1.05+Math.sin(a)*r*.6;if(!p.leaves.some(l=>leafHit(viewLeaf(l,crouch),x,y)))free++;}return free/16>=.45;}
export function baseRecords(basket:Mushroom[]){return Array.from({length:24},(_,kind)=>{const list=basket.filter(m=>m.kind===kind);return{count:list.length,min:list.length?Math.min(...list.map(m=>m.size)):0,max:list.length?Math.max(...list.map(m=>m.size)):0,places:[] as number[]};});}
export function normalize(s:Save){s.version=2;s.records=s.records||baseRecords(s.basket);s.completed=s.completed||[];s.observations=s.observations||[];s.history=s.history||[];s.encounters=s.encounters||[];s.mode=s.mode||'free';s.basket=s.basket.slice(-72);return s;}
export function pick(s:Save,m:Mushroom,crouch=0){const p=s.forest.patches[s.patch];if(!p.mushrooms.includes(m)||m.picked||C.species[m.kind]?.observeOnly||!exposed(p,m,crouch)||s.basket.some(v=>v.id===m.id))return false;
 const records=s.records; m.picked=true;m.observed=true;s.basket.push({...m});if(records&&s.mode!=='replay'){const v=records[m.kind];v.count++;v.min=v.min?Math.min(v.min,m.size):m.size;v.max=Math.max(v.max,m.size);const loc=p.location??Math.floor(s.patch/3);if(!v.places.includes(loc))v.places.push(loc);}if(s.basket.length>72)s.basket.shift();if(s.observations&&!s.observations.includes(m.kind))s.observations.push(m.kind);return true;}
export function observe(s:Save,m:Mushroom,crouch=0){const p=s.forest.patches[s.patch];if(!p.mushrooms.includes(m)||m.picked||!exposed(p,m,crouch))return false;m.observed=true;s.observations=s.observations||[];if(!s.observations.includes(m.kind))s.observations.push(m.kind);return true;}
export function encounter(s:Save){const e=s.forest.patches[s.patch].encounter;if(!e)return false;e.seen=true;s.encounters=s.encounters||[];if(!s.encounters.includes(e.kind))s.encounters.push(e.kind);return true;}
export function patchProgress(p:Patch){const ms=p.mushrooms.filter(m=>!C.species[m.kind].observeOnly);return{observed:p.mushrooms.filter(m=>m.observed||m.picked).length,collected:ms.filter(m=>m.picked).length,complete:ms.every(m=>m.picked)};}
export function challengeProgress(s:Save,id:string){const c=C.challenges.find(v=>v.id===id);if(!c)return 0;const ps=s.forest.patches.filter((p,i)=>(p.location??Math.floor(i/3))===c.location),seen=(p:Patch)=>p.mushrooms.filter(m=>m.observed||m.picked),ms=ps.reduce((a,p)=>a.concat(seen(p)),[] as Mushroom[]);let value=0;
 switch(c.type){case 'observe':value=ms.length;break;case 'sector':value=ps.filter(p=>p.sector===c.sector).reduce((n,p)=>n+seen(p).length,0);break;case 'sectors':value=ps.filter(p=>seen(p).length>0).length;break;case 'lightshade':value=ps.filter(p=>(p.sector===1||p.sector===2)&&seen(p).length>0).length;break;case 'small':value=ms.filter(m=>m.size<.045).length;break;case 'large':value=ms.filter(m=>m.size>.06).length;break;case 'family':value=ms.filter(m=>C.species[m.kind].family==='fan').length;break;case 'slender':value=ms.filter(m=>['round','bell'].includes(C.species[m.kind].family)).length;break;case 'cluster':case 'clusters':for(const p of ps){for(let slot=0;slot<6;slot++){const group=p.mushrooms.filter(m=>m.slot===slot);if(group.length&&(c.type==='cluster'?group.every(m=>m.picked):group.some(m=>m.observed||m.picked)))value++;}}break;default:value=ps.reduce((n,p)=>n+p.leaves.filter(l=>l.moved&&(c.type==='leaves'||l.type===c.type)).length,0);}
 return Math.min(c.target,value);}
export function checkChallenges(s:Save){if(s.mode!=='challenge'||!s.challenge)return false;const c=C.challenges.find(v=>v.id===s.challenge);if(!c||challengeProgress(s,c.id)<c.target)return false;s.completed=s.completed||[];if(s.completed.includes(c.id))return false;s.completed.push(c.id);return true;}
export function startRun(s:Save,seed:number,mode:string,challenge=''){normalize(s);const key=s.forest.seed;if(!s.history!.some(h=>h.seed===key))s.history!.unshift({seed:key,date:localDate(),mode:s.mode!});s.history=s.history!.slice(0,20);if(s.mode==='daily')s.dailyCache={date:s.runDate||localDate(),forest:s.forest,patch:s.patch,basket:s.basket};if(mode==='daily'&&s.dailyCache?.date===localDate()&&s.dailyCache.forest.seed===seed){s.forest=s.dailyCache.forest;s.patch=s.dailyCache.patch;s.basket=s.dailyCache.basket;s.dailyCache=undefined;s.mode=mode;s.runDate=localDate();s.challenge='';return;}s.runDate=localDate();if(mode==='daily')s.dailyCache=undefined;s.forest=generate(seed);s.basket=[];s.patch=0;s.mode=mode;s.challenge=challenge;s.practice=false;const c=C.challenges.find(v=>v.id===challenge);if(c)s.patch=c.location*3;}
export function readSave(raw:string|null):Save|null{try{const s=JSON.parse(raw||'null') as Save;if(!s||s.version&&s.version>2||!s.forest||!Number.isInteger(s.forest.seed)||!Array.isArray(s.forest.patches)||![3,18].includes(s.forest.patches.length)||!Number.isInteger(s.patch)||s.patch<0||s.patch>=s.forest.patches.length||!Array.isArray(s.basket)||s.basket.length>10000)return null;
 const validM=(m:Mushroom)=>m&&Number.isFinite(m.x+m.y+m.size)&&m.size>0&&m.size<.5&&Number.isInteger(m.kind)&&m.kind>=0&&m.kind<C.species.length&&typeof m.id==='string'&&m.id.length<128&&typeof m.picked==='boolean'&&(m.observed===undefined||typeof m.observed==='boolean');
 if(s.basket.some(m=>!validM(m))||new Set(s.basket.map(m=>m.id)).size!==s.basket.length)return null;
 for(const p of s.forest.patches){if(!Array.isArray(p.leaves)||!Array.isArray(p.mushrooms)||p.leaves.length>60||p.mushrooms.length>35||p.mushrooms.some(m=>!validM(m)))return null;for(const l of p.leaves)if(!Number.isFinite(l.x+l.y+l.r+l.angle+l.shade)||l.r<=0||l.r>.5||Math.abs(l.x)>2||Math.abs(l.y)>2||!Number.isFinite((l.vx??0)+(l.vy??0)))return null;if(p.encounter&&(!Number.isInteger(p.encounter.kind)||p.encounter.kind<0||p.encounter.kind>5||!Number.isFinite(p.encounter.x+p.encounter.y)))return null;}
 if(s.observations&&(!Array.isArray(s.observations)||s.observations.length>27||s.observations.some(k=>!Number.isInteger(k)||k<0||k>26)))return null;if(s.readNotes&&(!Array.isArray(s.readNotes)||s.readNotes.length>32||s.readNotes.some(k=>typeof k!=='string'||k.length>64)))return null;
 if(s.records&&(!Array.isArray(s.records)||s.records.length!==24||s.records.some(v=>!Number.isInteger(v.count)||v.count<0||v.count>1e9||!Number.isFinite(v.min+v.max)||!Array.isArray(v.places)||v.places.length>6||v.places.some(x=>!Number.isInteger(x)||x<0||x>5))))return null;
 if(s.completed&&(!Array.isArray(s.completed)||s.completed.length>24||s.completed.some(id=>!C.challenges.some(c=>c.id===id))))return null;
 if(s.encounters&&(!Array.isArray(s.encounters)||s.encounters.length>6||s.encounters.some(v=>!Number.isInteger(v)||v<0||v>5)))return null;
 if(s.history&&(!Array.isArray(s.history)||s.history.length>20||s.history.some(h=>!Number.isInteger(h.seed)||typeof h.date!=='string'||h.date.length>20||typeof h.mode!=='string')))return null;
 if(s.dailyCache){const d=s.dailyCache;if(typeof d.date!=='string'||d.date.length>20||!readSave(JSON.stringify({version:2,forest:d.forest,patch:d.patch,basket:d.basket})))return null;}if(s.runDate&&(typeof s.runDate!=='string'||s.runDate.length>20))return null;
 if(s.layout&&(!Array.isArray(s.layout)||s.layout.length>12||s.layout.some(v=>!Number.isInteger(v.kind)||v.kind<0||v.kind>23||!Number.isFinite(v.x+v.y)||v.x<0||v.x>1||v.y<0||v.y>1)))return null;
 if(s.settings)s.settings={assist:!!s.settings.assist,sound:!!s.settings.sound,reduced:!!s.settings.reduced};
 if(s.forest.patches.length===3){const forest=generate(s.forest.seed);s.forest.patches.forEach((p,i)=>{forest.patches[i*3]={...p,location:i,sector:0,encounter:forest.patches[i*3].encounter};});s.forest=forest;s.patch*=3;normalize(s);}return s;
 }catch{return null;}}
export interface Grip{left:number;right:number;startY:number;lastX:number}
export function viewLeaf(l:Leaf,crouch=0):Leaf{return{...l,x:l.x+Math.sin(l.angle)*crouch*.025,y:l.y+crouch*.055};}
export function dirtPoints(){return Array.from({length:12},(_,i)=>({x:Math.cos(i*2.399)*(.035+(i%4)*.022),y:-.15+Math.sin(i*2.399)*.055}));}
export function brushDirt(mask:number,from:{x:number;y:number},to:{x:number;y:number}){if(!Number.isFinite(from.x+from.y+to.x+to.y))return mask;const dx=to.x-from.x,dy=to.y-from.y,length=dx*dx+dy*dy;if(length<.000004)return mask;dirtPoints().forEach((p,i)=>{const u=Math.max(0,Math.min(1,((p.x-from.x)*dx+(p.y-from.y)*dy)/length));if(Math.hypot(p.x-from.x-u*dx,p.y-from.y-u*dy)<.043)mask|=1<<i;});return mask;}
export function moveGrip(g:Grip,x:number,y:number,size:number){const dx=x-g.lastX;g.lastX=x;if(dx<0)g.left-=dx;else g.right+=dx;return g.left>=size*.3&&g.right>=size*.3&&g.startY-y>=size*.85;}
export function settleLeaves(p:Pick<Patch,'leaves'>,dt:number){for(const l of p.leaves){if(!l.vx&&!l.vy)continue;l.x=Math.max(-.13,Math.min(1.13,l.x+(l.vx||0)*dt));l.y=Math.max(-.13,Math.min(1.13,l.y+(l.vy||0)*dt));l.vx=(l.vx||0)*Math.exp(-dt*17);l.vy=(l.vy||0)*Math.exp(-dt*17);if(Math.abs(l.vx)+Math.abs(l.vy)<.003){l.vx=0;l.vy=0;}}}
