import {EnvironmentMotion} from './environment-motion';
import {reeds,wind,contactRings} from './atmosphere';
import C from './content/content.json';
import {viewLeaf,dirtPoints,type Patch,type Mushroom,type Leaf} from './model';
export interface Inspection{m:Mushroom;mask:number;at?:{x:number;y:number};carrying?:boolean}
type SpriteKey='mushrooms'|'props'|'expanded'|'nature'|'occluders'|'families';
export interface Flight{m:Mushroom;t:number;origin?:{x:number;y:number}}
export class Scene {
 environment=new EnvironmentMotion();
 soil:{x:number;y:number;vx:number;vy:number;life:number}[]=[];
 crouch=0;targetCrouch=0;cameraTime=0;ctx:CanvasRenderingContext2D;w=1;h=1;scale=1;ox=0;oy=0;dpr=1;reduced=false;low=false;transition=0;lastPatch=-1;imageGroup=-1;
 images={mushrooms:new Image(),props:new Image(),forest:new Image(),expanded:new Image(),nature:new Image(),forestExtra:new Image(),occluders:new Image(),families:new Image()};
 constructor(public canvas:HTMLCanvasElement){this.ctx=canvas.getContext('2d')!;for(const key of ['mushrooms','props','expanded','nature','occluders','families'] as const)this.images[key].src=C.visuals[key].src;this.resize();}
 resize(){this.w=innerWidth;this.h=innerHeight;this.dpr=Math.min(devicePixelRatio||1,this.low?1:1.5,Math.sqrt((this.low?800000:1400000)/(this.w*this.h)));this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.scale=Math.min(this.w*.91,this.h*.63);this.ox=this.h>this.w?(this.w-this.scale)/2:this.w*.38-this.scale/2;this.oy=(this.h-this.scale)/2;}
 point(x:number,y:number){const z=1+this.crouch*.28;return{x:((x-this.ox)/this.scale-.5)/z+.5,y:((y-this.oy)/this.scale-.5-this.crouch*.025)/z+.5};}
 sprite(g:CanvasRenderingContext2D,key:SpriteKey,index:number,x:number,y:number,w:number,h:number){const im=this.images[key],f=C.visuals[key].frames[index];if(im.complete&&im.naturalWidth&&f)g.drawImage(im,f.x,f.y,f.w,f.h,x,y,w,h);}
 specimen(g:CanvasRenderingContext2D,kind:number,x:number,y:number,w:number,h:number){const k=C.species[kind],f=C.visuals[k.atlas as SpriteKey].frames[k.frame],scale=Math.min(w/f.w,h/f.h),dw=f.w*scale,dh=f.h*scale;this.sprite(g,k.atlas as SpriteKey,k.frame,x+(w-dw)/2,y+h-dh,dw,dh);}
 mushroom(g:CanvasRenderingContext2D,m:Mushroom,tilt=0){g.save();g.translate(m.x,m.y);g.rotate(tilt);g.fillStyle='#10180c66';g.beginPath();g.ellipse(0,.006,m.size*.8,m.size*.24,0,0,Math.PI*2);g.fill();this.specimen(g,m.kind,-m.size,-m.size*2,m.size*2,m.size*2.45);g.restore();}
 card(canvas:HTMLCanvasElement,kind:number){canvas.width=240;canvas.height=240;const k=C.species[kind],im=this.images[k.atlas as SpriteKey];const draw=()=>{const g=canvas.getContext('2d')!,f=C.visuals[k.atlas as SpriteKey].frames[k.frame],h=210,w=Math.min(224,h*f.w/f.h);g.clearRect(0,0,240,240);this.specimen(g,kind,(240-w)/2,10,w,h);};if(im.complete)draw();else im.addEventListener('load',draw,{once:true});}
 brush(before:number,after:number){dirtPoints().forEach((d,i)=>{if((after&(1<<i))&&!(before&(1<<i)))for(let j=0;j<3;j++){if(this.soil.length>=48)this.soil.shift();this.soil.push({x:this.ox+(.5+d.x)*this.scale,y:this.oy+(.5+d.y)*this.scale,vx:Math.sin(i*2.4+j)*12,vy:-3-j*3,life:.5+j*.06});}});}
 basketPosition(){return this.h>this.w?{x:this.w*.77,y:this.h*.81,r:48}:{x:this.w*.79,y:this.h*.53,r:48};}
 draw(p:Patch,selected:string|null,tilt:number,fly:Flight|null,patch:number,time:number,basket:Mushroom[],activeLeaf:Leaf|null,inspection:Inspection|null=null){
 const dt=Math.min(.05,Math.max(0,time-this.cameraTime));this.cameraTime=time;this.crouch+=(this.targetCrouch-this.crouch)*(this.reduced?1:1-Math.exp(-dt*6));const g=this.ctx,w=this.w,h=this.h,loc=p.location??Math.floor(patch/3),group=loc<3?0:1;
 if(group!==this.imageGroup){this.imageGroup=group;const key=group?'forestExtra':'forest';this.images[key].src=C.visuals[key].src;this.images[group?'forest':'forestExtra'].removeAttribute('src');}
 if(patch!==this.lastPatch){this.lastPatch=patch;this.transition=this.reduced?0:1;}this.transition=Math.max(0,this.transition-.085);
 g.setTransform(this.dpr,0,0,this.dpr,0,0);g.fillStyle='#344334';g.fillRect(0,0,w,h);
 const bg=group?this.images.forestExtra:this.images.forest,f=C.visuals[group?'forestExtra':'forest'].frames[loc%3];if(bg.complete&&bg.naturalWidth){const scale=Math.max(w/f.w,h/f.h)*(1.08+this.crouch*.1),dw=f.w*scale,dh=f.h*scale,offset=((p.sector??0)-1)*w*.025;const live=this.environment.draw(bg,f,C.environmentMotion[loc],time,this.low,this.reduced);if(this.canvas.dataset.environment!==this.environment.mode)this.canvas.dataset.environment=this.environment.mode;if(live)g.drawImage(live,(w-dw)/2+offset,(h-dh)/2+this.crouch*h*.025,dw,dh);else g.drawImage(bg,f.x,f.y,f.w,f.h,(w-dw)/2+offset,(h-dh)/2+this.crouch*h*.025,dw,dh);}
 reeds(g,w,h,time,C.atmosphere.reeds,this.low,this.reduced);
 const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#10251655');shade.addColorStop(.27,'#10251600');shade.addColorStop(.72,'#10251600');shade.addColorStop(1,'#0b2015bb');g.fillStyle=shade;g.fillRect(0,0,w,h);
 if(!this.reduced&&!this.low){g.save();g.globalAlpha=.035+Math.sin(time*.23)*.015;const ray=g.createLinearGradient(w*.8,0,w*.3,h);ray.addColorStop(0,'#fff3bbaa');ray.addColorStop(.6,'#ede8ac33');ray.addColorStop(1,'#ede8ac00');g.fillStyle=ray;g.beginPath();g.moveTo(w*.75,0);g.lineTo(w*.98,0);g.lineTo(w*.58,h);g.lineTo(w*.12,h);g.fill();g.restore();}
 if(!this.reduced){for(let i=0;i<(this.low?2:5);i++){const cycle=(time*.23+i*.731)%1,x=w*(i%2?.94:.045)+Math.sin(i*9)*w*.025,ground=h*(.5+(i%3)*.12);if(cycle<.2){const u=cycle/.2;g.strokeStyle='rgba(213,230,204,.38)';g.lineWidth=.8;g.beginPath();g.moveTo(x,ground-30+u*u*30);g.lineTo(x,ground-27+u*u*30);g.stroke();}else contactRings(g,x,ground,(cycle-.2)*7,.3,.3);}}
 g.save();g.translate(this.ox,this.oy);g.scale(this.scale,this.scale);g.translate(.5,.5+this.crouch*.025);g.scale(1+this.crouch*.28,1+this.crouch*.28);g.translate(-.5,-.5);
 for(const m of [...p.mushrooms].sort((a,b)=>a.y-b.y))if(!m.picked&&m.id!==inspection?.m.id)this.mushroom(g,m,m.id===selected?tilt:0);
 for(const l of p.leaves){g.save();const projected=viewLeaf(l,this.crouch);g.translate(projected.x,projected.y);g.rotate(l.angle);const lift=l===activeLeaf&&!this.reduced?.008:0;g.shadowColor='#07110988';g.shadowBlur=this.low?0:this.scale*(lift+.004);g.shadowOffsetY=this.scale*(lift+.004);const index=l.type==='branch'?5:l.type==='fern'?3:Math.min(2,Math.floor(l.shade*3));
 if(l.type==='needle'||l.type==='grass'){this.sprite(g,'occluders',l.type==='needle'?0:1,-l.r,-l.r*.57-lift,l.r*2,l.r*1.14);}else this.sprite(g,'props',index,-l.r,-l.r*(l.type==='branch'?.18:.57)-lift,l.r*2,l.r*(l.type==='branch'?.36:1.14));
 g.shadowBlur=0;g.shadowOffsetY=0;
 if(l.type!=='branch'&&!this.low){const gleam=.2+Math.max(0,wind(time*(this.reduced?.15:1),l.x*13+l.y*9))*.35;g.fillStyle='rgba(231,240,207,'+gleam+')';for(let bead=0;bead<3;bead++){const x=l.r*(-.28+bead*.27),y=l.r*Math.sin(bead*2.4+l.angle)*.13-lift;g.beginPath();g.ellipse(x,y,.0017,.0011,0,0,6.28);g.fill();}}
 if(l===activeLeaf&&!this.reduced){for(let i=0;i<3;i++){g.fillStyle='#e4eddf99';g.beginPath();g.ellipse(l.r*.4+i*.009,l.r*.35+Math.sin(time*5+i)*.006,.003,.004,0,0,Math.PI*2);g.fill();}}g.restore();}
 const e=p.encounter;if(e){g.save();g.translate(e.x,e.y);const t=this.reduced?0:time;if(e.kind<3){const q=e.kind===0?.055:.026;g.translate(Math.sin(t*.3)*.008,0);this.sprite(g,'nature',e.kind+3,-q,-q,q*2,q*1.5);}else if(e.kind===3){g.strokeStyle='#dfdfca88';g.lineWidth=.001;for(let i=0;i<7;i++){const a=i*Math.PI*2/7;g.beginPath();g.moveTo(0,0);g.lineTo(Math.cos(a)*.065,Math.sin(a)*.045);g.stroke();}for(let ring=1;ring<4;ring++){g.beginPath();g.ellipse(0,0,ring*.017,ring*.012,0,0,Math.PI*2);g.stroke();}g.fillStyle='#f4f5dbaa';for(let i=0;i<6;i++){g.beginPath();g.arc(Math.cos(i*2.4)*.04,Math.sin(i*2.4)*.025,.0035,0,7);g.fill();}}else if(e.kind===4){const a=(t*.55)%1;g.strokeStyle='#dce7d0aa';g.lineWidth=.0015;g.beginPath();g.ellipse(0,.025,.008+a*.045,.003+a*.018,0,0,7);g.stroke();g.fillStyle='#ddebd799';g.beginPath();g.ellipse(0,-.03+a*.05,.004,.007,0,0,7);g.fill();}else{g.rotate(Math.sin(t*.8)*.1);this.sprite(g,'props',0,-.05,-.03,.1,.06);}if(e.seen){g.strokeStyle='#d6c79955';g.lineWidth=.001;g.beginPath();g.arc(0,0,.07,0,7);g.stroke();}g.restore();}
 if(selected){const m=p.mushrooms.find(v=>v.id===selected);if(m){g.strokeStyle='#dec998aa';g.lineWidth=.002;g.beginPath();g.ellipse(m.x,m.y+.003,m.size*.45,m.size*.17,0,0,7);g.stroke();}}
 g.restore();if(inspection){g.fillStyle='rgba(12,27,17,.66)';g.fillRect(0,0,w,h);const center=inspection.at||{x:this.ox+this.scale*.5,y:this.oy+this.scale*.5};g.save();g.translate(center.x,center.y);this.specimen(g,inspection.m.kind,-this.scale*.25,-this.scale*.32,this.scale*.5,this.scale*.6);for(const [i,d] of dirtPoints().entries()){if(inspection.mask&(1<<i))continue;for(let j=0;j<4;j++){g.fillStyle=(i+j)%3?'#594633':'#887451';g.beginPath();g.ellipse(d.x*this.scale+Math.sin(j*2.4+i)*2,d.y*this.scale+Math.cos(j*2.4)*2,1.2+j*.2,.8+j*.15,j,0,6.28);g.fill();}}g.restore();}if(this.soil.length){g.save();for(const a of this.soil){a.life-=dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.vy+=dt*85;g.globalAlpha=Math.max(0,a.life*1.7);g.fillStyle='#85735b';g.fillRect(a.x,a.y,1.7,1.2);}this.soil=this.soil.filter(a=>a.life>0);g.restore();}const b=this.basketPosition();this.sprite(g,'props',4,b.x-b.r,b.y-b.r,b.r*2,b.r*2);
 basket.filter(m=>m.id!==fly?.m.id).slice(-5).forEach((m,i)=>{g.save();g.translate(b.x-22+i*10,b.y+2+Math.sin(i)*4);g.rotate((i-2)*.22);this.specimen(g,m.kind,-9,-24,18,29);g.restore();});
 if(fly){const t=fly.t,e=1-Math.pow(1-t,3),x=fly.origin?.x??this.ox+fly.m.x*this.scale,y=fly.origin?.y??this.oy+fly.m.y*this.scale;g.save();g.translate(x+(b.x-x)*e,y+(b.y-y)*e-(this.reduced?0:Math.sin(t*Math.PI)*70));g.rotate(this.reduced?0:t*.45);const r=fly.origin?this.scale*(.25*(1-e)+fly.m.size*.58*e):fly.m.size*this.scale*(1-e*.42);this.specimen(g,fly.m.kind,-r,-r*2,r*2,r*2.45);g.restore();if(t<.45&&!this.reduced){g.fillStyle='#3b2c1b';for(let i=0;i<9;i++){const a=i*2.4;g.fillRect(x+Math.cos(a)*t*65,y+Math.sin(a)*t*20+t*t*70,2,2);}}}
 if(this.transition>0){g.fillStyle='rgba(29,47,31,'+(this.transition*.7)+')';g.fillRect(0,0,w,h);}
 }
}
