import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {makeStudio,normalizeStudio,escapeHtml,elapsedLabel,randomReactionIds,suggestNickname,suggestAvatar} from '../src/model.mjs';
const content=JSON.parse(await readFile(new URL('../src/content/content.json',import.meta.url),'utf8'));
test('all templates reference available people and independent feature settings',()=>{const s=makeStudio(content);assert.equal(new Set(s.people.map(p=>p.id)).size,s.people.length);for(const id of [s.call.personId,s.chat.personId,s.chat.selfId,s.moment.authorId,...s.chat.messages.map(m=>m.personId),...s.moment.likes,...s.moment.comments.map(c=>c.personId)])assert.ok(s.people.some(p=>p.id===id));assert.equal(content.scenes,undefined);});
test('normalization bounds text and rejects malformed IDs and media fields',()=>{const s=normalizeStudio({people:[{id:'ok',name:'x'.repeat(100),avatar:'unknown'},{id:'ok',name:'duplicate'}],chat:{messages:[{personId:'bad',text:'x'.repeat(900)}]},moment:{text:'x'.repeat(1500)}},content);assert.equal(s.people.length,1);assert.equal(s.people[0].name.length,24);assert.equal(s.people[0].avatar,content.avatars[0].id);assert.equal(s.chat.messages[0].personId,'ok');assert.equal(s.chat.messages[0].text.length,500);assert.equal(s.moment.text.length,1000);});
test('user text is escaped and call timer format is stable',()=>{assert.equal(escapeHtml('<img src="x">'),'&lt;img src=&quot;x&quot;&gt;');assert.equal(elapsedLabel(68),'01:08');assert.equal(elapsedLabel(-1),'00:00');});
test('random reactions cannot exceed the library size',()=>{const people=content.people;const ids=randomReactionIds(people,people[0].id,100,()=>0);assert.equal(ids.length,people.length-1);assert.equal(new Set(ids).size,ids.length);assert.ok(ids.every(id=>people.some(p=>p.id===id)));});
test('every bundled avatar is local and has no active or remote references',async()=>{for(const avatar of content.avatars){const svg=await readFile(new URL('../assets/avatars/'+avatar.id+'.svg',import.meta.url),'utf8');assert.match(svg,/^<svg\b/);assert.doesNotMatch(svg,/<script|<foreignObject|<image/i);}});

test('new characters get unused names and avatars, with unique names when pool is exhausted',()=>{const s=makeStudio(content);assert.equal(content.avatars.length,24);assert.equal(new Set(content.nicknames).size,32);const name=suggestNickname(s.people,content.nicknames,'',()=>0);assert.ok(!s.people.some(p=>p.name===name));const avatar=suggestAvatar(s.people,content.avatars,()=>0);assert.ok(!s.people.some(p=>p.avatar===avatar));const everyone=content.nicknames.map(name=>({name}));everyone.push({name:content.nicknames[0]+'2'});assert.equal(suggestNickname(everyone,content.nicknames,'',()=>0),content.nicknames[0]+'3');assert.ok(content.avatars.some(a=>a.id===suggestAvatar(content.avatars.map(a=>({avatar:a.id})),content.avatars,()=>0)));});

test("date-time choices clamp month lengths and format selected time",()=>{const raw=makeStudio(content);raw.chat.timeParts={format:"date",month:4,day:31,hour:0,minute:5};const clean=normalizeStudio(raw,content);assert.equal(clean.chat.time,"4月30日 00:05");assert.equal(clean.chat.timeParts.day,30);raw.chat.timeParts={format:"weekday",weekday:7,hour:23,minute:59};assert.equal(normalizeStudio(raw,content).chat.time,"周日 23:59");});
