import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {makeStudio,normalizeStudio,personUsed,randomReactionIds,recordCall,switchChatMode} from '../src/model.mjs';
import {createCallPlayer} from '../src/call-player.mjs';
const data=JSON.parse(await readFile(new URL('../src/content/content.json',import.meta.url),'utf8'));
test('shared people survive reload and names update all references without storing media',()=>{const s=makeStudio(data);s.people.find(p=>p.id==='basketball').name='新名字';s.people[0].photo='data:image/png;base64,xxx';s.call.photo='blob:temporary';s.moment.likes=['basketball','basketball','missing'];s.chat.messages.push({personId:'missing',text:'保留正文'});const clean=normalizeStudio(s,data);assert.equal(clean.people.find(p=>p.id===clean.call.personId).name,'新名字');assert.equal(clean.people.find(p=>p.id===clean.chat.personId).name,'新名字');assert.equal(clean.people.find(p=>p.id===clean.moment.authorId).name,'新名字');assert.deepEqual(clean.moment.likes,['basketball']);assert.ok(clean.people.some(p=>p.id===clean.chat.messages.at(-1).personId));assert.doesNotMatch(JSON.stringify(clean),/base64|blob:/);assert.ok(personUsed(clean,'basketball'));});
test('obsolete and unknown data is discarded instead of reintroducing editable voice scripts',()=>{const s=normalizeStudio({obsolete:true,call:{intro:'不匹配录音',choices:[1]}},data);assert.equal(s.call.intro,undefined);assert.equal(s.call.choices,undefined);assert.equal(s.obsolete,undefined);assert.ok(s.people.length>1);});
test('call scripts and prompts name 16 unique local files and safe input bounds',()=>{const files=data.callScripts.flatMap(s=>s.segments.map(x=>x.file));assert.equal(files.length,16);assert.equal(new Set(files).size,16);for(const s of data.callScripts){assert.ok(s.prompt.length>40);assert.ok(s.voiceName.endsWith('2.0'));for(const x of s.segments)assert.match(x.file,/^[a-z-]+-\d{2}\.mp3$/);}const s=normalizeStudio({call:{delay:999,pause:-99},people:[null]},data);assert.equal(s.call.delay,30);assert.equal(s.call.pause,0);assert.ok(s.people.length>1);});
test('random likes pick existing distinct people and exclude the author',()=>{const s=makeStudio(data);const ids=randomReactionIds(s.people,s.moment.authorId,6,()=>.5);assert.equal(ids.length,6);assert.equal(new Set(ids).size,6);assert.ok(!ids.includes(s.moment.authorId));});
function fixture(){let n=0;const timers=new Map(),audios=[],events=[];const player=createCallPlayer({schedule(fn,ms){timers.set(++n,{fn,ms});return n;},cancel(id){timers.delete(id);},audioFactory(src){const a={src,play:()=>Promise.resolve(),pause(){this.paused=true;},removeAttribute(){}};audios.push(a);return a;}});const s=data.callScripts[0];const config={script:s,mode:'full',pause:0,available:s.segments.map(x=>x.file),onSegment:i=>events.push(i),onWaiting:()=>events.push('wait'),onEnd:()=>events.push('end')};const run=()=>{const [id,{fn,ms}]=timers.entries().next().value;timers.delete(id);fn();return ms;};return {player,timers,audios,events,config,run};}
test('voice playback waits for actual audio end, pauses, then ends after final segment',async()=>{const f=fixture();f.player.start(f.config);await Promise.resolve();assert.equal(f.timers.size,0);assert.deepEqual(f.events,[0]);f.audios[0].onended();assert.equal(f.run(),5000);await Promise.resolve();assert.deepEqual(f.events,[0,'wait',1]);f.audios[1].onended();assert.equal(f.run(),4000);await Promise.resolve();f.audios[2].onended();assert.equal(f.run(),2000);assert.equal(f.events.at(-1),'end');});
test('hangup cancels pending playback; intro-only remains open; mute reaches audio',async()=>{const f=fixture();f.player.start({...f.config,mode:'intro'});await Promise.resolve();f.player.setMuted(true);assert.equal(f.audios[0].muted,true);f.audios[0].onended();assert.equal(f.timers.size,0);assert.deepEqual(f.events,[0,'wait']);f.player.start(f.config);await Promise.resolve();f.audios.at(-1).onended();f.player.stop();assert.equal(f.timers.size,0);assert.equal(f.audios.at(-1).paused,true);});
test('missing audio has one fallback timer and never claims generated audio',()=>{const f=fixture();const errors=[];f.player.start({...f.config,available:[],onError:x=>errors.push(x)});assert.equal(errors.length,1);assert.equal(f.audios.length,0);assert.equal(f.timers.size,1);f.player.stop();assert.equal(f.timers.size,0);});

test('calls open caller chat and preserve other drafts after reload',()=>{let s=makeStudio(data);const original=structuredClone(s.chat);s.call.personId='miss-you';recordCall(s,true,0,data);assert.equal(s.chat.personId,'miss-you');assert.equal(s.chat.messages.length,1);assert.equal(s.chat.messages[0].text,'已拒绝');s=normalizeStudio(s,data);assert.deepEqual(s.chatArchives.basketball,original);s.call.personId='basketball';recordCall(s,false,65,data);assert.deepEqual(s.chat.messages.slice(0,-1),original.messages);assert.equal(s.chat.messages.at(-1).text,'通话时长 01:05');assert.equal(s.chat.messages.at(-1).kind,'call');assert.equal(s.chatArchives['miss-you'].messages.length,1);});
test('new call record remains within message limit',()=>{const s=makeStudio(data);s.chat.messages=Array.from({length:60},()=>({personId:'self',text:'消息'}));recordCall(s,false,0,data);const n=normalizeStudio(s,data);assert.equal(n.chat.messages.length,60);assert.equal(n.chat.messages.at(-1).text,'通话时长 00:00');assert.equal(n.chat.messages.at(-1).kind,'call');});

test('group and private drafts stay separate and calls never enter group history',()=>{let s=makeStudio(data);const privateMessages=JSON.parse(JSON.stringify(s.chat.messages));switchChatMode(s,'group',data);s=normalizeStudio(s,data);s.chat.groupTitle='测试群';s.chat.messages.push({personId:'tea-lamp',text:'群里见'});s=normalizeStudio(s,data);assert.ok(s.chat.members.includes('tea-lamp'));const groupMessages=JSON.parse(JSON.stringify(s.chat.messages));switchChatMode(s,'private',data);s=normalizeStudio(s,data);assert.deepEqual(s.chat.messages,privateMessages);switchChatMode(s,'group',data);recordCall(s,false,9,data);s=normalizeStudio(s,data);assert.equal(s.chat.mode,'private');assert.equal(s.chat.messages.at(-1).kind,'call');switchChatMode(s,'group',data);s=normalizeStudio(s,data);assert.equal(s.chat.groupTitle,'测试群');assert.deepEqual(s.chat.messages,groupMessages);});
